### ISSUE TITLE
sysdig_probe: Unknown symbol tracepoint_probe_unregister (err 0)

### ISSUE THREAD

**Issue by simos** [draios/sysdig#1005]
I am trying to install sysdig on a VPS that has a custom kernel.

The VPS [edit: does not fulfill] the requirements per https://www.sysdig.org/wiki/how-to-install-sysdig-from-the-source-code/

> For Linux, the following kernel options must be enabled (usually they are, unless a custom built kernel is used):
> CONFIG_TRACEPOINTS
> CONFIG_HAVE_SYSCALL_TRACEPOINTS

This kernel has, instead:

> $ zcat /proc/config.gz | grep TRACEPOINTS
> CONFIG_HAVE_SYSCALL_TRACEPOINTS=y
> $ zcat /proc/config.gz | grep FTRACE
> CONFIG_HAVE_KPROBES_ON_FTRACE=y
> CONFIG_HAVE_DYNAMIC_FTRACE=y
> CONFIG_HAVE_DYNAMIC_FTRACE_WITH_REGS=y
> CONFIG_HAVE_FTRACE_MCOUNT_RECORD=y
> CONFIG_FTRACE=y
> #CONFIG_FTRACE_SYSCALLS is not set
> 

When running sysdig, I get

```
# sysdig
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

and dmesg says

```
[ 7599.677747] sysdig_probe: Unknown symbol tracepoint_probe_unregister (err 0)
[ 7599.677871] sysdig_probe: Unknown symbol for_each_kernel_tracepoint (err 0)
[ 7599.677879] sysdig_probe: Unknown symbol tracepoint_probe_register (err 0)

```

Also, 
```
# cat /proc/kallsyms  | grep tracepoint
# 

```
So, no CONFIG_TRACEPOINTS means no sysdig?

**Comment by Mansuro** [comment]
The way sysdig works is by attaching probes/handlers to tracepoints, providing a hook to call those handlers from the kernel when specific events are captured.
So basically without tracepoints, sysdig-probe can not register the needed handlers, and as a result, it's not possible for sysdig to work.

**Comment by simos** [comment]
Thanks for the response. 

It's a Linux kernel thing that CONFIG_HAVE_SYSCALL_TRACEPOINTS does not imply CONFIG_TRACEPOINTS as well.
I am closing this report.
