### ISSUE TITLE
Build Google(GKE) ContainerOS compatible module

### ISSUE THREAD

**Issue by tydavis** [draios/sysdig#1061]
Currently, Sysdig [is not supported on GKE using ContainerOS (COS)][1], and
has been rejected in [an earlier issue][2]. The recommended alternative
requires foregoing the automatic COS upgrade path and using Ubuntu as the base
image.  This is not feasible for many customers who use GKE for its fully-
managed design, but also need sysdig's inspection capabilities.

Since the COS kernel is built around the vanilla kernel, Sysdig's docker
container could download the relevant kernel version, make the kernel-specific
headers, and produce COS-release-specific modules.

## Detection of ContainerOS

ContainerOS can be identified via the `NAME` entry in `/etc/os-release`.
Example:

```text
BUILD_ID=10385.0.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=ec22bec75d68e4bad3328e4155752a45059f7630
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=66
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=66
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

ContainerOS is also identifiable via `/etc/lsb-release` file (like Ubuntu), but
contains many variables starting with `CHROMEOS_` like:

```text
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_RELEASE_BOARD=lakitu-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=0
CHROMEOS_RELEASE_BUILDER_PATH=lakitu-release/R66-10385.0.0
CHROMEOS_RELEASE_BUILD_NUMBER=10385
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=66
CHROMEOS_RELEASE_DESCRIPTION=10385.0.0 (Official Build) dev-channel lakitu 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=dev-channel
CHROMEOS_RELEASE_VERSION=10385.0.0
DEVICETYPE=OTHER
GOOGLE_RELEASE=10385.0.0
HWID_OVERRIDE=LAKITU DEFAULT
```

## Sysdig-specific deviations

COS is based on [ChromiumOS][3], so the kernel and its headers cannot be
installed via a package manager. The output of `uname -r` contains a plus (+)
sign (ex: "4.4.114+"), which also ruins kernel path-building code.

To get the right version value, use `$(uname -r | tr -d '+')` during kernel
version detection.

To put the kernel headers in the right location:

```bash
# install make 
export KERN_VERSION=$(uname -r | tr -d '+')
curl -s https://www.kernel.org/pub/linux/kernel/v4.x/linux-$KERN_VERSION.tar.gz | tar xzf -
cd linux-$KERN_VERSION
mkdir /usr/src/$KERN_VERSION/
make headers_install INSTALL_HDR_PATH=/usr/src/$KERN_VERSION
# result is about 6MB of files under the headers/include path
```

[1]:https://cloud.google.com/kubernetes-engine/docs/concepts/node-images#sysdig_support
[2]:https://github.com/draios/sysdig/issues/945
[3]:https://www.chromium.org/chromium-os

**Comment by jshearer** [comment]
Hi @tydavis, did you end up having and luck here? I would love to use a fully default/managed GKE cluster with sysdig, and am unable to do that by switching to Ubuntu. Are there any plans to get this working?

Thanks! :)

**Comment by tydavis** [comment]
@jshearer I was able to "make it work" on a host directly, but never got around to fully testing, packaging, or deploying it.

**Comment by Stono** [comment]
This is my only reason for not using sysdig

**Comment by gianlucaborello** [comment]
If you folks want to be alpha testers for this and try the latest development release on any COS version running 4.14 kernel (https://cloud.google.com/container-optimized-os/docs/release-notes), it should work fine:

```
gianluca_borello@instance-1 ~ $ docker run -it --name sysdig --privileged --net=host -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /etc:/host/etc:ro -e SYSDIG_BPF_PROBE="" sysdig/sysdig:dev
* Setting up /usr/src links from host
* Mounting debugfs
Found kernel config at /proc/config.gz
* COS detected (build 10452.81.0), downloading and setting up kernel headers
* Downloading https://storage.googleapis.com/cos-tools/10452.81.0/kernel-src.tar.gz
* Extracting kernel sources
* Configuring kernel
* Trying to compile BPF probe sysdig-probe-bpf (sysdig-probe-bpf-0.99.2522dev-x86_64-4.14.22+-8953a03c1317cdc6d882d1f17b7fe001.o)
* BPF probe located, it's now possible to start sysdig
root@instance-1:/# sysdig -n10
16 22:37:13.302826321 1 sysdig (6743) > switch next=0 pgft_maj=0 pgft_min=1011 vm_size=72604 vm_rss=8788 vm_swap=0 
17 22:37:13.303244926 1 <NA> (0) > switch next=8 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
18 22:37:13.303250039 1 <NA> (8) > switch next=0 pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
...
```

There's still a benign warning in dmesg that I'm going to fix tomorrow, but besides that it should work fine and it can't cause instability to your machine despite being alpha.

Full documentation at: https://github.com/draios/sysdig/wiki/eBPF-(beta)

**Comment by ye** [comment]
The wiki page for `eBPF` seems to be changed to https://github.com/draios/sysdig/wiki/eBPF (without the beta part). I will give it a shot new week to test on GKE nodes running ContainerOS.

**Comment by fntlnz** [comment]
Ok this is almost two years old but I think that now we have all the pieces in place to make this work.

First, COS does not ship the kernel build sources by default, so we had to update the `sysdig-probe-loader` script to go grab them while we start sysdig.

The command that Gianluca posted is still valid now, just now using `dev` is not needed anymore, this is GA.

```
 docker run -it --name sysdig --privileged --net=host -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /etc:/host/etc:ro -e SYSDIG_BPF_PROBE="" sysdig/sysdig sysdig
```

What's important in this command :

`--privileged` is so that sysdig can do the `bpf` syscall, a specific capability `CAP_BPF` just reached Kernel 5.8 so ideally in the future we will drop this need (read more here: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=ed24a7a852b542911479383d5c80b9a2b4bb8caa)
`--net=host` is so that sysdig can translate network sockets while inspecting network syscalls
`-v /var/run/docker.sock:/host/var/run/docker.sock` is so that sinsp can go and check container information related to syscalls happening in a container - very useful on GKE
`-e SYSDIG_BPF_PROBE=""`: this actually tells sysdig to use the eBPF mode, you can also pass a path here to where the eBPF program is

Ideally, if you start sysdig to monitor a GKE cluster, you can also specify two more arguments to it to allow kubernetes metadata fetching: 

```
sysdig -K <path to the service account token here> -k https://<kubernetes apiserver url>
```

**Comment by fntlnz** [comment]
I think we can close this one since this was ultimately accomplished. Anyone feel free to continue the discussion if needed.
