### ISSUE TITLE
Trouble with tracers

### ISSUE THREAD

**Issue by immesys** [draios/sysdig#1064]
I am struggling to get tracers to work (be recognized by sysdig as a tracer). 

If I run `sudo sysdig proc.name=btrdbd and fd.name=/dev/null` I get pages of what looks like correct tracer output to me:
```
33345 11:29:22.965039516 7 btrdbd (22759) < write res=37 data=>:8902048641194924990:LinkAndStore::. 
34561 11:29:22.994328706 7 btrdbd (22759) > write fd=3(<f>/dev/null) size=37 
34562 11:29:22.994329756 7 btrdbd (22759) < write res=37 data=<:8902048641194924990:LinkAndStore::. 
34565 11:29:22.994336822 7 btrdbd (22759) > write fd=3(<f>/dev/null) size=40 
```

But If I run `sudo sysdig proc.name=btrdbd and evt.type=tracer` then I get nothing.

Also if I run csysdig and look at the Traces List, I also get nothing.

The `.` at the end of the data is a newline character. I have also tried without that and it did not change anything.

In case it is relevant, this is being written by a program inside a kubernetes pod.

Any pointers?

EDIT: I am using sysdig version 0.20.0

**Comment by immesys** [comment]
I think I may have worked out what the problem could be. Is it true that sysdig only recognizes the tracers if it sees the open syscall on /dev/null? So if sysdig was started after the program already opened the file descriptor, then it will not recognize any spans?

**Comment by ldegio** [comment]
You are right. 

Either make sure that sysdig starts before the traced program, or add the -T command line argument to sysdig to force tracers capture. 

This is done for performance reasons, to make sure that the tracers logic is enabled only when it's actually needed.

**Comment by bertocci** [comment]
Even with -T specified, tracers aren't working for tracer fds that are created before sysdig starts. It appears to be a regression from #883.
