### ISSUE TITLE
Sysdig and high CPU usage

### ISSUE THREAD

**Issue by vedranf** [draios/sysdig#1068]
Hello,

I'm testing latest sysdig on a production server (56 CPU cores, 128 GB of memory) with 4.9 kernel to monitor a directory tree with lots of i/o and the problem I'm encountering is that it uses 100% CPU (%us of a single dedicated CPU core) while running. This happens regardless of the filter I use (filter I use monitors a directory tree with a *lots* of reads and writes) and regardless of the chisel (e.g. just running sysdig > /dev/null seems to be even worse as is filtering per process). Problem here isn't that it uses 100% CPU as there are unused CPU cores I can run it on, problem is with what happens when there are more events than it can process. If it's saturates a CPU core, I assume events are being dropped which would make it unusable for me. Are there and tricks (or plans) to make sysdig more efficient or it is already pretty much as optimized as it could be? For example, it would probably help to disable part of its functionality early, that is, before events even reach the filter, e.g. for my case I don't need to capture any of the network i/o, yet such events likely add up to 2/3 or more of the total events sysdig sees.

Thanks,
Vedran

**Comment by ldegio** [comment]
The sysdig capture stack is already very optimized, so most of the further optimizations are not trivial and will require, at a minimum, to play with the souces and recompile sysdig.

That said, there are a couple of things you could try:
- If the capture you need to perform is limited in time, you can try to increase the size of the capture buffers by modifying RING_BUF_SIZE in https://github.com/draios/sysdig/blob/dev/driver/ppm_ringbuffer.h. The bigger the buffer, the longer you will be able to sustain staturation without dropping events. Remember, there's a buffer per CPU, so you will have limited maneuvering space in a 56 CPU machine.
- the scap library has a set of functions (scap_handle_eventmask, scap_set_eventmask, scap_unset_eventmask) to filter selected events in the kernel. This is not exposed to the sysdig user yet, but you could try to modify the sources to use it.
