### ISSUE TITLE
Cannot install sysdig module on kernel with retpoline

### ISSUE THREAD

**Issue by csilvers** [draios/sysdig#1078]
I am running a new Ubuntu trusty kernel:
```
% uname -a
Linux ip-10-137-123-178 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

When I run `sudo sysdig-probe-loader` it says:
```
Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms install for sysdig

sysdig-probe:
Running module version sanity check.
 - Original module
   - This kernel never originally had a module by this name
 - Installation
   - Installing to /lib/modules/3.13.0-143-generic/updates/dkms/

depmod....

DKMS: install completed.
* Trying to load a dkms sysdig-probe, if present
* Trying to load a system sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 3.13.0-143-generic
Found kernel config at /boot/config-3.13.0-143-generic
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.20.0-x86_64-3.13.0-143-generic-a9dc8cfc976e3dcbfb166b1eefbd6aa5.ko
Download succeeded, loading module
insmod: ERROR: could not insert module /home/ubuntu/.sysdig/sysdig-probe-0.20.0-x86_64-3.13.0-143-generic-a9dc8cfc976e3dcbfb166b1eefbd6aa5.ko: Invalid module format
```

The problem is this:
```
% dmesg | tail -n1
[  238.788224] sysdig_probe: version magic '3.13.0-143-generic SMP mod_unload modversions ' should be '3.13.0-143-generic SMP mod_unload modversions retpoline '
```

If I am reading this right, I am downloading a version of the module from s3 that was not built with a retpoline-aware gcc (I guess?), but I need that.

Any pointers on how to build this kernel module to get something that will work with my kernel?

**Comment by luca3m** [comment]
Can you please use `sysdig/sysdig:dev`? It has the fixes you need for retpoline

**Comment by csilvers** [comment]
I did this and didn't see the fix:
```
git clone https://github.com/draios/sysdig
cd sysdig/
git checkout dev
mkdir build && cd build
cmake ..
make driver
modinfo driver/sysdig-probe.ko
```
and it said:
```
vermagic:       3.13.0-143-generic SMP mod_unload modversions 
```
so I'm still not seeing `retpoline`.  Can you confirm that I should have seen it?  What does it mean that I don't? -- am I not using a retpoline-aware gcc or something?

**Comment by luca3m** [comment]
I meant to run sysdig in docker using the standard cmdline you already used by pointing it to `sysdig/sysdig:dev` rather than `sysdig/sysdig`. The former ships with a gcc 5 version that has retpoline support.

To make it work locally as you did I think you need to upgrade gcc as you said. Latest ubuntu version should have retpoline patches

**Comment by csilvers** [comment]
Thanks!

Is there any chance that https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries will be uploaded with repoline-aware modules?  In theory my local gcc has retpoline support but it seems to not be working in practice, so it would be awesome if I could rely on `sysdig-probe-loader` (which downloads the module from s3) instead.  I understand if that's not practical though.

**Comment by luca3m** [comment]
Yes, it will be done for the next sysdig release
