### ISSUE TITLE
OS X Issues

### ISSUE THREAD

**Issue by ylluminate** [draios/sysdig#109]
Really excited to see a homebrew formula for `sysdig` land over the last day or so.  What a thrilling opportunity since OS X is in serious need of an easy to use tool such as this!

Tried a couple of your examples and hit some walls that I wanted to report:
`sudo sysdig evt.type=open and fd.name`: 
filter error: unrecognized comparison operator after evt.type=open and fd.name

`sysdig -A -c echo_fds fd.sip=192.168.0.1 and proc.name=httpd`:
live capture not supported on OSX

**Comment by juliangruber** [comment]
are there plans to add more support for osx?

**Comment by luca3m** [comment]
On OSX you can read tracefiles captured on Linux. Patch are accepted but we don't have short term plans to add live capture on OSX right now.
