### ISSUE TITLE
sysdig-inspect can not handle scaps from sysdig 0.21.0

### ISSUE THREAD

**Issue by guardiande** [draios/sysdig#1099]
I recently upgraded sysdig 0.21.0 on Ubuntu 16.04. When I try to open scaps from 0.21.0 in sysdig-inspect 0.2.0 nothing is displayed. csysdig works.

Is this a known issue?

**Comment by davideschiera** [comment]
Closed via https://github.com/draios/sysdig-inspect/releases/tag/0.3.0.
