### ISSUE TITLE
Install guide for Arch / Manjaro linux

### ISSUE THREAD

**Issue by HaleTom** [draios/sysdig#1131]
I'm running Manjaro (based upon Arch).

I've installed the `sysdig` package, and see:

```
$ sudo sysdig
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

What am I missing?

**Comment by hxer** [comment]
sysdig driver not work, may be you can run `sysdig-probe-loader` with root

**Comment by pbar1** [comment]
I'm still seeing similar errors on
```Linux 4.14.79-1-MANJARO #1 SMP PREEMPT Sun Nov 4 16:57:03 UTC 2018 x86_64```
and
```sysdig version 0.24.1```

Running as root and executing `sysdig-probe-loader`:
```
* Unloading sysdig-probe, if present
* Running dkms install for sysdig
Module sysdig/0.24.1 already installed on kernel 4.14.79-1-MANJARO/x86_64
* Trying to load a dkms sysdig-probe, if present
sysdig-probe found and loaded in dkms
```
and then running `sysdig`:
```error creating the process list. Make sure you have root credentials.```

**Comment by HaleTom** [comment]
@hxer You'll need to install the kernel headers package. I forget the name.
