### ISSUE TITLE
Is there any guide to help me with reading the source code?

### ISSUE THREAD

**Issue by linjinjin123** [draios/sysdig#1135]
Hi there, I am interested in this project, I'd like to learn the principle of sysdig from source code and do some contribution in the future.  I want to know how can I get started ? Is there any guide to help me, such as reading some important file of source code firstly.

Thanks a lot !

**Comment by hxer** [comment]
i read source code for old version 0.1.72, that is easy to understand how to deal  with event.

**Comment by kristopolous** [comment]
start at the entry point of the main userland process over yonder: https://github.com/draios/sysdig/blob/dev/userspace/sysdig/sysdig.cpp
From there you can follow down the execution of different aspects to different parts. Have fun.
