### ISSUE TITLE
Driver Fails to Compile on Fedora 28

### ISSUE THREAD

**Issue by ptobin77** [draios/sysdig#1165]
OS
![image](https://user-images.githubusercontent.com/40795691/42219632-87cfab22-7e9a-11e8-90b9-a0f7d3a711f0.png)

Kernel Version
![image](https://user-images.githubusercontent.com/40795691/42219431-ee760444-7e99-11e8-8dc4-ebde7be42caa.png)

Loading the driver
![image](https://user-images.githubusercontent.com/40795691/42219535-3aac7cd0-7e9a-11e8-8117-6555075acdf4.png)

![image](https://user-images.githubusercontent.com/40795691/42219561-5068c72c-7e9a-11e8-9963-edc2b52ac33a.png)

![image](https://user-images.githubusercontent.com/40795691/42219574-5e0c3eb8-7e9a-11e8-82d4-e98a6ccf3023.png)

![image](https://user-images.githubusercontent.com/40795691/42219593-72507600-7e9a-11e8-8fa7-fe50ae675751.png)

When building from source, it builds up to the point when it starts to build the driver and fails in the same fashion. Any help is appreciated. On caveat, to build from the source, I had to change all 'SHELL' variables from '/bin/sh' to '/bin/bash'. I also tried to install falco on Fedora 27 and am having the same issues.

Running cmake ..
![image](https://user-images.githubusercontent.com/40795691/42219720-e3b68b9a-7e9a-11e8-8cd1-31a08c8456fa.png)

Running make
![image](https://user-images.githubusercontent.com/40795691/42219928-733fc2ae-7e9b-11e8-90ee-db43b1930020.png)

**Comment by Rosanna4** [comment]
This is duplicate of https://github.com/draios/sysdig/issues/1114 which should be fixed with https://github.com/draios/sysdig/commit/81b761d7131268b15a945f9aa7435fdfb638a242 . You have to build sysdig from latest github spource until new release is tagged.
