### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by swood** [draios/sysdig#1183]
Hello.

I downloaded the last version from the GitHub and try to build it in OBS. So, I got an error:

> [   91s] cd /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/build/userspace/libsinsp && /usr/bin/c++   -DHAS_CAPTURE -DK8S_DISABLE_THREAD -DPLATFORM_NAME=\"Linux\" -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/. -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/../../common -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/../libscap  -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -Wall -ggdb --std=c++0x -O2 -g -DNDEBUG   -o CMakeFiles/sinsp.dir/cursestable.cpp.o -c /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/cursestable.cpp
[   91s] [ 28%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/cursesspectro.cpp.o
[   91s] cd /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/build/userspace/libsinsp && /usr/bin/c++   -DHAS_CAPTURE -DK8S_DISABLE_THREAD -DPLATFORM_NAME=\"Linux\" -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/. -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/../../common -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/../libscap  -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -Wall -ggdb --std=c++0x -O2 -g -DNDEBUG   -o CMakeFiles/sinsp.dir/cursesspectro.cpp.o -c /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/cursesspectro.cpp
[   94s] In file included from /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/container.h:24:0,
[   94s]                  from /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/sinsp.h:77,
[   94s]                  from /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/container.cpp:25:
[   94s] /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/container.cpp: In constructor 'sinsp_container_engine_docker::sinsp_container_engine_docker()':
[   94s] /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/container.cpp:104:52: error: 'CURLPIPE_HTTP1' was not declared in this scope
[   94s]     curl_multi_setopt(m_curlm, CURLMOPT_PIPELINING, CURLPIPE_HTTP1|CURLPIPE_MULTIPLEX);
[   94s]                                                     ^
[   94s] /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/container.cpp:104:67: error: 'CURLPIPE_MULTIPLEX' was not declared in this scope
[   94s]     curl_multi_setopt(m_curlm, CURLMOPT_PIPELINING, CURLPIPE_HTTP1|CURLPIPE_MULTIPLEX);
[   94s]                                                                    ^
[   94s] /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/container.cpp:109:29: error: 'CURLOPT_UNIX_SOCKET_PATH' was not declared in this scope
[   94s]     curl_easy_setopt(m_curl, CURLOPT_UNIX_SOCKET_PATH, m_unix_socket_path.c_str());
[   94s]                              ^
[   95s] [ 29%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/cursesui.cpp.o
[   95s] cd /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/build/userspace/libsinsp && /usr/bin/c++   -DHAS_CAPTURE -DK8S_DISABLE_THREAD -DPLATFORM_NAME=\"Linux\" -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/. -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/../../common -I/home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/../libscap  -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -Wall -ggdb --std=c++0x -O2 -g -DNDEBUG   -o CMakeFiles/sinsp.dir/cursesui.cpp.o -c /home/abuild/rpmbuild/BUILD/sysdig-0.22.0/userspace/libsinsp/cursesui.cpp
[   95s] userspace/libsinsp/CMakeFiles/sinsp.dir/build.make:113: recipe for target 'userspace/libsinsp/CMakeFiles/sinsp.dir/container.cpp.o' failed
[   95s] make[2]: *** [userspace/libsinsp/CMakeFiles/sinsp.dir/container.cpp.o] Error 1
[   95s] make[2]: *** Waiting for unfinished jobs....

Probably someone could help me with this problem.
OS: SLES 12.3
Kernel: 4.17.1
gcc: 4.8

**Comment by swood** [comment]
Anybody could help me with this problem?

**Comment by nathan-b** [comment]
Do you have libcurl installed on your system?

**Comment by swood** [comment]
Yes, and header-package installed as well.

**Comment by nathan-b** [comment]
Apologies if this is a silly question, but I note you're using OBS. Did you make sure to specify libcurl as a requirement in the OBS recipe?

**Comment by kristopolous** [comment]
This may be silly but could you have an older version of curl installed, as in 2015 or older? The constant was first introduced in a release in 7.43.0 ([original commit](https://github.com/curl/curl/commit/02ec1ced9ba3bf70f6198b39c39b15fc80c97f09#diff-a539134a8261490f653400a3a99df731)), that's Jun 17, 2015.

You may have multiple versions of this header and the build is getting confused ... it's just a shot in the dark, but try

 >  locate curl/multi.h

If you get multiple results, I [have a really simple tool](https://github.com/kristopolous/tools/blob/master/src/inotify.c) that can tell you what file is being used using inotify(7). Compile it and do something like

 > locate curl/multi.h | xargs inotify

and run the build. You'll be able to see which one sysdig is interested in. If this is actually a real solution, then tell me and we can look at include path preferences.
