### ISSUE TITLE
Inaccurate output %proc.exe when evt.type=execve and evt.failed=true

### ISSUE THREAD

**Issue by hxer** [draios/sysdig#1217]
sysdig read offline scap file as follow:

sysdig -r 20180907_005910.scap proc.pid=15557 and evt.type=execve and evt.failed=true                 
35818187 00:54:54.534947884 1 sh (15557) < execve res=-8(ENOEXEC) exe=./mi666 args= tid=15557(sh) pid=15557(sh) ptid=15554(sh) cwd= fdlimit=100001 pgft_maj=0 pgft_min=65 vm_size=106072 vm_rss=380 vm_swap=0 comm=sh cgroups=cpuset=/.ns=/.cpu_cgroup=/limitcpu.cpuacct=/.mem_cgroup=/.devices=/.freezer=/... env=SHELL=/bin/bash.HISTSIZE=3000.SSH_CLIENT=142.93.30.3 38026 22.OLDPWD=/tmp.USE... tty=0 pgid=15547(bash) 

you can see execve res is -8(ENOEXEC), `exe=./mi666`, that is right

but run as follow:

sysdig -r 20180907_005910.scap proc.pid=15557 and evt.type=execve and evt.failed=true -p "%proc.exe"
sh

%proc.exe output is `sh`, why not is " exe=./mi666"???

why? what happed?

when execve failed, how to get accurate output for %proc.exe in chisels?

thanks.

**Comment by kristopolous** [comment]
Would you be comfortable posting the file or sending it to me via email? If you're really concerned about the privacy, feel free to encrypt it with my public key http://getpostdelete.com/id_rsa-ChrisMcKenzie.pub

**Comment by hxer** [comment]
Test file has been sent to you via email.
Thanks
