### ISSUE TITLE
What's the different between fd.sip  and fd.rip

### ISSUE THREAD

**Issue by yujinqiu** [draios/sysdig#1286]
Hi, 
   I was confused about the  sysdig doc  `sysdig -l`

```
fd.sip          server IP address.
fd.rip          remote IP address.
```
What's the different between `fd.sip` and  `fd.rip` ?   Are they the same things with different name?

**Comment by therealbobo** [comment]
Hi @yujinqiu! I think that a simple example can clarify the difference!
Given 2 machines (A and B), we'll run a simple http server (e.g. using `python3 -m http.server`) and `sysdig` in the machine A meanwhile the machine B will be our client. Now if we make a request (e.g. `curl http://<machine-A-ip>:8000`) will have something like this:
```
# sysdig -p '%proc.pid %proc.name %evt.type %evt.dir rip=%fd.rip sip=%fd.sip %evt.args' 'proc.name = "python"'
80896 python connect < rip=:: sip=:: res=0 tuple=::1:49557->:::8000
80896 python connect > rip=:: sip=:: fd=3(<6u>::1:49557->:::8000) addr=NULL
80896 python connect < rip=::1000:0:0:0 sip=::1000:0:0:0 res=0 tuple=:::0->::1000:0:0:0:0
80896 python connect > rip=0.0.0.0 sip=0.0.0.0 fd=3(<4>:::0->::1000:0:0:0:8000) addr=0.0.0.0:8000
80896 python connect < rip=::1000:0:0:0 sip=::1000:0:0:0 res=0 tuple=::ffff:127.0.0.1:57473->::1000:0:0:0:8000
80896 python close > rip=::1000:0:0:0 sip=::1000:0:0:0 fd=3(<6u>::ffff:127.0.0.1:57473->::1000:0:0:0:8000)
80896 python close < rip=::1000:0:0:0 sip=::1000:0:0:0 res=0
80896 python accept < rip=192.168.1.132 sip=192.168.1.10 fd=4(<4t>192.168.1.132:59289->192.168.1.10:8000) tuple=192.168.1.132:59289->192.168.1.10:8000 queuepct=0 queuelen=0 queuemax=5
80896 python recvfrom > rip=192.168.1.132 sip=192.168.1.10 fd=4(<4t>192.168.1.132:59289->192.168.1.10:8000) size=8192
80896 python recvfrom < rip=192.168.1.132 sip=192.168.1.10 res=81 data=GET / HTTP/1.1..Host: 192.168.1.10:8000..User-Agent: curl/7.87.0..Accept: */*... tuple=NULL
80896 python sendto > rip=192.168.1.132 sip=192.168.1.10 fd=4(<4t>192.168.1.132:59289->192.168.1.10:8000) size=156 tuple=NULL
80896 python sendto < rip=192.168.1.132 sip=192.168.1.10 res=156 data=HTTP/1.0 200 OK..Server: SimpleHTTP/0.6 Python/3.10.6..Date: Mon, 03 Apr 2023 07
80896 python sendto > rip=192.168.1.132 sip=192.168.1.10 fd=4(<4t>192.168.1.132:59289->192.168.1.10:8000) size=2027 tuple=NULL
80896 python sendto < rip=192.168.1.132 sip=192.168.1.10 res=2027 data=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/st
80896 python shutdown > rip=192.168.1.132 sip=192.168.1.10 fd=4(<4t>192.168.1.132:59289->192.168.1.10:8000) how=1
80896 python shutdown < rip=192.168.1.132 sip=192.168.1.10 res=0
80896 python close > rip=192.168.1.132 sip=192.168.1.10 fd=4(<4t>192.168.1.132:59289->192.168.1.10:8000)
80896 python close < rip=192.168.1.132 sip=192.168.1.10 res=0
```
On the contrary, if we run `sysdig` on the machine B `fd.rip` and `fd.sip` will be the same.
At the end we can summarise saying that `fd.sip` is the address of the machine that is listening meanwhile the `fd.rip` it's the actual remote address.
I hope that I was clear! Feel free to reopen if you want any further explanation! 😄

**Comment by tanrenxuan** [comment]
@therealbobo hello, I want to ask a question related to fd.rip：
When I use sysdig to output some log related to network, I can't find the remote Ip from fd(socket) field.
For example：

fd fd.lip fd.rip fd.lport fd.rport
10.10.0.67:51252->10.10.0.114:8080 10.10.0.114 10.10.0.67 8080 51252
10.10.0.67:51252->10.10.0.114:8080 10.10.0.114 10.10.0.67 8080 51252
10.10.0.67:51252->10.10.0.114:8080 10.10.0.114 10.10.0.67 8080 51252
10.10.0.67:51252->10.10.0.114:8080 27065 10.10.0.114 10.10.0.67 8080 51252
10.10.0.114:60986->10.102.100.24:8888 27084 10.102.100.24 10.10.0.114 8888 60986
10.10.0.114:60986->10.102.100.24:8888 27084 10.102.100.24 10.10.0.114 8888 60986

I use sysdig to record some fields in server 10.10.0.114, however, sometimes fd.lip records 10.10.0.114, and sometimes it records a different ip, which confused me.
