### ISSUE TITLE
0.24.2 csysdig -vcontainers shows only "Collecting Data" on LXD host (ubuntu 18.04)

### ISSUE THREAD

**Issue by gschintgen** [draios/sysdig#1289]
I can't get csysdig to show any information on my LXD containers. It only ever shows "Collecting Data" and nothing else when I choose the containers view (either via F2 or -vcontainers). Other views seem to work just fine.
This happens both with the ubuntu-provided 0.19.1 and with the official upstream 0.24.2.
It's 100% reproducible on my system. (Ubuntu 18.04 server, freshly installed, main usage is LXD host, LXD v3.8 installed through snap, current ubuntu kernel 4.15.0-43.46)

Is there anything that I may be missing? If not, is there some debugging info I could provide?

**Comment by gschintgen** [comment]
Somehow sysdig can't detect any of my running containers:
```
# sysdig -c lscontainers
container.type container.image container.name      container.id
-------------- --------------- ------------------- ------------
```

`lxc list` works just fine of course.

**Comment by JoeMattie** [comment]
Same issue here.  It can, however, show my docker containers

**Comment by JoeMattie** [comment]
I got this working again by downgrading lxd to 3.0.3/stable I'm unsure if this is a bug with lxd or sysdig at this point.

**Comment by JoeMattie** [comment]
@gschintgen I tracked down this issue eventually and submitted a PR to the sysdig repo: https://github.com/draios/sysdig/pull/1345

**Comment by jumarko** [comment]
I'm stuck with the same thing when I trie to show "Connections" for a (java) process running inside a Docker container.
It just shows "Collecting data" and nothing is ever shown.
It seems to work fine when I try a process running on the host directly like _ssh_.

I have similar issues with the "File Opens List" view - on the other hand, "Files" view seems to work.

Note: I'm very new to sysdig so I might have done something silly or I'm just misinterpreting things.

I installed sysdig like this: https://idroot.us/install-sysdig-ubuntu-20-04/
```
sudo apt install linux-headers-$(uname -r)

curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | bash

sudo apt update
sudo apt install sysdig

```

uname info: 
```
uname -a
Linux ubuntu-18 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
