### ISSUE TITLE
`sysdig -c spy_users` won't pipe data

### ISSUE THREAD

**Issue by ndangles** [draios/sysdig#1292]
Hi there,

I want to pipe the output of `sysdig -c spy_users` to a bash script for some real time parsing (`sysdig -c spy_users | ./myscript`, however for whatever reason I am not receiving any data even though I am confirming the command is outputting data. Running `sysdig -c spy_users` alone will output the commands but when piping that even to `cat` or a script it will not output anything (I tested same commands that worked for `sysdig -c spy_users`.

I can run `sysdig |cat` or `sysdig | ./myscript` and it'll work fine but for whatever reason, piping with `sysdig -c spy_users` I am receiving nothing. I am running these commands in a screen session. I am on Debian Scretch (9) using sysdig 0.13.0.

Does anyone have any idea why this might be? Any help is appreciated, thank you

**Comment by ldegio** [comment]
I'm pretty sure you are hitting stdout buffering issues in the C standard library.

sysdig has the `--unbuffered` command line flag to force stdout flushing in situations like these, but I'm pretty sure it doesn't apply to chisels output, so you will likely need to do some Lua coding and edit the spy_users chisel in some way similar to this https://stackoverflow.com/questions/18541636/is-stdin-stdout-stderr-buffered-or-unbuffered-in-lua.

**Comment by seyoatda** [comment]
> I'm pretty sure you are hitting stdout buffering issues in the C standard library.
> 
> sysdig has the `--unbuffered` command line flag to force stdout flushing in situations like these, but I'm pretty sure it doesn't apply to chisels output, so you will likely need to do some Lua coding and edit the spy_users chisel in some way similar to this https://stackoverflow.com/questions/18541636/is-stdin-stdout-stderr-buffered-or-unbuffered-in-lua.

this link solved my problem. For those who met the same issue, just find the `spy_users.lua` file and add `io.stdout:setvbuf 'no'` to the first line. the file is located at `/usr/share/sysdig/chisels/spy_users.lua` , if you install it by `apt`
