### ISSUE TITLE
Docker image build "Unable to locate package gcc-5"

### ISSUE THREAD

**Issue by oldebreeze** [draios/sysdig#1314]
Running `docker build -t <tag> sysdig/docker/<dockerfile_dir>` with the latest code fails on `E: Unable to locate package gcc-5` while trying to add the below step:

```
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
    bash-completion \
    bc \
    clang-7 \
    curl \
    dkms \
    gnupg2 \
    ca-certificates \
    gcc \
    gcc-5 \
    libc6-dev \
    libelf-dev \
    libelf1 \
    less \
    llvm-7 \
    procps \
    xz-utils \
 && rm -rf /var/lib/apt/lists/*
```

Run log located here: https://pastebin.com/b5QK9yQB

Discovered accidentally while trying to add a custom statsd check to the agent, attempted to build the image with the additions and this error occurred. Reproduced with fresh Dockerfiles from both the dev and master branches.

**Comment by mstemm** [comment]
Debian recently removed gcc 5 and gcc 6 from debian:unstable. Our Dockerfiles include a wide array of gcc versions so we can build kernel modules from inside the container that are loadable from the host.

Falco has had some recent releases where we worked around these issues (https://github.com/falcosecurity/falco/pull/501, https://github.com/falcosecurity/falco/pull/526). These kinds of changes should be brought over to sysdig, we just haven't done it yet.
