### ISSUE TITLE
PT_BYTEBUF max len mismatch with RW_MAX_SNAPLEN

### ISSUE THREAD

**Issue by invano** [draios/sysdig#1350]
Hi there,

I'm playing around with sysdig, with chisels in particular. My specific use case requires the biggest snap len possible when recording. I see it's 65000 bytes in kernel space as specified here: https://github.com/draios/sysdig/blob/9722dbc1d0ccaed5a5d29036f4666a5cbfe70dc4/driver/ppm_events_public.h#L1547

However, I noticed that `write` events with a big size always return a `evt.rawarg.data`/`BYTEBUF` with 16383 bytes at most.
I had a look at the userspace code and I found the limit here
https://github.com/draios/sysdig/blob/ecafb605f00e606420ae5a51d916249d6fbce763/userspace/libsinsp/chisel_api.cpp#L127-L128 and here https://github.com/draios/sysdig/blob/e404c50c346ce1a2750446aeaac59f4062f33b0a/userspace/libsinsp/chisel.h#L156

The user space code is protecting the buffer dropping the last byte but, at the same time, `sizeof(m_lua_fld_storage)` is definitively smaller than its kernel counterpart `PPM_MAX_ARG_SIZE`. This prevents to work correctly with chisels every time snaplen is configured to be greater than 16383 bytes.

At this point I'm wondering if there are any reasons for the mismatch, or it's just a bug.
Thanks!

**Comment by ldegio** [comment]
This looks like a bug.

Fixed here https://github.com/draios/sysdig/pull/1361
