### ISSUE TITLE
Rely as little as possible on tinfo for container metadata filterchecks

### ISSUE THREAD

**Issue by mstemm** [draios/sysdig#1368]
Currently, the container and k8s filterchecks rely on a valid threadinfo struct, as that's the only object that directly holds a container id, which is used to access container and k8s metadata.

There are some cases, though, where you don't have a threadinfo object. One case of this is container json events, which will be more important once https://github.com/draios/sysdig/pull/1326 is merged.

Ideally we should change any filterchecks that need container ids but not thread ids to directly get the container id without requiring a threadinfo object. This would require 1) moving the container id to be a direct property of the sinsp_evt 2) having additional work when creating the sinsp_evt object to directly fill in the container id when possible e.g. for container json events 3) change the filterchecks to use the container id of the sinsp_evt instead of having to fetch a threadinfo first.

**Comment by gnosek** [comment]
@mstemm, draft PR is here, comments appreciated: https://github.com/draios/sysdig/pull/1374
