### ISSUE TITLE
sql parser

### ISSUE THREAD

**Issue by gitdhar** [draios/sysdig#1393]
There is a mention of "improved sql parser" [here ](https://sysdigdocs.atlassian.net/wiki/spaces/SRN/pages/256540682/Sysdig+Agent+Release+Notes)but I cannot find any info about an SQL parser. Any info about this?

**Comment by Issif** [comment]
This is related to Sysdig Monitor, an agent and commercial product. Current repository is dedicated to sysdig, a FOSS on which is built Sysdig Monitor.

**Comment by fntlnz** [comment]
@gitdhar , @Issif is right, the doc you are linking does not refer to this Open Source project, closing this. Thanks for asking the question, it will be good as a future reference.
