### ISSUE TITLE
support for 32bit emulation

### ISSUE THREAD

**Issue by ldegio** [draios/sysdig#14]
the 64bit linux does some magic to run 32bit binaries. See:

http://stackoverflow.com/questions/3305350/how-do-32-bit-applications-make-system-calls-on-64-bit-linux
the CONFIG_IA32_EMULATION kernel flag
The result with our current driver is that the driver is uncapable of detecting and interpreting 32bit syscalls, generating a bunch of garbage and sometimes crashing the system.

How to replicate:
install skype on a 64bit fedora following these instructions http://www.unixmen.com/how-to-install-skype-on-fedora-18-64bit/ and capture its activity.

**Comment by pachulo** [comment]
+1

When trying to analyse skype activity in my Ubuntu 14.04 x64 machine all I can see are "switch" events:

```
619 09:10:52.546781405 1 skype (23179) > switch next=98 pgft_maj=495 pgft_min=35625 vm_size=599632 vm_rss=187440 vm_swap=0 
624 09:10:52.547725199 1 skype (23179) > switch next=0 pgft_maj=495 pgft_min=35625 vm_size=599632 vm_rss=187440 vm_swap=0 
1348 09:10:52.589806801 1 skype (23179) > switch next=0 pgft_maj=495 pgft_min=35625 vm_size=599632 vm_rss=187440 vm_swap=0 
1598 09:10:52.602041138 1 skype (23179) > switch next=0 pgft_maj=495 pgft_min=35625 vm_size=599632 vm_rss=187440 vm_swap=0 
2474 09:10:52.631827970 1 skype (23179) > switch next=0 pgft_maj=495 pgft_min=35625 vm_size=599632 vm_rss=187440 vm_swap=0 
2603 09:10:52.637640003 2 skype (23331) > switch next=0 pgft_maj=0 pgft_min=8 vm_size=599632 vm_rss=187440 vm_swap=0
```

**Comment by luca3m** [comment]
We have it now.
