### ISSUE TITLE
sysdig kernel module fails to build since Linux 5.1

### ISSUE THREAD

**Issue by Maryse47** [draios/sysdig#1404]
As usual in every kernel major update, the sysdig module fails to build. Here are specififc errors that occur multiple times during build;
```
/var/lib/dkms/sysdig/0.25/build/ppm_fillers.c:150:2: error: too many arguments to function ‘syscall_get_arguments’
  syscall_get_arguments(current, args->regs, 0, 1, &val);
  ^~~~~~~~~~~~~~~~~~~~~
```

```
In file included from /var/lib/dkms/sysdig/0.25/build/ppm_events.c:40:
/var/lib/dkms/sysdig/0.25/build/ppm_flag_helpers.h: In function ‘mmap_flags_to_scap’:
/var/lib/dkms/sysdig/0.25/build/ppm_flag_helpers.h:380:14: error: ‘MAP_SHARED’ undeclared (first use in this function); did you mean ‘VM_SHARED’?
  if (flags & MAP_SHARED)
              ^~~~~~~~~~
              VM_SHARED
/var/lib/dkms/sysdig/0.25/build/ppm_flag_helpers.h:380:14: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/sysdig/0.25/build/ppm_flag_helpers.h:383:14: error: ‘MAP_PRIVATE’ undeclared (first use in this function); did you mean ‘DQF_PRIVATE’?
  if (flags & MAP_PRIVATE)
              ^~~~~~~~~~~
              DQF_PRIVATE

```
There are also following warnings:
```
/var/lib/dkms/sysdig/0.25/build/main.c:1447:40: warning: passing argument 3 of ‘syscall_get_arguments’ makes pointer from integer without a cast [-Wint-conversion]
   syscall_get_arguments(current, regs, 1, 1, &arg);
```

Full log below:
[make.log.txt](https://github.com/draios/sysdig/files/3179839/make.log.txt)

**Comment by abucodonosor** [comment]
The first error is caused by these changes:

https://lkml.org/lkml/2019/4/1/498

The second one is a missing include now, caused by:

ae5d11d206fce924efcaa8127ffdbdb60c660d7a

**Comment by fayak** [comment]
Same error with 
```
$ uname -a
Linux ... 5.1.2-arch1-1-ARCH #1 SMP PREEMPT Wed May 15 00:09:47 UTC 2019 x86_64 GNU/Linux
```

**Comment by nathan-b** [comment]
@abucodonosor thanks for tracking down the relevant commits! Much appreciated. Taking a look.

**Comment by abucodonosor** [comment]
@nathan-b 

The second issue is fixed by something like this:

```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 1, 0)
# include <uapi/linux/mman.h>
#endif

```

However syscall_*_arguments() changes are somewhat biggISH 
and you need a lot #if .. #else .. around the code.

**Comment by nathan-b** [comment]
@abucodonosor Thanks! You can check out https://github.com/draios/sysdig/pull/1413 if you're interested. I think the preprocessor guards around linux/mman.h are not required because that file has existed in the repository since the 2.6 kernel days (https://github.com/torvalds/linux/blob/1da177e4c3f41524e886b7f1b8a0c1fc7321cac2/include/linux/mman.h#L8).

**Comment by Maryse47** [comment]
Fixed with https://github.com/draios/sysdig/commit/a6ab1e66fc05a02178e051ea2441633996d5871e
