### ISSUE TITLE
release-0.26.0 complied, but unable to load the driver

### ISSUE THREAD

**Issue by 18823832169** [draios/sysdig#1423]
Hi！
I downloaded the source code of the release-0.26.0 branch from github. After compiling, run **sudo ./sysdig** and report the following error:
```
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

**Comment by fntlnz** [comment]
Hi @18823832169 can you give some more info? What is the OS you are on, which kernel version, do you have the kernel headers package installed for your distro?

**Comment by 18823832169** [comment]
I have found the problem, I did not continue after executing **make install**, I also need to use **insmod** to load the _sysdig-probe.ko_ file in order to run normally.
