### ISSUE TITLE
Module not built for newer amazon linux AMIs

### ISSUE THREAD

**Issue by fntlnz** [draios/sysdig#1429]
@prsimoes on slack reported that he is not seeing the images for the eks amazon linux flavor on kernel `4.14.106-97.85.amzn2.x86_64`.

That image seems to have been around for at least 5 days now so it's strange that the kernel module is not listed in the bucket yet.

Bucket: https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/index.html

**Comment by fntlnz** [comment]
Errata: I see the modules, the page didn't load completely before, maybe @prsimoes you are on an older Falco version like 0.14.0 ?

<a href="falco-probe-0.15.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">falco-probe-0.15.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 13-May-2019 23:49  700K
 35 9250k   35 3284k    0     0  2484k      0  0:00:03  0:00:01  0:00:02 2482k      <a href="sysdig-probe-0.25-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdig-probe-0.25-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 28-Mar-2019 16:41  696K
 <a href="sysdig-probe-0.26.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdig-probe-0.26.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 22-May-2019 17:58  700K
      <a href="sysdig-probe-0.26.1-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdig-probe-0.26.1-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 28-May-2019 18:57  700K
      <a href="sysdigcloud-probe-0.89.4-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdigcloud-probe-0.89.4-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 28-Mar-2019 16:48  700K
      <a href="sysdigcloud-probe-0.89.5-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdigcloud-probe-0.89.5-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 01-Apr-2019 20:08  700K
      <a href="sysdigcloud-probe-0.90.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdigcloud-probe-0.90.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 10-May-2019 20:30  700K
      <a href="sysdigcloud-probe-0.90.1-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdigcloud-probe-0.90.1-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 21-May-2019 23:01  700K
      <a href="sysdigcloud-probe-0.90.2-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko">sysdigcloud-probe-0.90.2-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko</a> 29-May-2019  5:31  700K

**Comment by Issif** [comment]
I confirme the modules for falco 0.15 et sysdig 0.25/6 are in s3 bucket :

```bash

$  aws s3 ls s3://download.draios.com/stable/sysdig-probe-binaries/ | grep amzn2 | grep "4.14.106-97"

2019-05-14 02:00:59     714648 falco-probe-0.15.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko
2019-04-01 17:57:48     712272 sysdig-probe-0.25-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko
2019-05-22 20:19:46     714712 sysdig-probe-0.26.0-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko
2019-05-28 21:18:16     714664 sysdig-probe-0.26.1-x86_64-4.14.106-97.85.amzn2.x86_64-a7281d2454de7f0821a9f5b26148085e.ko
```

**Comment by fntlnz** [comment]
Ok @prsimoes reported that he is using Falco 0.14.0 and so the module was missing for that version, I'm closing this, will open an issue on Falco to discuss about this.
