### ISSUE TITLE
Allow dragent to emit structured logs (JSON) so that they can be shipped to services such as Elasticsearch

### ISSUE THREAD

**Issue by slmingol** [draios/sysdig#1442]
Raised issue with sysdig. We noticed this option to `sysdig` CLI - https://github.com/draios/sysdig/wiki/Sysdig-Quick-Reference-Guide.

```
-j, --json
Emit output as json, data buffer encoding will depend from the print format selected.
```

This option doesn't appear to be available to dragent. I asked this question of support but don't see my RFE here in your issues.

![image](https://user-images.githubusercontent.com/15072/59710905-fa02e280-91d7-11e9-8c7b-f1b55eb95652.png)

**Comment by therealbobo** [comment]
Hi @slmingol! This repo is intended for `sysdig` cli only 😞
