### ISSUE TITLE
Kernel panic during processing signals on AWS ECS

### ISSUE THREAD

**Issue by budenny** [draios/sysdig#1459]
Don't know how to obtain panic logs from unresponsive instance, so will describe how to reproduce.

1. Create ECS EC2 based instance(t2.micro in my case).
`uname -a
Linux ip-10-0-1-102 4.14.128-87.105.amzn1.x86_64 #1 SMP Thu Jun 20 00:43:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
**The issue doesn't happen on ordinary EC2 instance only on ECS EC2-based.**
2. run sysdig under load or just don't print output: `/usr/bin/sysdig &>/dev/null`
Ordinary sysdig execution not always causes panic, without output  or continuously calling
https://github.com/draios/sysdig/blob/ee6b0c536fb4dd88d0554a7a061f521acacf8f26/userspace/libscap/scap.h#L621 always lead to panic for me(probably some kind of race-condition)

   Here how I run container:
    ```
    docker run --rm -it --privileged=true \
    --volume=/var/run/docker.sock:/host/var/run/docker.sock \
    --volume=/dev:/host/dev \
    --volume=/proc:/host/proc:ro \
    --volume=/boot:/host/boot:ro \
    --volume=/lib/modules:/host/lib/modules:ro \
    --volume=/usr:/host/usr:ro \
    sysdig/sysdig:0.26.1
   ```
    Version doesn't matter.

3. Continuously query docker in parallel: `for _ in {1..10}; do sudo docker ps -a; done`

Almost instantly machine panics during processing the following branch https://github.com/draios/sysdig/blob/ee6b0c536fb4dd88d0554a7a061f521acacf8f26/driver/main.c#L1738
It happens because `event_datap->event_info.signal_data.info` is NULL.

The following workaround-patch solved panics because I actually don't need to monitor signals but it doesn't fix root cause.
```
diff --git a/driver/main.c b/driver/main.c
index fc87685..12dc70b 100644
--- a/driver/main.c
+++ b/driver/main.c
@@ -1725,7 +1725,7 @@ static int record_event_consumer(struct ppm_consumer_t *consumer,
                        args.sched_next = NULL;
                }

-               if (event_datap->category == PPMC_SIGNAL) {
+               if (event_datap->category == PPMC_SIGNAL && event_datap->event_info.signal_data.info) {
                        args.signo = event_datap->event_info.signal_data.sig;

                        if (args.signo == SIGKILL) {
```

**Comment by leodido** [comment]
This seems to happen because `get_signal` passes a NULL pointer to the tracer function when another process is terminated (eg., `sleep 10 & (killall -9 sleep)`).

But AFAIK this only happens for newer (>=5.1.8) kernels (https://elixir.bootlin.com/linux/v5.1.8/source/kernel/signal.c#L2444).

Anyway it is better to check if the pointer passed by `get_signal` is NULL prior to accessing elements (assert macro seems to have no effect on the build in this case).

**Comment by bertocci** [comment]
Nice analysis, @budenny and @leodido! `event_datap->event_info.signal_data.info` is null when the signal is sent with SEND_SIG_NOINFO, so we'll never have an spid for those events. The workaround patch fixes most of the issues, but it's still possible to have problems in `f_sys_signaldeliver_e()`. Generally that would manifest as bogus spid values in the scap file, but I think it could cause a crash too.

This is the same issue as https://github.com/draios/sysdig/issues/1454, and I'll have a PR up soon.
