### ISSUE TITLE
Unable to load the driver error creating the process list. Make sure you have root credentials.

### ISSUE THREAD

**Issue by necsf** [draios/sysdig#1467]
I used the official image directly and ran docker according to the command they provided.But something went wrong, and I didn't know how to fix it. I tried some ways to solve the problem, but nothing worked.
`root@043b79774c90:/# sysdig`
`
Unable to load the driver
error creating the process list. Make sure you have root credentials.
`

`root@043b79774c90:/#dkms sysdig status`
`sysdig, 0.26.1, 4.15.0-55-generic, x86_64: installed (WARNING! Diff between built and installed module!)`

`root@043b79774c90:/#sysdig-probe-loader `
```
* Unloading sysdig-probe, if present
* Running dkms install for sysdig
Module sysdig/0.26.1 already installed on kernel 4.15.0-55-generic/x86_64
* Trying to load a dkms sysdig-probe, if present
sysdig-probe found and loaded in dkms
```

**Comment by nathan-b** [comment]
Hi @necsf. Thanks for your bug report! Can we get some more information?

* What distribution and version (if applicable) are you running?
* You mentioned that you ran docker according to the command provided. Can you give us that command you used?
* How did you install sysdig?

Thanks again!

**Comment by livelace** [comment]
Got the same problem under 4.19.67 (gentoo). Sysdig version is 0.26.4.

**Comment by livelace** [comment]
Found this one https://github.com/draios/sysdig/issues/820

```
localhost /usr/include # cat /proc/cgroups 
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  5       2       1
cpu     3       95      1
cpuacct 3       95      1
blkio   6       95      1
memory  8       188     1
devices 7       93      1
freezer 9       2       1
net_cls 2       2       1
perf_event      10      2       1
net_prio        2       2       1
hugetlb 4       2       1
pids    11      105     1
```

**Comment by livelace** [comment]
I run sysdig just as a regular command, without any container technology.

**Comment by necsf** [comment]
> 嗨@necsf。感谢您的错误报告！我们可以获得更多信息吗？
> 
> * 你在运行什么发行版和版本（如果适用）？
> * 你提到你根据提供的命令运行了docker。你能告诉我们你用过的那个命令吗？
> * 你是怎么安装sysdig的？
> 
> 再次感谢！


> 嗨@necsf。感谢您的错误报告！我们可以获得更多信息吗？
> 
> * 你在运行什么发行版和版本（如果适用）？
> * 你提到你根据提供的命令运行了docker。你能告诉我们你用过的那个命令吗？
> * 你是怎么安装sysdig的？
> 
> 再次感谢！

I am so sorry for replying to your message so late.
I run this command. `docker run -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro sysdig/sysdig`
But when I used another Ubuntu virtual machine, this command successfully created a sysdig container
