### ISSUE TITLE
read() exit not registered for NVME storage device

### ISSUE THREAD

**Issue by jcdutton** [draios/sysdig#1495]
When accessing the SSD, It correctly gets read() entry and exit events.
When accessing the NVME. Only the read() entry is registered. Not the read() exit.
Tests failed with kernel 5.2.9 and 5.3.0-rc6
sysdig dev branch from git commit fd30d120651166c7efffd826769881988a41b7e8

**Comment by therealbobo** [comment]
Hi @jcdutton! Could you please verify that this bug is still present in the latest version? I tried and it seems to work fine. 😄
