### ISSUE TITLE
Ability to use sysdig inside openvz/lxc/docker containers

### ISSUE THREAD

**Issue by pavel-odintsov** [draios/sysdig#152]
Hello!

sysdig perfectly work on server with many containers but it's very useful provide ability to run it inside container from container customer.

It did not work now (I checked it for OpenVZ containers):
sysdig
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.

But on hardware server sysdig module work fine.

**Comment by shawnholt** [comment]
Unfortunately, no way to get it to work inside an OpenVZ container :(

**Comment by azharz** [comment]
Too many sysdig instances attached to device /dev/sysdig0. Current value for /sys/module/sysdig_probe/parameters/max_consumers is '5'.

what should i do

**Comment by ChanderG** [comment]
Slightly tangential to this thread, but if people end up here with the same problem that @azharz has faced, this is the solution:
1. Unload the sysdig_probe module: `sudo modprobe -r sysdig_probe`.
2. Load the module with the parameter specified, eg: `sudo modprobe sysdig_probe max_consumers=10`.
