### ISSUE TITLE
Segmentation fault when running with Datadog Network Monitoring

### ISSUE THREAD

**Issue by stonith** [draios/sysdig#1529]
Getting `Segmentation fault (core dumped)` after running sysdig. It runs briefly with some output but then crashes.

Running it with: `docker run -it --name sysdig --privileged --net=host -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /etc:/host/etc:ro -e SYSDIG_BPF_PROBE="" sysdig/sysdig`

`Linux gke-core-us-central1-2-default-1-1e74006e-q801 4.14.127+ #1 SMP Tue Jun 18 23:08:40 PDT 2019 x86_64 Intel(R) Xeon(R) CPU @ 2.00GHz GenuineIntel GNU/Linux`

**Comment by davidreuss** [comment]
We see the same thing on our vms in AWS,

```
root@ip-172-16-112-185:~# docker run -it --name sysdig --privileged --net=host -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /etc:/host/etc:ro -e SYSDIG_BPF_PROBE="" sysdig/sysdig
* Setting up /usr/src links from host
* Mounting debugfs
Found kernel config at /host/boot/config-4.15.0-1052-aws
* Trying to compile BPF probe sysdig-probe-bpf (sysdig-probe-bpf-0.26.4-x86_64-4.15.0-1052-aws-8810d36069f9c098e4b86f146ce39c7e.o)
* BPF probe located, it's now possible to start sysdig
root@ip-172-16-112-185:/# sysdig

<.... a couple of pages of events .....>

Segmentation fault (core dumped)
```

Looking in dmesg afterwards...

```
[Fri Nov  1 07:23:44 2019] sysdig[17421]: segfault at 400000001 ip 0000000000651e94 sp 00007ffe8c736b38 error 4 in sysdig[400000+adb000]
```

🐼

**Comment by nathan-b** [comment]
That's interesting @davidreuss . I've been trying to reproduce this issue and even though I'm on what looks like nearly the same node that you are 
```root@ip-172-31-55-153:/# uname -a
Linux ip-172-31-55-153 4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 GNU/Linux
```
I can't make it happen...Still looking

**Comment by stonith** [comment]
Took some time to try 3 different cos images this morning and none of them crashed.

**Comment by stonith** [comment]
We have Datadog Network Performance Monitoring enabled https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L616 which seems to be conflicting with Sysdig and causing the crash.

**Comment by nathan-b** [comment]
Thanks for digging into this @stonith! No answers yet, but I'll do some digging...

**Comment by nathan-b** [comment]
@stonith : can you post your config (or preferably a minimal config which reproduces the problem)? Thanks!

**Comment by davidreuss** [comment]
fyi, we are in the same situation — datadog with network perf monitoring enabled as well .. so might be on to something ..

**Comment by stonith** [comment]
@nathan-b I tried testing on a brand new cluster and wasn't able to consistently reproduce the crashes. However, I did ocassionally. It our prod clusters just running `sysdig` will crash quite fast. However, running something like `sysdig proc.name=kubelet` may crash a few times and then may work. Removing datadog fixes however. I don't have much time right now to dig further unfortunately.

**Comment by stonith** [comment]
It's possible that we're actually running into https://github.com/draios/sysdig/issues/1475

**Comment by nathan-b** [comment]
Is this issue still happening now that #1475 is fixed?

**Comment by stonith** [comment]
Sorry, I haven't had a chance to test this since. Closing for now.
