### ISSUE TITLE
Remove references to Falco

### ISSUE THREAD

**Issue by krisnova** [draios/sysdig#1542]
Can we rename some parts of the code for architectural vanity please?

This was started https://github.com/draios/sysdig/pull/1532 but we can still see [some Falco references](https://github.com/falcosecurity/falco/search?utf8=%E2%9C%93&q=sysdig&type=) slipped through.

**Comment by nathan-b** [comment]
It looks to me that the only references to falco are in the probe builder:

```
nathan@nathanb-dev ~/src/draios/sysdig (git)-[bpf_build] % find . -print0 | xargs -0 grep -n -i -dskip "falco"            
./scripts/build-probe-binaries:62:# The previously released versions of sysdig, falco, and the agent
./scripts/build-probe-binaries:70:if [ $SYSDIG_TAG = "0.24.1" ] || [ $SYSDIG_TAG = "agent/0.85.1" ] || [ $SYSDIG_TAG = "falco/0.12.1" ]; then
./scripts/build-probe-binaries:684:	# to do the sysdig/falco/agent git clone/pulls.
./scripts/build-probe-binaries:743:	#if [ $PROBE_NAME = "falco-probe" ]; then
```

It looks like these are mostly vestigial. We can remove them if you so desire.
