### ISSUE TITLE
404 from Debian repo for ppc64el

### ISSUE THREAD

**Issue by poovannan89** [draios/sysdig#1551]
I have the below entry in /etc/apt/sources.list.d/draios.list : 
deb http://download.draios.com/stable/deb stable-$(ARCH)/

My environment is ppc64el.

The curl request for ppc64el is failing as 404. 
curl http://download.draios.com/stable/deb/stable-ppc64el/Packages
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: stable/deb/stable-ppc64el/Packages</li>
<li>RequestId: 1351797C8E24F4EF</li>
<li>HostId: w+OjGtvnHVj8VQsAP8lDa/7s/1dnOcIZSdTHaKYf7V0O2Vxocr0ib3gFiDoSA5e9Ia7CwDquPy0=</li>
</ul>
<hr/>
</body>
</html>

I get below error in sudo apt-get update also : 
Err:48 http://download.draios.com/stable/deb stable-ppc64el/ Packages
  404  Not Found

Anything changed with respect to ppc64el ?

**Comment by nathan-b** [comment]
Hi, sorry for the long delay in answering your question. We don't currently have a PPC build of sysdig.

Did this used to work for you?

**Comment by poovannan89** [comment]
Sorry for delay from my side also. Yes, it used to work earlier. I think from November 2019 or so, it was stopped or removed. I guess ppc build of sysdig was supported earlier ?

**Comment by nathan-b** [comment]
sysdig still support ppc64, but the build and release process for sysdig was retooled and I guess whatever mechanism was used to build and release the ppc64 Debian package no longer exists. Nobody that I've talked to even remembers having a ppc build, so it must have been an old system that just kept working in the background...until it didn't.

We don't currently have plans to (re)introduce a ppc build. Your options are to check out the source code and build it yourself or contact the package maintainers for your distro and request that they package sysdig for ppc64.

Sorry for the inconvenience.
