### ISSUE TITLE
Sysdig for Domain name

### ISSUE THREAD

**Issue by Changzhu1997** [draios/sysdig#1571]
While using sysdig to collect data about domain name( sysdig -p "%fd.sip.name"), it did not show anything, but it can show the ip address (sysdig -p "%fd.sip").
I have updated sysdig to 0.26. Does this version support fd.sip.name ?

**Comment by UTDEngineer** [comment]
![image](https://user-images.githubusercontent.com/58642588/71934714-ab646800-316a-11ea-832d-b5b13e54c68a.png)
Sample test for this issue. I hope i can get more information about this one.
