### ISSUE TITLE
AWS EC2 Ubuntu version update

### ISSUE THREAD

**Issue by mojoa** [draios/sysdig#1575]
AWS EC2 Ubuntu image sysdig is outdated and update instructions do not provide latest stable version of sysdig.
AWS EC2 sysdig --version is 0.19.1. And frequently crashes the instance.
Current update instructions do not update to latest stable version (26.4):
https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux

**Comment by mojoa** [comment]
Someone is working on this. Thanks!
1 package can be updated.
Unpacking sysdig (0.26.4) over (0.19.1-1ubuntu1.1) ...
Setting up sysdig (0.26.4) ...
# sysdig --version
sysdig version 0.26.4

**Comment by nathan-b** [comment]
Hi @mojoa . Is your problem sorted (for now, at least)?

**Comment by mojoa** [comment]
Yes, thanks!
