### ISSUE TITLE
URL "https://sysdig.org" is just an adware page now

### ISSUE THREAD

**Issue by JamesBlandford** [draios/sysdig#1579]
The "official" website now redirects multiple times and lands on advertising spam

**Comment by nathan-b** [comment]
Thanks for reporting this. Looking into it...

**Comment by ffledgling** [comment]
Seconded, please fix this.

**Comment by dsever** [comment]
Have the same problem here, and it is blocked by FW

**Comment by nathan-b** [comment]
This should be fixed now. sysdig.org and sysdig.net should both redirect to sysdig.com
