### ISSUE TITLE
K8S deployment/damonset

### ISSUE THREAD

**Issue by dsever** [draios/sysdig#1581]
Hi,

For research purposes, I would like to export syscalls from K8s cluster (I don't need full falco, only basic syscalls), I saw In past there was some tries, but in repo can't find anything useful for k8s, so if anyone done it so far please can you share some detail with me.

Dubravko

**Comment by pawelprazak** [comment]
this might be of interest to you, I needed to run sysdig as a DaemonSet on k8s some time ago, not that the nodes might require additional packages, like kernel headers
https://github.com/VirtusLab/ergaleia

**Comment by saiyam1814** [comment]
Hi @pawelprazak I tried running ergaleia but when I run 
`sysdig -c spy_user` it gives below error :
Unable to load the driver
error opening device /host/dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.

**Comment by dsever** [comment]
@pawelprazak 

You are missing module, try to run sysdig-probe-loader
