### ISSUE TITLE
sysdig-probe event drops on Ubuntu 18.04.3 LTS with 0.26.4.x

### ISSUE THREAD

**Issue by budenny** [draios/sysdig#1584]
There were ubuntu 18.04 LTS update last week which brought  **linux-image-5.3.0-26-generic:amd64** to the system. sysdig-probe reports event drops since that time. It happens both for official sysdig/sysdig docker image and ubuntu deb package.

**The issue solves with sysdig-probe 0.26.5 built from github sources.**

Unfortunately, there are no officially published neither sysdig/sysdig docker image nor deb package to update app to working version. Could you please deploy official docker image with version 0.26.5

Machine with repro:

> _Linux ubuntu **5.3.0-26-generic** #28~18.04.1-Ubuntu SMP Wed **Dec 18 16:40:14 UTC 2019** x86_64 x86_64 x86_64 GNU/Linux_

> _No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	**Ubuntu 18.04.3 LTS**
> Release:	18.04
> Codename:	bionic_
> 
> 

scap-validatebuffer from sysdig-master/userspace/libscap/examples/02-validatebuffer:

> ..
> bps:2317852129 totbytes:13275124241 - evts/s:39516436 totevs:225809086 **drops:12856**
>  0)bps:34936732 totbytes:174790204 - evts/s:706082 totevs:3303893
>  1)bps:121741366 totbytes:727224860 - evts/s:2748296 totevs:16469595
>  2)bps:32864054 totbytes:196184918 - evts/s:610054 totevs:3673934
>  3)bps:211156464 totbytes:1584434097 - evts/s:3731730 totevs:27158960
>  4)bps:940244048 totbytes:7442784751 - evts/s:15843807 totevs:123119176
>  5)bps:1235667492 totbytes:5726315567 - evts/s:20515427 totevs:96238924
> bps:2576610156 totbytes:15851734397 - evts/s:44155396 totevs:269964482 **drops:14121**

Same machine prior to update:
> Linux ubuntu 5**.0.0-37-generic** #40~18.04.1-Ubuntu SMP Thu **Nov 14 12:06:39 UTC 2019** x86_64 x86_64 x86_64 GNU/Linux

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	**Ubuntu 18.04.2 LTS**
> Release:	18.04
> Codename:	bionic

./scap-validatebuffer
> 0)bps:3027306868 totbytes:3027306868 - evts/s:61439049 totevs:61439049
>  1)bps:1592874317 totbytes:1592874317 - evts/s:31235467 totevs:31235467
>  2)bps:1573195876 totbytes:1573195876 - evts/s:31810872 totevs:31810872
>  3)bps:4045296796 totbytes:4045296796 - evts/s:79688329 totevs:79688329
>  4)bps:4650361230 totbytes:4650361230 - evts/s:91639896 totevs:91639896
>  5)bps:3411117068 totbytes:3411117068 - evts/s:67165993 totevs:67165993
> bps:18300152155 totbytes:18300152155 - evts/s:362979606 totevs:362979606 **drops:0**

**Comment by bertocci** [comment]
0.26.5 is marked as a pre-release. We're working on getting the release out, at which point we'll deploy the docker image for that version.
