### ISSUE TITLE
Handling signals

### ISSUE THREAD

**Issue by mechmind** [draios/sysdig#160]
It would be very useful to show incoming signals for a process and especially - trace origin of them, if possible.

**Comment by mechmind** [comment]
It have been implemented? Or closed because wontfix?

**Comment by gianlucaborello** [comment]
It's been supported for a few releases now, take a look at the signaldeliver event:

```
signaldeliver(PID spid, PID dpid, SIGTYPE sig)
```

I hope it's what you were looking for.

**Comment by mechmind** [comment]
Nice, thanks!
