### ISSUE TITLE
"renameat2" syscall support

### ISSUE THREAD

**Issue by budenny** [draios/sysdig#1603]
Some applications like "mv" on RHEL 8.1 are using renameat2 syscall for file rename operations. Sysdig driver doesn't provide information about this syscall.

RHEL8.1:

[user@localhost ~]$ sudo sysdig proc.name=mv | grep newname
...

[user@localhost ~]$ sudo strace mv oldname newname 2>&1 | grep rename
**renameat2**(AT_FDCWD, "oldname", AT_FDCWD, "newname", RENAME_NOREPLACE) = 0

Ubuntu 18.04:
sudo sysdig proc.name=mv | grep newname
...
8853 05:32:48.621815439 1 mv (5522) < **rename** res=0 oldpath=old(/home/user/old) newpath=newname(/home/user/newname)

**Comment by leogr** [comment]
The same issue on Arch `5.6.15-arch1-1`.
