### ISSUE TITLE
Document behavior of leading asterisk/star in format string

### ISSUE THREAD

**Issue by chrahunt** [draios/sysdig#1606]
Currently, if the format string provided to sysdig (`-p`) references a field that does not exist in an event then that event is not printed.

If an asterisk is specified as the first character of the format string, then all events will be output even if they are missing a field specified in the format string. See, for example:

```
# sysdig --json -p "*%evt.type %proc.pid %proc.pid %proc.ppid %proc.name %proc.args %evt.time %evt.dir %evt.res %evt.arg.flags" "evt.type in ('procexit', 'fork', 'vfork', 'execve', 'clone')"
{"evt.arg.flags":null,"evt.dir":">","evt.res":null,"evt.time":1584898602360388184,"evt.type":"clone","proc.args":"","proc.name":"python","proc.pid":16427,"proc.ppid":7571}
{"evt.arg.flags":"CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID","evt.dir":"<","evt.res":"SUCCESS","evt.time":1584898602360610872,"evt.type":"clone","proc.args":"","proc.name":"python","proc.pid":16427,"proc.ppid":7571}
```

Notice that the first "enter" event doesn't have `evt.arg.flags` so the value is just `null`. Without the leading "*" in the format string this first event would not be printed.

This makes it pretty easy to use `sysdig` to get a bunch of fields for various types of events from a trace file or from the system with 1 invocation, and `null` is a good value to use to identify missing fields. None of this behavior seems to be documented, though.

In some of the examples in the documentation there is a leading asterisk but no explanation. From [here](http://man7.org/linux/man-pages/man8/sysdig.8.html):

> By default, sysdig prints the information for each captured event  on  
a single line, with the following format:
> *%evt.num %evt.time %evt.cpu %proc.name (%thread.tid) %evt.dir %evt.type %evt.in‐  
fo

We should document this so it's easier to discover and call out the specific behavior users should expect on normal and json-format output. Currently for missing field values normal output prints `<NA>` and json output uses a `null`.

**Comment by chrahunt** [comment]
This was also described in [#345 (comment)](https://github.com/draios/sysdig/issues/345#issuecomment-88592998).

**Comment by jordan-wright** [comment]
Just wanted to chime in that this can probably be closed depending on what you mean by "document". In the current user guide, I see:

> By default, a line is printed only if all the fields specified by –p are present in the event. You can, however, prepend the string with a * to make it print no matter what. In that case, the missing fields will be rendered as <NA>.

I will suggest that it's _kind of_ buried but someone reading the guide should catch it.
