### ISSUE TITLE
eBPF driver does not compile on CentOS 8

### ISSUE THREAD

**Issue by smijolovic** [draios/sysdig#1611]
For reference, bug filed in Falco:
https://github.com/falcosecurity/falco/issues/1129

Falco version: 0.21.0
CentOS 8.1
kernel version 4.18.0-147.5.1.el8_1.x86_64

cmake -DBUILD_BPF=ON ..
make bpf

falco-0.21.0/build/sysdig-repo/sysdig-prefix/src/sysdig/driver/bpf/fillers.h:1369:21: error: no member named 'pids' in 'struct task_struct'
return _READ(task->pids[PIDTYPE_PID].pid);

Digging into the fillers.h file, I noticed the following 4 lines:
1368 #if LINUX_VERSION_CODE < KERNEL_VERSION(4, 19, 0)
1405 #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 19, 0)
1424 #if LINUX_VERSION_CODE < KERNEL_VERSION(4, 19, 0)
1447 #if LINUX_VERSION_CODE < KERNEL_VERSION(4, 19, 0)

It appears as if the kernel versions might be too "forward". When those 4 lines were replaced with:
KERNEL_VERSION(4, 18, 0)

The driver compiled cleanly with no errors or warnings.

**Comment by smijolovic** [comment]
Wondering if it behaves differently in mainline vs CentOS8/RHEL8 4.18.0-147+

**Comment by nathan-b** [comment]
This might be a backport issue. Thanks for reporting.

**Comment by leodido** [comment]
Yes @nathan-b it is. Patches about `.pids[]` and `__PIDTYPE_TID` have been backported.

@fntlnz and I approached the problem on branch `fix/filler_procstartupdate3_bpf_functions` ([diff](https://github.com/draios/sysdig/tree/fix/filler_procstartupdate3_bpf_functions)), but still far from have a real working fix.

**Comment by nathan-b** [comment]
@leodido @fntlnz Check out https://github.com/draios/sysdig/pull/1276

It's old, but it might be a good starting point

**Comment by nathan-b** [comment]
I believe #1650 should have solved this issue. @leodido, @fntlnz, I think we can just close this bug. Do you agree?

**Comment by leodido** [comment]
Yup :)
