### ISSUE TITLE
Copying sysdig sump files to remote storage

### ISSUE THREAD

**Issue by jaychan-q** [draios/sysdig#1613]
Hello All, Is there a way to generate sysdig dump files based on the timestamp ? I am trying to copy the dump files to gcp storage and not want to overwrite the files. Currently i am doing this (which generates dumps every 15 min and keeps 5 files).

`sysdig -G 900 -W 5 -qw /opt/sysdig_dumps/sysdig-$(date +'%Y%m%d-%H%M%S').scap`
This generates files like below and first file gets overwritten after 5th dump file is generated.
sysdig-20200406-212213.scap0
sysdig-20200406-212213.scap1
sysdig-20200406-212213.scap2
sysdig-20200406-212213.scap3
sysdig-20200406-212213.scap4

How do we keep these dump files without getting overwritten and sent to remote storage? 

Thanks

**Comment by kristopolous** [comment]
Logrotate can handle all of this, including the timestamp.
