### ISSUE TITLE
sysdig 0.26.7 does not compile on centos7

### ISSUE THREAD

**Issue by vela-security** [draios/sysdig#1627]
[  3%] Built target b64
[  7%] Built target c-ares
[ 11%] Built target openssl
[ 15%] Built target curl
[ 19%] Built target zlib
[ 23%] Built target protobuf
[ 23%] Performing build step for 'grpc'
[HOSTLD]  Linking /root/sysdig-0.26.7/build/grpc-prefix/src/grpc/bins/opt/grpc_cpp_plugin
/bin/ld: cannot find -ldl
/bin/ld: cannot find -lrt
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lstdc++
/bin/ld: cannot find -lm
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[3]: *** [/root/sysdig-0.26.7/build/grpc-prefix/src/grpc/bins/opt/grpc_cpp_plugin] Error 1
make[2]: *** [grpc-prefix/src/grpc-stamp/grpc-build] Error 2
make[1]: *** [CMakeFiles/grpc.dir/all] Error 2
make: *** [all] Error 2

**Comment by guardiande** [comment]
You need to install static versions of some standard libraries...

This is on FC32:

```
glibc-static.x86_64                                2.31-2.fc32                        @fedora
libstdc++-static.x86_64                            10.0.1-0.13.fc32                   @updates
```

**Comment by therealbobo** [comment]
We'll close this issue. Please feel free to reopen if you encounter this problem again! 😄

**Comment by therealbobo** [comment]
Hi @vela-security! Did you solved this issue? 😄
