### ISSUE TITLE
403 from Debian repo

### ISSUE THREAD

**Issue by abraithwaite** [draios/sysdig#163]
Getting this error when trying to update/download sysdig.

```
W: Failed to fetch http://download.draios.com/stable/deb/stable-amd64/Packages  403  Forbidden
```

Visiting the url in the browser results in a 403 as well:

```
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: F96FDD6ADACF78A5
HostId: 3R9QB6kgR4g1lo<snip>Nha8WSglIjr+fpPUx0Yeaz+yj
```

**Comment by FedericoCeratto** [comment]
Sysdig is packaged in Debian: https://packages.debian.org/sid/sysdig

**Comment by luca3m** [comment]
Yes, if you want to keep up to date with last features, use our repositories.
