### ISSUE TITLE
FTBFS on MIPS architectures

### ISSUE THREAD

**Issue by hlieberman** [draios/sysdig#1644]
Since Linux 5.0, MIPS syscalls are built from a table.  This change causes sysdig to fail to build from source, as it fails to correctly determine the base syscall value.  For most architectures, this is zero, but for mips, it is [456]000.

PR #1643 closes this issue; this patch is currently deployed into Debian unstable.

**Comment by nathan-b** [comment]
I accepted your PR. Thanks for your contribution!
