### ISSUE TITLE
*at syscalls (eg., unlinkat, fchmodat, execveat, etc.) handle pathname args differently from their corrispectives

### ISSUE THREAD

**Issue by leodido** [draios/sysdig#1659]
While working with @fntlnz on the filler for `execveat`, we discovered that `*at` syscalls have a common behavior that was not detected and correctly handled by sysdig.

As you can read into `man 2 fchmodat` (but the same applies for `exceveat` or `unlinkat`, etc.)

> The  fchmodat()  system call operates in exactly the same way as chmod(), except for the differences
>  described here.
> 
> If the pathname given in pathname is relative, then it is interpreted relative to the directory  re‐
> ferred to by the file descriptor dirfd (**rather than** relative to the current working directory of the
> calling process, as is done by chmod() for a relative pathname).
> 
> If pathname is relative and dirfd is the special value AT_FDCWD, then pathname is interpreted  rela‐
> tive to the current working directory of the calling process (like chmod()).
> 
> If pathname is absolute, then dirfd is ignored.

the `pathname` argument does not always refer to the current working directory (as sysdig is currently handling it).

In fact, if the `pathname` is relative, for `*at` syscalls, it should be considered relative to the directory specified by the `dirfd` file descriptor.

For example:

```c
#include <sys/stat.h>

#include <fcntl.h> /* Definition of AT_* constants */
#include <sys/stat.h>
#define AT_FDCWD -100
int main()
{
    int dirfd = open("/tmp/test1/", O_RDONLY);
    fchmodat(dirfd, "rel1", S_ISUID, 0);
}
```

**current**: `dirfd=/tmp/test1 filename=rel1(/vagrant/rel1)`
**expected**:  `dirfd=/tmp/test1 filename=rel1(/tmp/test1/rel1)`

As you can see sysdig currently reports the filename absolute path as `/vagrant/rel1` since I'm executing the above C snippet from `/vagrant`, while in reality, the file I'm setting SUID on is `/tmp/test1/rel1` (executing such script from `/vagrant`).

This can lead to vulns, IMHO.

Anyways it affects all the `*at` syscalls with `dirfd` and `pathname`, also the one with two combinations of such arguments (old, new).

---

The other cases about `pathname` relation with `dirfd` works:

```c
#include <sys/stat.h>

#include <fcntl.h> /* Definition of AT_* constants */
#include <sys/stat.h>
#define AT_FDCWD -100
int main()
{
    fchmodat(AT_FDCWD, "/tmp/test1/rel1", S_ISUID, 0);
}
```

**current**: `dirfd=AT_FDCWD filename=rel1(/tmp/test1/rel1)`
**expected**: `dirfd=AT_FDCWD filename=/tmp/test1/rel1`

```c
#include <sys/stat.h>

#include <fcntl.h> /* Definition of AT_* constants */
#include <sys/stat.h>
#define AT_FDCWD -100
int main()
{
    fchmodat(AT_FDCWD, "rel1", S_ISUID, 0);
}
```

**current**: `dirfd=AT_FDCWD filename=rel1(/vagrant/rel1)`
**expected**: `dirfd=AT_FDCWD filename=rel1(/vagrant/rel1)`

**Comment by fntlnz** [comment]
I'm reopening this since we had to revert the changes here https://github.com/draios/sysdig/pull/1679
