### ISSUE TITLE
Data security in sysdig monitoring

### ISSUE THREAD

**Issue by dongwangdw** [draios/sysdig#1665]
Maybe it is not the right place for the enterprise issue. Please help it.
I have a perhaps silly question. If we use sysdig monitoring, our data will be stored in your side not our own? right? Because I found in your doc that the data retention will differ according to the cost.

**Comment by nathan-b** [comment]
This site is for the open-source `sysdig` program, not the commercial offering. 

To get information about the commercial offering, go to [sydig.com](https://sysdig.com). A chat box will pop up and you can ask questions there.
