### ISSUE TITLE
csysdig doesn't work with xterm-256color

### ISSUE THREAD

**Issue by deric** [draios/sysdig#1675]
On Debian 10:
```
$ csysdig 
Error opening terminal: xterm-256color.
```
Simply running:
```
$ TERM=xterm csysdig
```
works fine. Would it be possible to support `xterm-256color`?

**Comment by deric** [comment]
The issue could be solved by installing `ncurses-term`. Maybe add as a dependency?

**Comment by kristopolous** [comment]
Assuming you used the debian official this is best resolved by contacting the maintainers (the current ones will always be listed at https://tracker.debian.org/pkg/sysdig) @evgeni is the user on github. Maybe they will see this thread in their menchies.

**Comment by evgeni** [comment]
I must admit I didn't do much around sysdig in recent times, @hlieberman was doing most of the work ;)

But your suggestion sounds pretty reasonable to me.
