### ISSUE TITLE
Sysdig CPU Usage at 100% - Oracle Linux 7

### ISSUE THREAD

**Issue by denis738** [draios/sysdig#1692]
I've run into a CPU Usage issue when running sysdig on a few of my Oracle Enterprise Linux 7 devices. I'm currently running Sysdig version 0.26.7 on the systems and the sysdig process shows that it is utilizing 100% CPU when running the top command. Has anyone ever experienced this before? Where is the best place to look and see why Sysdig's CPU usage is at 100%?

**Comment by kristopolous** [comment]
What's the output of strace on the pid? There's probably a busy loop somewhere, poll and select are frequent culprits.

**Comment by therealbobo** [comment]
We'll close this issue. Please feel free to reopen if you encounter this problem again! 😄

**Comment by therealbobo** [comment]
Hi @denis738! Any update on this?
