### ISSUE TITLE
installing sysdig on alpine linux

### ISSUE THREAD

**Issue by jaberelmazini** [draios/sysdig#1707]
the usual directive (Cf. Wiki section) doesn't do the job.
each time the make build fail !!
any structured process dedicated to alpine (exact dependencies needed, cmake parameters, ...) ?

**Comment by kristopolous** [comment]
can you be a bit more specific? Copy/ paste from your terminal would be helpful

**Comment by Slach** [comment]
@kristopolous I think @jaberelmazini means
`curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash`
doesn't work
```
Unsupported operating system. Please consider writing to the mailing list at
https://groups.google.com/forum/#!forum/sysdig or trying the manual
installation.
```
and manual installation doesn't applicable to Alpine Linux

**Comment by nathan-b** [comment]
Alpine Linux uses musl rather than glibc, so it's a bit of a special case. 

@fntlnz and @leodido added build options for targeting musl instead of glibc in https://github.com/draios/sysdig/pull/1682. Maybe check those out?
