### ISSUE TITLE
sysdig-probe module cross compilation for ARM in bitbake

### ISSUE THREAD

**Issue by nats5886** [draios/sysdig#1708]
Hi,

I am trying to compile sysdig-probe kernel module from yoctoLinux morty branch with below changes in sysdig_git.bb
Compilation got succeeded, both userspace sydig binaries and sysdig-probe.ko are generated. 
However, the sysdig-probe.ko is compiled for host x86_64 architecture.
userspace binaries are compiled for ARM architecture.

I explored but not able to find the reason for this strange behaviour?
Do we need to set  any other parameters for kernel module compilation?

 SRCREV = "85d16f33a82a17f87ccdbc088749271c71d87013"
 PV = "0.1.102+git${SRCPV}"

+EXTRA_OEMAKE += "KERNELDIR=${STAGING_KERNEL_BUILDDIR}"
 EXTRA_OECMAKE = ' -DUSE_BUNDLED_LUAJIT="OFF" \
                   -DUSE_BUNDLED_ZLIB="OFF" \
-                  -DBUILD_DRIVER="OFF" \
+                  -DBUILD_DRIVER="ON" \

Regards
Natarajan

**Comment by nathan-b** [comment]
You are correct, this behavior is surprising and strange.

Can you try manually building the driver?
