### ISSUE TITLE
Sysdig Failed to use automatic installation script

### ISSUE THREAD

**Issue by ferrymo** [draios/sysdig#1710]
The following is the complete installation information！

[admin@iZ256hvj5s6Z usr]$ curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
* Detecting operating system
* Installing sysdig public key
* Installing sysdig repository
* Installing kernel headers
https://download.sysdig.com/stable/rpm/x86_64/repodata/repomd.xml: [Errno 14] problem making ssl connection
Trying other mirror.
Error: Nothing to do
Unable to find kernel development files for the current kernel version 4.4.241-1.el6.elrepo.x86_64
This usually means that your system is not up-to-date or you installed a custom kernel version.
The installation will continue but you'll need to install these yourself in order to use sysdig.
Please write to the mailing list at https://groups.google.com/forum/#!forum/sysdig
if you need further assistance.
* Installing sysdig
Package sysdig-0.27.1-1.x86_64 already installed and latest version
FATAL: Module sysdig_probe not found.

**Comment by ghost** [comment]
Same problem occurs here.

My environment is:
```bash
$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

$ yum list installed kernel*
...
kernel.x86_64 3.10.0-1127.el7 @anaconda
kernel.x86_64 3.10.0-1160.6.1.el7 @updates 
kernel-devel.x86_64 3.10.0-1160.6.1.el7 @updates 
kernel-headers.x86_64 3.10.0-1160.6.1.el7 @updates 
kernel-tools.x86_64 3.10.0-1160.6.1.el7 @updates 
kernel-tools-libs.x86_64 3.10.0-1160.6.1.el7 
```

The cause seems to be `yum -y install kernel-devel-$(uname -r)` results in error as below.

```bash
# yum -y install kernel-devel-$(uname -r)
...
No package kernel-devel-3.10.0-1127.el7.x86_64 available.
Error: Nothing to do
```

Scripts(https://s3.amazonaws.com/download.draios.com/stable/install-sysdig) tries to execute the command, but it failures.

```bash
KERNEL_VERSION=$(uname -r)
	if [[ $KERNEL_VERSION == *PAE* ]]; then
		yum -q -y install kernel-PAE-devel-${KERNEL_VERSION%.PAE} || kernel_warning
	elif [[ $KERNEL_VERSION == *stab* ]]; then
		# It's OpenVZ kernel and we should install another package
		yum -q -y install vzkernel-devel-$KERNEL_VERSION || kernel_warning
	elif [[ $KERNEL_VERSION == *uek* ]]; then
		yum -q -y install kernel-uek-devel-$KERNEL_VERSION || kernel_warning
	else
		yum -q -y install kernel-devel-$KERNEL_VERSION || kernel_warning
	fi
	echo "* Installing sysdig"
```

Could you improve somehow?

**Comment by ASmoliak** [comment]
Does anyone have a solution to this? is this even a problem?

I have a situation exactly like this, updating the kernel to the latest version solves this, it seems that it is likely because there are no packages that are corresponding to the current kernel you have anymore, only headers to the latest version of the kernel.

Even if I can update the kernel, I will still have to reboot the system in order to begin using the new kernel, and this is NOT an option.
