### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [draios/sysdig#1726]
Hi Team,

I am trying to use the **sysdig/agent** image on arm64 platform but it seems it is not available for arm64. So I tried to build **sysdig/agent** image on my arm64 local machine using command **docker build -t image_name .** but it is failing as it is trying to download following deb files which are not available for arm64 in the mentioned link:
cpp-5_5.5.0-12
gcc-5-base_5.5.0-12
gcc-5_5.5.0-12
Libasan2_5.5.0-12
libgcc-5-dev_5.5.0-12 
libisl15_0.18-4
libmpx0_5.5.0-12

It will be very helpful if the image is released for the ARM64 platform. If required, I am happy to contribute. But as a start, Can you please provide me with some pointers on the above deb files and issues?

**Comment by nathan-b** [comment]
As far as I know, none of the package installers (.deb and .rpm) have been tested on arm64. You may need to build it yourself (I'm not 100% sure that it will build on arm64, but I believe it did at one point at least :))
