### ISSUE TITLE
Can't capture 'echo' command

### ISSUE THREAD

**Issue by pqhais** [draios/sysdig#1736]
Hi, 

It's my first time with sysdig and I found it very intuitive so far, but I'm struggling to capture the 'echo' command.

My situation: 

- I'am running sysdig on my host machine, which is monitoring the commands executed on multiple containers, one at a time.
- I use: 'sysdig -pc -c spy_users container.name=my_docker' for this purpose. However, it seems like sysdig misses capturing the 'echo' command:
    - Commands executed on the containter:
     `user@docker:~$ touch test.sh`
     `user@docker:~$ chmod 775 test.sh` 
     `user@docker:~$ rm test.sh`
     `user@docker:~$ echo this string will never be shown by sysdig`
     `this string will never be shown by sysdig`

    - Sysdig output:
    `user@host:~$ sudo sysdig -pc -c spy_users container.name=docker`
    `2146 10:08:01 user@docker) touch test.sh`
    `2146 10:08:06 user@docker) chmod 775 test.sh`
    `2146 10:08:11 user@docker) rm test.sh`

- After some investigation and filtering the raw output of 'sysdig', I found that 'echo' command is captured as:
    - proc.name=bash
    - evt.type=write
    - the 'write' event inlcudes a 'data' field where the string to be printed is shown:
`211314 13:50:40.027291399 3 bash (5716) < write res=19 data=echo this string will never be shown by sysdig`

- These proc.name and evt.type are very generic, but filtering something like 'starts with echo' in the 'data' field might be possible (I don't know if this can be done). As I said before I'm new with this tool so there might be other easier ways to achieve the same goal, so I'd appreciate any kind of help.

Thanks in advance!

**Comment by holyspectral** [comment]
If you specify a full path for echo, like `/bin/echo`, would sysdig or strace detect it?
Echo is also a built-in command of bash, so in that case it would be difficult to detect this usage.

**Comment by pqhais** [comment]
Thanks for your response!

Yes it would. Besides, I did a little trial and error and  it turns out the `echo` command is captured at least in the next two situations:
- `/bin/echo my_string` 
     - Sysdig output: `2146 10:08:01 user@docker) /bin/echo my_string`
- `sudo echo my_string` as sudo commands are shown as duplicated, first with the `sudo` prefix and then without it.
     - Sysdig output: 
         - `2146 10:08:01 user@docker) sudo echo my_string`
         - `2146 10:08:01 user@docker) echo my_string`

- Apart from this, if echo is used for execution purposes, e.g. given `echo 'cd /etc/' | bash`, it is captured as `cd /etc/`. Sysdig does great with `execve` calls but I can't figure out what's going on with `echo` as sometimes it's captured, sometimes it's not.

**Comment by holyspectral** [comment]
yeah it looks like it pretty much depends on bash's implementation.  `bash`'s source code may provide some hints regarding how this is implemented.
