### ISSUE TITLE
proc.cmdline is truncated

### ISSUE THREAD

**Issue by laurentdelosieresmano** [draios/sysdig#1740]
Hello,

It seems that the max size buffer for the first argument of the cmd line is set to 16 characters (15 characters + end character), any other characters are truncated. For instance, if I am monitoring all the commands that are executed in the Docker, and I am executing the following command `docker-credentials-get-ecr get`, I will get a truncated log as follows:

`15:09:17.644416967: Notice A command is run in container (user=root infallible_bartik (id=95e3ff695740) parent=sh cmdline=docker-credenti get)`.

Best,
Laurent

**Comment by therealbobo** [comment]
Hi @laurentdelosieresmano! The `proc.cmdline` is actually `proc.name + proc.args` (https://github.com/falcosecurity/libs/blob/2024af2e264e1cd76ec8bc43924f1857937848a8/userspace/libsinsp/filterchecks.cpp#LL1880C2-L1880C2) and `proc.name` is taken from `/proc/<pid>/comm` which is the basename of the executable truncated after 15 char (this is just how the kernel works). Maybe you could use `proc.exe` (which is actually `argv[0]`) but there is no guarantee that it represents the actual name of the process. 😞 I close this but feel free to reopen if you need any further information or if you have any idea to improve this behaviour! 😄
