### ISSUE TITLE
Binaries and Docker image for s390x architecture

### ISSUE THREAD

**Issue by kun-lu20** [draios/sysdig#1746]
Hello, we are trying to add s390x support for .deb, .rpm files and docker image released officially by the community.
However we could not find any information on the process used to build and release the same.
Considering s390x is already a part of existing Travis CI. Wondering if support can be extended to binaries and docker image as well. Thanks.

**Comment by kun-lu20** [comment]
Hello, we're looking for feedback for this issue. Could anyone help with this? Thanks!

**Comment by kun-lu20** [comment]
@nathan-b Could you please take a look? Thanks!

**Comment by kun-lu20** [comment]
@fntlnz Could you please take a look? Thank you very much!

**Comment by nathan-b** [comment]
Hi @kun-lu20 , sorry for the lack of response.

I will look into this and get back to you.

**Comment by kun-lu20** [comment]
@nathan-b Thank you very much!

**Comment by nathan-b** [comment]
Hi @kun-lu20. This repository is in a bit of a transitional state right now. We're having larger discussions internally about the sysdig release process and what it's going to look like going forward. Hopefully the result will provide you with the tools you need to modify the build and add s390x support.

Thank you for your patience as we figure this stuff out.

**Comment by kun-lu20** [comment]
Hi @nathan-b , thank you very much! We're looking forward to hearing the result.

**Comment by kun-lu20** [comment]
Hi @nathan-b , any updates from the sysdig release process? Thanks!

**Comment by nathan-b** [comment]
Hi @kun-lu20. I know we've kept you waiting a long time. I gave the issue another push, and it sounds like we are really going to try to make re-engineering the release process a priority. Thanks for your patience, as always, and I do hope that we can have something for you soon!

**Comment by kun-lu20** [comment]
Hi @nathan-b , thank you so much! We're looking forward to hearing about the new release process.

**Comment by zuc** [comment]
Hi @kun-lu20, I'm currently working on this with some other folks from the OSS team. We still don't have a precise ETA but will keep you updated. Thanks for your patience!

**Comment by kun-lu20** [comment]
Hi @zuc , thanks for letting me know! We're looking forward to hearing the updates from you!

**Comment by nathan-b** [comment]
Hi @kun-lu20, it's been a while! In case you have not heard, the Sysdig release process is now moving into the open. We have released 0.28.0 (https://github.com/draios/sysdig/releases/tag/0.28.0) using this new process.

**Comment by kun-lu20** [comment]
Thanks @nathan-b ! That's great news! We'll look into the new release process in GitHub Actions to see how we can add s390x support.
