### ISSUE TITLE
Container metadata not collected with Podman

### ISSUE THREAD

**Issue by 0snug0** [draios/sysdig#1748]
Feature Request:
Support Podman Runtime

Problem:
Running Sysdig on a host with Podman, each container shows up as a host. Podman is being pushed heavily with RHEL 8 and OCP 4.6, and will likely see strong adoption going forward.

**Comment by FedeDP** [comment]
Hi!
Just a quick heads up: this is being implemented in https://github.com/falcosecurity/libs/pull/67.  
It will hopefully get merged soon ;)

**Comment by jasondellaluce** [comment]
I think this should be solved right now, right @FedeDP?

**Comment by FedeDP** [comment]
Yep it is!
