### ISSUE TITLE
Running with bpf fails (on manually compiled sysdig)

### ISSUE THREAD

**Issue by yjGT** [draios/sysdig#1751]
Building completes without error.

Running sysdig fails with err 14 when loading bpf probe.
`~/sysdig/build/userspace/sysdig$ sudo ./sysdig --bpf=/home/yang/sysdig/build/driver/bpf/probe.o`
`bpf_load_program() err=14 event=filler/terminate_filler message=`

Kernel 5.4.0, ubuntu20.04, LLVM, clang 8.0
sysdig commit: fd59f0e75c6d10a9
falcosecurity/libs commit: 9d15f29ae930421b83cae50b553ae7dfc6328e03

**Comment by btruong-pjr** [comment]
I've come across the same issue, have you found a workaround?
Kernel 5.8.0, Linux Mint 20, clang 10

**Comment by tzachiabo** [comment]
I am having the same issue, 
Did you find a workaround?

**Comment by FedeDP** [comment]
Hi @tzachiabo !
On which version of sysdig are you seeing this error?

**Comment by therealbobo** [comment]
At the moment it seems to work! Please feel free to reopen the issue if you encounter it again! 😄 @tzachiabo

**Comment by therealbobo** [comment]
Any update on this? 😄 @tzachiabo @btruong-pjr @yjGT

**Comment by linajiang** [comment]
same issue ,any updates?

**Comment by therealbobo** [comment]
Hi @linajiang! Could you give more info? e.g. sysdig version, kernel version, distro... 😄
