### ISSUE TITLE
sysdig can't monitor the event in pod create 

### ISSUE THREAD

**Issue by terenceli** [draios/sysdig#1752]
When I start 'sysdig -k <k8s api-server> -pk k8s.pod.name=<pod_name>'

I can't get the entry point execution event of the new create pod.
For example, for a nginx image, I hope we can get the event of 'execve of nginx'. However, I don't get that.

Is this a bug or I missed anything?

Thanks

**Comment by nyrahul** [comment]
Hi @terenceli, did you get this working?

For me, I couldn't get filtering based on any k8s filters.
For details, please [check](https://github.com/draios/sysdig/issues/1756#issuecomment-837047055).
