### ISSUE TITLE
Sysdig fails to parse connect events to abstract unix sockets

### ISSUE THREAD

**Issue by HybridReaverHD** [draios/sysdig#1758]
there can be abstract unix sockets in which the sockaddr_un ->sun_path will start with \x00 (NULL_TERMINATOR)
in those cases sysdig fails to parse the unix socket name (since it start with a terminator) and the fd.name becomes empty

links:
abstract unix sockets - [Link](https://unix.stackexchange.com/questions/206386/what-does-the-symbol-denote-in-the-beginning-of-a-unix-domain-socket-path-in-l)
how strace handles this - [Link](https://github.com/strace/strace/blob/fcd88d188802a8628b465ebd4d5561564d3552bd/src/sockaddr.c#L57)

from strace:
![image](https://user-images.githubusercontent.com/82084130/118640147-50706580-b7e1-11eb-80ca-11c7e9af2979.png)

from sysdig:
![image](https://user-images.githubusercontent.com/82084130/118640432-a218f000-b7e1-11eb-9006-c983f028f469.png)

how to recreate:
  in terminal: sysdig "proc.name=xwd and evt.type=connect"
  in another terminal: xwd -out screenshot.img

**Comment by HybridReaverHD** [comment]
probably related to [another issue](https://github.com/draios/sysdig/issues/452)

**Comment by HybridReaverHD** [comment]
@nathan-b  Could you please take a look? Thanks!

**Comment by nathan-b** [comment]
Hi @HybridReaverHD, thanks for the bug report!

Can you say what the expected output of sysdig would be in this case?

**Comment by idanh-cynet** [comment]
@nathan-b the way strace handles this is by adding "@" to the start of the socket name ("@/tmp/.X11-unix/X10") to specify its an abstract UNIX socket

but the important part in my opinion is to print the socket name _which currently is empty_ because of the NULL terminator

**Comment by HybridReaverHD** [comment]
@nathan-b the way strace handles this is by adding "@" to the start of the socket name ("@/tmp/.X11-unix/X10") to specify its an abstract UNIX socket

but the important part in my opinion is to correctly print the socket name which currently is empty because of the NULL terminator

**Comment by HybridReaverHD** [comment]
@nathan-b hi nathan, any updates on this?

**Comment by nathan-b** [comment]
Hi @HybridReaverHD. I mentioned this to the team about a month ago, but I haven't heard anything back. I'll check...

The other problem is that Sysdig (the company) donated the libraries which do the syscall instrumentation / parsing / reporting to the CNCF. You can find that repository here: https://github.com/falcosecurity/libs

When I took a look at it earlier, I noted that the problem actually resided in the sysdig inspector, which is part of that repository. However, the CNCF did not want the actual `sysdig` program itself, so we are in the process of retooling how `sysdig` (the open-source tool) is built so it can use the libraries now owned by CNCF / the Falco project.

I am fully confident that we will resolve this behind-the-scenes issue pretty soon and we'll have a new sysdig build and (hopefully) also have a fix for this bug report. But both of those tasks are owned by other teams, so all I can do is push and ask for status updates :)

Thanks for understanding!

**Comment by HybridReaverHD** [comment]
@nathan-b in your opinion, will it be probable for the devs from falco to accept/approve a merge request if i already have a branch with a fix for this (the fix is in the kernel module itself)

**Comment by nathan-b** [comment]
I think it's likely. I've found them to be very easy to work with!

**Comment by nathan-b** [comment]
Closing this old issue as it's no longer relevant (driver changes should go in falcosecurity instead)
