### ISSUE TITLE
exit status of processes are shown incorrectly

### ISSUE THREAD

**Issue by jttoivon** [draios/sysdig#1760]
Is the status that is shown with the procexit event really the exit code of the process?

I have the following program

```
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char* argv[])
{
  if (argc == 1)
    return 0;
  int ret = atoi(argv[1]);
  return ret;
}
```
I compile it with `gcc ret.c -o ret`, and run sysdig to capture the procexit events of the program
with command `sudo sysdig proc.name=ret and evt.type=procexit`.
Then running `./ret 0; ./ret 1; ./ret 2; ./ret 3; ./ret 4` gives the following output from sysdig:
```
65460 23:02:01.949866941 3 ret (38071) > procexit status=0 
65833 23:02:01.952725393 3 ret (38072) > procexit status=256 
66070 23:02:01.955482994 1 ret (38073) > procexit status=512 
66352 23:02:01.958196456 9 ret (38074) > procexit status=768 
66556 23:02:01.960968025 3 ret (38075) > procexit status=1024 
```
Does sysdig get the byte order wrong or what is going on? I have tried both 0.27.1 and 0.26.4 versions of sysdig.

**Comment by FedeDP** [comment]
Hi @jttoivon !
Can confirm the issue; will look into that asap.
Thanks for reporting this!

**Comment by FedeDP** [comment]
Hi! The issue is resolved by https://github.com/falcosecurity/libs/pull/126; let's wait on it to get hopefully merged.
