### ISSUE TITLE
capture filter "container.id" is not working when providing the full container id

### ISSUE THREAD

**Issue by jossef** [draios/sysdig#1763]
If I use the following command, I'm getting all container events as expected:
```
sysdig container.id=00f372b35933
```

However, if I use
```
sysdig container.id=00f372b35933e9c8d1020bc399949235d0337cf3f105486f5f9fb6a56f2cfd
```

Sysdig doesn't capture any event

**Comment by therealbobo** [comment]
Hi @jossef! I took a quick look and this appears the correct behaviour (here some references https://github.com/falcosecurity/libs/blob/0e0a7b26ed1f7e0f7717e2afec6b99b7ae72ecc0/userspace/libsinsp/filterchecks.cpp#L6598 https://github.com/falcosecurity/libs/blob/0e0a7b26ed1f7e0f7717e2afec6b99b7ae72ecc0/userspace/libsinsp/runc.cpp#L67). If you think that it's good idea to add a new field or to change the `container.id` field, you can open an issue on the libs repo (https://github.com/falcosecurity/libs) and start a discussion with the maintainers! 😄
