### ISSUE TITLE
Arch Linux install error: sysdig: error while loading shared libraries: libprotobuf.so.27: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ElijahLynn** [draios/sysdig#1764]
Putting this here to rubber duck why I am getting this error when installing on Arch. 

Package comes from https://archlinux.org/packages/community/x86_64/sysdig/. 

I installed with `yay --refresh --sync sysdig` and I run `sudo sysdig` or `sysdig` and get:
> sysdig: error while loading shared libraries: libprotobuf.so.27: cannot open shared object file: No such file or directory

I have `protobuf` 3.15.6 installed.

Trying suggestions in https://stackoverflow.com/questions/25518701/protobuf-cannot-find-shared-libraries, I have also run `sudo ldconfig` and `export LD_LIBRARY_PATH=/usr/local/lib`.

**Comment by ElijahLynn** [comment]
> sysdig: error while loading shared libraries: libprotobuf.so.27:

I am thinking there is a dependency on protobuf 2.7. Hrm. Wonder what downgrading would break? Arch doesn't make it easy to downgrade with the package manager, so it would have to be manual.

**Comment by ElijahLynn** [comment]
> I am thinking there is a dependency on protobuf 2.7.

Doesn't exist: 
![image](https://user-images.githubusercontent.com/1504756/122317116-d7445b00-ced1-11eb-9077-0f0a4a0d1cc9.png)

**Comment by ElijahLynn** [comment]
libprotbuf.so.27 does come with https://archlinux.org/packages/extra/x86_64/protobuf/: 

![image](https://user-images.githubusercontent.com/1504756/122317587-a6185a80-ced2-11eb-8533-9bbe40f7a86c.png)

And I upgraded to protobuf 3.16.0 and I have from a while ago:
> lrwxrwxrwx 1 root root      21 May  8 03:56 /usr/lib/libprotobuf.so.27 -> libprotobuf.so.27.0.0*

So it does seem like it just can't find it.

**Comment by ElijahLynn** [comment]
So I tried to soon after updating protobuf me thinks as I still had the same error then, but I tried again a bit later and that error went away and I got this new error:

```
❯ sudo sysdig -w file.scap
[sudo] password for elijah: 
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by sysdig)
sysdig: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by sysdig)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libgrpc++_unsecure.so.1.38)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libgrpc_unsecure.so.16)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libgpr.so.16)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libabsl_status.so.2103.0.1)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libabsl_cord.so.2103.0.1)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libabsl_str_format_internal.so.2103.0.1)
sysdig: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libabsl_time_zone.so.2103.0.1)
```

And then did a system update which brought in gcc-libs 11 from 10.2:

```
1 core/gcc-libs 11.1.0-1 (30.5 MiB 122.3 MiB) (Installed: 10.2.0-6)
    Runtime libraries shipped by GCC
```

And did a reboot and now I have: 
```
❯ sudo sysdig
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

**Comment by ElijahLynn** [comment]
Per https://github.com/draios/sysdig/issues/30, I then tried: 

```
❯ modprobe sysdig-probe                                                                 
modprobe: FATAL: Module sysdig-probe not found in directory /lib/modules/5.12.11-arch1-1
```

```
❯ sudo sysdig-probe-loader                                                                                                                                                           
* Unloading sysdig-probe, if present                                                                                                                                                 
* Running dkms install for sysdig                                                                                                                                                    
Error! Could not find module source directory.                                                                                                                                       
Directory: /usr/src/sysdig-0.27.1 does not exist.                                                                                                                                    
* Running dkms build failed, couldn't find /var/lib/dkms/sysdig/0.27.1/build/make.log                                                                                                
* Trying to load a system sysdig-probe, if present                                                                                                                                   
* Trying to find precompiled sysdig-probe for 5.12.11-arch1-1                                                                                                                        
Found kernel config at /proc/config.gz                                                                                                                                               
* Trying to download precompiled module from https://download.sysdig.com/stable/sysdig-probe-binaries/sysdig-probe-0.27.1-x86_64-5.12.11-arch1-1-f19fe3540fc7e95e8cc0ec09ac2ba7e0.ko 
curl: (22) The requested URL returned error: 404                                                                                                                                     
```

```
yay --remove sysdig
```

```
yay sysdig
```

```
yay sysdig-dkms
...
(2/2) Install DKMS modules
==> Unable to install module sysdig/0.27.1 for kernel *: Missing kernel headers.
```

**Comment by therealbobo** [comment]
At the moment it seems to work! Please reopen if you are still encountering this issue! 😄 @ElijahLynn

**Comment by therealbobo** [comment]
Hi @ElijahLynn ! I think that you are missing the kernel headers! Try to install them using `pacman -S linux-headers`. 😄

**Comment by ch4xer** [comment]
Same error here on Arch Linux, with `linux-zen`, `linux-zen-headers`, `sysdig` and `sysdig-dkms` installed.

```
❯ uname -a                      
Linux Survive 6.3.1-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 10 May 2023 08:54:24 +0000 x86_64 GNU/Linux
❯ modprobe sysdig-probe
modprobe: FATAL: Module sysdig-probe not found in directory /lib/modules/6.3.1-zen2-1-zen
❯ sudo sysdig-probe-loader  
sudo: sysdig-probe-loader: command not found
```

**Comment by therealbobo** [comment]
Hi @ch3n9w! The actual name of the kernel module is `scap`. Normally you just have to do `sudo modprobe scap`. Sadly the 6.3 kernel broke the kernel module. In a few days (I think) will be release the new libs and, at that point, there will be a new release of sysdig. 😄

**Comment by ElijahLynn** [comment]
Thanks @therealbobo, I'll try that when I come across this again. We should close this I suppose, and re-open if your solution doesn't work for anyone.
