### ISSUE TITLE
Error while building from binaries at 93% (Ubuntu 20.04.2 on Raspi 3)

### ISSUE THREAD

**Issue by TheGim** [draios/sysdig#1768]
Got it running a month ago, but know it throws me some errors at 93%.

![image](https://user-images.githubusercontent.com/38396922/129481358-79882678-bd79-41ae-8840-dd4384aa2d32.png)

**Comment by ducktype** [comment]
Same here Ubuntu 20.04 sysdig 0.27.1

**Comment by TheGim** [comment]
I fixed it a while ago, someone updated the kernel-header and I had to build it again.

**Comment by TheGim** [comment]
I had a problem with the falcosecurity-lib-repo, I used an older version which fixed it for me.
