### ISSUE TITLE
Has 0.28.0 been retagged?

### ISSUE THREAD

**Issue by dvzrv** [draios/sysdig#1822]
Hi! I'm currently rebuilding 0.28.0 for Arch Linux and noticed that the checksum for the tarball of 0.28.0 does not match anymore:

before (2021-12-14):
`227eea9ffb65829c079fed379f4830fcb3b3a1ae597aa10d639fb49273afb18c`

now:
`817e595d501acf3fe11dc659a154aadbba848dd87ae801f5bf34a42e84979f37`

If the release has indeed been retagged: Please do not do this, as it a) breaks downstream builds that rely on reproducible tarballs to build from and b) requires downstreams to investigate whether a supply-chain attack is currently in motion.
Just tag a new release (e.g. 0.28.1).

Looking at https://github.com/draios/sysdig/commit/4fb6288275f567f63515df0ff0a6518043ecfa9b it appears as if the current 0.28.0 points at a hotfix for docker images done by @luca-sd. It would be great to get some feedback on this.

**Comment by LucaGuerra** [comment]
Hey David! You are correct, a retag (two 🙄) accidentally happened due to issues with the new release process, now corrected. There should've been only one tag which is the one that exists now. No retags will happen for future versions. Sorry for the inconvenience this may have caused.

**Comment by dvzrv** [comment]
@LucaGuerra thanks for getting back on this so quick!
I had a look at the commits and couldn't find anything obvious that would warrant a red flag in the meantime and also saw that a patch by @mtorromeo had been merged (who is actually maintaining the package for Arch).

Thanks again for clearing this up! :)
