### ISSUE TITLE
sysdig docker container in UÑbuntu 20.04

### ISSUE THREAD

**Issue by laurafbec** [draios/sysdig#1824]
Hi everyone,
I'm trying to use a Sysdig docker container based on the official Docker Hub image, but when running it I get the following message. Can anyone help me? Thanks in advance

docker run -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro sysdig/sysdig:0.28.0
* Setting up /usr/src links from host
* Running scap-driver-loader for: driver version=2160111cd088aea9ae2235d3385ecb0b1ab6623c
* Running scap-driver-loader with: driver=module, compile=yes, download=yes
* Unloading scap module, if present
* Trying to load a system scap module, if present
* Looking for a scap module locally (kernel 5.11.0-43-generic)
**Detected an unsupported target system, please get in touch with the Falco community**
[root@fe4314b81539 /]# sysdig
**Unable to load the driver
error opening device /host/dev/scap0. Make sure you have root credentials and that the scap module is loaded.**
[root@fe4314b81539 /]# sudo sysdig
bash: sudo: command not found
[root@fe4314b81539 /]#

**Comment by sach-12** [comment]
@laurafbec how did you fix this issue?

**Comment by laurafbec** [comment]
Hi @sach-12
I think it worked after updating the linux headers. 
Try with this link https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux
