### ISSUE TITLE
Where can I find an EL6 Sysdig Binary RPM ?

### ISSUE THREAD

**Issue by prynhart1** [draios/sysdig#1838]
Apologies for opening this as an issue, but I'm working on an old EL6 box (which I'm trying to migrate to EL8).  Sysdig would be very helpful on this system, because I'm trying to track down what the box is doing exactly.

Online searching says that I should be looking for the binary RPM sysdig-0.6.0-x86_64.rpm, or something around this build.  Can anyone point me in the direction as to where I could find this resource, or another RPM which will work with EL6.

Thank you, 

Patrick

**Comment by therealbobo** [comment]
Hi @prynhart1! Sorry for the extreme delay 😢 I took a look around but I can't find that exact version. If you _really_ need it, I can try to compile the old 0.6.0 tag but I can't promise anything. 😄
