### ISSUE TITLE
Filter events from type "execveat" cause to error in 0.28.0

### ISSUE THREAD

**Issue by liorzemah** [draios/sysdig#1842]
Hi,
I updated to the latest version (0.28.0) and when I tried to run Sysdig and filter events from "execveat" type I got unknown event type error.

 I run the following command:
```
sysdig "evt.type=execveat"
```
and got this error:
`filter error at position 17: unknown event type execveat`

This error not reproduce under Sysdig 0.27.1.

This is a bug in the new version? or Sysdig not support anymore in tracing of this syscall?
By the way I am looking in your documents if there is any commit from your side to be backward compatible and it's not clear.

**Comment by FedeDP** [comment]
Hi! 
`execveat` support entered Falco 1month ago: https://github.com/falcosecurity/libs/pull/141; there has been no `sysdig` release that supports it though.

> This error not reproduce under Sysdig 0.27.1.

Was sysdig 0.27.1 catching any event for it? (it shouldn't).
Perhaps it was just a bug in the evt.type checker.

**Comment by liorzemah** [comment]
I tried to simulate using of `execveat` syscall and Sysdig 0.27.1 not catched it. 

Thank you for the quick answer.
