### ISSUE TITLE
Should you have the latest kernel version?

### ISSUE THREAD

**Issue by ASmoliak** [draios/sysdig#1847]
Hi, recently I've been trying to install Sysdig on an CentOS7 machine, the automatic script fails because it tries to download kernel headers that do not exist.

My kernel version:  `3.10.0-957.el7.x86_64`
The only available kernel headers: `kernel-devel-3.10.0-1160`
Only way for me to make this work is to update my kernel to the latest version and reboot, but I am not willing to do that.

~~The script mentions that it cannot install the headers, and yet Sysdig does successfully install and run, I don't understand if it's that important.~~

**Comment by FedeDP** [comment]
>  Only way for me to make this work is to update my kernel to the latest version and reboot, but I am not willing to do that.

Well, you could also download right kernel headers for your currently running kernel version too; it does not require a reboot :) 

> The script mentions that it cannot install the headers, and yet Sysdig does successfully install and run, I don't understand if it's that important.

Can you share a snippet for this?

**Comment by ASmoliak** [comment]
I'm sorry about the latter part of your reply. it works because a previous
proper install left a probe, and as soon as I removed the probe, sysdig
would not run.

**Comment by ASmoliak** [comment]
As for the kernel headers, We're trying to deploy Sysdig on a wide variety of machines with varying update states, Is there a script that can automatically install the required headers for the current machine?

**Comment by FedeDP** [comment]
Hi! 

> As for the kernel headers, We're trying to deploy Sysdig on a wide variety of machines with varying update states, Is there a script that can automatically install the required headers for the current machine?

I don't think so. We have a script (https://github.com/draios/sysdig/blob/dev/scripts/scap-driver-loader.in) to try to fetch a prebuilt module; if it is missing, it tries to build one for you for the current (as in `uname -r`) kernel version.

If you want full control, you can build the module/eBPF probe from source by downloading release source code tarball.
