### ISSUE TITLE
Sysdig read does not skip pre-existing container events

### ISSUE THREAD

**Issue by Rob-Francis** [draios/sysdig#1850]
**Describe the bug**
When reading from a scap file sysdig should skip all initial container events, however it does not skip them and in some cases updates the timestamps to the current system time.

**How to reproduce it**
It requires containers running to cause container events - in my case I am starting minikube (a local kubernetes cluster) with docker - other methods and container runtimes may work.
`sudo sysdig -w temp.scap
minikube start
sysdig -r temp.scap | head`

This produces events as shown below - where all values are identical aside from container id.
`2 11:38:40.361382000 0 container:a72418a30fbd (-1) > container json={"container":{"Mounts":[],"cpu_period":100000,"cpu_quota":0,"cpu_shares":1024,"cpuset_cpu_count":0,"created_time":33899465587712339,"env":[],"full_id":"","id":"a72418a30fbd","image":"","imagedigest":"","imageid":"","imagerepo":"","imagetag":"","ip":"0.0.0.0","is_pod_sandbox":false,"labels":null,"lookup_state":1,"memory_limit":0,"metadata_deadline":0,"name":"","port_mappings":[],"privileged":false,"swap_limit":0,"type":0}}`

**Expected behaviour**
These initial container events should be ignored when reading from a scap file.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue!
I was wondering: on which OS are you seeing this?
Can you by chance sharing `docker info` output too?

EDIT: I'd expect you to be on a cgroups v1 system, because cgroups v2 support was fixed recently (https://github.com/falcosecurity/libs/pull/219) and now cgroupsv2 systems too are showing this behavior.
But that fix is still not merged into sysdig.

**Comment by Rob-Francis** [comment]
No problem, sorry for the late reply!
I am on Ubuntu 20.04.3 and here is most of the docker info:

> Client:
             Context:    default
             Debug Mode: false
             Plugins:
              app: Docker App (Docker Inc., v0.9.1-beta3)
              buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
              scan: Docker Scan (Docker Inc., v0.12.0)
Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 435
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.0-1024-oem
 Operating System: Ubuntu 20.04.3 LTS

**Comment by FedeDP** [comment]
>  Cgroup Version: 1

Great, as i thought! Thanks! 
The PR to fix this behavior is opened: https://github.com/falcosecurity/libs/pull/231
Hopefully it will get merged soon ;)

**Comment by FedeDP** [comment]
The fix was merged on libs master and will be backported in sysdig 0.29 release (that will come in the next few days!)
Stay tuned :)

**Comment by FedeDP** [comment]
The new sysdig 0.29.1 was released and fixed this issue.
Care to test? Thanks!

**Comment by Rob-Francis** [comment]
Sorry for the late reply. I finally got around to upgrading and from the testing I've done it seems to be working. Thanks for the help and great work!
