### ISSUE TITLE
Sysdig running as a container does not log metrics for other containers running on the host 

### ISSUE THREAD

**Issue by eshaan-m** [draios/sysdig#1852]
I am launching sysdig as a container, as described in the documentation here: https://github.com/draios/sysdig#getting-started

But upon running `sysdig -c lscontainers`, to get the list of all the containers running on the host, sysdig can only detect 1 container while there are multiple containers running on the host. 

Output of `docker ps -a` on the host 
![image](https://user-images.githubusercontent.com/30475194/156587001-1a6c5a93-249b-4b60-a115-4fe7d7ac716d.png)

Output of `sysdig -c lscontainers` within the sysdig container 
![image](https://user-images.githubusercontent.com/30475194/156587048-16b6edae-9af9-465c-8635-c3cc27e9b01a.png)

Am I doing something wrong when launching sysdig as a container that it is not able to detect the other containers running on the host ? I would like to collect sysdig logs (with sysdig running as a container) for all other containers running on the host machine.

**Comment by therealbobo** [comment]
Hi @eshaan-m! It seems to work fine on my side. Could you retry with the latest version of sysdig? 🤔
