### ISSUE TITLE
build sysdig-0.28.0 for arm 32bit platform

### ISSUE THREAD

**Issue by lkyptw** [draios/sysdig#1857]
Hi all,

Currently I try to build sysdig-0.28.0 for an Armv7 embedded linux environment (raspberry pi3). The kernel version is v5.4 and OS is ubuntu server 20.04.4 LTS
Use the following build command:
`mkdir build`
`cd build`
`cmake ..`
`make`
`make install`

But when doing `make` get error message like this:

ubuntu@ubuntu:~/sysdig-0.28.0/build$ make
[  4%] Built target tbb
[  8%] Built target jq
[ 12%] Built target openssl
[ 16%] Built target c-ares
[ 19%] Built target b64
[ 23%] Built target zlib
[ 26%] Built target curl
[ 34%] Built target scap
ERROR: "__aeabi_uldivmod" [/home/ubuntu/sysdig-0.28.0/build/driver/src/scap.ko] undefined!
make[5]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[4]: *** [Makefile:1678: modules] Error 2
make[3]: *** [Makefile:16: all] Error 2
make[2]: *** [driver/CMakeFiles/driver.dir/build.make:57: driver/CMakeFiles/driver] Error 2
make[1]: *** [CMakeFiles/Makefile2:548: driver/CMakeFiles/driver.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

It seem that default it will build for 64bit, but I don't know to to fix it.
Does anyone can help me or give me some direction that how to modify build setting.
Many thanks.

**Comment by FedeDP** [comment]
Hi! At the moment, i think only x86_64 is officially supported.
At Falco, we are working to provide arm64 support for the next release (0.32.0), and it should also benefits next sysdig release of course.

There is no plan for arm32 at the moment.
