### ISSUE TITLE
missing arm package ?

### ISSUE THREAD

**Issue by grosser** [draios/sysdig#1880]
ubuntu 20.04.1-Ubuntu has 0.26.4-1ubuntu0.3 for arm
the https://s3.amazonaws.com/download.draios.com/stable/deb/draios.list has 29
... but nothing for arm 😞 

# Things that worked for me

## Option A: Manual install (ubuntu 20.04)

simple but slow ~1h

```
  sudo su
  DEBIAN_FRONTEND=noninteractive apt-get install \
    cmake libluajit-5.1-dev libelf-dev
  git clone https://github.com/draios/sysdig.git
  cd sysdig
  git reset --hard ${SYSDIG_VERSION}
  mkdir build
  cd build
  cmake -DUSE_BUNDLED_LUAJIT=OFF ..
  make
  make install
  insmod driver/scap.ko
```

## Option B: Package + install (ubuntu 20.04)
more complicated but much faster in the install step

### Package
```
sudo su

apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  cmake libluajit-5.1-dev libelf-dev build-essential git-core linux-virtual rpm

export SYSDIG_VERSION=0.29.2

git clone https://github.com/draios/sysdig.git
cd sysdig

git reset --hard ${SYSDIG_VERSION}
sed -i "s/0.1.1dev/${SYSDIG_VERSION}/g" CMakeLists.txt

mkdir build
cd build

cmake -DUSE_BUNDLED_LUAJIT=OFF ..
make
make package
# upload .deb file
```

### Install

```
  # download package
  deb=<file>
  apt install ./$deb || (apt --fix-broken install && apt install ./$deb)

  # install dependencies that are not tracked in the package
  DEBIAN_FRONTEND=noninteractive apt-get install libluajit-5.1-dev
```

# Things that did not work for me

## Build the builder image

it fails to build on arm

## Build in docker without builder image

it fails on missing linux headers (known docker issue, did not find a workaround)

**Comment by therealbobo** [comment]
Hi @grosser! If you take a look now, you'll find the precompiled arm package! 😄 Feel free to reopen if you encounter any problem! 😄

**Comment by grosser** [comment]
thx!
