### ISSUE TITLE
Raspberry Pi 4 aarch64 install errors

### ISSUE THREAD

**Issue by f1linux** [draios/sysdig#1883]
Installed sysdig on a Raspberry Pi 4 running Ubuntu 22.04 Desktop edition, 64bit (aarch64).

Executed `apt-get install sysdig` and the below error was puked:

    Setting up sysdig-dkms (0.27.1-0.3build1) ...
    Loading new sysdig-0.27.1 DKMS files...
    Building for 5.15.0-1011-raspi
    Building initial module for 5.15.0-1011-raspi
    Error! Bad return status for module build on kernel: 5.15.0-1011-raspi (aarch64)
    Consult /var/lib/dkms/sysdig/0.27.1/build/make.log for more information.
    dpkg: error processing package sysdig-dkms (--configure):
    installed sysdig-dkms package post-installation script subprocess returned error exit status 10

The referenced log in the error is attached-

[sysdig_install_errors.txt](https://github.com/draios/sysdig/files/8958785/sysdig_install_errors.txt)

**Comment by therealbobo** [comment]
The version you're trying to install from the repo is quite old. If you want, you can use the official Sysdig repo using the commands below:
```
curl -s https://download.sysdig.com/DRAIOS-GPG-KEY.public | sudo apt-key add -  
sudo curl -s -o /etc/apt/sources.list.d/draios.list https://download.sysdig.com/stable/deb/draios.list  
sudo apt-get update
```
It'll work just fine! 😄 @f1linux
