### ISSUE TITLE
Segmentation fault when loaded chisel with calling to set_filter in "on_init"

### ISSUE THREAD

**Issue by liorzemah** [draios/sysdig#1892]
First of all, I am compiling Sysdig from the source and linking existing Falcolibs. 
When I am trying to load chisel that contains "set_filter" command in the scope of "on_init" I crash with the SIGSEGV Segmentation fault.

For example:
After I build Sysdig from the source I run the following command:
`sysdig -c list_login_shells.lua`
And get the SIGSEGV Segmentation fault.

After investigation, I found that there is no verification about the kernel driver state, no matter if I am loading the scap.ko kernel module or not I got the same error.  My guess is that when I am building Sysdig from the source the existing driver (that is already built ) does not fetch. 

Is any way to detect in runtime if the driver is fetched?

**Comment by therealbobo** [comment]
I think this issue was fixed with the latest release! 😄 @liorzemah
