### ISSUE TITLE
Missing Prebuilt Kernel Modules

### ISSUE THREAD

**Issue by chkp-ofek** [draios/sysdig#1897]
Hi,
I'm searching for a few prebuilt drivers for the following kernel releases:
5.10.106-102.504.amzn2.x86_64
5.4.0-1085-azure
5.4.0-1078-azure
5.4.0-1086-azure
3.10.0-1160.71.1.el7.x86_64
5.4.196-108.356.amzn2.x86_64

I couldn't find them for any driver version.
Do you know where I can find them?

Thanks!!

**Comment by therealbobo** [comment]
I just checked! Appears that the drivers you requested are all present! If you use the `scap-driver-loader` script, you'll be good to go! 😄 If you encounter problems in the download process, feel free to reopen this issue! @chkp-ofek
