### ISSUE TITLE
How to get ouput from command and http request

### ISSUE THREAD

**Issue by ev11ccaatt** [draios/sysdig#1910]
I try to record the output into dumpfile 
but after i run cat/proc/meminfo 
i got a result like 
![image](https://user-images.githubusercontent.com/70800641/193436370-f62c4cf7-e201-44e4-b1c0-b23cb8ef8896.png)
dosent like 
![image](https://user-images.githubusercontent.com/70800641/193436423-61cdc2c4-1dd7-40b6-a03d-7f211adcf651.png)
can u help me?

**Comment by therealbobo** [comment]
Using these commands it seems to work correctly:
```
sysdig -A -pc '(fd.port=80 and proc.name=curl) or proc.name=cat' -s 10000 -w test.scap
sysdig -A -pc '(fd.port=80 and proc.name=curl) or proc.name=cat' -r test.scap
```
Do you have any update? 🤔 
@ev11ccaatt
