### ISSUE TITLE
System Call Missing By Sysdig

### ISSUE THREAD

**Issue by kunzeng-ch** [draios/sysdig#1913]
Hello! Can you help me? I used the commond(sysdig -p "time:%evt.time&&container_name:%container.name&&proc_name:%proc.name&&proc_pname:%proc.pname&&proc_cmdline:%proc.cmdline&&evt_type:%syscall.type&&evt_args:%evt.args" > sysdig_final.txt) to get the system call of specified container. I found that the collected system calls are missing half of the actual system calls used.

**Comment by therealbobo** [comment]
Hi @kunzeng-ch ! Could you help me to reproduce the issue? What kind of application do you use in the container you are monitoring? 😄
