### ISSUE TITLE
how to install sysdig offline

### ISSUE THREAD

**Issue by ningmingxiao** [draios/sysdig#1921]

**Comment by jasondellaluce** [comment]
@ningmingxiao please expand on what you issue is.

**Comment by therealbobo** [comment]
Hi @ningmingxiao! What do you mean by offline? You don't necessarily have to download the driver: you can compile it locally (you need the kernel headers to do that) or you can use the modern bpf probe. 😄

**Comment by ningmingxiao** [comment]
> Hi @ningmingxiao! What do you mean by offline? You don't necessarily have to download the driver: you can compile it locally (you need the kernel headers to do that) or you can use the modern bpf probe. 😄

sometimes I can't connect the internet to download some rpm which are needed by sysdig. can sysdig list which rpm it is need ? at readme.

**Comment by therealbobo** [comment]
The only dependency needed is dkms and it is only needed with the kmod driver. I'll update the readme! 😄 If you need anything else, feel free to reopen this!

**Comment by chixiaome** [comment]
> The only dependency needed is dkms and it is only needed with the kmod driver. I'll update the readme! 😄 If you need anything else, feel free to reopen this!

I also encountered this problem. Sometimes my server cannot connect to the Internet. How can I install sysdig? Can you provide automatic installation scripts or installation packages.
