### ISSUE TITLE
Segfault of csysdig 0.30.0 in Debian 11

### ISSUE THREAD

**Issue by vjjmiras** [draios/sysdig#1926]
In the kernel ring buffer, it generates the following error:

csysdig[643]: segfault at 0 ip 00007ff2ebdcbd76 sp 00007ffc61ba1e58 error 4 in libc-2.31.so[7ff2ebd53000+15a000]

sysdig 0.30.0 works fine though.

Current version of libc is 2.31-13+deb11u5

csysdig 0.29.0 seems to work fine on that same configuration.

**Comment by vjjmiras** [comment]
In Debian 10 the error is:

segfault at 0 ip 00007f267873ff31 sp 00007fffc5d6a218 error 4 in libc-2.28.so[7f2678606000+147000]

csysdig 0.29.0 works fine.

**Comment by jasondellaluce** [comment]
This is fixed in version 0.30.1, just released.

**Comment by vjjmiras** [comment]
Thanks!
