### ISSUE TITLE
Windows Support...

### ISSUE THREAD

**Issue by frioux** [draios/sysdig#193]
It's not obvious from anything but the wiki installation page (at least to me) that windows support is only for parsing the files.  It might be nice if at the very least this were made more obvious in the install pages at http://www.sysdig.org/install/.  I mean it says something like "try `sysdig -cl`" but after listing those commands none of the can be run.  Kindav a bummer :(

**Comment by ajhalls** [comment]
Just checking back in on Windows Support for live capture. I recently used sysdig to identify a problem with OpenStreetMap / Apache2 configuration and loved what it could do, as I develop c# apps, it would be awesome to have that level of reporting available in Windows as well.

I realize it isn't top priority, so if it isn't going to happen for a few more years, any suggestions for another package I could look at?
