### ISSUE TITLE
Ubuntu 22.04 not supported?

### ISSUE THREAD

**Issue by ElixsDev** [draios/sysdig#1932]
Automatic installation try on Ubuntu Server 22.04 throws:

`sudo` curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
> Unsupported operating system. Please consider writing to the mailing list at
https://groups.google.com/forum/#!forum/sysdig or trying the manual
installation.

**Comment by therealbobo** [comment]
On my Ubuntu Server 22.04 works as expected. Have you resolved this issue? 🤔 @EliServices

**Comment by therealbobo** [comment]
Works fine on my ubuntu server instance! Have you retried? 🤔
