### ISSUE TITLE
BPF_PROBE variable naming issue

### ISSUE THREAD

**Issue by deepskyblue86** [draios/sysdig#1934]
I was about to use sysdig with the container image (on amazon linux) and I noticed that `/usr/bin/scap-driver-loader` and `sysdig`/`csysdig` use two different naming:

- scap-driver-loader has FALCO_BPF_PROBE
- the tools has SYSDIG_BPF_PROBE

Workaround: pass `-e FALCO_BPF_PROBE="" -e SYSDIG_BPF_PROBE=""` to docker

**Comment by FedeDP** [comment]
The issue is now fixed; a 0.30.2 is being released! Thanks for the feedback!
