### ISSUE TITLE
sysdig 0.30.1 0.30.2 build issue

### ISSUE THREAD

**Issue by chenrui333** [draios/sysdig#1936]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
  [ 33%] No update step for 'driver'
  [ 44%] Performing patch step for 'driver'
  [ 55%] No configure step for 'driver'
  [ 66%] No build step for 'driver'
  [ 77%] No install step for 'driver'
  [ 88%] No test step for 'driver'
  [100%] Completed 'driver'
  [100%] Built target driver
  CMake Warning at build/driver-repo/driver-prefix/src/driver/CMakeLists.txt:15 (message):
    Target architecture not officially supported by our drivers!


  CMake Error at build/driver-repo/driver-prefix/src/driver/CMakeLists.txt:70 (include):
    include could not find requested file:

      compute_versions


  CMake Error at build/driver-repo/driver-prefix/src/driver/CMakeLists.txt:72 (message):
    problem with compute_versions.cmake in
    /tmp/sysdig-20221120-85610-1gnb86x/sysdig-0.30.2/cmake/modules;/private/tmp/sysdig-20221120-85610-1gnb86x/sysdig-0.30.2/falcosecurity-libs/cmake/modules
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/3509938821/jobs/5879427805
relates to Homebrew/homebrew-core#116224

**Comment by chenrui333** [comment]
same build issue happend for 0.30.1 build as well, https://github.com/Homebrew/homebrew-core/pull/115894

**Comment by jasondellaluce** [comment]
This is an issue with the CMake setup of the driver. Unfortunately, for now we're sticking with it because it's hard to do better due to CMake limitations. You can circumvent this by deleting the `build/driver-repo/` directory whenever the codebase updates the libs/driver versions, which can happen when pulling new commits from mainline.

**Comment by chenrui333** [comment]
> You can circumvent this by deleting the `build/driver-repo/` directory whenever the codebase updates the libs/driver versions, which can happen when pulling new commits from mainline.

let me give that a try.

**Comment by therealbobo** [comment]
Do you have any update on this? 😄 @chenrui333
