### ISSUE TITLE
what is the mapping relation between evt.type and evt.category?

### ISSUE THREAD

**Issue by zhang-xh95** [draios/sysdig#1989]
Execuse me. I'm wondering the excat mapping relation between evt.type and evt.category. Is there any config file or docs define the relation?

**Comment by therealbobo** [comment]
Hi @zhang-xh95! The event type is syscall name itself; meanwhile the category are just groups of syscall. To find out in which group is a syscall you can take a look [here](https://github.com/falcosecurity/libs/blob/e54bbb8eaaf996cbcf49ce17da3d94ba5933070f/driver/event_table.c#L49) in the event table. Do you think that this should be documented in some way?

**Comment by zhang-xh95** [comment]
Thanks very much for your help. In my opinion, It would be better if the event table relation link can be provided in the docs.

**Comment by therealbobo** [comment]
If you want you could open an issue (and maybe contribute 😄) to [libs](https://github.com/falcosecurity/libs) to bring up this topic with the maintainers!
