### ISSUE TITLE
sysdig can't open compress scap

### ISSUE THREAD

**Issue by flylinfan** [draios/sysdig#2007]
OS:
Windows 10 x64
Software:
[sysdig-0.32.0-AMD64.exe](https://github.com/draios/sysdig/releases/download/0.32.0/sysdig-0.32.0-AMD64.exe)

sysdig open compress scap file the command return "invalid block type"

**Comment by therealbobo** [comment]
Hi @flylinfan! Could you give us more info about the scap file (e.g. version of sysdig that generated the scapfile)?

**Comment by flylinfan** [comment]
> Hi @flylinfan! Could you give us more info about the scap file (e.g. version of sysdig that generated the scapfile)?

sysdig 0.17.0 generated compress scap file in ubuntu 14.04 LTS

**Comment by therealbobo** [comment]
Hey @flylinfan! I think the problem was in `libs`. It should be fixed in the next sysdig release!
