### ISSUE TITLE
Red Hat 9 isn't supported - SHA 1 deprecated 

### ISSUE THREAD

**Issue by SilverPlate3** [draios/sysdig#2038]
Red Hat 9 have deprecated SHA-1 and looks like this severely effects the product. 
1 - We can't install sysdig 
2 - After finding a workaround and installing sysdig. we can't do things like:  `rpm -qi sysdig`
![image](https://github.com/draios/sysdig/assets/93097769/ba46e514-edda-434a-bcf4-fbabccb6d9f0)

What is the workaround:
```
update-crypto-policies --set DEFAULT:SHA1
reboot 
```
*reboot is a must for some capabilities*

this goes against the security best practices. 
https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

Please sign the package with sha256 as well.

**Comment by nick2432** [comment]
can i work on this?

**Comment by therealbobo** [comment]
Hi @nick2432! Sadly this has already been resolved! I'll release a new version as soon as the new libs are out. Feel free to look around in the issue, maybe you'll find something interesting! If you need help, ping me! 😄
