### ISSUE TITLE
`evt.res` and `evt.rawres` and `evt.failed` are gone

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#2064]
Hi. I'm the Debian maintainer of sysdig. For the last few releases the sysdig in Debian is missing these filter fields, and perhaps others. Were these intentionally removed? If so, can we please get them back?

Thanks

**Comment by jasondellaluce** [comment]
Interesting. I gave this a test and it seems like that starting from `sysdig` v0.30 we don't show the broad `evt.*` filter field class with the `--list` option, although they are still definitely supported when using them in the tool (tested in the vlatest 0.34.1). Will investigate this.

**Comment by jasondellaluce** [comment]
cc @leogr
