### ISSUE TITLE
implicit declaration of function 'strlcpy'; did you mean 'strscpy'?

### ISSUE THREAD

**Issue by jfly** [draios/sysdig#2077]
It looks like the Linux kernel recently dropped the `strlcpy` function:  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=57f22c8dab6b266ae36b89b073a4a33dea71e762, which is preventing me from building sysdig with errors like this:

```
/build/source/build/driver/src/ppm_events.c: In function 'val_to_ring':
/build/source/build/driver/src/ppm_events.c:652:36: error: implicit declaration of function 'strlcpy'; did you mean 'strscpy'? [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-function-declaration-Werror=implicit-function-declaration8;;]
  652 |                         len = (int)strlcpy(args->buffer + args->arg_data_offset,
      |                                    ^~~~~~~
      |                                    strscpy
```

**Comment by SebTM** [comment]
Hey, fyi - I had the same issue and for NixOS we can patch it for certain kernel-versions like this: https://github.com/NixOS/nixpkgs/pull/300630/files#diff-d7c05622bef53ebc52172fc79725acbdcd6663638d515c27f8909e9989bd8756R79

Not nice/optimal but a solution until fixed upstream 🙏🏻

**Comment by therealbobo** [comment]
Hey @jfly! Thanks for the issue! Please refer to https://github.com/falcosecurity/libs for any driver related issue: we relay on libs for the drivers :)

**Comment by jfly** [comment]
Ah, ok. Closing in favor of https://github.com/falcosecurity/libs/issues/1740!
