### ISSUE TITLE
Trash in images

### ISSUE THREAD

**Issue by albe19029** [draios/sysdig#2078]
While checking for content of sysdig images I found files, which seams like a trash.

-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1030.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1031.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1032.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1033.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1034.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1035.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx1036.bc
-rw-r--r-- 1 root root 203K Jul 15  2023 libomptarget-amdgpu-gfx1100.bc
-rw-r--r-- 1 root root 203K Jul 15  2023 libomptarget-amdgpu-gfx1101.bc
-rw-r--r-- 1 root root 203K Jul 15  2023 libomptarget-amdgpu-gfx1102.bc
-rw-r--r-- 1 root root 203K Jul 15  2023 libomptarget-amdgpu-gfx1103.bc
-rw-r--r-- 1 root root 202K Jul 15  2023 libomptarget-amdgpu-gfx700.bc
-rw-r--r-- 1 root root 202K Jul 15  2023 libomptarget-amdgpu-gfx701.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx801.bc
-rw-r--r-- 1 root root 204K Jul 15  2023 libomptarget-amdgpu-gfx803.bc
-rw-r--r-- 1 root root 200K Jul 15  2023 libomptarget-amdgpu-gfx900.bc
-rw-r--r-- 1 root root 200K Jul 15  2023 libomptarget-amdgpu-gfx902.bc
-rw-r--r-- 1 root root 202K Jul 15  2023 libomptarget-amdgpu-gfx906.bc
-rw-r--r-- 1 root root 205K Jul 15  2023 libomptarget-amdgpu-gfx908.bc
-rw-r--r-- 1 root root 205K Jul 15  2023 libomptarget-amdgpu-gfx90a.bc
-rw-r--r-- 1 root root 200K Jul 15  2023 libomptarget-amdgpu-gfx90c.bc
-rw-r--r-- 1 root root 206K Jul 15  2023 libomptarget-amdgpu-gfx940.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_35.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_37.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_50.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_52.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_53.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_60.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_61.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_62.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_70.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_72.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_75.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_80.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_86.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_89.bc
-rw-r--r-- 1 root root 260K Jul 15  2023 libomptarget-nvptx-sm_90.bc

Do we need this GPU specific files in images?

**Comment by therealbobo** [comment]
Hey @albe19029! Thanks for the issue! Good catch! We'll surely update the `sysdig` docker image in the short term! :)

**Comment by albe19029** [comment]
Can I ask one more question. Is yum required in your image? The problem is that python 3.6 is rather old and has a lot of security vulnerabilities. And I see only this utility from which /usr/lib/python3.6/site-packages/* and /usr/lib64/libpython3.6m.so.1.0 can depends on. As python3 is not installed in your image.

**Comment by albe19029** [comment]
[Cves.csv](https://github.com/draios/sysdig/files/14918743/Cves.csv)
Will leave CVE report here just to understand what I am talking about.
I apologize in advance if I am too annoying.
