### ISSUE TITLE
Issue with Terraform Provider

### ISSUE THREAD

**Issue by marbcGH** [draios/sysdig#2079]
I Am attempting to deploy a Notification Terraform resource (email notification). I am using proper credentials that come from the documentation: https://registry.terraform.io/providers/sysdiglabs/sysdig/latest/docs 

The Goal I am trying to accomplish is to create a notification for the sysdig monitoring alert. However I am getting this error consistently ..
```
sysdig_monitor_notification_channel_email.bam_alerts_test: Creating...
╷
│ Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.
│ 
│   with sysdig_monitor_notification_channel_email.bam_alerts_test,
│   on main.tf line 30, in resource "sysdig_monitor_notification_channel_email" "bam_alerts_test":
│   30: resource "sysdig_monitor_notification_channel_email" "bam_alerts_test" {
│ 
╵
```

**Comment by therealbobo** [comment]
Hey @marbcGH! Thanks for the issue but this repository is meant for the sysdig cli tool project and not for the Sysdig Agent project. To solve your issue please reach out the Sysdig support. 😄
