### ISSUE TITLE
Question: Implications of chisles removal from falcosecurity/libs

### ISSUE THREAD

**Issue by eugenesan** [draios/sysdig#2080]
I've noticed that chisels are planned to be removed from libs https://github.com/falcosecurity/libs/issues/1743
How is that going to affect sysdig?

**Comment by jasondellaluce** [comment]
@eugenesan Sysdig is so far the only (known) consumer of chisels. The plan is to hard-fork the code area related to chisels and maintaining it inside the sysdig repo from the moment of deprecation onwards. cc @therealbobo @leogr

**Comment by leogr** [comment]
> @eugenesan Sysdig is so far the only (known) consumer of chisels. The plan is to hard-fork the code area related to chisels and maintaining it inside the sysdig repo from the moment of deprecation onwards. cc @therealbobo @leogr

:+1: 

I also wanted to highlight that this won't disrupt sysdig users in any way. It's just a matter of moving a piece of codebase from one place to another.
