### ISSUE TITLE
the event information captured by sysdig is incomplete，and the evt.num is not consecutive？

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [draios/sysdig#2117]
I run sysdig in the terminal，but these event information is incomplete，that's why？
![image](https://github.com/draios/sysdig/assets/71766358/c18aea1b-db13-4b2c-b688-390e65e0f6a5)
sysdig version：0.38.0-rc1
system：
![image](https://github.com/draios/sysdig/assets/71766358/91badce0-3b78-4a91-8293-7f71e5005bdd)

**Comment by therealbobo** [comment]
The `evt.num` seems consecutive to me 🤔 The data captured by `sysdig` is limited to the `snaplen` setting which is 80 byte by default. If you need to capture more you can use the `--snaplen` option and accordingly set the snaplen with your needs. 😄
