### ISSUE TITLE
Sysdig -B crashes on multiple ubuntus

### ISSUE THREAD

**Issue by SilverPlate3** [draios/sysdig#2120]
### Machine 1:
Kernel version: 
`5.4.0-100-generic`
clang version:
```
Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-12/bin
```
LLVM version:
`LLVM version 12.0.0`

In this machine I installed latest release [tar.gz](https://github.com/draios/sysdig/archive/refs/tags/0.38.1.tar.gz) 
And did 
```
mkdir build
cd build
cmake -DBUILD_BPF=ON ..
make
```
Just as [page ](https://github.com/draios/sysdig/wiki/eBPF) says.

Then I executed sysdig like this
sudo `./userspace/sysdig/sysdig --bpf=driver/bpf/probe.o`
After few seconds I get:
![image](https://github.com/user-attachments/assets/108650c7-46ad-4dd8-8a5b-36a763d77cc1)

### Machine 2:
Kernel version:
`5.4.0-100-generic`

clang version:
```
Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-12/bin
```

LLVM version:
`LLVM version 12.0.0`

In this machine I did:
`apt-get install sysdig-0.38.0`
Then I executed the sysdig like this:
`sysdig -B`
After a few seconds I get:
![image](https://github.com/user-attachments/assets/879d6025-3c5e-47fe-a23e-a62ae00b6aeb)

Another question. The output of sysdig with EBPF is completly different then sysdig with KMOD 
EBPF:
![image](https://github.com/user-attachments/assets/db890855-aafa-4bc4-9ab3-53c4fa7388f4)
KMOD:
![image](https://github.com/user-attachments/assets/6c14920e-a7b1-4f22-bee4-66eac601eaf5)
Why is that? 
And will I be able to run the same chisels on both?

**Comment by therealbobo** [comment]
Hey @SilverPlate3! The old BPF probe seems broken on your kernel and it seems due to the complexity of the probe itself. `sysdig` is relying on the drivers of https://github.com/falcosecurity/libs. Please consider opening an issue.

> Another question. The output of sysdig with EBPF is completly different then sysdig with KMOD

The output is different because the probe doesnt' work corretly.

**Comment by SilverPlate3** [comment]
Thanks!
