### ISSUE TITLE
sysdiag install problem for kernel 6.10.10-100.fc39.x86_64

### ISSUE THREAD

**Issue by stfast** [draios/sysdig#2124]
# dnf install sysdig

Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                           1/1 
  Installing       : dkms-3.0.13-1.fc39.noarch                                                                                                                                                 1/2 
  Running scriptlet: dkms-3.0.13-1.fc39.noarch                                                                                                                                                 1/2 
Created symlink /etc/systemd/system/multi-user.target.wants/dkms.service → /usr/lib/systemd/system/dkms.service.

  Installing       : sysdig-0.38.1-1.x86_64                                                                                                                                                    2/2 
  Running scriptlet: sysdig-0.38.1-1.x86_64                                                                                                                                                    2/2 
Creating symlink /var/lib/dkms/scap/7.2.0+driver/source -> /usr/src/scap-7.2.0+driver
Sign command: /lib/modules/6.10.10-100.fc39.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
Building module(s).....(bad exit status: 2)
Failed command:
make -j10 KERNELRELEASE=6.10.10-100.fc39.x86_64 -C /lib/modules/6.10.10-100.fc39.x86_64/build M=/var/lib/dkms/scap/7.2.0+driver/build
Error! Bad return status for module build on kernel: 6.10.10-100.fc39.x86_64 (x86_64)
Consult /var/lib/dkms/scap/7.2.0+driver/build/make.log for more information.
Sign command: /lib/modules/6.10.10-100.fc39.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
Building module(s).....(bad exit status: 2)
Failed command:
make -j10 KERNELRELEASE=6.10.10-100.fc39.x86_64 -C /lib/modules/6.10.10-100.fc39.x86_64/build M=/var/lib/dkms/scap/7.2.0+driver/build
Error! Bad return status for module build on kernel: 6.10.10-100.fc39.x86_64 (x86_64)
Consult /var/lib/dkms/scap/7.2.0+driver/build/make.log for more information.
warning: %post(sysdig-0.38.1-1.x86_64) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package sysdig
  Verifying        : sysdig-0.38.1-1.x86_64                                                                                                                                                    1/2 
  Verifying        : dkms-3.0.13-1.fc39.noarch                                                                                                                                                 2/2 

Installed:
  dkms-3.0.13-1.fc39.noarch                                                                         sysdig-0.38.1-1.x86_64 

# cat  /var/lib/dkms/scap/7.2.0+driver/build/make.log

DKMS make.log for scap-7.2.0+driver for kernel 6.10.10-100.fc39.x86_64 (x86_64)
Mon Sep 23 07:24:31 PM CEST 2024
make: Entering directory '/usr/src/kernels/6.10.10-100.fc39.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 13.3.1 20240522 (Red Hat 13.3.1-1)
  You are using:           gcc (GCC) 13.3.1 20240913 (Red Hat 13.3.1-3)
[configure-kmod] Including /var/lib/dkms/scap/7.2.0+driver/build//configure/CLASS_CREATE_1/Makefile.inc /var/lib/dkms/scap/7.2.0+driver/build//configure/ACCESS_OK_2/Makefile.inc /var/lib/dkms/scap/7.2.0+driver/build//configure/DEVNODE_ARG1_CONST/Makefile.inc
[configure-kmod] Setting HAS_CLASS_CREATE_1 flag
[configure-kmod] Setting HAS_ACCESS_OK_2 flag
[configure-kmod] Setting HAS_DEVNODE_ARG1_CONST flag
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/main.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/fillers_table.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/dynamic_params_table.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/flags_table.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/ppm_events.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/syscall_table64.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/event_table.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/ppm_cputime.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/ppm_tp.o
  CC [M]  /var/lib/dkms/scap/7.2.0+driver/build/syscall_ia32_64_map.o
/var/lib/dkms/scap/7.2.0+driver/build/ppm_cputime.c:353:10: warning: no previous prototype for ‘nsec_to_clock_t’ [-Wmissing-prototypes]
  353 | uint64_t nsec_to_clock_t(uint64_t x)
      |          ^~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:509:14: warning: no previous prototype for ‘ppm_get_mm_exe_file’ [-Wmissing-prototypes]
  509 | struct file *ppm_get_mm_exe_file(struct mm_struct *mm)
      |              ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:550:15: warning: no previous prototype for ‘ppm_get_mm_counter’ [-Wmissing-prototypes]
  550 | unsigned long ppm_get_mm_counter(struct mm_struct *mm, int member)
      |               ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:729:5: warning: no previous prototype for ‘accumulate_argv_or_env’ [-Wmissing-prototypes]
  729 | int accumulate_argv_or_env(const void __user * argv,
      |     ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:784:5: warning: no previous prototype for ‘compat_accumulate_argv_or_env’ [-Wmissing-prototypes]
  784 | int compat_accumulate_argv_or_env(compat_uptr_t argv,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:884:6: warning: no previous prototype for ‘ppm_is_upper_layer’ [-Wmissing-prototypes]
  884 | bool ppm_is_upper_layer(struct file *exe_file){
      |      ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:2277:5: warning: no previous prototype for ‘f_sys_send_e_common’ [-Wmissing-prototypes]
 2277 | int f_sys_send_e_common(struct event_filler_arguments *args, int *fd)
      |     ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/main.c: In function ‘drop_nostate_event’:
/var/lib/dkms/scap/7.2.0+driver/build/ppm_fillers.c:2413:5: warning: no previous prototype for ‘f_sys_recv_x_common’ [-Wmissing-prototypes]
 2413 | int f_sys_recv_x_common(struct event_filler_arguments *args, int64_t *retval)
      |     ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/main.c:1653:22: error: implicit declaration of function ‘fd_is_open’; did you mean ‘finish_open’? [-Werror=implicit-function-declaration]
 1653 |                     !fd_is_open(close_fd, fdt)
      |                      ^~~~~~~~~~
      |                      finish_open
/var/lib/dkms/scap/7.2.0+driver/build/main.c: At top level:
/var/lib/dkms/scap/7.2.0+driver/build/main.c:2829:5: warning: no previous prototype for ‘scap_init’ [-Wmissing-prototypes]
 2829 | int scap_init(void)
      |     ^~~~~~~~~
/var/lib/dkms/scap/7.2.0+driver/build/main.c:2992:6: warning: no previous prototype for ‘scap_exit’ [-Wmissing-prototypes]
 2992 | void scap_exit(void)
      |      ^~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:244: /var/lib/dkms/scap/7.2.0+driver/build/main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/kernels/6.10.10-100.fc39.x86_64/Makefile:1946: /var/lib/dkms/scap/7.2.0+driver/build] Error 2
make: *** [Makefile:252: __sub-make] Error 2
make: Leaving directory '/usr/src/kernels/6.10.10-100.fc39.x86_64'

**Comment by Almazick** [comment]
the same issue, any solutions?

**Comment by unknowndevQwQ** [comment]
We may need to file an issue at https://github.com/falcosecurity/libs/issues

**Comment by unknowndevQwQ** [comment]
https://github.com/falcosecurity/libs/pull/1884
It looks like it should be fixed, maybe wait for the Fedora packager to use the patch from this PR?

**Comment by stfast** [comment]
> [falcosecurity/libs#1884](https://github.com/falcosecurity/libs/pull/1884) It looks like it should be fixed, maybe wait for the Fedora packager to use the patch from this PR?

It is fixed, it works on Fedora 40 with latest kernel-6.11.4-201.fc40.x86_64 too.
