### ISSUE TITLE
Rolling data

### ISSUE THREAD

**Issue by icholy** [draios/sysdig#263]
It would be useful to have a flag to specify how much data to preserve.

`sysdig -w <output> -e <expire>`

`sysdig -w dump -e 3h` 

This way I can have it constantly running on a server without it growing too big.

**Comment by icholy** [comment]
Related #216 #133

**Comment by rmack** [comment]
@icholy 

I understand the concept of running it for so long, but when you say "how much data to preserve", I am not sure how this translates to time, as each system depending on its load will produce a different amount of data given an expiration time period.

Doesn't the log rotation solve this problem for you as referenced in issue #133 ? I.e. log file size plus the ability to rotate logs?  This would, I believe, solves your statement; "This way I can have it constantly running on a server without it growing too big."

How do you envision this option as being important, when would you use it, thank you?

**Comment by icholy** [comment]
@rmack you're right. #133 is what I want.
