### ISSUE TITLE
Network events generated by a Windows app under wine are not traced

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#278]
Hi. I'm running a Windows application under wine. It does some TCP stuff. I can see the communication with strace, but with sysdig those events just aren't there. Basic sysdig filters such as 'evt.type = connect' and 'fd.ip = 192.168.x.y' return nothing relevant. I know that the application actually does those things because the device at that ip sees the traffic and, like I said, because strace sees this.

I'm making an assumption that the wine layer is somehow responsible. Is this expected? I can point you to the specific executable if that's helpful, but asking first seems like a good idea.

Thanks

**Comment by dkogan** [comment]
Hi. I still don't have a fix, but at least I now know what the problem is. The core of the problem is that I'm running a 64-bit Linux install (Debian amd64), but wine is a 32-bit process. The same behavior (sysdig not seeing any events) can be reproduced by building a 32-bit application, and trying to sysdig it. For instance, say I have tst.c:

    #include <stdio.h>
    #include <stdlib.h>

    #include <sys/types.h>
    #include <sys/stat.h>
    #include <fcntl.h>

    int main(int argc, char* argv[])
    {

        while(1)
        {
            int fd = open("/dev/null", O_RDONLY);
            close(fd);
            sleep(1);
        }

        return 0;
    }


Then I build it with

    gcc -m32 -o tst tst.c

Sysdig sees no events from this application; strace does see events. This is a general issues with Linux tracepoints. I see the same no-events-seen behavior when using tracepoints more directly by poking around in

    /sys/kernel/debug/tracing

This possibly isn't fixable without heavy kernel mods. I may look at some point, but in the meantime it's probably OK to close this issue, which I'm doing now. Thanks

**Comment by kalgnana** [comment]
> Hi. I still don't have a fix, but at least I now know what the problem is. The core of the problem is that I'm running a 64-bit Linux install (Debian amd64), but wine is a 32-bit process. The same behavior (sysdig not seeing any events) can be reproduced by building a 32-bit application, and trying to sysdig it. For instance, say I have tst.c:
> 
> ```
> #include <stdio.h>
> #include <stdlib.h>
> 
> #include <sys/types.h>
> #include <sys/stat.h>
> #include <fcntl.h>
> 
> int main(int argc, char* argv[])
> {
> 
>     while(1)
>     {
>         int fd = open("/dev/null", O_RDONLY);
>         close(fd);
>         sleep(1);
>     }
> 
>     return 0;
> }
> ```
> 
> Then I build it with
> 
> ```
> gcc -m32 -o tst tst.c
> ```
> 
> Sysdig sees no events from this application; strace does see events. This is a general issues with Linux tracepoints. I see the same no-events-seen behavior when using tracepoints more directly by poking around in
> 
> ```
> /sys/kernel/debug/tracing
> ```
> 
> This possibly isn't fixable without heavy kernel mods. I may look at some point, but in the meantime it's probably OK to close this issue, which I'm doing now. Thanks

I am facing the same issue with 5.4.0-52-generic kernel version. Which is the right forum to raise this issue or track the updates.
