### ISSUE TITLE
Bad syntax in zsh completion 

### ISSUE THREAD

**Issue by jovaha** [draios/sysdig#290]
The completion function for zsh doesn't work.  The problem is a bad quote.

The solution is easy. Line 215 in [ sysdig/scripts/completions/zsh/_sysdig](https://github.com/draios/sysdig/blob/dev/scripts/completions/zsh/_sysdig)

`    '(-E --exclude-users)'{-E,--exclude-users}'[Don't create the user/group tables when starting]'       \`
should be changed to
`    '(-E --exclude-users)'{-E,--exclude-users}'[Don'\''t create the user/group tables when starting]'       \`
or
`    '(-E --exclude-users)'{-E,--exclude-users}"[Don't create the user/group tables when starting]"       \`.

The problem is that the ' in Don't ends the quote.

**Comment by vampolo** [comment]
Thank you for you report. it should be fixed in the `dev` branch now.
