### ISSUE TITLE
Need chisel for count TOP HTTP Url with group by process name and tcp port

### ISSUE THREAD

**Issue by Slach** [draios/sysdig#293]
Can sysdig parse http protocol and get URL when monitoring 80 TCP port?

I need chisel for count TOP HTTP URL with group by process name and tcp port 
and with filter by URL

**Comment by rmack** [comment]
@Slach, Would you like to take a stab at this?

Here are some references for you:
* [Chisel Reference Manual](https://github.com/draios/sysdig/wiki/sysdig%20Chisel%20API%20Reference%20Manual)
* [Chisel Tutorial](https://github.com/draios/sysdig/wiki/Writing%20a%20Sysdig%20Chisel,%20a%20Tutorial)
* Chisels are under sysdig/userspace/sysdig/chisel, you can see examples here.

**Comment by Slach** [comment]
thanks @rmack 
I will try, but I don't know LUA ;)

**Comment by rmack** [comment]
@Slach, Please take a look at these links for help with Lua. If you get something started reach out to me and I can take a look, thank you very much @Slach.

* [Learn Lua in 15 Minutes](http://tylerneylon.com/a/learn-lua/)
* [Learn X in Y minutes](http://learnxinyminutes.com/docs/lua/)

**Comment by luca3m** [comment]
We have `httptop` and `httplog` chisel now, check if they work for you!

**Comment by Slach** [comment]
awesome ;) thanks guys !
