### ISSUE TITLE
unable to run 0.1.95

### ISSUE THREAD

**Issue by pjagielski** [draios/sysdig#295]
$ sudo sysdig
error mapping the ring buffer for device /dev/sysdig0

output from dmesg:
[Fri Jan 23 09:36:36 2015] sysdig_probe: Invalid mmap size 16777216

version 0.1.93 works fine 

env: Ubuntu 12.04.4 LTS (GNU/Linux 3.2.0-70-generic x86_64)

**Comment by gianlucaborello** [comment]
It seems like you are using the new sysdig binary with the old sysdig-probe kernel module. If you installed it from packages, can you try with "rmmod sysdig-probe; modprobe sysdig-probe"?

**Comment by wendigo** [comment]
@gianlucaborello is right - I have observed the same issue with kernel module / client application mismatch

**Comment by pjagielski** [comment]
OK, I worked, thanks

**Comment by retrohacker** [comment]
I had installed via package manager first, then run `aptitude purge sysdig` and encountered this error after reinstalling through `curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash`

`rmmod sysdig-probe; modprobe sysdig-probe` did the trick
