### ISSUE TITLE
sysdig segfaults when used with topfiles_bytes chisel and incorrect event type

### ISSUE THREAD

**Issue by checkmypi** [draios/sysdig#296]
```
# sysdig --version
sysdig version 0.1.95
# uname -a
Linux  2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 16 06:12:23 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
# sysdig -c topfiles_bytes evt.type=pwdbc
Segmentation fault (core dumped)
```

**Comment by vampolo** [comment]
Hi checkmypi

What system call are you tring to detect with the /evt.type=pwdbc/ filter ?

Looking at http://syscalls.kernelgrok.com/ and searching for /pw/ i only 
find /pwwrite64/ /epoll_pwait/ and /pwritenv/ as valid system calls.

Anyway i just compiled sysdig 0.1.95 and tried your command

|➜  build git:(dev) sudo sysdig -c topfiles_bytes evt.type=pwdbc
unknown event type pwdbc
|

As supposed i see the error with the syscall. Did you compiled sysdig 
yourself? If you see the /Segmentation Fault/ can you give us more 
informations about it ?

On 23/01/2015 15:30, checkmypi wrote:

>
>   sysdig --version
>
> sysdig version 0.1.95
>
>
>   uname -a
>
> Linux 2.6.32-431.23.3.el6.x86_64 #1 
> <https://github.com/draios/sysdig/issues/1> SMP Wed Jul 16 06:12:23 
> EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
>
>
>   sysdig -c topfiles_bytes evt.type=pwdbc
>
> Segmentation fault (core dumped)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/draios/sysdig/issues/296>.
>
​

**Comment by gianlucaborello** [comment]
This is a known issue in 0.1.95, it has been fixed on dev (https://github.com/draios/sysdig/issues/295).

Please use the dev branch or wait a few days until we release 0.1.96

thanks
