### ISSUE TITLE
Mouse pointer legend not changing when new AWS Service view selected.

### ISSUE THREAD

**Issue by mlewald** [draios/sysdig#298]
The legend at the mouse pointer is wrong on the 'aws.rds.BinLogDiskUsage'  panel after selecting another panel from ELB Instances view

![1-wrong mouse pointer legend](https://cloud.githubusercontent.com/assets/9828569/5930592/2a5c7ba8-a646-11e4-809c-fa8ed7ddbaf8.jpg)
:

On ELB Instances View I selected an instance then the aws.elb.UnHealthyHostCount    then goto  RDS Instances View, pick an instance and see the default aws.rds.BinLogDiskUsage subview appear but with the wrong text forthe legend at teh mouse pointer.

This seems to be the case with any previous view chosen. and any AWS services views,  

If I then select another RDS view from drop down views list, the legend changes.

Mac and PC,  tried refreshing page and F5 - didnt clear until I selected another subview.

tested on app.sdc.com only

**Comment by gianlucaborello** [comment]
This should probably go to the SDC repository, this is for the opensource sysdig :)
