### ISSUE TITLE
thread exe doesn't contain the full path when the process comes from capturing clone

### ISSUE THREAD

**Issue by ldegio** [draios/sysdig#3]
the clone and execve filler only captures the process executable name, not the full exe. This creates inconsistencies with getting the info from proc.

HOW TO REPLICATE
1. ./sysdig -p"%user.name) %proc.name %proc.exe" "evt.type=procexit"
2. cat
3. CTRL+C for cat
   -> result: root) cat cat
4. cat
5. ./sdump -p"%user.name) %proc.name %proc.exe" "evt.type=procexit"
6. CTRL+C for cat -> result: cat /usr/bin/cat

**Comment by therealbobo** [comment]
The `%proc.exepath` prints exactly the executable path! 😄
