### ISSUE TITLE
lsof showing duplicates

### ISSUE THREAD

**Issue by icholy** [draios/sysdig#300]
The `lsof` chisel is showing the same file descriptor multiple times with only the `TID` (thread id) changing. This doesn't make sense because threads share file descriptors.

Is there a way to get the chisel's results to match those of lsof?

**Comment by ldegio** [comment]
you are right, but this is "by design". 

File descriptors are internally stored by sysdig only in the main thread entry of the thread table, but the chisel choses to show them for each child thread. This, as you point out, is not accurate, on the other hand those *are* file descriptors accessible by that thread, so not showing them might be even more confusing.

Maybe we could implement a flag in the chisel to trigger the behavior you desire, it just needs to be well documented because it could be hard to understand. If you think it would be useful, feel free to send a pull request, it should be a pretty easy change to the chisel.

**Comment by icholy** [comment]
I can't think of a way of introducing a flag without breaking backward compatibility with the current interface. Is there a way to have two optional arguments?

**Comment by ldegio** [comment]
having two optional arguments, as far as I know, should not be a problem. You just declare both of them as optional in the args section of the chisel.

Another possibility is having the chisel (optionally or by default) show only processes and not threads. This could be an issue in some unlikely situations when the use is looking for a specific thread, but in 90% of the cases would show a clearer output.

**Comment by rmack** [comment]
@icholy 

Can you please help me understand what you mean by the output matching lsof, thank you? I would like to clarify on your original input before making any changes to the chisel.  With this...

Specifically I tried running **lsof** and the sysdig **chisel lsof** and it appears they are both doing what you have described above. I.e. "showing the same file descriptor multiple times with only the TID (thread id) changing".

E.g.
-----
I used sqlite3 and created a table with all of the output from the **chisel lsof**.  I then queried looking for thread ids changing within the same pid, but the FD staying the same.  After finding a PID with this occurrence I ran the the chisel again filtering on this PID and then ran **lsof** again grepping for the same PID.  It appears **lsof** does the same thing as the **chisel lsof**. As you can see below in my sample output the **FD** and **NODE NAME** stay the same, but the **TID** changes.

lsof output
-------------
COMMAND     PID **TID**        USER **FD**    TYPE             DEVICE   SIZE/OFF       NODE NAME
Xorg               1658 **N/A**    root    **cwd**     DIR                8,1       4096     524296 /etc/X11
Xorg               1658**1677**  root    **cwd**     DIR                8,1       4096     524296 /etc/X11
Xorg               1658**1678**  root    **cwd**     DIR                8,1       4096     524296 /etc/X11
...

**Comment by icholy** [comment]
@rmack I don't get `TID` as a column in `lsof`'s output.

```
$ sudo lsof | head                  
COMMAND     PID       USER   FD      TYPE             DEVICE   SIZE/OFF       NODE NAME
init          1       root  cwd       DIR                8,2       4096          2 /
init          1       root  rtd       DIR                8,2       4096          2 /
init          1       root  txt       REG                8,2     167192   23639101 /sbin/init
init          1       root  mem       REG                8,2      52120   21279077 /lib/x86_64-linux-gnu/libnss_files-2.15.so
init          1       root  mem       REG                8,2      47680   21279462 /lib/x86_64-linux-gnu/libnss_nis-2.15.so
init          1       root  mem       REG                8,2      97248   21279076 /lib/x86_64-linux-gnu/libnsl-2.15.so
init          1       root  mem       REG                8,2      35680   21279458 /lib/x86_64-linux-gnu/libnss_compat-2.15.so
init          1       root  mem       REG                8,2    1811128   21279108 /lib/x86_64-linux-gnu/libc-2.15.so
init          1       root  mem       REG                8,2      31752   21275335 /lib/x86_64-linux-gnu/librt-2.15.so
```

My `lsof` version info.

```
$ lsof -v
lsof version information:
    revision: 4.81
    latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
    latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
    latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
    constructed: Sun Mar 7 03:33:46 UTC 2010
    constructed by and on: buildd@crested
    compiler: cc
    compiler version: 4.4.3 (Ubuntu 4.4.3-3ubuntu1) 
    compiler flags: -DLINUXV=26024 -DGLIBCV=211 -DHASIPv6 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAS_STRFTIME -DLSOF_VSTR="2.6.24-23-server" -O
    loader flags: -L./lib -llsof 
    system info: Linux crested 2.6.24-23-server #1 SMP Wed Apr 1 22:14:30 UTC 2009 x86_64 GNU/Linux
    Anyone can list all files.
    /dev warnings are disabled.
    Kernel ID check is disabled.
```

**Comment by rmack** [comment]
@icholy - Thank you very much for providing this information to me, and your example.  It looks like the **lsof chisel** is producing the same result with my version of **lsof**. I would think this would also mean that the latest version of **lsof** coincides with sysdig's current way of showing a result set. Can you version of **lsof** produce output with the thread ID, and if so what does it look like, thank you?

Do you still believe it would bring value to add an argument to remove the TID from the chisel? I believe the result set is a correct representation of the data given its tabular output.  I am very interested in hearing your opinion on this given the latest version of lsof, thank you?

My Version
--------------
~~~ bash
$lsof -v
lsof version information:
    revision: 4.86
    latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
    latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
    latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
    constructed: Sun Dec 2 02:36:48 UTC 2012
    constructed by and on: buildd@allspice
    compiler: cc
    compiler version: 4.7.2 (Ubuntu/Linaro 4.7.2-12ubuntu1) 
    compiler flags: -g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DLINUXV=37000 -DGLIBCV=216 -DHASIPv6 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DHAS_STRFTIME -DLSOF_VSTR="3.7.0" -O
    loader flags: -L./lib -llsof -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now
    system info: Linux allspice 3.2.0-33-generic #52-Ubuntu SMP Thu Oct 18 16:29:15 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
    Anyone can list all files.
    /dev warnings are disabled.
    Kernel ID check is disabled.

**Comment by icholy** [comment]
@rmack - With my current version (the one that ships with **Ubuntu 12.04**), I can't find an option for enabling the `TID` column. However, the version that ships with **Ubuntu 14.10** does have it.

In light of this, I agree that the chisel has the correct behaviour.

**Comment by ewirch** [comment]
So how would one tell `lsof` to list file descriptors only per process (don't repeat for each thread). Current behavior makes it really hard to diagnose "too many opened files" problems.

**Comment by Cousjava** [comment]
@ewirch `lsof -Ki` to ignore threads

**Comment by johnyannj** [comment]
@Cousjava  -Ki  not work
