### ISSUE TITLE
chisel.set_event_formatter("default") dropping %evt.num

### ISSUE THREAD

**Issue by Hefeweizen** [draios/sysdig#317]
My understanding is that passing "default" to chisel.set_event_formatter() should produce identical output to sysdig.  It does not.  It drops the %evt.num field.

--------
tested on 0.1.96

**Comment by Hefeweizen** [comment]
And I don't really expect this to work, but I'm mentioning it:  sysdig -p "default" just repeats the word on screen.  I bring this up more because it sounds like there's two different code paths for filter output.  How hard would it be to have one?

**Comment by rmack** [comment]
@Hefeweizen, you are correct the current dev and master branch are not printing the **%evt.num** field.  I am looking into it and might add it back in, thank you.
