### ISSUE TITLE
branch "curses" - funky layout and 'reserve_thread_memory' error.

### ISSUE THREAD

**Issue by Hefeweizen** [draios/sysdig#320]
I'm loathe to call this a bug, as I don't believe the branch is meant to be considered 'done'.  That said, I saw the demo at Meetup#2 and I was excited to play with systop.  The screen shot below is a build on Ubuntu Trusty 64 inside a vagrant machine - so some formatting/screen drawing needs to be ironed out.

Also, if I press enter, I get:
```bash
$ sudo systop
reserve_thread_memory can't be called after capture starts
```
I'm not sure what's breaking.

As a final point, systop isn't created by the 'make install'; I manually linked it.

Just close this if it's entirely too premature.  Or, if you want further info, let me know.

![screen shot 2015-02-16 at 22 38 42](https://cloud.githubusercontent.com/assets/3291490/6224176/9ce85714-b62c-11e4-8eb9-e0731ae91c0f.png)

**Comment by ldegio** [comment]
yes, this should be considered unstable yet. I let you know when we reach the point where this is usable. In the meantime I'm closing this issue.
