### ISSUE TITLE
sysdig -pc -c spy_users is not showing container commands

### ISSUE THREAD

**Issue by rothgar** [draios/sysdig#334]
I have active containers running I wanted to test spy_users with. I wasn't seeing any output from inside the containers running sysdig 0.1.98-1

Here's an example of what I did
```
sysdig -pc -c spy_users
docker run --rm -it centos bash
```
Inside the container I run any command and it doesn't show up under spy_users nor do commands from my other running containers. I was basing my testing off the latest blog post showing this functionality but it isn't working for me on Red Hat 6.6

**Comment by gianlucaborello** [comment]
I just tried typing your same exact commands from a CentOS 6.6. I tried running sysdig before and after starting the docker container, and in both cases I was able to see the commands in spy_users. Is there something non-obvious in your setup? Maybe you upgraded sysdig from an older version and forgot to reload the kernel module?

If not, I'll need a trace file while you run these commands inside the container to troubleshoot what's going on.

Thanks.

**Comment by rothgar** [comment]
I rebooted to make sure the module was completely reloaded. What's the
command to give you a trace? I can do it Monday and report back.

I'm running docker 1.4.1 if that makes a difference.

On Friday, March 6, 2015, Gianluca Borello <notifications@github.com> wrote:

> I just tried typing your same exact commands from a CentOS 6.6. I tried
> running sysdig before and after starting the docker container, and in both
> cases I was able to see the commands in spy_users. Is there something
> non-obvious in your setup? Maybe you upgraded sysdig from an older version
> and forgot to reload the kernel module?
>
> If not, I'll need a trace file while you run these commands inside the
> container to troubleshoot what's going on.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/draios/sysdig/issues/334#issuecomment-77667847>.
>


-- 
Sent from my phone

**Comment by gianlucaborello** [comment]
You can just do "sysdig -zw trace.scap" while you execute the commands inside the container. I'm very curious to dig into this issue because it's working fine for me on what seems to be a very similar setup to yours.

**Comment by rmack** [comment]
@rothgar, please note I also tried it as well on the dev branch and everything is working well for me too.  I ran it from Ubuntu with the centos container. I ran the following command and got the following output. If you look you will see me simply doing an ls -lrt with the container and it showing up within the output. In addition to Gianluca's comments/request, where did you get your version of sysdig, thank you?

~/git/sysdig/userspace/sysdig/chisels $ sudo sysdig -pc -c spy_users
[sudo] password for x: 
23571 20:54:11 x@host) docker run --rm -it centos bash
23571 20:54:46 x@host) docker run --rm -it centos /usr/bash
23571 20:54:51 x@host) ls --color=auto -lrt /usr/bash
23571 20:54:54 x@host) /bin/sh /usr/bin/which bash
23571 20:55:01 x@host) docker run --rm -it centos /bin/bash
23571 20:55:21 x@host) sudo docker run -v /home/x:/media -i -t centos /bin/bash
    23571 20:55:21 root@host) docker run -v /home/x:/media -i -t centos /bin/bash
6161 20:55:22 root@host) mkdir -p /run/network
6161 20:55:22 root@host) ifquery --allow hotplug -l
6161 20:55:22 root@host) grep -q ^veth13b6a1c$
6168 20:55:22 root@host) mkdir -p /run/network
6168 20:55:22 root@host) ifquery --allow hotplug -l
6168 20:55:22 root@host) grep -q ^veth2093885$
6174 20:55:22 root@host) ifquery --allow hotplug -l
6174 20:55:22 root@host) grep -q ^veth13b6a1c$
6143 20:55:22 root@compassionate_perlman) grep -qi ^COLOR.*none /etc/GREP_COLORS
    6143 20:55:22 root@compassionate_perlman) tty -s
    6143 20:55:22 root@compassionate_perlman) tput colors
    6143 20:55:22 root@compassionate_perlman) mktemp .colorlsXXX --tmpdir=/tmp
6143 20:55:22 root@compassionate_perlman) grep --color=auto -v ^INCLUDE /etc/DIR_COLORS
    6143 20:55:22 root@compassionate_perlman) dircolors --sh /tmp/.colorlsgOX
6143 20:55:22 root@compassionate_perlman) rm -i -f /tmp/.colorlsgOX
6143 20:55:22 root@compassionate_perlman) grep --color=auto -qi ^COLOR.*none /etc/DIR_COLORS
6143 20:55:24 root@compassionate_perlman) ls --color=auto -lrt
6227 20:56:36 root@host) ifquery --allow hotplug -l
6227 20:56:36 root@host) grep -q ^veth2093885$
23571 20:56:52 x@host) sudo docker run --rm -it centos /bin/bash
    23571 20:56:52 root@host) docker run --rm -it centos /bin/bash
6256 20:56:52 root@host) mkdir -p /run/network
6256 20:56:52 root@host) ifquery --allow hotplug -l
6256 20:56:52 root@host) grep -q ^veth470a2dc$
6267 20:56:52 root@host) mkdir -p /run/network
6267 20:56:52 root@host) grep -q ^veth8b2e9ab$
6267 20:56:52 root@host) ifquery --allow hotplug -l
6271 20:56:52 root@host) grep -q ^veth470a2dc$
6271 20:56:52 root@host) ifquery --allow hotplug -l
6246 20:56:52 root@angry_banach6) grep -qi ^COLOR.*none /etc/GREP_COLORS
    6246 20:56:52 root@angry_banach6) tty -s
    6246 20:56:52 root@angry_banach6) tput colors
    6246 20:56:52 root@angry_banach6) mktemp .colorlsXXX --tmpdir=/tmp
6246 20:56:52 root@angry_banach6) grep --color=auto -v ^INCLUDE /etc/DIR_COLORS
    6246 20:56:52 root@angry_banach6) dircolors --sh /tmp/.colorlsJRH
6246 20:56:52 root@angry_banach6) rm -i -f /tmp/.colorlsJRH
6246 20:56:52 root@angry_banach6) grep --color=auto -qi ^COLOR.*none /etc/DIR_COLORS
6246 20:56:55 root@angry_banach6) ls --color=auto -lrt

**Comment by rothgar** [comment]
I just tried again on my el workstation and also on my fedora 21 laptop with the same result. I'm posting output from fedora with docker 1.5.0 as I was more easily able to make the trace less noisy.
I started a container `docker run --rm -it ubuntu bash` and then ran `ls -latr` and `ps aux` and then stopped the trace and container.

Upon examining the trace [file here](https://transfer.sh/ICJG1/trace.scap) I found the commands are in the trace but I did not see the commands in my shell running `sysdig -pc -c spy_users`

So the the problem may only be with the chisel or I may have something wrong with my command

**Comment by gianlucaborello** [comment]
Seems to work for me from the trace file:

```
$ sysdig -pc -r trace.scap -c spy_users
18717 08:49:28 root@grave_wozniak) ls --color=auto -latr
18717 08:49:31 root@grave_wozniak) ps aux
18660 08:49:36 root@host) clear
```

**Comment by rothgar** [comment]
Yes, the capture shows the commands run. But is there a reason spy_users doesn't work for containers in an interactive shell?

**Comment by rmack** [comment]
@rothgar, spy_users output should show up while in an interactive shell. The output from my example above was working this way.  I have also tried this with different version of Docker and again everything seems to be working for me under Linux Mint, Ubuntu, and CentOS.  I haven't tried in on Fedora yet.  Can you provide any more env details?  Thank you.

**Comment by rothgar** [comment]
I just tried again logging in as root in runlevel 3. I used two ttys in one I watched spy_users and the 2nd I ran the container commands. That time it worked so it must only be a problem when using sudo as my user. I restarted runlevel 5 and then tried with my user and the spy_users output was blank again for the container commands.

I started another trace and ran `docker run --rm -it ubuntu bash` and ran `ls -latr` and `ps aux` while the trace was running. This time I don't see that output in the [trace file](transfer.sh/FYBzH/trace.scap).

The spy_users output shows me running docker and the next thing you see is `git ls-files --other --exclude-standard` which is part of my shell prompt.

**Comment by rmack** [comment]
@rothgar, can you try su - and then running the sysdig -pc -c spy_users command. Then try running your docker command and let us know what happens, thank you.

**Comment by rothgar** [comment]
Tried with `su -`, `su`, and `sudo su -` and all three showed no container command output for spy_users.

I dropped back down to runlevel 3 and tried logging in with my local user using sudo and the output was blank. Leaving one tty logged in as me I opened another tty and logged in as root (leaving the container running). In that shell the spy_users output was correct.

**Comment by gianlucaborello** [comment]
I think the issue I just fixed could have been the cause, if you can play a bit with it and confirm would be great (probably a more efficient fix can be done).

**Comment by rothgar** [comment]
Although I couldn't get the code compiled on either of my machines I was able to update to 0.1.99 and this is working for me now.

Thanks for the help
