### ISSUE TITLE
‘__NR_prlimit64’ undeclared

### ISSUE THREAD

**Issue by naox** [draios/sysdig#335]
```
[ 32%] Building C object userspace/libscap/CMakeFiles/scap.dir/scap_procs.c.o
/root/a/f/sysdig/userspace/libscap/scap_procs.c: In function ‘scap_proc_fill_flimit’:
/root/a/f/sysdig/userspace/libscap/scap_procs.c:236:13: error: ‘__NR_prlimit64’ undeclared (first use in this function)
/root/a/f/sysdig/userspace/libscap/scap_procs.c:236:13: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [userspace/libscap/CMakeFiles/scap.dir/scap_procs.c.o] Error 1
make[1]: *** [userspace/libscap/CMakeFiles/scap.dir/all] Error 2
make: *** [all] Error 2
```
when I edit userspace/libscap/scap_procs.c from:
```
static int32_t scap_proc_fill_flimit(uint64_t tid, struct scap_threadinfo* tinfo)
#ifdef SYS_prlimit64
{
        struct rlimit rl;

        if(syscall(SYS_prlimit64, tid, RLIMIT_NOFILE, NULL, &rl) == 0)
        {
                tinfo->fdlimit = rl.rlim_cur;
                return SCAP_SUCCESS;
        }

        tinfo->fdlimit = -1;
        return SCAP_SUCCESS;
}
#else
{
        tinfo->fdlimit = -1;
        return SCAP_SUCCESS;
}
#endif
```
to:
```
static int32_t scap_proc_fill_flimit(uint64_t tid, struct scap_threadinfo* tinfo)
{
        tinfo->fdlimit = -1;
        return SCAP_SUCCESS;
}
```

sysdig compiles and works fine.

I'm using kernel 3.4.106 (compiled myself). Am I missing something in kernel? Perhaps there is some undocumented kernel dependency? CONFIG_TRACEPOINTS and CONFIG_HAVE_SYSCALL_TRACEPOINTS are compiled in.

**Comment by gianlucaborello** [comment]
Should be fixed now. Out of curiosity, I'd like to get your kernel config and what distribution you're using.

**Comment by naox** [comment]
yes, this fix works.
I'm using centos 5.3 and I compile sysdig with
CC=/opt/rh/devtoolset-1.1/root/usr/bin/gcc CXX=/opt/rh/devtoolset-1.1/root/usr/bin/g++  cmake -DCMAKE_INSTALL_PREFIX=/usr/sysdig ..
and kernel line 3.4.x from kernel.org and its .config is http://pastebin.com/r1Dd4iVb

**Comment by gianlucaborello** [comment]
Ah, that explains, you're running Centos 5 so probably a very old userspace runtime despite the new kernel, thanks for the clarification.
