### ISSUE TITLE
Add documentation for loading/unloading probe kernel module

### ISSUE THREAD

**Issue by rothgar** [draios/sysdig#337]
The [documentation for running sysdig from source](http://www.sysdig.org/wiki/how-to-install-sysdig-from-the-source-code/) is helpful for building sysdig but it also would be helpful for users to have code examples of checking/unloading the current sysdig kernel module and loading the newly built module so the new sysdig binary can be used.

eg
```
# Verify module info
modinfo sysdig_probe

# check if module is loaded
lsmod | grep sysdig

# unload module
modprobe -r sysdig_probe

# load new module
insmod ./build/sysdig-probe.ko
```

**Comment by rmack** [comment]
@rothgar, thank you.  Please note we do have this in the wiki: https://github.com/draios/sysdig/wiki/How%20to%20Install%20Sysdig%20from%20the%20Source%20Code

If you want to install the driver in the current kernel modules directory, then use (as root):
**make install_driver**

Even with this I understand your request and I will update the wiki at the link location mentioned above.

**Comment by rmack** [comment]
I have updated the wiki: https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code
