### ISSUE TITLE
/sys/module/sysdig_probe/parameters/max_consumers - allow read/write

### ISSUE THREAD

**Issue by Hefeweizen** [draios/sysdig#341]
https://github.com/draios/sysdig/blob/dev/driver/main.c#L1713 - currently, the max_consumers parameter is set to read only; the value can be set at module load time.

request: adjust this so that the parameter is writable

https://github.com/draios/sysdig/pull/336 <- has a discussion that suggests this could be fairly straightforward, but extensive testing should be done.

Creating this ticket to track that work.

**Comment by jarun** [comment]
Hi,

Can you explain what kind of testing would be required for this?

**Comment by ChanderG** [comment]
Only partially related to this issue, but if anyone else was wondering how to set the max_consumers paramter:
