### ISSUE TITLE
CoreOS support?

### ISSUE THREAD

**Issue by storedbox** [draios/sysdig#342]
Would love to see sysdig officially supported on [CoreOS](http://coreos.com).

**Comment by gianlucaborello** [comment]
I just added "CoreOS" to the list of supported distributions.

To install on CoreOS you can just follow the standard guide, skipping the installation of kernel headers:

https://github.com/draios/sysdig/wiki/How%20to%20Install%20Sysdig%20for%20Linux#installation-inside-a-docker-container

**Comment by PierreKircher** [comment]
https://github.com/coreos/bugs/issues/325
