### ISSUE TITLE
Distinguishing chisel parameter/filter from sysdig filter

### ISSUE THREAD

**Issue by mkevac** [draios/sysdig#343]
If one wants to see a process list from 11:00:00, one could use sysdig like this

```
sysdig -r /tmp/sysdig.dump -c ps "evt.time.s=11:00:00"
```

But it does not work because chisel "ps" itself awaits parameter that it will use as a filter. So there is no way to distinguish chisel filter from sysdig filter.

The way to overcome this problem right now is to use "allow all" filter for chisel like this

```
sysdig -r /tmp/sysdig.dump -c ps "thread.tid!=0" "evt.time.s=11:00:00"
```

**Comment by Hefeweizen** [comment]
it's non-intuitive, but you do have recourse:
```bash
$ sysdig -r /tmp/sysdig.dump "evt.time.s=11:00:00" -c ps
```
That said, I appreciate that it would be easier if there were a way to specify non-chisel filters.  Perhaps a '-f' flag to clearly specify that the filter should be applied by sysdig itself and not the chisel.
