### ISSUE TITLE
Top procs by cpu chisel inconsistency

### ISSUE THREAD

**Issue by bhnedo** [draios/sysdig#346]
I just compared the output of the chisels (topprocs_cpu) which display the top processes by CPU usage. The first one is from the old chisel version and the output seems to be correct:

CPU%      Process   
20.60%    plugin-containe
14.30%    dolphin
5.97%     sysdig
4.11%     kwin
2.45%     Xorg
1.69%     java
1.08%     beam.smp
1.06%     konsole
1.02%     alsa-sink
0.94%     pulseaudio

Now the output from the latest chisel's version:

CPU%      Process   PID       
131.23%   java      4283
106.40%   plugin-con4689
53.74%    mongod    1364
26.10%    alsa-sink 2948
17.97%    pulseaudio2948
15.12%    sysdig    13439
12.91%    threaded-m4689
5.28%     java      4366
4.63%     java      5802
4.50%     beam.smp  2171

The average values for cpu usage are going too high in comparison to the first chisel. Diving into the sources of the chisel, I can see that the old  version used the "proc.name" field as a table key, while the latest version indexes by the key which is built by concatenating various keys. Later on, in the `on_interval` function the key is extracted from `cpustates` table as follows `key = cpustates[cpuid][4]`, which is the next process  saved in `on_event` callback as follows ` cpustates[cpuid][4] = evt.field(fnext)`, but the key of `grtable` holds the concatenated fields, rather then the process name itself. Can someone please confirm this?

Cheers

**Comment by ldegio** [comment]
You are right, and looks like the issue has been introduced by this commit bcf1948383e91b25692dff3af13d335902e05dd4. Since you've already looked into it, would you be willing to send a patch? Otherwise, I can just revert that commit.

**Comment by bhnedo** [comment]
Hi ldegio

Yes, I can confirm the issue has been introduced by the after-mentioned commit. If the `key`variable is initialized with `proc.name` field instead of the concatenated ones, everything works as expected.
Please give me some time, so I can work on it and prepare the patch.

Regards

Nedim

**Comment by ldegio** [comment]
@bhnedo, just checking if you made progress on this. I want to make sure this is fixed by the time we make the next release.

**Comment by bhnedo** [comment]
I didn't manage to make it work the "easy" way. The solution I had to implement requieres a significant amount of refactoring. Rather then keeping the stats as a table key, I moved it to a separate data structure, and a new "index" field is used keep track of those stats. Here is a full code that is part of a project I'm working on by aggregating and streaming the chisels statistics (mostly LXC related ones) over ZeroMQ sockets. The "middleclass" rock is used to implement this in a object oriented fashion.

```lua
local json = require 'dkjson'
local class = require 'middleclass'

-- Base class for the container stats. Statistics are serialized to JSON format
-- and streamed over ZeroMQ socket using the PUSH pattern.
local LxcStats = class('LxcStats')

--- Creates an instance of LXC stat.
-- @param chisel reference to the sysdig chisel
-- @param zmqsock 0mq socket for statistics streaming
function LxcStats:initialize(chisel, zmqsock)

    self.chisel = chisel
    self.zmqsock = zmqsock

    assert(self.chisel ~= nil, 'Chisel reference should not be null')
    assert(self.zmqsock ~= nil, 'ZeroMQ socket instance cannot be null')

    self.chisel_fields = {}
    self.chisel_field_names = {}

    self.top = 10

    self.value_field_name = 'bytes'
    self.index_field = nil

    self.value_field = nil
    self.ts_field = nil

    self.units = 'none'
    self.typology = 'none'

    self.stats = {}

    self.require_cpustates = false

end

--- Initializes the necessary chisel fields.
-- @param chisel_field_names chisel field names used by LXC stats
-- @param value_field the name of the value field
-- @param index_field the name of the field used for indexing the stats table
-- @param cpus the number of cores detected on the machine
function LxcStats:init_stat_fields(chisel_field_names,
                                    value_field,
                                    index_field,
                                    cpus )

    self.chisel_field_names = chisel_field_names
    for i, f in ipairs( chisel_field_names ) do
        self.chisel_fields[i] = self.chisel.request_field(f)
    end

    self.value_field = chisel.request_field(value_field)
    self.index_field = ( index_field ~= nil and chisel.request_field(index_field) or nil )
    self.ts_field = chisel.request_field('evt.datetime')

    if self.require_cpustates == true and cpus ~= nil then
        self.cpustates = {}
        self.next_arg = self.chisel.request_field("evt.arg.next")
        self.next_rawarg = self.chisel.request_field("evt.rawarg.next")

        self.ncpus = cpus
        for j = 1, cpus do
            self.cpustates[j] = { 0, 0, 0, "" }
        end
    end

end

--- Builds a table which contains the stats values and data.
-- @param evt the current capturing event
function LxcStats:build_stats(evt)
    local statt = {}
    local cindex = nil

    for i, f in ipairs(self.chisel_fields) do
        v = evt.field( f )
        if v == nil then
            return
        end
        if self.chisel_field_names[i] ~= nil then
            statt[self.chisel_field_names[i]] = v
        end
        cindex = cindex ~= nil and cindex .. v or v
    end

    local index = (self.index_field ~= nil and evt.field(self.index_field) or cindex)

    value = evt.field(self.value_field)
    cpuid = evt.get_cpuid() + 1

    if value ~= nil and index ~= nil and value > 0 then
        self.stats[index] = { value = value,
                              stats = statt
                            }
        if self.require_cpustates == true then
            thissec = value - self.cpustates[cpuid][3]
            if thissec < 0 then
                thissec = 0
            end

            if self.stats[index] ~= nil then
                self.stats[index].value = self.stats[index].value + thissec
            end

            self.cpustates[cpuid][1], self.cpustates[cpuid][2] = evt.get_ts()
        end
    end

    if self.require_cpustates == true then
        if evt.field(self.next_arg) ~= "" .. evt.field(self.next_rawarg) then
            self.cpustates[cpuid][4] = evt.field(self.next_arg)
        else
            self.cpustates[cpuid][4] = nil
        end

        self.cpustates[cpuid][3] = 0
    end

end

--- This method is called for every event captured by sysdig.
-- @param evt the current capture event
function LxcStats:collect(evt)

end

--- Aggregates the top stats and formats the output value.
--- Finally, the stat table is enriched with some extra data
--- and then sent over zeromq socket as JSON payload.
-- @param evt the current capturing event
-- @param delta the delta time between the call and the previous call to on_interval()
-- @param node the host name
function LxcStats:emit(evt, delta, node)

    if self.require_cpustates == true then
        for cpuid = 1, self.ncpus do
            if self.cpustates[cpuid][1] ~= 0 then
                self.cpustates[cpuid][3] = 1000000000 - self.cpustates[cpuid][2]

                index = self.cpustates[cpuid][4]

                if index ~= nil and value ~= nil and value > 0 then
                    if self.stats[index] == nil then
                        self.stats[index] = { value = self.cpustates[cpuid][3] }
                    else
                        self.stats[index].value = self.stats[index].value +
                                            self.cpustates[cpuid][3]
                    end
                end
            end
        end
    end

    local topn_stats = top_n(self.stats,
                self.top,
                function(t, a, b)
                    return t[b].value < t[a].value
                end)
    local stats = {}


    for _, v in topn_stats do
        if v.stats ~= nil then
            if self.units == 'timepct' then
                if delta ~= 0 then
                    v.stats[self.value_field_name] = string.format("%.2f%%", v.value / delta * 100)
                else
                    v.stats[self.value_field_name] = "0.00%"
                end
            elseif self.units == 'time' then
                v.stats[self.value_field_name] = format_time_interval( v.value )
            elseif self.units == 'bytes' then
                v.stats[self.value_field_name] = format_bytes( v.value )
            elseif self.units == 'none' then
                v.stats[self.value_field_name] = tostring( v.value )
            end
            table.insert(stats, v.stats)
        end
    end

    local output = {
        typology = self.typology,
        node = node,
        time = evt.field(self.ts_field),
        stats = stats
    }
    if ( #output.stats > 0 ) then
        local stats_to_json = json.encode(output)
        self.zmqsock:send( stats_to_json )
    end

    self.stats = {}
end
```

Hope that will be helpful.

Cheers
Nedim

**Comment by bhnedo** [comment]
P.S. there are a few more chisels having the same issue as above.

**Comment by ldegio** [comment]
fixed with this commit https://github.com/draios/sysdig/commit/b4eca991cafa395ace013a1b3a81ea55a5641560, which leverages the better CPU measurement infrastructure added with csysdig.

**Comment by kosnet2** [comment]
Hello, 

I am trying to use this chisel to monitor a specific process (i.e. firefox) on a _Ubuntu 18.04 LTS Linux Virtual Machine_. The command I use for this task is `sudo sysdig -c topprocs_cpu proc.name=firefox`.

For some reason I get CPU usage percentage values greater than 100 (i.e. 150, 435234, etc..) which does not really make sense (at least to me). 
![image](https://user-images.githubusercontent.com/20568574/74203335-ec72ff00-4c77-11ea-90dc-2f178108a201.png)

CPU
![image](https://user-images.githubusercontent.com/20568574/74203515-9783b880-4c78-11ea-86b9-a2226b7eba87.png)

Linux/kernel
![image](https://user-images.githubusercontent.com/20568574/74203638-f9442280-4c78-11ea-9b70-0ce5799a9cbb.png)

How could I solve this issue (in case I am doing something wrong)? Any suggestion would be really helpful. :)
