### ISSUE TITLE
Install script should put all code inside functions

### ISSUE THREAD

**Issue by ThomasHabets** [draios/sysdig#348]
If the download is aborted by a network glitch or anything else, bash will execute the partial line that's at the end of the script. If the line is "rm -fr /tmp/blaha.${TMPDIR}" and the download is interrupted at "rm -fr /", you're gonna have a bad time.

Much better:

```
#!/bin/sh
function do_install() {
  do_stuff
  rm -fr /tmp/blaha.${TMPDIR}
}
do_install()
```

That way it's always safe. A minimal change that doesn't hurt, and only helps.

**Comment by therealbobo** [comment]
Hi @ThomasHabets! Thank you for this issue! I just checked and it looks like this has been already fixed! 😄
