### ISSUE TITLE
armv7l support scaleway.com

### ISSUE THREAD

**Issue by PierreKircher** [draios/sysdig#351]
scaleway.com is the new baremetal cloud offering from Online Labs

im not in any way involved with them but the are working on coreos support 
so it might be worth to investigate that build target.

id be super interrested !

uname -a
Linux scw-3abf9f 3.2.34-29 #16 SMP Thu Mar 12 09:45:43 UTC 2015 armv7l armv7l armv7l GNU/Linux

uname -m
armv7l

root@scw-3abf9f:~/sysdig-continuous# cat /proc/cpuinfo 
Processor   : Marvell PJ4Bv7 Processor rev 2 (v7l)
processor   : 0
BogoMIPS    : 1332.01

processor   : 1
BogoMIPS    : 1332.01

processor   : 2
BogoMIPS    : 1332.01

processor   : 3
BogoMIPS    : 1332.01

Features    : swp half thumb fastmult vfp edsp vfpv3 tls 
CPU implementer : 0x56
CPU architecture: 7
CPU variant : 0x2
CPU part    : 0x584
CPU revision    : 2

Hardware    : Online Labs C1
Revision    : 0000
Serial       : 0000000000000000

**Comment by moul** [comment]
Subscribing to issue.
I'm from the Scaleway team and can help
