### ISSUE TITLE
Last few bytes of string arguments are masked

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#352]
Hi. I'm fixing a different bug right now, and have run into this new one. I'm building the dev branch at d562104. I run

    sysdig evt.type = execve and proc.exe contains true

And at the same time issue

    /bin/true 1234
    /bin/true 12345
    /bin/true 123456

Sysdig says
> 5007117 23:48:44.875872555 0 true (31640) < execve res=0 exe=/bin/true args=12... tid=31640(true) pid=31640(true) ptid=9534(zsh) cwd=/home/dima fdlimit=65536 pgft_maj=0 pgft_min=54 vm_size=324 vm_rss=4 vm_swap=0 comm=true cgroups=cpuset=/.cpu=/.cpuacct=/.memory=/.devices=/.freezer=/.net_cls=/.blkio=/.perf_... env=ALTERNATE_EDITOR=.MAIL=/var/mail/dima.USER=dima.XDG_SEAT=seat0.SSH_AGENT_PID=... 
> 5021862 23:48:49.367662886 1 true (31642) < execve res=0 exe=/bin/true args=123... tid=31642(true) pid=31642(true) ptid=9534(zsh) cwd=/home/dima fdlimit=65536 pgft_maj=0 pgft_min=54 vm_size=324 vm_rss=4 vm_swap=0 comm=true cgroups=cpuset=/.cpu=/.cpuacct=/.memory=/.devices=/.freezer=/.net_cls=/.blkio=/.perf_... env=ALTERNATE_EDITOR=.MAIL=/var/mail/dima.USER=dima.XDG_SEAT=seat0.SSH_AGENT_PID=... 
> 5030714 23:48:52.179159586 1 true (31644) < execve res=0 exe=/bin/true args=1234... tid=31644(true) pid=31644(true) ptid=9534(zsh) cwd=/home/dima fdlimit=65536 pgft_maj=0 pgft_min=51 vm_size=324 vm_rss=4 vm_swap=0 comm=true cgroups=cpuset=/.cpu=/.cpuacct=/.memory=/.devices=/.freezer=/.net_cls=/.blkio=/.perf_... env=ALTERNATE_EDITOR=.MAIL=/var/mail/dima.USER=dima.XDG_SEAT=seat0.SSH_AGENT_PID=... 

Look at the args report in each line: the last two bytes are masked with .

**Comment by ldegio** [comment]
hmm. Are you by any chance using an older version of sysdig?

I see proper behavior with both the latest release of sysdig and a binary built from the dev branch. And I remember fixing a bug that was causing a behavior like the one you describe a month or two ago.

**Comment by dkogan** [comment]
I thought I just pulled the latest code, but I guess I didn't. I just tested it again (using confirmed latest code this time), and as you say the issue is gone. Sorry for the noise.
