### ISSUE TITLE
csysdig filter issue

### ISSUE THREAD

**Issue by ljagiello** [draios/sysdig#364]
```
:~# csysdig -r dump.scap
unexpected '(' after (((evt.type!=switch) and proc.pid=13521) and ((evt.type!=switch) and thread.tid=13521) and ((fd.type=file or fd.type=directory and fd.name!='') and fd.name=/tmp/.xcache.0.13449.14.mutex
```
I was browsing earlier created dump and csysdig crashed with this problem.

```
:~# csysdig --version
sysdig version 0.1.101
```

**Comment by ljagiello** [comment]
![screenshot 2015-06-04 00 28 04](https://cloud.githubusercontent.com/assets/380707/7979035/a25171cc-0a50-11e5-831c-69b95fe0ecce.png)

**Comment by ldegio** [comment]
@ljagiello, could you share the trace file and the steps to make sysdig crash?

**Comment by ljagiello** [comment]
@ldegio trace file - https://www.dropbox.com/s/9bifyiqrtxjj14f/dump_crash1.scap.gz?dl=0

Steps:
* switch view to files,
* try to enter any /tmp/.xcache…

**Comment by SamuelePilleri** [comment]
The problem is escaping value of filters which value type is string (PT_CHARBUF). Tested on gdb and works. Mods to be done in sinsp_cursesui::do_drilldown. Workining on it.
