### ISSUE TITLE
csysdig crashes after a few seconds

### ISSUE THREAD

**Issue by faxm0dem** [draios/sysdig#365]
Happens on 0.1.101 and f64f0a7
This is the only error message:

```
scap error: Error calling PPM_IOCTL_GET_PROCLISTCTRL
```

OS is debian 8 on a x64

**Comment by luca3m** [comment]
Hi,

After installing, have you reloaded the sysdig_probe kernel module? Can you look if there is something meaninful syslogs?

**Comment by faxm0dem** [comment]
Yes I did a reload. Checking logs now will update comment

**Comment by faxm0dem** [comment]
I'm sorry, I just did a reload and now everything works fine.
Consider this a PBCAK. Thanks for quick answer

**Comment by luca3m** [comment]
No problem!

**Comment by faxm0dem** [comment]
quick question: are you guys on IRC #sysdig?
