### ISSUE TITLE
ncurses issue on sysdig build on Fedora 22

### ISSUE THREAD

**Issue by Hefeweizen** [draios/sysdig#368]
I get a complaint about mismatched parenthesis.  Logging issue now, will investigate as I can.  Error included below.

Should you try and recreate, this was inside the Fedora provided F22 image.
--=--
[vagrant@localhost build]$ cmake .. && make && sudo make install
...
==== Successfully built LuaJIT 2.0.3 ====
[ 10%] No install step for 'luajit'
[ 11%] Completed 'luajit'
[ 11%] Built target luajit
Scanning dependencies of target ncurses
[ 13%] Creating directories for 'ncurses'
[ 14%] Performing download step (download, verify and extract) for 'ncurses'
-- downloading...
     src='http://download.draios.com/dependencies/ncurses-5.9.tar.gz'
     dst='/home/vagrant/sysdig/build/ncurses-prefix/src/ncurses-5.9.tar.gz'
     timeout='none'
-- [download 100% complete]
-- downloading... done
-- verifying file...
     file='/home/vagrant/sysdig/build/ncurses-prefix/src/ncurses-5.9.tar.gz'
-- verifying file... done
-- extracting...
     src='/home/vagrant/sysdig/build/ncurses-prefix/src/ncurses-5.9.tar.gz'
     dst='/home/vagrant/sysdig/build/ncurses-prefix/src/ncurses'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 16%] No patch step for 'ncurses'
[ 17%] No update step for 'ncurses'
[ 19%] Performing configure step for 'ncurses'
checking for egrep... grep -E
...
Appending rules for normal model (ncurses: termlib+ext_tinfo+base+ext_funcs)
Appending rules for debug model (ncurses: termlib+ext_tinfo+base+ext_funcs)
Appending rules for normal model (panel: termlib+ext_tinfo+base+ext_funcs)
Appending rules for debug model (panel: termlib+ext_tinfo+base+ext_funcs)
Appending rules for normal model (menu: termlib+ext_tinfo+base+ext_funcs)
Appending rules for debug model (menu: termlib+ext_tinfo+base+ext_funcs)
Appending rules for normal model (form: termlib+ext_tinfo+base+ext_funcs)
Appending rules for debug model (form: termlib+ext_tinfo+base+ext_funcs)
creating headers.sh
make[3]: Entering directory '/home/vagrant/sysdig/build/ncurses-prefix/src/ncurses'

** Configuration summary for NCURSES 5.9 20110404:

     extended funcs: yes
     xterm terminfo: xterm-new

      bin directory: /usr/bin
      lib directory: /usr/lib
  include directory: /usr/include
      man directory: /usr/man
 terminfo directory: /usr/share/terminfo

make[3]: Leaving directory '/home/vagrant/sysdig/build/ncurses-prefix/src/ncurses'
[ 20%] Performing build step for 'ncurses'
** edit: HAVE_TCGETATTR 1
** edit: HAVE_TERMIOS_H 1
** edit: HAVE_TERMIO_H 1
** edit: BROKEN_LINKER 0
In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_23722.c:835:15: error: expected ')' before 'int'
../include/curses.h:1594:56: note: in definition of macro 'mouse_trafo'
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:783: recipe for target '../objects/lib_gen.o' failed
make[4]: *** [../objects/lib_gen.o] Error 1
Makefile:109: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ncurses.dir/build.make:111: recipe for target 'ncurses-prefix/src/ncurses-stamp/ncurses-build' failed
make[2]: *** [ncurses-prefix/src/ncurses-stamp/ncurses-build] Error 2
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/ncurses.dir/all' failed
make[1]: *** [CMakeFiles/ncurses.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
[vagrant@localhost build]$ cat /etc/redhat-release 
Fedora release 22 (Twenty Two)

**Comment by gianlucaborello** [comment]
It's probably because Fedora is using ncurses 5.9 from snapshots (ftp://invisible-island.net/ncurses/current/), whereas I'm embedding the current stable one (ftp://invisible-island.net/ncurses/ncurses-5.9.tar.gz), which is quite old and doesn't compile with GCC 5.x.

If you want to propose one that works well for your platform, feel free. I am not sure how to interpret all those "current" releases since there seems to be one every week and I don't know how stable they are, so I felt dizzy and played it very safe for the embedded version.

Of course, you could always install ncurses-devel and build with USE_BUNDLED_NCURSES=OFF and that should work.

**Comment by Hefeweizen** [comment]
I'll experiment with that last option.

**Comment by ckolos** [comment]
According to [this](https://lists.gnu.org/archive/html/bug-ncurses/2014-07/msg00020.html) , this has been a issue for some time in the 5.9 line. On my Arch Linux system, setting USE_BUNDLED_NCURSES to OFF worked, using the installed ncurses 5.9-7 (built on 2014-12-06)

**Comment by spkane** [comment]
To be clear for Fedora 22:

sudo dnf -y install ncurses-devel
mkdir build
cd build
cmake ..
vi CMakeCache.txt
  Change the line: USE_BUNDLED_NCURSES:BOOL=ON
  To read USE_BUNDLED_NCURSES:BOOL=OFF
make
sudo make install

**Comment by gianlucaborello** [comment]
That's definitely an option, but don't forget that you can cleany pass it a cmake-time:

```
cmake -DUSE_BUNDLED_NCURSES=OFF ..
```

We have a couple examples here: https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code

**Comment by spkane** [comment]
I actually found those and edited the response before your reply, but thank you for the pointer. That is definitely much cleaner.

**Comment by gianlucaborello** [comment]
This should be fixed with 0.1.103
