### ISSUE TITLE
Csysdig exits if you attempt to interactively filter by filenames that contain the sequence "\u"

### ISSUE THREAD

**Issue by Pw7LK4HK4AfqN1RgiOaTdwxmNbOuGrpV** [draios/sysdig#370]
I have a file named "/var/lib/ceph/osd/ceph-0/current/0.14_head/DIR_4/DIR_D/DIR_C/rbd\udata.101f6b8b4567.0000000000000144__head_A54CDCD4__0"

If I use csysdig and attempt to inspect calls related to this filename csysdig exits with the following error:

    filter error: unrecognized escape sequence at /var/lib/ceph/osd/ceph-0/current/0.14_head/DIR_4/DIR_D/DIR_C/rbd\udata.101f6b8b4567.0000000000000144__head_A54CDCD4__0)) and (evt.type!=switch)

Csysdig probably needs to rewrite filenames before searching for them to escape the escape character and other special characters.

**Comment by ldegio** [comment]
this should be fixed by 103415316b0b40d7ea9ef1372e9b1bc95ad02814.
