### ISSUE TITLE
expand fdlist in polls and select

### ISSUE THREAD

**Issue by awreece** [draios/sysdig#371]
From the mailing list:

I'm trying to do a sysdig query: "print the ip addresses for all fds in the array when a poll times out"

I'm starting with

    sudo sysdig -p '%fds.cip' evt.type=poll and evt.rawarg.res=0

But `%fds.cip` doesn't work (`'%fds` doesn't work either).

This is because the list of FDs coming from a poll or a select is currently not expanded into resolved FDs.

**Comment by ldegio** [comment]
commit 5ccbb2e5f0ba5621566ca2c15f4b863702e6c387 adds the fdlist filter class, which allows you to do stuff like:
sysdig -p '%fdlist.cips' evt.type=poll and evt.rawarg.res=0
or
sysdig fdlist.sports contains 8080
