### ISSUE TITLE
file descriptor filename lost on container name filtering

### ISSUE THREAD

**Issue by rrva** [draios/sysdig#379]
When capturing the file usage of docker containers, using a filter like container.name=foo gives different values for fd.filename in captured events than without the filter.

**Comment by luca3m** [comment]
Can you explain better how to reproduce it?

**Comment by rrva** [comment]
Sorry, that was a bad bug report and turns out that it was not that simple either.

To fully reproduce, I put up a small repo at https://github.com/rrva/repro-galera-mysqld-bin-index. I could not isolate it further but it is reasonably small and does not take long time to run or setup. Requires docker, that is all.

1. Build some containers which we will capture events from:

        git clone git@github.com:rrva/repro-galera-mysqld-bin-index.git
        cd repro-galera-mysqld-bin-index
        ./setup_env.sh

2. On the docker host, start a sysdig capture

        sysdig -w all.scap

3. Then start the activity we want to capture

        cd repro-galera-mysqld-bin-index
        ./start_containers.sh

4. Stop the capture

5. Check for presence on some events regarding fd.filename=mysqld-bin.index

        sysdig -r all.scap container.name=xdb1 and evt.type=write \
        and proc.name=wsrep_sst_rsync and fd.filename=mysqld-bin.index

    I got these four events:

        1782320 20:09:41.835235233 2 wsrep_sst_rsync (7787) > write fd=1(<f>/var/lib/mysql/mysqld-bin.index) size=79
        1782321 20:09:41.835243920 2 wsrep_sst_rsync (7787) < write res=79 data=WSREP_SST: [INFO] Preparing binlog files for transfer: (20150620 18:09:41.834).
        3768322 20:09:57.500441613 0 wsrep_sst_rsync (8484) > write fd=1(<f>/var/lib/mysql/mysqld-bin.index) size=79
        3768323 20:09:57.500450561 0 wsrep_sst_rsync (8484) < write res=79 data=WSREP_SST: [INFO] Preparing binlog files for transfer: (20150620 18:09:57.500).

6. Filter on container name to new file

        sysdig -r all.scap -pc container.name=xdb1 -w xdb1.scap

7.  Read from filtered file, searching for fd.filename=mysqld-bin.index

        sysdig -r xdb1.scap evt.type=write and proc.name=wsrep_sst_rsync \
        and fd.filename=mysqld-bin.index

    No events found.

8. Read from filtered file, without filename filter:

        sysdig -r xdb1.scap evt.type=write and proc.name=wsrep_sst_rsync | grep size=79

    fd.filename has changed to /dev/null in the filtered file:

        151034 20:09:41.835235233 2 wsrep_sst_rsync (7787) > write fd=1(<f>/dev/null) size=79

Expected behavior is that even when I filter on container.name, fd.filename is intact.

**Comment by SamuelePilleri** [comment]
@rrva I'm trying to replicate the error but I'm new to CoreOS and, when executing setup_env.sh, it gives me this error.

```bash
[root@localhost repro-galera-mysqld-bin-index]# ./setup_env.sh 
Sending build context to Docker daemon 
FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cgroupparent=&cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=galera-repro: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
Sending build context to Docker daemon 
FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cgroupparent=&cpusetcpus=&cpushares=0&dockerfile=Dockerfile.fab&memory=0&memswap=0&rm=1&t=galera-repro-fab: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by SamuelePilleri** [comment]
My bad, docker deamon was not running.

**Comment by SamuelePilleri** [comment]
Unfortunately, we cannot replicate the problem. Can you send us the original `all.scap` file, please? Thank you.
