### ISSUE TITLE
unable to download precompiled sysdig-probe

### ISSUE THREAD

**Issue by glerchundi** [draios/sysdig#381]
Hi @gianlucaborello,

I'm unable to make sysdig work because it tries to download precompiled sysdig-probe module. Any ideas why is this happening?

When I run this command (i'm using CoreOS) it fails loading sysdig-probe and the fails downloading it:
```
$ docker run -i -t --rm --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro sysdig/sysdig
* Setting up /usr/src links from host
ls: cannot access /host/usr/src: No such file or directory
* Unloading sysdig-probe, if present
rmmod: ERROR: ../libkmod/libkmod.c:506 lookup_builtin_file() could not open builtin file '/lib/modules/3.17.8+/modules.builtin.bin'
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms autoinstall
Error! echo
Your kernel headers for kernel 3.17.8+ cannot be found at
/lib/modules/3.17.8+/build or /lib/modules/3.17.8+/source.
* Trying to load a system sysdig-probe, if present
* Trying to load a dkms sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 3.17.8+
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.1.101-x86_64-3.17.8+-1b215c695614961288b3f986e3070750.ko
Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community
```

```
root@c105169d7cd5:/# curl -L https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.1.101-x86_64-3.17.8+-1b215c695614961288b3f986e3070750.ko
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C404BFC42C78F29D</RequestId><HostId>TP5fhbv0xG93ZRWKKkmOLQQuhdRtBJ2uZoZr98/+TY/O2dMyWlVjozSO/tXr4X6Vf4iBPUU5fqM=</HostId></Error>
```

I thought it could be an issue related to AWS (where it's actually running) but it's not because it also failed on my machine.

**Comment by gianlucaborello** [comment]
Hi,

Judging from your kernel, you're running a very old version of CoreOS, we support all CoreOS releases that came after we released sysdig support for containers, so the minimum one is 591.0.0.

You might want to update it to the latest version, and if it's not possible, please describe your use case and we'll see what can be done to support even older distributions.

**Comment by glerchundi** [comment]
oh, we cannot upgrade our unique production machine...it will cause downtime, we're working on a cluster to chaos monkey everything but right now it's impossible for us.

Don't worry and thanks anyway, although I would like to use it, I can live without it until we upgrade everything.
