### ISSUE TITLE
By default the event filename is printed ONLY in the entry direction

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#382]
Hi. This isn't a bug per se, but a feature request. Currently basic i/o events like write() only print out the descriptor filename on the entry direction. This makes filtered output less useful than it could be with specific filters.

Suppose I'm using sysdig to answer the question: "where is all this specific data being written to?" As a toy example I trace an sh process that does

    echo 1234 > /dev/null

Then I run sysdig to answer that question. The output looks like this:

    $ sudo sysdig evt.buffer contains 1234 and evt.type=write

    15 14:17:42.893564830 0 dash (26810) < write res=5 data=1234. 

So sysdig saw the event, but it didn't answer the question: I still don't know where the data was written to. I know that it was written SOMEWHERE, but not more specifically. This currently is printed in the entry direction, but the entry doesn't have evt.buffer and can't be filtered on it. I'm proposing that the fd information be added to the default --print set for both directions. Thanks for a very useful tool!

**Comment by ldegio** [comment]
Hey Dima,
you are right, the event by itself doesn't give you the file name information, but you can easily leverage the state engine using the -p flag. For example:

sysdig -p"%fd.name" proc.name=echo and evt.buffer contains 1234
