### ISSUE TITLE
Feature Request: drill down to event in csysdig

### ISSUE THREAD

**Issue by frioux** [draios/sysdig#384]
I am having trouble with a filter in sysdig and I thought that csysdig would be able to help me.  The issue I'm running into is that when I use proc.aname it's not finding the expected child processes.  My guess is that proc.name is something other than what I expect.

What I'd like to do is use csysdig to find an event underneath the parent process that I am interested in and then expand *that*.  Currently once you drill down to the event view you can't go any deeper.  What I'd like to see would be a window of key=value pairs within the event, so that I can figure out how to filter against it.

So for example, I have an even that looks something like this:

```
1918673 13:04:31.638948034 3 sync-perl-versi (123233) > open
```

I'd like to be able to double-click (or F6 or something) the event and then see something like:
```
container.id=deadbeef
contaner.image=cafebabe
container.name=tmp
evt.abspath=...
...
```

**Comment by ldegio** [comment]
Would creating a view that contains the fields you want to see solve your problem? This page explains how to create views https://github.com/draios/sysdig/wiki/Csysdig%20View%20Format%20Reference.

**Comment by frioux** [comment]
Yes!  Thanks for the tip, I'll make a view and probably contribute it back when I am done with it.  Thanks for the great tool!
