### ISSUE TITLE
Sysdig fails to build from source on ARM architectures

### ISSUE THREAD

**Issue by hlieberman** [draios/sysdig#386]
Since 0.1.101, sysdig no longer builds from source on ARM architectures.  (armel, armhf, and arm64 tested).

The error is 
``` 
cd /«PKGBUILDDIR»/obj-arm-linux-gnueabi/userspace/libsinsp && /usr/bin/c++   -DHAS_CAPTURE -DPLATFORM_NAME=\"Linux\" -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -D_FORTIFY_SOURCE=2  -Wall -ggdb --std=c++0x -I/«PKGBUILDDIR»/userspace/libsinsp/. -I/«PKGBUILDDIR»/userspace/libsinsp/../../common -I/«PKGBUILDDIR»/userspace/libsinsp/../libscap -I/usr/include/jsoncpp -I/usr/include/luajit-2.0    -o CMakeFiles/sinsp.dir/ctext.cpp.o -c /«PKGBUILDDIR»/userspace/libsinsp/ctext.cpp
In file included from /«PKGBUILDDIR»/userspace/libsinsp/ctext.cpp:21:0:
/«PKGBUILDDIR»/userspace/libsinsp/ctext.h:376:50: error: could not convert '0' from 'int' to 'va_list {aka __va_list}'
   int8_t vprintf(const char*format, va_list ap = 0);
```

This bug is tracked as Debian bug [#790828](https://bugs.debian.org/790828).

Build logs are located at:
armel: https://buildd.debian.org/status/fetch.php?pkg=sysdig&arch=armel&ver=0.1.101-1&stamp=1434557750
armhf: https://buildd.debian.org/status/fetch.php?pkg=sysdig&arch=armhf&ver=0.1.101-1&stamp=1434557499
arm64: https://buildd.debian.org/status/fetch.php?pkg=sysdig&arch=arm64&ver=0.1.101-1&stamp=1434556708

**Comment by hlieberman** [comment]
This is related to, but does not replace, #377.

**Comment by gianlucaborello** [comment]
Is this the same one of https://github.com/draios/sysdig/pull/373 ?

**Comment by hlieberman** [comment]
Yes, it does seem to be.  Let me test that patch.

**Comment by evgeni** [comment]
@hlieberman I already tested all patches, and am about to upload a patched version to debian ;)

**Comment by evgeni** [comment]
It built fine on all arches with the two patches, please close :)

**Comment by hlieberman** [comment]
Thanks evgeni!
