### ISSUE TITLE
Hash mismatch build error

### ISSUE THREAD

**Issue by aleks-f** [draios/sysdig#392]
System:
```
$ uname -a
Linux box 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Build:
```
$ mkdir build
$ cd build
$ cmake ..
-- Using bundled LuaJIT in '/home/alex/sysdig/build/luajit-prefix/src/luajit/src'
-- Using bundled jsoncpp in '/home/alex/sysdig/userspace/libsinsp/third-party/jsoncpp'
-- Using bundled zlib in '/home/alex/sysdig/build/zlib-prefix/src/zlib'
-- Using bundled ncurses in '/home/alex/sysdig/build/ncurses-prefix/src/ncurses'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alex/sysdig/build
$ make
[  1%] Performing download step (download, verify and extract) for 'luajit'
-- downloading...
     src='http://download.draios.com/dependencies/LuaJIT-2.0.3.tar.gz'
     dst='/home/alex/sysdig/build/luajit-prefix/src/LuaJIT-2.0.3.tar.gz'
     timeout='none'
CMake Error at luajit-stamp/download-luajit.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/alex/sysdig/build/luajit-prefix/src/LuaJIT-2.0.3.tar.gz]
      expected hash: [f14e9104be513913810cd59c8c658dc0]
        actual hash: [c90bbc0010184e753aa09b84b952c2f4]



make[2]: *** [luajit-prefix/src/luajit-stamp/luajit-download] Error 1
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
```

Every time I run make, I get a different actual hash (which, of course, also differs from the [expected one](https://github.com/draios/sysdig/blob/dev/CMakeLists.txt#L127)). Am I doing something wrong?

**Comment by gianlucaborello** [comment]
What happens if you download the file manually (http://download.draios.com/dependencies/LuaJIT-2.0.3.tar.gz) with wget? Do you always get a consistent md5 with the expected one in the cmake file?

**Comment by aleks-f** [comment]
I tried to do that and had same problem - it looks like build script always downloads fresh file but I did not investigate deeper so I could be wrong; it is strange that calculated hash is always different, almost like something is tinkering with the file along the way.

**Comment by gianlucaborello** [comment]
Do you have any proxy or something that might be messing up with the file? We're heavily downloading the same tarball on our integration servers and it never fails.

**Comment by aleks-f** [comment]
That indeed seems to be the case. I tried through an open (no firewall) connection and it works! Thank you.
