### ISSUE TITLE
csysdig aborts w/ truncated input file

### ISSUE THREAD

**Issue by charles-dyfis-net** [draios/sysdig#394]
Whereas the CLI `sysdig` tool can usefully analyze traces which don't terminate gently, this is not true of `csysdig` (as of 0.1.101):

> expecting 48 bytes, read 12 at /builds/sysdig/src/sysdig-0.1.101/userspace/libscap/scap_savefile.c, line 2026. Is the file truncated?

**Comment by ldegio** [comment]
hey @charles-dyfis-net, could you share a small trace file that replicates the problem?

**Comment by charles-dyfis-net** [comment]
Artificially generating this problem is trivial -- truncate a valid file almost anywhere. Is a sample generated that way acceptable, or do you want an organic example? (I'm trying to figure out how and why my systemd-managed sysdig instances don't have the opportunity to shut down gracefully -- it's not supposed to send a SIGKILL until 1m30s after a SIGTERM, and no such timeout is taking place in practice -- but that's an ongoing investigation).

**Comment by charles-dyfis-net** [comment]
As requested, posted a truncated trace file in xz-compressed form to http://ix.io/jMk -- content should have md5sum 5ed7c321fce8cec44fbdd211f765f60e and sha1sum acaccd045141a82f112bdcdf88592b49a09fc18f.

**Comment by charles-dyfis-net** [comment]
@ldegio, ...would you be willing to make a pronouncement on how this should be fixed? Right now, the "fail on a short read" behavior is really quite explicit. If we want to change that, I'd argue that defining new/desired behavior (say, "succeed on a short read with a log message to stderr as long as at least one event has been successfully read") is the bigger part.

Which is to say -- I wouldn't mind taking a shot at this one myself, but only once there's agreement on what the new behavior would be.

**Comment by ldegio** [comment]
this commit should solve the issue https://github.com/draios/sysdig/commit/99a6384. csysdig now opens the file and reports that it's truncated. It was easy enough to solve that I just did it. :-)

Let me know if it works for you too.
