### ISSUE TITLE
Centos5 does NOT compile

### ISSUE THREAD

**Issue by thetwinpeaks** [draios/sysdig#400]
Hi,
I want to install sysdig edition for RHEL 5.10 which located by following link:
https://github.com/draios/sysdig/tree/centos5
I do: 
1) mkdir aaa
2) cd aaa
3) cmake ..
4) make  
BUT while running make command I get the following error:

[root@localhost aaa]# make
[ 10%] Built target luajit
[ 21%] Built target ncurses
[ 32%] Built target zlib
In file included from /home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c:22:
include/linux/cdev.h:24: warning: ‘struct inode’ declared inside parameter list
include/linux/cdev.h:24: warning: its scope is only this definition or declaration, which is probably not what you want
/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c: In function ‘open_flags_to_scap’:
/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c:482: error: ‘O_CLOEXEC’ undeclared (first use in this function)
/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c:482: error: (Each undeclared identifier is reported only once
/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c:482: error: for each function it appears in.)
/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c: At top level:
/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.c:3275: warning: ‘struct task_cputime’ declared inside parameter list
make[5]: *** [/home/user/Desktop/sysdig-centos5/driver/ppm_fillers.o] Error 1
make[4]: *** [_module_/home/user/Desktop/sysdig-centos5/driver] Error 2
make[3]: *** [all] Error 2
make[2]: *** [driver/CMakeFiles/driver] Error 2
make[1]: *** [driver/CMakeFiles/driver.dir/all] Error 2
make: *** [all] Error 2
[root@localhost aaa]#

**Comment by gianlucaborello** [comment]
Should be fixed via https://github.com/draios/sysdig/commit/4f36770ded6ebe29d608fa104caefedc509ce7b7
