### ISSUE TITLE
proc.exe sometimes returns the name of a process and not its full path

### ISSUE THREAD

**Issue by izianv** [draios/sysdig#403]
When printing proc.exe, sometimes the name of the process is returned and not it's full path, resulting in inconsistencies.

How to reproduce:
1. sysdig "proc.name=sshd and evt.type=close and fd.type=ipv4 and fd.l4proto=tcp" -p "%proc.exe"
2. In another terminal: ssh localhost

Results:
/usr/sbin/sshd
/usr/sbin/sshd
/usr/sbin/sshd
/usr/sbin/sshd
sshd: root@pts/5
sshd: root@pts/5

**Comment by ldegio** [comment]
I believe you're seeing different processes here. If I do:

sysdig "proc.name=sshd and evt.type=close and fd.type=ipv4 and fd.l4proto=tcp" -p "%proc.pid %proc.exe"

I get:

1159 /usr/sbin/sshd
1159 /usr/sbin/sshd
18381 /usr/sbin/sshd
18381 /usr/sbin/sshd
18420 sshd: root@pts/9
18420 sshd: root@pts/9

Which is 3 different processes.

Also, note that Linux makes it possible for a process to change its executable name at runtime. This will cause the name to change not only in sysdig, but also in other tools like ps and top. %proc.name should be less sensitive to that.
