### ISSUE TITLE
Backspace not supported in csysdig on tmux

### ISSUE THREAD

**Issue by charles-dyfis-net** [draios/sysdig#406]
Observed with `TERM=screen-256color`. `^H` does work.

Setting a breakpoint in `curses_table::handle_input` shows that when using the backspace key, `ch` has a value of 127; when using `^H`, it is 263.

**Comment by ldegio** [comment]
Even if I don't see the issue in tmux on my ubuntu 14, I tried to address the issue with this commit https://github.com/draios/sysdig/commit/cb9b66dd0754573fdfba38976ee2e5ceaa0da19a.

can you please try to build from the 'backspace' branch and tell me if it works?

**Comment by charles-dyfis-net** [comment]
The backspace branch resolves this issue.
