### ISSUE TITLE
evt.latency description doesn't state the units

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#407]
Hi. The 'sysdig -l' description of 'evt.latency' is 'delta between an exit event and the correspondent enter event.'. This doesn't specify the units of this delta. Running some experiments, I can see that it's nanoseconds, but the docs should say this explicitly.

**Comment by dkogan** [comment]
It looks like there are several events for which this applies. Another is 'deltatime'

**Comment by ldegio** [comment]
this commit should solve the issue https://github.com/draios/sysdig/commit/18ccbe035dd0bbdcc97a7ecd8d7d3dbb0480d00c. Feel free to reopen if I forgot some of them.
