### ISSUE TITLE
API

### ISSUE THREAD

**Issue by zrml** [draios/sysdig#409]
Hi team,

is there a programmatic API I can use vs calling the exe with params?
thank you

**Comment by luca3m** [comment]
Yes, you have two options: create a [chisel](https://github.com/draios/sysdig/wiki/Chisels-User-Guide) or use [libsinsp](https://github.com/draios/sysdig/tree/dev/userspace/libsinsp).

**Comment by zrml** [comment]
grazie Luca. I'll investigate those.

**Comment by zrml** [comment]
had a quick look at both. Perfect! :-) thank you guys. Also I had a nice chat with with Michael F. today. Looking promising :-)
ciao
