### ISSUE TITLE
sysdig 0.1.101 freeze with 3.14.49-grsec

### ISSUE THREAD

**Issue by lazy404** [draios/sysdig#410]
Sysdig proces is frozen after issuing sysdig -c subsecoffset or others like -c bottlenecks etc. on a 3.14.1 with grsecuirity 3.1

dmesg:
sysdig_probe: driver loading
sysdig_probe: adding new consumer ffff8800c83b8590
sysdig_probe: initializing ring buffer for CPU 0
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: initializing ring buffer for CPU 1
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: initializing ring buffer for CPU 2
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: initializing ring buffer for CPU 3
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: starting capture
sysdig_probe: deallocating consumer ffff8800c83b8590
sysdig_probe: no more consumers, stopping capture
sysdig_probe: adding new consumer ffff880223327590
sysdig_probe: initializing ring buffer for CPU 0
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: initializing ring buffer for CPU 1
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: initializing ring buffer for CPU 2
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: initializing ring buffer for CPU 3
sysdig_probe: CPU buffer initialized, size=8388608
sysdig_probe: starting capture

PAX: please report this to pageexec@freemail.hu
BUG: unable to handle kernel paging request at 0000000000ec2578
IP: [<ffffffffa0789242>] ppm_ioctl+0x53a/0x880 [sysdig_probe]
PGD 223548000 
Oops: 0000 [#1] SMP 
Modules linked in: sysdig_probe(O) zfs(PO) zunicode(PO) zcommon(PO) znvpair(PO) spl(O) zavl(PO) zlib_deflate xt_limit ipt_REJECT xt_addrtype xt_owner xt_set xt_tcpudp ip_set_hash_ip ip_set nfnetlink iptable_filter ip_tables x_tables quota_v2 iscsi_tcp libiscsi_tcp quota_tree libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs lockd fscache sunrpc ipmi_devintf loop sr_mod evdev dcdbas usbhid ehci_pci usb_storage ipmi_si ipmi_msghandler button ext4 crc16 jbd2 dm_mod md_mod ide_cd_mod cdrom ata_piix libata ide_pci_generic sg sd_mod megaraid_sas uhci_hcd scsi_mod piix ide_core bnx2 ehci_hcd
CPU: 2 PID: 14413 Comm: sysdig Tainted: P           O 3.14.49-grsec #8
Hardware name: Dell Inc. PowerEdge 1950/0DT097, BIOS 1.2.0 10/18/2006
task: ffff880223327590 ti: ffff880223327ae0 task.ti: ffff880223327ae0
RIP: 0010:[<ffffffffa0789242>]  [<ffffffffa0789242>] ppm_ioctl+0x53a/0x880 [sysdig_probe]
RSP: 0018:ffff8800c83bfcd8  EFLAGS: 00010283
RAX: 0000000000ec2570 RBX: ffff8800cb4ac3c0 RCX: 0000000000000001
RDX: ffff8802250c94d8 RSI: 0000000000000008 RDI: ffff8800c83bfd00
RBP: ffff8800c83bfd78 R08: 0000000000ec2560 R09: 0000000055c8a5ad
R10: 13f91c92dbe46923 R11: 0000000000000246 R12: ffff8802250c9150
R13: ffff8802250c9150 R14: ffff8802250c9360 R15: ffff880223327ae0
FS:  00000354656b5740(0000) GS:ffff88022fc80000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000000000ec2578 CR3: 000000000133d000 CR4: 00000000000007b0
Stack:
 ffffc90000022000 ffff880223327590 0000000000000087 ffff880223327ae0
 0000000000000000 0000000000ec2570 ffffffffa07886aa ffff8802250c94d8
 ffffc90001acd40c 00000010007fff1d 0000000300000014 0000001e00000003
Call Trace:
 [<ffffffffa07886aa>] ? record_event_all_consumers+0x43/0x6e [sysdig_probe]
 [<ffffffff81104556>] do_vfs_ioctl+0x689/0x793
 [<ffffffffa07886aa>] ? record_event_all_consumers+0x43/0x6e [sysdig_probe]
 [<ffffffff81056ea5>] ? hrtimer_get_res+0x45/0x45
 [<ffffffff81104699>] SyS_ioctl+0x39/0x64
 [<ffffffff81331408>] tracesys+0xc8/0xcd
Code: 88 97 00 00 49 c7 c5 f0 08 4f 81 4c 89 bd 78 ff ff ff e9 4e 01 00 00 49 8b 86 c0 03 00 00 48 8b 40 10 e9 13 01 00 00 48 8b 45 88 <48> 8b 50 08 48 39 55 80 0f 83 f5 00 00 00 48 8d 55 98 4c 89 e7 
RIP  [<ffffffffa0789242>] ppm_ioctl+0x53a/0x880 [sysdig_probe]
 RSP <ffff8800c83bfcd8>
CR2: 0000000000ec2578
---[ end trace 0fb0cf40fa1450d9 ]---

sysctl w:
  task                        PC stack   pid father
sysdig          D 00000000ffffffff     0 14413   4560 0x10000002
 ffff8800c83bf7b8 0000000000000046 ffff880209eca590 ffff8800c83bf7e0
 ffff880223327ae0 ffff880223327590 000000000000dc40 000000000000dc40
 ffff880225305610 ffff880223327590 ffff88022352d780 0000000000043400
Call Trace:
 [<ffffffffa01f8bb3>] ? ext4_file_write+0x395/0x3ca [ext4]
 [<ffffffff811db9e5>] ? __list_del_entry+0xf/0x25
 [<ffffffff813309cb>] ? retint_restore_args+0x6/0x6
 [<ffffffff810c19a8>] ? free_pcppages_bulk+0x215/0x30c
 [<ffffffff8132e176>] schedule+0x6a/0x6c
 [<ffffffff8132e423>] schedule_preempt_disabled+0x9/0xb
 [<ffffffff8132f628>] __mutex_lock_slowpath+0x11e/0x16c
 [<ffffffff8132f692>] mutex_lock+0x1c/0x2d
 [<ffffffffa0788baa>] ppm_release+0x2e/0x18c [sysdig_probe]
 [<ffffffff810f578a>] __fput+0xe8/0x1d9
 [<ffffffff810f58a9>] ____fput+0x9/0xb
 [<ffffffff81051d8c>] task_work_run+0x79/0x91
 [<ffffffff81037446>] do_exit+0x37b/0x891
 [<ffffffff8132a0d3>] ? printk+0x48/0x4a
 [<ffffffff810379f1>] do_group_exit+0x68/0x9b
 [<ffffffff81005a68>] oops_end+0x80/0x85
 [<ffffffff81329774>] no_context+0x286/0x2b2
 [<ffffffff8132995e>] __bad_area_nosemaphore+0x1be/0x1df
 [<ffffffff8132a0d3>] ? printk+0x48/0x4a
 [<ffffffff8132998d>] bad_area_nosemaphore+0xe/0x10
 [<ffffffff8102ae5e>] __do_page_fault+0x44d/0x4ea
 [<ffffffffa07886aa>] ? record_event_all_consumers+0x43/0x6e [sysdig_probe]
 [<ffffffff8102af26>] do_page_fault+0xc/0xe
 [<ffffffff81330bf2>] page_fault+0x22/0x30
 [<ffffffffa0789242>] ? ppm_ioctl+0x53a/0x880 [sysdig_probe]
 [<ffffffffa07894da>] ? ppm_ioctl+0x7d2/0x880 [sysdig_probe]
 [<ffffffffa07886aa>] ? record_event_all_consumers+0x43/0x6e [sysdig_probe]
 [<ffffffff81104556>] do_vfs_ioctl+0x689/0x793
 [<ffffffffa07886aa>] ? record_event_all_consumers+0x43/0x6e [sysdig_probe]
 [<ffffffff81056ea5>] ? hrtimer_get_res+0x45/0x45
 [<ffffffff81104699>] SyS_ioctl+0x39/0x64
 [<ffffffff81331408>] tracesys+0xc8/0xcd

**Comment by gianlucaborello** [comment]
Any chances you can try this on 0.1.102? There have been fixes in the kernel code that might be related to this panic.

**Comment by lazy404** [comment]
No problems on 0.1.102

I didn't notice the new release. Sorry for the noise.

Thank You for Your time.
