### ISSUE TITLE
Documentation is unclear about the default -p format, and how -t affects it

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#416]
Hi. This is two related documentation deficiencies:

1. The manpage says that the default format is

```
    <evt.num> <evt.time> <evt.cpu> <proc.name> <thread.tid> <evt.dir> <evt.type> <evt.args>
```
This isn't something you can pass to -p, since it takes %xxx instead of <xxx>. I think this should be changed to use %xxx. Also the above does not appear next to where -p is documented. Stating what the default for -p is directly where -p is described would be helpful.

2. Without -p (using the default) it is possible to change what kind of timestamps we get by using -t. It appears, however, that there's no %xxx print format that accepts this setting. I.e. %evt.time is not affected by -t. There are several ways to resolve this, but I think that explicitly asking for the default -p format should always produce the same output as omitting it.

**Comment by dkogan** [comment]
I just had a thought: in addition to the above it would be useful to add a new format (%default maybe) to expand to the full default string. This can then be used to easily add new fields if using something like awk to process the output.

**Comment by ldegio** [comment]
commit 97445161f931aeb1514630b64be7538093d6b0a9 better documents the format and also documents -pp.
