### ISSUE TITLE
Container names limited to 10 characters

### ISSUE THREAD

**Issue by discostur** [draios/sysdig#424]
Hi,

if i do some sysdig commands to my containers i only get the first 10 / 19 characters of my containernames shown, for example:

<pre>
sysdig -pc -c topfiles_bytes

Bytes           container.name  Filename        
--------------------------------------------------------------------------------
397.39KB        LXCAdbc18b      /tmp/#sql_122f_0.MYD
125.09KB        host            /etc/passwd
114.87KB        LXCAdbc18b      /etc/services
107.27KB        LXCAdbc18b      /usr/share/mysql/charsets/Index.xml
</pre>

or 

<pre>
sysdig -c lscontainers

container.type container.image container.name      container.id 
-------------- --------------- ------------------- ------------ 
libvirt_lxc                    LXCAdbc18b688a2856a LXCAdbc18b68 
libvirt_lxc                    LXCAc65395fb005fd1e LXCAc65395fb 
</pre>

Could you fix it that we can see the full containername?

Thanks
Greets
Kilian

**Comment by ldegio** [comment]
You can make the columns wider by changing the EXTEND_STRING_SIZE constant in the common.lua file, which is usually installed in /usr/share/sysdig/chisels/.

This is the line to change:
https://github.com/draios/sysdig/blob/dev/userspace/sysdig/chisels/common.lua#L185
