### ISSUE TITLE
Documentation is unclear about what "delta" time is

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#425]
Hi. The manpage and 'sysdig -l' say that 'deltatime' is 'delta between this event and the previous event'. It isn't obvious from reading that whether 'previous' is before or after filtering. It would be nice if this was explicitly stated.

**Comment by dkogan** [comment]
I just discovered a different, but related issue. 'sysdig -l' says that 'sysdig -t -r' reports 'relative time from capture start'. This is false. It's not from 'capture start', but from the first filtered event. In addition to clarifying the documentation, I think it'd be useful to have both relative timings available. For my uses I usually do want 'relative from capture start'.

**Comment by gianlucaborello** [comment]
@dkogan can you verify if this can be then closed after the recent fix? Thanks

**Comment by dkogan** [comment]
Hi. Sorry about this, but this report once again has two different issues in it. I promise to stop doing that. I checked, and the recent patches fix the second part of this bug report (Thanks!). The original issue is still open, however.

The original issue is the unclear documentation of what "deltatime" means. It refers to a "previous" event, but filtering can change what the previous event is, and it would be good for the documentation to state whether "previous" means before or after filtering.
