### ISSUE TITLE
Default format string is wrong if -t is used

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#426]
Hi. Thank you for resolving #416. I was sloppy in putting multiple issues into that same report, so this is a separate report for pieces of #416 that are still unresolved.

We want omitting -p and passing -p with the defaults to produce the same output. Normally this is the case:

```
$ ./sysdig -r /tmp/fg.scap evt.num=11 
11 23:37:03.733165187 1 feedgnuplot (25943) < open fd=3(<f>/etc/ld.so.cache) name=/etc/ld.so.cache flags=1(O_RDONLY) mode=0 

$ ./sysdig -p "`sysdig -pp`" -r /tmp/fg.scap evt.num=11 
11 23:37:03.733165187 1 feedgnuplot (25943) < open fd=3(<f>/etc/ld.so.cache) name=/etc/ld.so.cache flags=1(O_RDONLY) mode=0 
```

However, if we specify a -t option, then they are no longer the same:

```
$ ./sysdig -t r -r /tmp/fg.scap evt.num=11 
11 0.000000000 1 feedgnuplot (25943) < open fd=3(<f>/etc/ld.so.cache) name=/etc/ld.so.cache flags=1(O_RDONLY) mode=0 

$ ./sysdig -t r -p "`sysdig -pp`" -r /tmp/fg.scap evt.num=11
11 23:37:03.733165187 1 feedgnuplot (25943) < open fd=3(<f>/etc/ld.so.cache) name=/etc/ld.so.cache flags=1(O_RDONLY) mode=0 
```

This is because -t affects the timestamp being printed by default but does NOT affect %evt.time. So currently the "default" format really isn't a "default" format, which I think is confusing.

**Comment by SamuelePilleri** [comment]
I've just closed this by introducing a new field in the standard output format. Basically, now we use `%evt.outputtime` which is designed to fix this problem with all `-t` flags. It can be used only when printing and doesn't affect `%evt.time` behaviour which is still costant.

This merge also fixes a bug with the inspector that assumed as timestamp of the first event the timestamp of the first event approved by the filters and not the first event globally, behaviour that lead `-t r` to report `0` on every capture without regarding the presence of filters. In the example you reported, `$ ./sysdig -t r -r /tmp/fg.scap evt.num=11` shouldn't have returned `0.000000000` but the offset from the first event.

**Comment by dkogan** [comment]
Hi. Thanks for the fix. Is the second part of your comment related to #425?

**Comment by SamuelePilleri** [comment]
I've just seen the issue now. Yes, it is definitely related and partially fixes it.
