### ISSUE TITLE
system crash caused by sysdig_probe on RHEL6

### ISSUE THREAD

**Issue by elfchief** [draios/sysdig#427]
When running sysdig on a RHEL6 box with a relatively simple filter, the system crashed, with a stack trace pointing inside the sysdig module. Possibly relevant data:

$ sysdig --version
sysdig version 0.1.103
(we built the kernel module built locally)

$ uname -a
Linux <hostname removed> 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 22 13:46:17 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux
(this is a stock RHEL6 kernel)

The command that caused the crash (executed a few seconds before crash):
$ sysdig -w random.scap --fatfile fd.name=/dev/random or fd.name=/dev/urandom

The kernel crash itself:

<1>BUG: unable to handle kernel NULL pointer dereference at 0000000000000038
<1>IP: [<ffffffffa01ea054>] f_sys_accept_x+0xe4/0x180 [sysdig_probe]
<4>PGD 2391ca067 PUD 238744067 PMD 0
<4>Oops: 0000 [#1] SMP
<4>last sysfs file: /sys/devices/system/cpu/online
<4>CPU 1
<4>Modules linked in: sysdig_probe(U) vsock(U) vmci(U) ipv6 microcode ppdev vmware_balloon parport_pc parport vmxnet3 sg i2c_piix4 i2c_core shpchp ext4 jbd2 mbcache sd_mod crc_t10dif vmw_pvscsi pata_acpi ata_generic ata_piix dm_mirror dm_region_hash dm_log dm_mod [last unloaded: speedstep_lib]
<4>
<4>Pid: 14045, comm: java Not tainted 2.6.32-573.el6.x86_64 #1 VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform
<4>RIP: 0010:[<ffffffffa01ea054>]  [<ffffffffa01ea054>] f_sys_accept_x+0xe4/0x180 [sysdig_probe]
<4>RSP: 0018:ffff88023b2b3d60  EFLAGS: 00010246
<4>RAX: 0000000000000000 RBX: ffff88023b2b3df0 RCX: 0000000000000000
<4>RDX: 0000000000000001 RSI: 00000000000008af RDI: 0000000000000070
<4>RBP: ffff88023b2b3da0 R08: 0000000000000000 R09: 0000000000000005
<4>R10: ffffc9001454130f R11: ffffc900145412f9 R12: 0000000000000000
<4>R13: 0000000000000000 R14: ffff88023b2b3ea0 R15: ffffc9001179e000
<4>FS:  00007fa2e05c8700(0000) GS:ffff880028300000(0000) knlGS:0000000000000000
<4>CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
<4>CR2: 0000000000000038 CR3: 000000023a613000 CR4: 00000000000007e0
<4>DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
<4>DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
<4>Process java (pid: 14045, threadinfo ffff88023b2b0000, task ffff8802380ce040)
<4>Stack:
<4> ffff880200001000 ffff8801feab3840 000000000000003c fffffff73b2b3d98
<4><d> ffffffff811ab8af ffffe8ffffd00a90 00000000000000f7 ffffc90000c78000
<4><d> ffff88023b2b3e90 ffffffffa01e52e8 ffff8801feab3840 ffff88023b2b3dd8
<4>Call Trace:
<4> [<ffffffff811ab8af>] ? __d_free+0x3f/0x60
<4> [<ffffffffa01e52e8>] record_event_consumer+0x298/0x600 [sysdig_probe]
<4> [<ffffffff811b43d0>] ? mntput_no_expire+0x30/0x110
<4> [<ffffffff81014a19>] ? read_tsc+0x9/0x10
<4> [<ffffffffa01e58b4>] record_event_all_consumers+0x54/0x80 [sysdig_probe]
<4> [<ffffffffa01e5a5b>] syscall_exit_probe+0x7b/0x80 [sysdig_probe]
<4> [<ffffffff810199d0>] syscall_trace_leave+0xe0/0xf0
<4> [<ffffffff81019767>] ? syscall_trace_enter+0x177/0x1e0
<4> [<ffffffff8100b386>] int_check_syscall_exit_work+0x34/0x3d
<4>Code: 01 00 00 45 31 ed 66 85 c9 75 7c 49 8b 7c 24 30 e8 42 95 fa e0 45 31 c0 31 c9 31 d2 4c 89 ee 48 89 df e8 60 d8 ff ff 85 c0 75 51 <49> 8b 44 24 38 45 31 ed 48 89 df 0f b7 80 58 01 00 00 66 85 c0
<1>RIP  [<ffffffffa01ea054>] f_sys_accept_x+0xe4/0x180 [sysdig_probe]
<4> RSP <ffff88023b2b3d60>
<4>CR2: 0000000000000038

...I have a vmcore file and can provide any data from that needed, just let me know what.

**Comment by gianlucaborello** [comment]
Thanks for finding this, very unfortunate. https://github.com/draios/sysdig/commit/d9c467c6481b1cf1e31fd01729c74a2e2e1e95f7 should fix it, we're in the process of reviewing it internally and we'll ship a new release in the next few minutes.

**Comment by gianlucaborello** [comment]
0.1.104 has just been released and I'm very positive it should fix the issue you were facing. Could you try again please?

**Comment by elfchief** [comment]
Holy cow that was quick turnaround! I am duly impressed.

I probably won't be able to rebuild and retest until the morning, but will report back as soon as I have!

**Comment by elfchief** [comment]
I have verified that 0.1.104 does indeed fix this crash, and does not appear to have any new crashes in my (admittedly limited) testing. Thanks for the awesome-fast turnaround!
