### ISSUE TITLE
Ability to monitor all files in a specific folder/path

### ISSUE THREAD

**Issue by sh3llsh0ck** [draios/sysdig#433]
Is there an existing chisel which allows me to monitor a whole directory ? instead of spy_file which have the ability to limit with one file .

What if i want to limit by a specific path ? like `/etc/nginx/vhosts` so i can spy all files if changed or created or deleted.

Is there a something like this or should i write a custom chisel for this ?

**Comment by gianlucaborello** [comment]
I think this discussion is spot on: https://groups.google.com/forum/#!topic/sysdig/9PWXxSDW044

**Comment by ldegio** [comment]
Closing since this seems to be addresses by the linked discussion
