### ISSUE TITLE
Centeralized Server for sysdig

### ISSUE THREAD

**Issue by sh3llsh0ck** [draios/sysdig#434]
I have a problem and i am looking forward to help md solving it. Maybe here is not a suitabld place for asking but i couldn't find a help anywhere else. Currently i have sysdig installed on more than one server and i need to collect all the JSON data from thesd servers into one server as a storage place or something.

I will use just few chisels like `topprocess_cpu` and `tophttp` and so on. By using a command like this `sysdig -c topprocess_cpu -j`

- What are the possible scenarios in order to send the json output from alll these servers to ond server ? Can ZeroMQ do the job ? I tried but i cannog get it.

- I need to have the server name (hostnamd) included in sidd the jsob output so i can identify which server is sending these data ?

- Another problem with sysdig itself that i consuming alot of CPU is there any solution for that ?

Thanks in Adance

**Comment by ldegio** [comment]
All of the features that you mention require quite a bit of work and are not currently included in sysdig.

Sysdig Cloud (https://sysdig.com/) is designed to offer a solution to this exactly problem, including keeping the CPU usage under control. It's a commercial product, which might be an issue for certain uses, but it's worth taking a look at for a use case like yours.
