### ISSUE TITLE
freeze kernel panic

### ISSUE THREAD

**Issue by Abukamel** [draios/sysdig#436]
Happens quite few times with me especially on cloud instances on Digital ocean and amazon AWS
The following pic is from amazon AWS
![img](http://i.imgur.com/whOA3qf.jpg)
I couldn't capture console output but when this happend before on DO I saw kernel panic message at console but has not screen shot it.

**Comment by gianlucaborello** [comment]
Can you confirm what version are you using? 0.1.103 contained a possible kernel panic bug, which was fixed in 0.1.104.

**Comment by Abukamel** [comment]
0.1.104

**Comment by gianlucaborello** [comment]
Would you be able to provide further information of any kind? We have been heavily using 0.1.104 on AWS for a few weeks now and haven't noticed anything. Ideally, these would be of very big help:

- What distribution (even AMI id if possible) did the crash occur on?

- What activity were you doing? What processes? Is there a way to consistently replicate this, starting from a clean instance?

- After the crash occurs, and before manually restarting the instance, is there any information in the AWS console, if you right click on the instance and choose "Get System Logs"?

- After the crash occurs, and after having restarted the instance, is there anything strange towards the end of /var/log/{messages, syslog, dmesg} (depending on your distribution)?

Thanks, we take kernel bugs very seriously and I hope you'll be able to provide some more information

**Comment by Abukamel** [comment]
AMI ID: CentOS 7 x86_64 (2014_09_29) EBS
HVM-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d2a117ba.2 (ami-7cc4f661)
Activity: started csysdig
info: no info before restarting but after restarting machine stuck at this
log http://i.imgur.com/VLzurDS.jpg
after restart: machine don't want to respond at all and no ping, see
previous picture

**Comment by gianlucaborello** [comment]
I've just started the same AMI, same kernel, and used csysdig 0.1.104 for a few minutes while doing a bunch of stuff (I also installed and ran a mariadb test since I saw in your init log that you're starting it).

Any other peculiar things about this machine that could help us replicate this on our side? Do you have many CPUs? Are you using hotplug by any chance?

Otherwise, without a screenshot of the kernel panic I really have no clue on what might be going on.

**Comment by ketank-new** [comment]
@gianlucaborello : are you looking to build sysdig?

**Comment by gianlucaborello** [comment]
@ketank-new what do you mean? The guy reported a kernel panic so I was trying to obtain more information in order to troubleshoot the issue.

**Comment by ketank-new** [comment]
@gianlucaborello : I mean to ask you, whether you would be interested in getting a recipe which builds sysdig without any kernel panic
So i was just confirming whether you are facing a kernel-panic while building sysdig or while using sysdig binary
