### ISSUE TITLE
Incorrect fd filtering

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#443]
Hi. I'm observing that sometimes the fd.num filter doesn't work. Look:

    $ sudo sysdig -w /tmp/gdb.scap proc.name=gdb

In another window run gdb, and exit it. So it just prints the copyright message to stdout

    $ sysdig -r /tmp/gdb.scap fd.num=1          
    597 18:59:14.553142232 1 gdb (17553) < dup res=1(<p>) 
    602 18:59:14.553151032 1 gdb (17553) > dup fd=1(<p>) 

So it says that those are the only events on fd=1. This is false:

    $ sysdig -r /tmp/gdb.scap evt.type=write | tail -n 2

3051 18:59:15.070251815 1 gdb (17552) > write fd=1 size=5 
3052 18:59:15.070259987 1 gdb (17552) < write res=5 data=quit.

**Comment by ldegio** [comment]
@dkogan can you share the file?

**Comment by dkogan** [comment]
http://pub.secretsauce.net/gdb.scap

**Comment by ldegio** [comment]
this commit should solve the issue https://github.com/draios/sysdig/commit/c47b9b146e443411eda43006c9221fbc65891e3f

could you try and close if it works?
