### ISSUE TITLE
Feature request: commandline option to unbuffer the sysdig output

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#444]
Hi. Currently it's not possible (as far as I know) to make something like this useful:

     sudo sysdig [whatever; no -r] | grep --line-buffered whatever

The pipe causes sysdig to buffer its output, and the grep would see the sysdig output with a (potentially very long) delay. The ways to get around this are kinda ugly (run sysdig with unbuffer, tell | to pretend to be a tty, etc). I don't know of any nice ways. Proposal: add --unbuffered commandline option to sysdig to turn off the output buffering. This is a simple setvbuf(...) call. I can give yall a patch if this sounds reasonable.

**Comment by dkogan** [comment]
Hi. I really need this feature, and using 'unbuffer' is unwieldy (it's a TCL tool). Can I get an ack that such a patch would be accepted? Or a better way to do this?

To be clear that this is useful, here's the real world use case I'm hitting currently. I'm debugging the emacs daemon, and I need to see its console output. The daemon redirects its stderr to /dev/null, so it doesn't actually go anywhere, but sysdig can be used to see it. I can do something like

```
sudo sysdig proc.name=emacs -c stderr
```

which works (sysdig output goes to TTY, so the standard C library does line buffering). But apparently the writer puts bytes in one at a time, so the output gives me one byte per line. This is inconvenient. I want to do

```
sudo sysdig ... | perl -ne '<combine individual bytes into lines of useful output>'
```

However the sysdig output is then not a TTY, and the pipe doesn't receive the data when it comes in, but much later, whenever the internal buffer fills. In this case I want to 'sysdig --unbuffered'

**Comment by ldegio** [comment]
A patch for this would definitely be accepted and should not be hard (it's a matter of calling flush() after writing each line or, even better, using setvbuf).

Alternatively, I can work on this, but probably not until the weekend.

**Comment by dkogan** [comment]
If you can do this, that'd be great. Let me know if you can't find the time, and I'll give you a patch.

**Comment by ldegio** [comment]
Can you tell me if this commit does what you need? https://github.com/draios/sysdig/commit/13bb255aee8e7021492711da5e2698efe0f31abb

**Comment by dkogan** [comment]
This does indeed do what I need. Thanks!
