### ISSUE TITLE
Zsh completion seems broken

### ISSUE THREAD

**Issue by mgraff** [draios/sysdig#447]
Hello,

When I load the _sysdig completion file into zsh, I get the following error while using completion on sysdig command :

```
_filter:9: failed to compile regex: repetition-operator operand invalid
_filter:9: failed to compile regex: repetition-operator operand invalid
_filter:9: failed to compile regex: repetition-operator operand invalid
[...]
```

It seems that the problem comes from this line :

```
if [[ $line =~ "^([a-zA-Z0-9_]+\.[a-zA-Z0-9_\.]+) +(.*?)$" ]]; then
```

and more specifically from the `*?` symbols which are incompatible when used together. 

Thanks

**Comment by shazib-summar** [comment]
@mgraff were you able to solve this? im getting this error on 

```
^((?!(istio-operator|kube-.*|play-.*|frontend)).)*$
```
