### ISSUE TITLE
Possible to add other filters to the docker module?

### ISSUE THREAD

**Issue by ashish235** [draios/sysdig#448]
I 'm planning to use sysdig to monitor my applications running inside docker container. I could see some great possibilities here which can be done with sysdig. 

I was just checking if filters like container.process or container.pid could also work? 

The command "sysdig -pc -c topprocs_cpu container.name=WebAPP" is fine but I 've actually 2-3 process running inside the container. Now in this case, I need to monitor a particular process with a command say sysdig -pc -c topprocs_cpu container.name=PCRF2 and container.process=xyx. I can't find any relevant documentation for this. 

Is this supported? if not can it be supported in future releases?

Thanks.

--
Ashish

**Comment by luca3m** [comment]
Have you tried with:

`container.name = xxx and proc.name = yyy` ?

Also you can use the pid of the process as seen inside the container, it's called `vpid`.

`container.name = xxx and proc.vpid = 1`

**Comment by ashish235** [comment]
It works!

Thanks @luca3m 

--
Ashish

**Comment by luca3m** [comment]
Cool! You're welcome
