### ISSUE TITLE
Filtering captures does not modify the /proc information

### ISSUE THREAD

**Issue by swsnider** [draios/sysdig#450]
Example: `sysdig -r out.scap -w out2.scap -pc container.name=mysql`, when viewed with `csysdig` includes lines from the mysql container and the host, as expected, but also contains lines from the toher processes running in other containers because the information from /proc is not correctly filtered.

You can find example captures here: https://drive.google.com/folderview?id=0B5NeVqbOMiRjdko1Zk9GUEl3YjA&usp=sharing. out.scap is the original capture, out2.scap is the filtered capture using the above command.

**Comment by swsnider** [comment]
ping?

**Comment by gianlucaborello** [comment]
Sorry for the long delay.

You are right, on top of the normal system events we include information from /proc and other internal events (e.g. containers, kubernetes) and at the moment we don't filter them, mainly because their format is not prone to be filtered easily.

May I ask what is your exact use case? If it's for sanitization of the trace file, the proper fix might take a while, as I said above. If it's just for consistency, we might do something such as including the user filter in the resulting trace file, and reapplying it on the fly when reading the capture.

Thanks

**Comment by swsnider** [comment]
My use case is sanitization -- I'm running a bunch of containers in a mesos cluster, and I'm trying to provide optics into the container activity to each user, while providing as much secrecy as possible.

**Comment by ldegio** [comment]
@swsnider, could you please try the latest dev branch and tell me if it does what you need? Commit 7b851b1fcd54e26066a3ee7e0ac68e97cf6e686e should add what you are asking for. It still doesn't filter out individual FDs, but I can work on that in the next days.

**Comment by swsnider** [comment]
Sorry for the late reply from me!

I tried what you asked, and after building the userspace on OS X El Capitan (10.11.2 15C50), I ran

`./userspace/sysdig/sysdig -r out.scap -w out2.scap -pc container.name=mysql`

which completed successfully.

I then ran

`./userspace/sysdig/sysdig -D -r out2.scap`

Which failed:

```
12-15 05:49:22.507518 starting offline capture
corrupted input file. Can't find file descriptor list block.
```

Running the same command on out.scap is successful (prints events to console).

**Comment by ldegio** [comment]
hmm, doesn't happen to me. What branch are you compiling from? Could you share a small trace file that replicates the problem?

**Comment by swsnider** [comment]
I'm compiling from 7b851b1 via the following commands:

1. `git clone https://github.com/draios/sysdig.git`
2. `git reset --hard 7b851b1`
3. `mkdir build`
4. `cd build`
5. `cmake ..`
6. `make`

The offending trace file is here: https://drive.google.com/open?id=0B5NeVqbOMiRjSzlsMG9vV3U3N1k

**Comment by ldegio** [comment]
try to just compile the head of the dev branch, I made some fixes after that commit. As an alternative, I believe the release of sysdig that went out yesterday should include the changes.

**Comment by swsnider** [comment]
I get the same result for head of dev, and for the release tarball.

Resulting trace from HEAD (bcee641e674109ad9f7f05f6cebd0bf77542bf60) of dev: https://drive.google.com/open?id=0B5NeVqbOMiRjbEpmSHJQUmI3TEk

Resulting trace from 0.6.0 release: https://drive.google.com/open?id=0B5NeVqbOMiRjTktaaXBRbWVmTms

**Comment by ldegio** [comment]
could you send me the original trace file that you have before filtering?

**Comment by swsnider** [comment]
It's in the link at the top: https://drive.google.com/folderview?id=0B5NeVqbOMiRjdko1Zk9GUEl3YjA&usp=sharing (out.scap is the original file)

**Comment by ldegio** [comment]
can you try again by building the dev branch?

**Comment by maryamag85** [comment]
Hi,
I have difficulty opening the .scap file in the Linux and process it. what is the best software or library to open it in linux / python.?
