### ISSUE TITLE
IPv6 support for CentOS repo

### ISSUE THREAD

**Issue by ton31337** [draios/sysdig#459]
Hi,

any plans to have support for IPv6-only hosts?
```
~$ dig AAAA download.draios.com +short
~$
```

**Comment by ltagliamonte** [comment]
Hi @ton31337,
download.draios.com is an A "alias record" to an AWS S3 bucket and at the moment AWS doesn't support AAAA alias records to S3 buckets, when AWS will increase its support to IPv6 we will be happy to configure it. Closing for now.
