### ISSUE TITLE
Sysdig fails to run after CPU hotplug

### ISSUE THREAD

**Issue by gnosek** [draios/sysdig#462]
After adding extra CPUs to a VM sysdig (0.1.101 here) fails to start:

```
root@XXX:~# sysdig evt.type=open and fd.name contains jpg
error opening device /dev/sysdig4. Make sure you have root credentials and that the sysdig-probe module is loaded.
root@XXX:~# lsmod | grep sysdig
sysdig_probe          367160  0
```

Removing the sysdig_probe module (so it recreates the devices after being loaded again) solves the issue so it isn't critical, but made my heart stop for a second ;)

**Comment by luca3m** [comment]
CPU hotplug support has been added on `0.1.103`, would you like to try this version or better the latest available?

**Comment by gnosek** [comment]
Yup, will update and retest, but as I said, it's not critical :) If you say hotplug has been added in the meantime, I'll just close the issue and open another if it doesn't work.

Thanks!
