### ISSUE TITLE
Segmentation fault: parinfo->m_len == sizeof(uint16_t)

### ISSUE THREAD

**Issue by ljagiello** [draios/sysdig#464]
```
# ./sysdig -r /root/crashes/id\:000000\,sig\:11\,src\:000000\,op\:arith8\,pos\:21360\,val\:+1
sysdig: /root/debug/sysdig-0.5.0/userspace/libsinsp/filterchecks.cpp:2791: virtual uint8_t* sinsp_filter_check_event::extract(sinsp_evt*, uint32_t*): Assertion `parinfo->m_len == sizeof(uint16_t)' failed.
Aborted
```

I was playing a bit with [afl-fuzz](http://lcamtuf.coredump.cx/afl/) and I was able to generate segmentation fault as above.

Problematic scap file: https://www.dropbox.com/s/ezfbzludgdt8lw8/id%3A000000%2Csig%3A11%2Csrc%3A000000%2Cop%3Aarith8%2Cpos%3A21360%2Cval%3A%2B1?dl=0

**Comment by ldegio** [comment]
This is an assertion telling us that the file is corrupted. How did you create it?

Note that, at this point, sysdig has limited event validation, so a corrupted or malign trace file will easily crash it.

**Comment by ldegio** [comment]
This is an assertion telling us that the file is corrupted. How did you create it?

Note that, at this point, sysdig has limited event validation, so a corrupted or malign trace file will easily crash it.

**Comment by ljagiello** [comment]
@ldegio yes it was crafted just to crash sysdig.
