### ISSUE TITLE
sysdig build of 0.5.0 fails on mac with brew

### ISSUE THREAD

**Issue by Hefeweizen** [draios/sysdig#467]
0.4.0 builds fine in this way.

using `brew edit` to update the formula to point at https://github.com/draios/sysdig/archive/0.5.0.tar.gz (also updating sha256).
Then proceed to call `brew upgrade sysdig`; it bombs with the attached output.
[homebrew.sysdig.make_failure.201511112.txt](https://github.com/draios/sysdig/files/33088/homebrew.sysdig.make_failure.201511112.txt)

**Comment by aleks-f** [comment]
Confirmed. Apparently OpenSSL defaults to 32-bit and requires explicit 64-bit configure step.

**Comment by gianlucaborello** [comment]
@aleks-f we don't need openssl at all on OSX though, so let's just treat it like Windows here.

**Comment by aleks-f** [comment]
@gianlucaborello same goes for curl as well, right?

**Comment by gianlucaborello** [comment]
Absolutely, I would do this:

1) In the cmake files, let's exclude all those with something like `if(CMAKE_SYSTEM_NAME MATCHES "Linux")`

2) In the cpp code for k8s, let's exclude parts with `#ifdef HAS_CAPTURE`, since it's already there and it automatically covers windows and osx
