### ISSUE TITLE
Kubernetes flag does not work on compiled or rpm pkg on Centos

### ISSUE THREAD

**Issue by bh016088** [draios/sysdig#472]
Following these instructions: https://sysdig.com/digging-into-kubernetes-with-sysdig/

I went through the setup of sysdig on my Centos 7 server.  Trying both an RPM install and building it from source.  Version 0.5.0.

I was not able to get  the -k option  to work for either of these. 

sysdig -k "http://kubernetes01.company.com:8080"
 returns the error: 
"An error occured while trying to retrieve data for k8s nodes: Couldn't connect to server"

Aside from the misspelled word, this is also not accurate, as I am able to connect just fine to my kube cluster api:

curl -L http://kubernetes01.company.com:8080
{
  "paths": [
    "/api",
    "/api/v1",
    "/healthz",
    "/healthz/ping",
    "/logs/",
    "/metrics",
    "/resetMetrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]

I noticed in the help for sysdig and csysdig that you may want credentials.  I don't currently have auth for my kube cluster.

Anyone know what is going on?

**Comment by gianlucaborello** [comment]
That's definitely not expected. Can you try with?

```
$ sudo sysdig -D
11-13 18:16:07.135686 Fetching initial k8s state
11-13 18:16:07.137330 Retrieving all data from http://127.0.0.1:8080/api/v1/nodes
11-13 18:16:07.137799 An error occured while trying to retrieve data for k8s nodes: Couldn't connect to server
An error occured while trying to retrieve data for k8s nodes: Couldn't connect to server
```

You should get a more detailed output so we can see what's going on. Could you try to curl the exact URL that sysdig is trying to contact and verify it works with curl?

Also, if you compiled from source you might want to try the latest dev branch, it contains some bugfixes, although I don't think it's going to make a big difference since you don't seem to be using an https connection.

Thanks

**Comment by bh016088** [comment]
I scrubbed it for personal/company data but it worked in the curl and not in the sysdig:

/usr/local/bin/sysdig -k "http://kubernetes01.company.com:8080" -D
11-13 21:55:30.015922 Fetching initial k8s state
11-13 21:55:30.016118 Retrieving all data from http://kubernetes01.company.com:8080/api/v1/nodes
11-13 21:55:30.621809 An error occured while trying to retrieve data for k8s nodes: Couldn't connect to server
An error occured while trying to retrieve data for k8s nodes: Couldn't connect to server


[root@kubernetes01:~/sysdig/sysdig/build]$ curl -L http://kubernetes01.company.com:8080/api/v1/nodes
{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/nodes",
    "resourceVersion": "2710058"
  },
  "items": [
    {
      "metadata": {
        "name": "kubernetes02",
        "selfLink": "/api/v1/nodes/kubernetes02",
        "uid": "3b6b2531-4820-11e5-9477-005056b478bc",
        "resourceVersion": "2710048",
        "creationTimestamp": "2015-08-21T16:18:17Z",
        "labels": {
          "kubernetes.io/hostname": "kubernetes02"
        }
      },
      "spec": {
        "externalID": "kubernetes02"
      },
      "status": {
        "capacity": {
          "cpu": "1",
          "memory": "1881248Ki",
          "pods": "40"
        },
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2015-11-13T21:55:32Z",
            "lastTransitionTime": "2015-08-21T16:18:17Z",
            "reason": "kubelet is posting ready status"
          }
        ],
        "addresses": [
          {
            "type": "LegacyHostIP",
            "address": "127.0.0.1"
          }
        ],
        "nodeInfo": {
          "machineID": "643c9a98f0174a0eb5e76b2644dc3db9",
          "systemUUID": "42349EE5-81A0-477F-AA5C-9EA26AB37B87",
          "bootID": "a904a8dc-acfb-4e3c-85c9-91372f21c0f1",
          "kernelVersion": "3.10.0-229.7.2.el7.x86_64",
          "osImage": "CentOS Linux 7 (Core)",
          "containerRuntimeVersion": "docker://1.8.1",
          "kubeletVersion": "v1.0.3",
          "kubeProxyVersion": "v1.0.3"
        }
      }
    },
    {
      "metadata": {
        "name": "kubernetes03",
        "selfLink": "/api/v1/nodes/kubernetes03",
        "uid": "3dd97ce1-4820-11e5-9477-005056b478bc",
        "resourceVersion": "2710050",
        "creationTimestamp": "2015-08-21T16:18:21Z",
        "labels": {
          "kubernetes.io/hostname": "kubernetes03"
        }
      },
      "spec": {
        "externalID": "kubernetes03"
      },
      "status": {
        "capacity": {
          "cpu": "1",
          "memory": "1881248Ki",
          "pods": "40"
        },
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2015-11-13T21:55:38Z",
            "lastTransitionTime": "2015-08-21T20:00:12Z",
            "reason": "kubelet is posting ready status"
          }
        ],
        "addresses": [
          {
            "type": "LegacyHostIP",
            "address": "127.0.0.1"
          }
        ],
        "nodeInfo": {
          "machineID": "643c9a98f0174a0eb5e76b2644dc3db9",
          "systemUUID": "4234C522-32CD-3409-FE71-F44484DD4836",
          "bootID": "48ca1e8e-dc99-4d51-88ad-d7b5e404f501",
          "kernelVersion": "3.10.0-229.7.2.el7.x86_64",
          "osImage": "CentOS Linux 7 (Core)",
          "containerRuntimeVersion": "docker://1.8.1",
          "kubeletVersion": "v1.0.3",
          "kubeProxyVersion": "v1.0.3"
        }
      }
    },
    {
      "metadata": {
        "name": "kubernetes04",
        "selfLink": "/api/v1/nodes/kubernetes04",
        "uid": "3e5e3a7a-4820-11e5-9477-005056b478bc",
        "resourceVersion": "2710051",
        "creationTimestamp": "2015-08-21T16:18:22Z",
        "labels": {
          "kubernetes.io/hostname": "kubernetes04"
        }
      },
      "spec": {
        "externalID": "kubernetes04"
      },
      "status": {
        "capacity": {
          "cpu": "1",
          "memory": "1881248Ki",
          "pods": "40"
        },
        "conditions": [
          {
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2015-11-13T21:55:38Z",
            "lastTransitionTime": "2015-08-24T16:17:47Z",
            "reason": "kubelet is posting ready status"
          }
        ],
        "addresses": [
          {
            "type": "LegacyHostIP",
            "address": "127.0.0.1"
          }
        ],
        "nodeInfo": {
          "machineID": "643c9a98f0174a0eb5e76b2644dc3db9",
          "systemUUID": "42348C80-42FB-1F7F-5912-DD67F2D091DA",
          "bootID": "55934a89-aaf0-4134-9fde-77d2bfa6c2ed",
          "kernelVersion": "3.10.0-229.7.2.el7.x86_64",
          "osImage": "CentOS Linux 7 (Core)",
          "containerRuntimeVersion": "docker://1.8.1",
          "kubeletVersion": "v1.0.3",
          "kubeProxyVersion": "v1.0.3"
        }
      }
    }
  ]

**Comment by gianlucaborello** [comment]
Do you have a non-standard configuration? Can we see what happens at HTTP level with "curl -v"?

Thanks

**Comment by bh016088** [comment]
Okay, good call.  I checked my verbose curl and saw I still had my http_proxy set still.  I cleared it and now I can get in to csysdig just fine!  

Unfortunately, it just hangs on "Collecting Data" when I try and select any k8s filter.  I'll open another issue if I can't figure out what is going on.  

Thanks for your help!
