### ISSUE TITLE
sysdig/sysdig container - missing less for csysdig

### ISSUE THREAD

**Issue by pctj101** [draios/sysdig#476]
When starting sysdig as follows:

```
docker pull sysdig/sysdig
docker run -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro sysdig/sysdig
```

Then running csysdig, I want to "less" a file so that I can view the contents (not tail realtime).

However the less executable is not present so after pressing 'l' (L) many times and exiting csysdig, I see this on the console

```
root@e300eb25aa8b:/tmp# csysdig
sh: 1: less: not found
sh: 1: less: not found
sh: 1: less: not found
sh: 1: less: not found
sh: 1: less: not found
sh: 1: less: not found
sh: 1: less: not found
```

I'm sure there's a billion ways to get less into the image.  Is there a 'right way' way for me to help?

**Comment by pctj101** [comment]
Oh that was interesting.  I did apt-get install less, and that worked great.

But I was unable to "less" a file from a different container.

#/tmp/something.txt: No such file or directory

I wonder what to do now... hmm!

**Comment by ldegio** [comment]
Unfortunately, running hotkey actions in other containers is not supported yet, and it's not easy to support since things live in separate namespaces. 

We should probably make it more clear in the documentation.

**Comment by pctj101** [comment]
Ah okay.  What's a good alternative to running in a container?

**Comment by ldegio** [comment]
The only solution now is attacing to the container ('a' key in csysdig) or starting a bash shell ('b' key) and then manually running less. There might be an opportunity to automate it, but it would require a non negligible amount of work.
