### ISSUE TITLE
non-root instructions in the wiki don't work on arch linux

### ISSUE THREAD

**Issue by oryband** [draios/sysdig#483]
Following #89 and the [wiki page](https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Linux) for letting `sysdig` and `csysdig` run without sudo on my Arch Linux machine. I'm getting the following error:
```
$ groupadd sysdig
$ usermod -aG sysdig ory
$ which sysdig
/usr/bin/sysdig
$ sudo visudo
# adding %sysdig ALL= /usr/bin/sysdig to the file and saving
$ sysdig
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```
Any idea what am I doing wrong? Please not I'd also like to add `csysdig` as well.

**Comment by HugoGuiroux** [comment]
The instructions explain how a user can use `sudo` only for `sysdig`, not how to launch `sysdig` as if it was launched using `sudo`.
So you still need to call `sudo sysdig` (and if you did the instructions for the user you use, it will be allowed to execute the command).

If you want to get rid of the `sudo` prefix, you can still add an alias in your shell configuration (add `alias sysdig='sudo sysdig'` in your ~/.bashrc). But it is potentially a bad behavior, as it is always better to be aware that the command you are trying to execute needs root privileges.

**Comment by oryband** [comment]
right, I was confused, sorry.
