### ISSUE TITLE
Unable to download precompiled module on Atomic Host 

### ISSUE THREAD

**Issue by marc-sensenich** [draios/sysdig#487]
When attempting to run the sysdig container on Red Hat Enterprise Linux Atomic Host release 7.2, it fails to download the precompiled module. Example output from the `docker run` is below:
```
docker run -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/mo dules:ro -v /usr:/host/usr:ro sysdig/sysdig
* Setting up /usr/src links from host
* Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms autoinstall
Error! echo
Your kernel headers for kernel 3.10.0-327.el7.x86_64 cannot be found at
/lib/modules/3.10.0-327.el7.x86_64/build or /lib/modules/3.10.0-327.el7.x86_64/source.
* Trying to load a system sysdig-probe, if present
* Trying to load a dkms sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 3.10.0-327.el7.x86_64
Found kernel config at /host/usr/lib/ostree-boot/config-3.10.0-327.el7.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.5.1-x86_64-3.10.0-327.el7.x86_64-45dfffe3d701dbc0d44d119a0a8157f8.ko
Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community
```
It seems that this is due to the kernel in version in Red Hat Enterprise Linux Atomic Host release 7.2: 3.10.0-327.el7.x86_64. We can use sysdig on Red Hat Enterprise Linux Atomic Host release 7.1.6, since the kernel version is 3.10.0-229.20.1.el7.x86_64.

**Comment by gianlucaborello** [comment]
We build sysdig-probe binaries using the public repositories of CentOS, and CentOS 7.2 hasn't been released yet, so this affects RHEL as well. If you happen to find a free and legal mirror where I can download the kernel headers for `3.10.0-327.el7.x86_64` please let me know (or submit a PR against https://github.com/draios/sysdig/blob/dev/scripts/kernel-crawler.py#L16), otherwise, unless I'm missing something, we'll have to wait for CentOS 7.2.

**Comment by gianlucaborello** [comment]
As of today, CentOS 7.2 has been released ad our automation system picked it up automatically, and https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.5.1-x86_64-3.10.0-327.el7.x86_64-45dfffe3d701dbc0d44d119a0a8157f8.ko is fully available for download
