### ISSUE TITLE
[Feature] Display memory usage as "bytes" instead of as "kilobytes"

### ISSUE THREAD

**Issue by Kodiack** [draios/sysdig#492]
Currently, csysdig displays memory usage as a number of kilobytes. For example, "200K" means "200,000 kilobytes", which may not be the most intuitive way of handling it. It threw a coworker and me for a loop at first until we realised what was actually going on.

**Comment by donovan** [comment]
We came up with a fix:

https://github.com/draios/sysdig/compare/dev...donovan:filterchecks-byte-prefix-bug

but it breaks everything else. The function sinsp_filter_check_reference is clearly expecting val to be bytes. This leads to the confusion when memory vals are in KB.

**Comment by ldegio** [comment]
commits https://github.com/draios/sysdig/commit/5377b63d1113e5b8c0842dd579d155aaba782642, https://github.com/draios/sysdig/commit/7559c7c237693b07bccc4886ac65039a31984539 and https://github.com/draios/sysdig/commit/75e36a7cb36b9a19bdd3aa7b576408563f619ecd should fix this. 

Could you please try and let me know if it works as expected?

**Comment by ldegio** [comment]
Not having received comments I'm assuming this is OK and I'm going to close the issue. Feel free to reopen if that's not the case.

**Comment by Kodiack** [comment]
Yes, this looks good to me. Thank you for the quick response and fix!
