### ISSUE TITLE
csysdig help text doesn't mention Actions (F8)

### ISSUE THREAD

**Issue by aspiers** [draios/sysdig#504]
If I start `csysdig` and press `h` for help, it explains what all the function keys do except for F8 (actions).

**Comment by ldegio** [comment]
168b8b43d50cc3216152cc5cce52021919d4f9bc adds information about actions to the help and manual pages

**Comment by aspiers** [comment]
Wow, I think this project has the most insanely fast response to bug reports I have ever seen ;-)
