### ISSUE TITLE
document install on openSUSE

### ISSUE THREAD

**Issue by aspiers** [draios/sysdig#509]
sysdig is now available via [1 Click Install](https://en.opensuse.org/openSUSE:One_Click_Install) for openSUSE Leap 42.1, Tumbleweed, and old versions 13.2 and 13.1:
- https://software.opensuse.org/package/sysdig

So http://www.sysdig.org/install/ should be updated accordingly.  Please let me know if you need any help with this.

**Comment by aspiers** [comment]
Oh and BTW, our package build process is fully open via the [Open Build Service](http://openbuildservice.org/) :)

- https://build.opensuse.org/package/show/devel:tools/sysdig
- https://en.opensuse.org/openSUSE:Build_Service_Tutorial

**Comment by gianlucaborello** [comment]
That's awesome!

I have a couple notes/questions:

1) Packages names contain "5.1", is it normal? e.g. http://download.opensuse.org/repositories/devel:/tools/openSUSE_Leap_42.1/x86_64/sysdig-0.6.0-5.1.x86_64.rpm

2) You're packaging the driver using KMPs, which seems to be the recommended way under SUSE. I just wanted to know as a personal curiosity, what's your opinion (if you have any) on that approach vs, say, dkms, which in theory should be a bit more flexible at the cost of having the user install a build toolchain on his machine? 

With dkms we are doing some pretty crazy stunts here. For example, the sysdig docker container can auto-build pretty much all sysdig-probes regardless of the host kernel, even if it's from a completely different distribution than the container's runtime, as long as the headers are mounted inside the container (which seems, and sort of is, very dirty, but it's allowing us to cover many customer environments with minimal effort on our side).

Thanks

**Comment by aspiers** [comment]
The 5.1 is merely the release number, and it automatically increments every time OBS rebuilds the package (e.g. if the .spec file or dependencies get updated).  So any resemblance to 0.5.1 is totally coincidental :-)

Regarding dkms, I don't really know enough to have a qualified opinion :-)  My best guess follows ...

Presumably the advantage with the current approach is quicker installation and fewer dependencies like you say (since the kernel module is built at build-time not install-time), and the disadvantage is that it can't be used by people running custom kernels.  However I think the vast majority of openSUSE users use prebuilt the kernels from the distro which are built in OBS, and which these sysdig kmp packages get built against.  So I suspect dkms *might* be a bit overkill in this context.  Having said that, we could still use dkms at package build-time, but even without that I guess that people with custom kernels could simply rebuild from the existing source rpm, so I'm not sure how much it would gain.

I may well be missing some crucial considerations regarding containers though.

Finally, since not many people know, I just wanted to mention that OBS also builds packages for other non-SUSE distros, e.g. Fedora, CentOS, RHEL, Ubuntu, Debian, Arch, Scientific Linux ... and of course it's all F/OSS and free for anyone to use or even set up their own OBS instance :-)

**Comment by gianlucaborello** [comment]
Thanks for your explanation.

Yes, OBS is interesting, it was on my "to look" list a while ago but we have this limitation where we're using the same yum/apt repository to push sysdig (open source) and sysdig cloud agent (commercial), so we are using our own private jenkins job.

I missed the bit about the ability to setup my own OBS instance, so I might definitely take a look again since that way we might be able to leverage it for our closed-source code as well.

**Comment by gianlucaborello** [comment]
While I was trying the sysdig build for the other issue you reported, I noticed that the version within sysdig gets wrongly set:

```
# sysdig --version
sysdig version 0.1.1dev
# zypper info sysdig
...
Name: sysdig
Version: 0.6.0-5.1
Installed: Yes
...
```

At the moment, we require to put it at cmake time, in the future (or if a PR comes) we'll get it straight from the git tag. FYI, these are the flags that we use on jenkins for our release:

```
cmake -DCMAKE_BUILD_TYPE=Release -DSYSDIG_VERSION=$SYSDIG_VERSION -DDIR_ETC=/etc -DCMAKE_INSTALL_PREFIX=/usr $SYSDIG_SOURCEDIR
```

**Comment by aspiers** [comment]
Oh yeah, thanks for the reminder and info - I had noticed that but forgot to investigate further.  I can easily submit a request (a.k.a. `submitreq` - OBS equivalent of a pull request) to fix this, or alternatively if you are looking for an excuse to learn a bit more about collaboration workflows in OBS, you are of course welcome to do it yourself :)  The workflow is [well documented](https://en.opensuse.org/openSUSE:Build_Service_Tutorial#A_start_to_end_example_of_a_simple_change).

**Comment by aspiers** [comment]
> I missed the bit about the ability to setup my own OBS instance, so I might definitely take a look again since that way we might be able to leverage it for our closed-source code as well.

Yes, several of our hardware and software partners do exactly that.  It is also possible to share code across OBS instances ...
