### ISSUE TITLE
sysdig links GPLv2 code to OpenSSL

### ISSUE THREAD

**Issue by evgeni** [draios/sysdig#512]
Ohai,

while working on sysdig for Debian, I noticed that you link to OpenSSL these days, but the code says it's GPLv2-only.

The OpenSSL license is not compatible with GPLv2: https://en.wikipedia.org/wiki/OpenSSL#Licensing, https://people.gnome.org/~markmc/openssl-and-the-gpl

Can you please check with all copyright holders if an OpenSSL exemption is OK and then add it to the sysdig license?

Greets
Evgeni

**Comment by ldegio** [comment]
This shouldn't be a problem, since for the moment the only copyright holder is sysdig inc. Give me few days to check this with the other team members, things are slow this week because of the holidays.

**Comment by evgeni** [comment]
Hi Loris,

while Sysdig/Draios is the only name in the headers, GitHub currently lists 67 contributors which are not all employed by you :)

IANAL but I think that due to the fact sysdig has no CLA or other copyright assignment, the actual patches are copyrighted by the contributors and not Sysdig/Draios and you'd need to gather input from them all.

Btw, I, as a contributor, am fine if you add the openssl exemtion to gpl2 of my changes.

Greets

On December 28, 2015 7:56:05 PM GMT+01:00, Loris Degioanni <notifications@github.com> wrote:
>This shouldn't be a problem, since for the moment the only copyright
>holder is sysdig inc. Give me few days to check this with the other
>team members, things are slow this week because of the holidays.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/draios/sysdig/issues/512#issuecomment-167628602

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by 03cranec** [comment]
Hi Evgeni - We have resolved this issue with our lawyers and added the OpenSSL exemption to our GPL license. More info on CLAs coming soon. Thanks again for bringing this to our attention. Cheers.
