### ISSUE TITLE
sysdig build of 0.7.0 fails on mac with brew

### ISSUE THREAD

**Issue by Hefeweizen** [draios/sysdig#524]
0.6.0 builds fine in this way.

using brew edit to update the formula to point at https://github.com/draios/sysdig/archive/0.7.0.tar.gz (also updating sha256).
Then proceed to call brew upgrade sysdig; it bombs with the attached output.
[homebrew.sysdig.make_failure.20160122.txt](https://github.com/draios/sysdig/files/101725/homebrew.sysdig.make_failure.20160122.txt)

**Comment by gianlucaborello** [comment]
Fixed in 0.7.1, thanks for reporting.
