### ISSUE TITLE
CoreOS Docker

### ISSUE THREAD

**Issue by mozzymoz** [draios/sysdig#528]
Hi there,
when I try to run csysdig in a container in coreos I get an error
"Error opening terminal: xterm-1002"

Any idea what I'm doing wrong?

**Comment by luca3m** [comment]
It's a bug introduced with sysdig 0.7.0. It will be solved with the next
release. Right now please use the old version.

Luca Marturana
Software Engineer / Sysdig

**Comment by mozzymoz** [comment]
Ah oki, thanks :)

**Comment by gianlucaborello** [comment]
You can also keep using the latest version and just do, inside the container:

```
apt-get update && apt-get -y install ncurses-term
```

**Comment by mozzymoz** [comment]
Installing ncurses-term does fix the issue

**Comment by luca3m** [comment]
It has been fixed with 0.8.0

**Comment by mozzymoz** [comment]
:+1:
