### ISSUE TITLE
libssh2 error when building on debian jessie

### ISSUE THREAD

**Issue by kristopolous** [draios/sysdig#533]
Hi,

I'm building on debian jessie and I got an error (see http://9ol.es/libssh2-error.txt)

I was able to fix this with a cmake change. PR coming soon.

**Comment by kristopolous** [comment]
For more context, I also talked about this in the IRC channel, ![irc screencap](http://i.imgur.com/9hP4VPL.png)

**Comment by gianlucaborello** [comment]
Hi

We don't need `libssh2` at all and we don't want to fail on systems that don't have it installed, so I think https://github.com/draios/sysdig/commit/8f7d757426592aa2c060f5eddf8635190e7e9b18 is the right fix. Please try again starting from a completely empty build directory, thanks.

**Comment by kristopolous** [comment]
alright sure hold on

**Comment by kristopolous** [comment]
it failed with -j5 ... http://9ol.es/1455329864-sysdig.txt I'm going to try to build again on top of it

**Comment by kristopolous** [comment]
ok success ... it's kind of a pity that job control doesn't work.

**Comment by kristopolous** [comment]
let me close that pr then ...we don't need it

**Comment by kristopolous** [comment]
patched in https://github.com/draios/sysdig/commit/8f7d757426592aa2c060f5eddf8635190e7e9b18
