### ISSUE TITLE
Memory keep growing when filtering on CentOS6.7

### ISSUE THREAD

**Issue by hzhaop** [draios/sysdig#537]
Same problem with this link: [https://groups.google.com/forum/#!msg/sysdig/vi0X_H-zo2Y/p36V16ViFAAJ](url)

CentOS6.7, 
sysdig 0.8, 
Linux easyops 2.6.32-573.el6.x86_64 

Memory keep growing when I add some filters until OOM. 
When I remove filters,  memory usage seems to be normal. 

It's likely to have memory leak when I call sysdig with some filters. 

processes num: 187 
thread num: 1271 
open fds: 6265

**Comment by luca3m** [comment]
Thanks for reporting, we are working on it

**Comment by luca3m** [comment]
Hi it has been fixed on dev, will be released with 0.9.0. If the issue still happens on your machine please reopen.
