### ISSUE TITLE
sysdig filters and trace files

### ISSUE THREAD

**Issue by tsigian** [draios/sysdig#557]
If I do 'sysdig proc.name=myapp' , and start the 'myapp' program' sysdig will start print to console only the events for the 'myapp' program, so far so good.

But if I do 'sysdig -C 10 -W 10 -w /tmp/myapp.scap proc.name=myapp', and start 'myapp', sysdig does not save only the 'myapp' events in /tmp/myapp.scap but all kernel events.

Is that the expected behavior ?
How can I achieve saving only filtered events to trace files ?

**Comment by ldegio** [comment]
I can't replicate this. Which version of sysdig are you using? Can you try the latest one?

**Comment by ldegio** [comment]
Closing since we're missing the context to replicate it. Feel free to reopen if you come up with additional info.
