### ISSUE TITLE
Running sysdig result in kernel oops and hard freeze after 1-2s.

### ISSUE THREAD

**Issue by slashbeast** [draios/sysdig#566]
Hi,

After 1 or 2 seconds of running sysdig I am getting a kernel oops and hard freeze. Sysdig does print what it should, depending on the filter, and then machine hangs. I can reproduce it on two boxes, one running kernel 4.4.4 and another 4.5.0.

sysdig-0.6.0

The oops:
![fooooooooooo](https://cloud.githubusercontent.com/assets/180211/14049722/5aea5a1a-f2b7-11e5-9262-0e113511fa86.jpeg)

**Comment by GreenRecycleBin** [comment]
Could you provide more information just like in https://github.com/draios/sysdig/issues/556?

**Comment by slashbeast** [comment]
Not all that much. I cannot use gdb as the screen is coverd in kernel oops on crash and I cannot run backtrack afterward as the system is hard frozen and I need to reset it with power button.

The system It gentoo, ~amd64, and the kernel config as attached
[config.gz](https://github.com/draios/sysdig/files/190387/config.gz)

The sysdig arguments that I've used: `sysdig -p "%12user.name %6proc.pid %12proc.name %3fd.num %fd.typechar %fd.name" evt.type=open`

**Comment by slashbeast** [comment]
Friendly bump.

**Comment by gianlucaborello** [comment]
Can you replicate this in 0.9.0?

If yes, please post again the exact kernel version and config you're using, and see if, after rebooting, you find those oops messages in /var/log/{kern.log,messages,syslog}, a comprehensive list would be very useful, in particular I'm looking for the first oops.

Also, please try to see if you're able, upon crash, to scroll the console screen up, usually it's something like `shift + page up` or `alt + shift + page up`. Once again, the very first oops would be useful.

If not, a recent screenshot of the oops on 0.9.0 will be useful as well.

**Comment by slashbeast** [comment]
Hello.

I cannot reproduce crash on 0.9.0. Since the crash was in the very first seconds I can say that the issue is no more. :)

Should I/you close this issue or you do want to debug it futher and want me to provide you more logs form the 0.6.0?

**Comment by gianlucaborello** [comment]
Thanks for the update. I think it's safe to close the issue, 0.6.0 is pretty old and there have been some bugs in the driver which were fixed since then. That being said, if you experience a crash on the latest stable, don't hesitate in reaching out, kernel bugs against those versions are treated very seriously.
