### ISSUE TITLE
Backspace in csysdig should jump to previous View

### ISSUE THREAD

**Issue by philrz** [draios/sysdig#571]
(Opening this issue after a 1-on-1 conversation with Loris where he agreed it was issue-worthy and should be submitted to the community for further comment.)

As a fairly new user, I've been tripped a few times by the subtleties of F2 vs. Backspace when working with Views. I'm so accustomed to hitting Backspace to go backwards during drill-down workflows, that when I start from the default "Processes" view, then hit F2 and select something like "Traces Spectrogram" and see "BKSPACE:Back" in the hints at the bottom, I sit there pounding Backspace and wondering why it's not changing the View. Then I remember that I've just made a horizontal transition between Views and hence I just need to hit F2 and select yet another view. Of course, I "get it" how the Backspace in that context was for the case of going backwards in a drill-down such as from "Traces List" if I'd hit F12 to get into the Traces Spectrogram. But it sure would be nice if it could remember the previous View in the first example such that Backspace would effectively be "horizontally switch back to the last View I came from".

**Comment by sangrealest** [comment]
That's what exactly I want to say!  The hit 'BKSPACE:Back' 'really confused me at the first time of using csysdig.

**Comment by faxm0dem** [comment]
:+1:

**Comment by ldegio** [comment]
commit fe793d01e981459ad00c2130c90c448d4b4459b4 changes the behavior in the following way: now  backspace **always** brings you back to the previous view, no matter if the last view change was generated by F2 or by a drill down.

I think this is what you guys expect, let me know if I'm still missing something.
