### ISSUE TITLE
sysdig fails to build from source

### ISSUE THREAD

**Issue by hlieberman** [draios/sysdig#584]
Hello!

It seems both 0.8.0 and 0.9.0 are currently failing to build from source in Debian unstable -- it looks like userspace/libsinsp/cursesspectro.cpp and userspace/libsinsp/filterchecks.cpp don't #include <math.h>.

A patch is attached to fix this.
[0001-fix-import.patch.txt](https://github.com/draios/sysdig/files/235671/0001-fix-import.patch.txt)

**Comment by gianlucaborello** [comment]
I believe this was fixed this morning: https://github.com/draios/sysdig/commit/1f905597e614929d8bc131050a6ffb70219f3d07

Do you agree with the fix?

Thanks

**Comment by hlieberman** [comment]
On April 25, 2016 8:32:23 PM EDT, Gianluca Borello <notifications@github.com> wrote:
>I believe this was fixed this morning:
>https://github.com/draios/sysdig/commit/1f905597e614929d8bc131050a6ffb70219f3d07
>
>Do you agree with the fix?
>
>Thanks
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/draios/sysdig/issues/584#issuecomment-214572114

Yup, that looks good to me!
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by gianlucaborello** [comment]
Great, I'll close this one then
