### ISSUE TITLE
Segmentation fault:11 on OSX for many actions.

### ISSUE THREAD

**Issue by tillt** [draios/sysdig#588]
Just recently started playing for sysdig and am getting plenty of segfaults unfortunately.

On CoreOS I installed sysdig 0.9.0 via docker. On OSX, I installed sysdig 0.8.0 via brew. 

One example; I captured about 100mb of zipped events  on CoreOS 

```
$ sysdig -s 4096 -z -w session4.scap.tar.gz
```

which I am now trying to analyse on OSX.
```
$ sysdig -c bottlenecks -r session4.scap.tar.gz
Segmentation fault: 11
```

Right now I am assuming the problem lies within the version discrepancy (capture via 0.9.0 and analysis via 0.8.0) so I went ahead and tried to build sysdig 0.9.0 on OSX which unfortunately did not work out of the box even after installing ncurses 6.0. I tried the latter as the bundled version did not build for me. Seems there is a bit more tingling needed to achieve what I want, which is analyzing an scap on OSX.

Any pointers?

**Comment by ldegio** [comment]
Could you share the trace file so I can try to replicate this locally?

**Comment by tillt** [comment]
Sure thing - please send a mail to till@mesosphere.io, I'll provide you with the link in return.

**Comment by luca3m** [comment]
The issue looks related to the fact that the capture was made with sysdig 0.9.0 which has support for Mesos and some fixes inside the scap format. So the 0.8.0 it's not able to read it properly.

In general we support new versions reading old file but not the opposite. So upgrading to 0.9.0 should fix it for you. If it's not feel free to reopen the issue.

**Comment by tillt** [comment]
Thanks a lot for looking into it that nice and quickly. I wish the brew formula was updated to 0.9.0 for a convenient update/install -- will keep an eye on brew updates.
