### ISSUE TITLE
sysdig assertion failure when evt.res can't be resolved

### ISSUE THREAD

**Issue by mstemm** [draios/sysdig#598]
In one of the docker-compose files I've been using for falco testing, the result from a call to clone is -513 (which shouldn't happen from my reading of clone(), but it's there):

```
2215327 15:13:37.217888690 0 docker (531) > clone
2215328 15:13:37.219435808 0 docker (531) < clone res=-513 exe= args= tid=531(docker) pid=17116(docker) ptid=1(systemd) cwd=/ fdlimit=1048576 pgft_maj=0 pgft_min=28599 vm_size=893864 vm_rss=64092 vm_swap=4 comm=docker cgroups=cpuset=/system.slice.cpu=/system.slice.cpuacct=/system.slice.blkio=/system.sl... flags=0 uid=0 gid=0 vtid=531(docker) vpid=17116(docker)
```

If I run sysdig on this trace file with a filter `sysdig -r ../../falco/test/traces-negative/docker-compose.scap evt.res = EACCESS` in debug mode, I get an assertion failure:

```
sysdig -r ../../falco/test/traces-negative/docker-compose.scap evt.res = EACCESS
sysdig: /mnt/sf_mstemm/work/src/sysdig/userspace/libsinsp/filterchecks.cpp:3287: virtual uint8_t* sinsp_filter_check_event::extract(sinsp_evt*, uint32_t*): Assertion `resolved_argstr != __null && resolved_argstr[0] != 0' failed.
Aborted (core dumped)
```

Here's the relevant code:

```
ASSERT(pi->m_len == sizeof(int64_t));

int64_t res = *(int64_t*)pi->m_val;
if(res >= 0)
{
    *len = sizeof("SUCCESS");
    return (uint8_t*)"SUCCESS";
}
else
{
    argstr = evt->get_param_value_str("res", &resolved_argstr);
    ASSERT(resolved_argstr != NULL && resolved_argstr[0] != 0);

    if(resolved_argstr != NULL && resolved_argstr[0] != 0)
    {
       return (uint8_t*)resolved_argstr;
    }
    else if(argstr != NULL)
    {
       return (uint8_t*)argstr;
    }
}
```

The raw value of res cast to an int64_t is -12, btw.

It seems like the assertion should be removed as the if handles that case.

**Comment by gianlucaborello** [comment]
We put many of those assertions even for conditions that get actually handled within the code, just to point out that something is "likely" wrong when we run in debug. In this case, the assert might be good since -513 is weird. Are you able to replicate it live? If so, what does strace show?

**Comment by mstemm** [comment]
Ok that reasoning makes sense. I'll go back and see if I can reproduce why the clone result was -513.

**Comment by mstemm** [comment]
I've tried running the docker-compose test in a loop for 10 or so iterations with a live sysdig, and wasn't able to reproduce the problem. And you gave a good reason why we want to keep the debug asserts, so I'll close this.
