### ISSUE TITLE
Mouse not functional in v0.9.0

### ISSUE THREAD

**Issue by hagfelsh** [draios/sysdig#599]
Hello,

I just discovered this incredible tool!  I've been fooling around with all the views and such and discovered that clicking on the screens of the application has no effect whatsoever.  I've tried it in BitVise & PuTTY terminals as well as on the MATE terminal within the GUI.  These three all provide no interactivity to csysdig at all.

I suspect I've got something wrong somewhere... Can anyone here point me in the right direction?

TERM=xterm
CentOS 7.1.1503
dkms version 2.2.0.3-30.git.7c3e7c5.el7
ncurses 5.9-13.201305011.el7

Thank you for your help!

**Comment by ldegio** [comment]
Could you try to build from the dev branch, run csysdig with the force-term-compat flag

`./csysdig --force-term-compat`

and tell me if it works better?

**Comment by hagfelsh** [comment]
Will do, I'll let you know what I get!

**Comment by ldegio** [comment]
Closing this since I didn't hear negative feedback. Feel free to reopen in case it doesn't work.

**Comment by axot** [comment]
Does mouse functional in OSX? I got Mouse Input not supported in this terminal with --force-term-compat flag.
