### ISSUE TITLE
Sysdig for EL5

### ISSUE THREAD

**Issue by Rydekull** [draios/sysdig#60]
sysdig seems quite excellent, the problem I see is that since I work on a plethora of platforms one of the more commonly used (sadly) is still EL5. 

As such, I'd love to see sysdig available for EL5, is this possible?

**Comment by zatricky** [comment]
CloudLinux 5 servers using a "Hybrid" kernel currently run 2.6.32 - there are probably a lot of these about.

control10 httpdocs # uname -r
2.6.32-531.23.3.lve1.2.66.el5h.x86_64
control10 httpdocs # cat /etc/*release | sort | uniq
CloudLinux Server release 5.10 (Georgy Beregovoy)
control10 httpdocs #

**Comment by gianlucaborello** [comment]
Then it should be doable, you might just have to upgrade GCC (which can live in a sandbox), see if this helps:

https://groups.google.com/d/msg/sysdig/paSm6vFkg-I/lzTqgT5MmzEJ
