### ISSUE TITLE
Compilation error container.cpp no emplace field

### ISSUE THREAD

**Issue by rscipien** [draios/sysdig#605]
Hi

I have just downloaded sysdig and I have compilation error in [container.cpp](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/container.cpp#L639-L642), [user_event.cpp](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/user_event.cpp#L102-L114) 
No emplace. After commenting emplace project was compiled. Unfortunately insmode sysdig-probe.ko give error Error: could not insert module sysdig-probe.ko: Operation not permitted. It may be connected with this commented lines ?

**Comment by luca3m** [comment]
Are you root whey you try to insert the module? Those lines should not be commented out, can you use a newer GCC that fully supports C++11?

**Comment by rscipien** [comment]
I have changed gcc to 4.8 and compilation went smooth. I have still problem with loading sysdig module but it is probably connected with custom kernel. Thanks for help. In [Wiki page](https://github.com/draios/sysdig/wiki/How%20to%20Install%20Sysdig%20from%20the%20Source%20Code) min gcc version is > 4.4.

**Comment by gianlucaborello** [comment]
Updated the wiki.
