### ISSUE TITLE
Regression tests are failing on Mac build

### ISSUE THREAD

**Issue by ltagliamonte** [draios/sysdig#614]
Using `BUILD_TYPE=Release` the regression tests are failing on `topports_server` check.
following the steps to replicate the issue. Please be sure to have the following dependency installed:
`cmake, luajit, coreutils` brew installation are fine.
Steps to replicate the issue on Mac:

```
cd /tmp/
mkdir -p sysdig-build
git clone https://github.com/draios/sysdig.git
cd sysdig
git checkout travis-mac-build
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_ZLIB=OFF -DCMAKE_INSTALL_PREFIX=/tmp/sysdig-build
make install
../test/sysdig_trace_regression.sh /tmp/sysdig-build/bin/sysdig /tmp/sysdig-build/share/sysdig/chisels/ travis-mac-build
```

**Comment by aleks-f** [comment]
@ltagliamonte fyi, not done yet, problem is deeper than what's been committed

**Comment by aleks-f** [comment]
@ltagliamonte the `topports_server` script is fixed, now the travis build ails with this error:
```
Done. Your build exited with 1.
/Users/travis/build.sh: line 155: shell_session_update: command not found
```

**Comment by ltagliamonte** [comment]
@aleks-f the build is now passing correctly.
The problem you mentioned is a problem wit the ruby version installed in Travis CI OSX image as you can read [here](https://github.com/travis-ci/travis-ci/issues/6307)
