### ISSUE TITLE
sysdig slow start

### ISSUE THREAD

**Issue by rainliu67** [draios/sysdig#616]
We've installed sysdig on our servers and we are seeing slow work and slow start.

 details below:

> [root@galaxynode build]# sysdig -D
> 06-29 09:21:58.312907 starting live capture
> 
> 1 17:22:44.848771695 2 sysdig (4359) < ioctl res=0 
> 2 17:22:44.848773522 2 sysdig (4359) > ioctl fd=6(<f>/dev/sysdig3) request=7301 argument=18 
> 3 17:22:44.848775800 2 sysdig (4359) < ioctl res=0 
> 4 17:22:44.848775910 3 <NA> (30) > switch next=1027(NetworkManager) pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
> 
> sysdig version: 
> - sysdig -h
>   sysdig version 0.10.1
>   Usage: sysdig [options] [-p <output_format>] [filter]
> 
> [root@galaxynode build]# uname -ar
> Linux localhost.localdomain 3.18.32 #1 SMP Thu May 12 14:11:26 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
> 
> [root@galaxynode build]#  date "+%Y-%m-%d %H:%M:%S" 
> 2016-06-29 17:37:11

**Comment by luca3m** [comment]
Thanks for reporting this issue! Can you please share with us a sysdig capture that replicates this behaviour?

**Comment by rainliu67** [comment]
> read(59, "cel           4108/udp          "..., 4096) = 4096
read(59, "s   # Cedros Fraud Detection Sys"..., 4096) = 4096
read(59, "rvices\nsm-disc         4174/udp "..., 4096) = 4096
read(59, " Protocol\ntrim-event      4322/t"..., 4096) = 4096
read(59, "disc        4371/udp            "..., 4096) = 4096
read(59, "           # L-ACOUSTICS managem"..., 4096) = 4096
read(59, "  # MIH Services\nieee-mih       "..., 4096) = 4096
read(59, "ice\nmmaeds          4668/udp    "..., 4096) = 4096
read(59, "ux          4728/tcp            "..., 4096) = 4096
read(59, "         # OPC UA TCP Protocol\nq"..., 4096) = 4096
read(59, "             # Equitrac Office\ne"..., 4096) = 4096
read(59, "onpsocket       5014/udp        "..., 4096) = 4096
read(59, " # STANAG-5066-SUBNET-INTF\nauthe"..., 4096) = 4096
read(59, "# MyCTS server port\nrmonitor_sec"..., 4096) = 4096
read(59, "t           5234/tcp            "..., 4096) = 4096
read(59, "     # opalis-rbt-ipc\nopalis-rbt"..., 4096) = 4096
read(59, " # Salient User Manager\nsalient-"..., 4096) = 4096
read(59, "ker   5465/tcp                # "..., 4096) = 4096
read(59, "     # A3-SDUNode\na4-sdunode    "..., 4096) = 4096
read(59, "video\nprosharedata    5715/tcp  "..., 4096) = 4096
read(59, "\nnetagent        5771/tcp       "..., 4096) = 4096
read(59, "tcp                # WBEM Export"..., 4096) = 4096
read(59, "uch    6117/tcp                #"..., 4096) = 4096
read(59, "er Interface\ngrid            626"..., 4096) = 4096
read(59, "# Business Objects Enterprise in"..., 4096) = 4096
read(59, "td    # BoKS Clntd\nbadm_priv    "..., 4096) = 4096
read(59, "   # Allied Electronics NeXGen\nn"..., 4096) = 4096
read(59, "b Console Admin\nsmc-http        "..., 4096) = 4096
read(59, " Serve Admin\nctdp            702"..., 4096) = 4096
read(59, " UPP Gateway\ndisplay         723"..., 4096) = 4096
read(59, "cp                # OpenView DM "..., 4096) = 4096
read(59, "penXDAS Wire Protocol\nhawk      "..., 4096) = 4096
read(59, "97/tcp                # Propel C"..., 4096) = 4096
read(59, "            # Intuit Entitlement"..., 4096) = 4096
read(59, "          # Check Point Clusteri"..., 4096) = 4096
read(59, " 8300/tcp                # Trans"..., 4096) = 4096
read(59, "-tunnel      8567/udp           "..., 4096) = 4096
read(59, "  # Desktop Data TCP 4: FARM pro"..., 4096) = 4096
read(59, "/udp                # IBM AURORA"..., 4096) = 4096
read(59, "re\nwap-vcal-s      9207/udp     "..., 4096) = 4096
read(59, "\nmphlpdmc        9344/tcp       "..., 4096) = 4096
read(59, "ervice\ncondor          9618/udp "..., 4096) = 4096
read(59, "  # HaloteC Instrument Network\na"..., 4096) = 4096
read(59, "ssaging\nnetiq-endpoint  10113/tc"..., 4096) = 4096
read(59, "p        11110/tcp              "..., 4096) = 4096
read(59, "mserver1   12005/tcp            "..., 4096) = 4096
read(59, "             # Blackmagic Design"..., 4096) = 4096
read(59, "ate Notification\npduncs         "..., 4096) = 4096
read(59, "    # OPSEC CVP\nopsec-ufp       "..., 4096) = 4096
read(59, "Interdevice Interaction discover"..., 4096) = 4096
read(59, "dard\ncaldsoft-backup 22537/tcp  "..., 4096) = 4096
read(59, "trix StorageLink Gateway\nassoc-d"..., 4096) = 4096
read(59, "m      28200/tcp               #"..., 4096) = 4096
read(59, "          # FileNET BPM IOR\nfile"..., 4096) = 4096
read(59, "rt\nsafetynetp      40000/tcp    "..., 4096) = 4096
read(59, "   45678/tcp               # EBA"..., 4096) = 2645
read(59, "", 4096)                      = 0
close(59)                               = 0
munmap(0x7f4385a55000, 4096)            = 0
open("/etc/services", O_RDONLY|O_CLOEXEC) = 59
fstat(59, {st_mode=S_IFREG|0644, st_size=670293, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4385a55000

**Comment by luca3m** [comment]
I was meaning a sysdig capture made with `sysdig -w trace.scap`. By the way from the output you posted (looks like a strace output), there is a lot of activity on `services` file, can you try also if using sysdig with `-N` flag works better? `sysdig -N`

**Comment by rainliu67** [comment]
Yes, much better.Can you tell me why ？Thx

**Comment by rainliu67** [comment]
1. there is no output:

> sysdig -p "%proc.name, %proc.pid, %thread.cpu"   evt.type=procinfo

But  the "sysdig -c topprocs_cpu"  is normal.I read the topprocs_cpu.lua source code, also used the "evt.type=procinfo" filter.

2. After waiting for a long time segfault error occurred

**Comment by rainliu67** [comment]
May I induige in a IittIe advice? 

> The return value of "sysdig.get_thread_table(filter) " should include process state and tcp connection state

**Comment by luca3m** [comment]
1. with -N sysdig does not parse `services` files because port resolution is disabled
2. procinfo is not printed on output because is an internal event
3. about the segafult again if you can manage to send us a tracefile or a stacktrace that can help us to understand the issue
4. you have the fdtable for each thread when you call `sysdig.get_thread_table`

**Comment by rainliu67** [comment]
Well, I mean:

- Linux process states

> PROCESS STATE CODES
   R  running or runnable (on run queue)
   D  uninterruptible sleep (usually IO)
   S  interruptible sleep (waiting for an event to complete)
   Z  defunct/zombie, terminated but not reaped by its parent
   T  stopped, either by a job control signal or because
      it is being traced
   [...]

- Linux TCP Connection state

> TIME_WAIT — The socket is waiting after close for remote shutdown transmission so it may handle packets still in the network
CLOSE_WAIT — The remote side has been shut down and is now waiting for the socket to close
[...]

**Comment by rainliu67** [comment]
another issue

>  sysdig -N  -c graph.lua 
graph.lua chisel error: not enough memory

>  free
              total        used        free      shared  buff/cache   available
Mem:       98721412     7273528    62815688     4274648    28632196    86406172
Swap:       4194300           8     4194292

Is caused by the following code:
> local ttable = sysdig.get_thread_table()

**Comment by luca3m** [comment]
about the first problem about `-N`, we'll fix it soon, related to #814

**Comment by luca3m** [comment]
Fixed on 0.16
