### ISSUE TITLE
Sysdig make fails if there are spaces in the current directory

### ISSUE THREAD

**Issue by itamartal** [draios/sysdig#621]
Trying to build sysdig using the instructions found here: https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code

build fails just after running 'make' with the following error:

```
cd "/var/lib/jenkins/workspace/Build Sysdig/sysdig/build/openssl-prefix/src" && /usr/bin/cmake -E touch "/var/lib/jenkins/workspace/Build Sysdig/sysdig/build/openssl-prefix/src/openssl-stamp/openssl-download"
[  8%] No patch step for 'openssl'
/usr/bin/cmake -E echo_append
/usr/bin/cmake -E touch "/var/lib/jenkins/workspace/Build Sysdig/sysdig/build/openssl-prefix/src/openssl-stamp/openssl-patch"
[  9%] No update step for 'openssl'
/usr/bin/cmake -E echo_append
/usr/bin/cmake -E touch "/var/lib/jenkins/workspace/Build Sysdig/sysdig/build/openssl-prefix/src/openssl-stamp/openssl-update"
[ 10%] Performing configure step for 'openssl'
cd "/var/lib/jenkins/workspace/Build Sysdig/sysdig/build/openssl-prefix/src/openssl" && ./config shared "--prefix=/var/lib/jenkins/workspace/Build Sysdig/sysdig/build/openssl-prefix/src/openssl/target"
Operating system: x86_64-whatever-linux2
Configuring for linux-x86_64
target already defined - linux-x86_64 (offending arg: external)
make[2]: *** [openssl-prefix/src/openssl-stamp/openssl-configure] Error 255
make[2]: Leaving directory `/var/lib/jenkins/workspace/Build Sysdig/sysdig/build'
make[1]: *** [CMakeFiles/openssl.dir/all] Error 2
make[1]: Leaving directory `/var/lib/jenkins/workspace/Build Sysdig/sysdig/build'
make: *** [all] Error 2
```

when changing directory name to a path without spaces, the build works...

**Comment by kadamvandita** [comment]
Could you give more details on the OS on which you are installing sysdig as the https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code points to different OS. Also some more details on the error.

**Comment by itamartal** [comment]
Following the instructions on a CentOS 6 machine after cloning the repo
under a directory with spaces in the path broke the make procedure.
Renaming the path fixed it. It was a long time ago but i can try and
reproduce it.

**Comment by kadamvandita** [comment]
Could you give more details on the steps so that I can reproduce it from my side

**Comment by urihershgc** [comment]
hey @kadamvandita 
it happens whenever you compile sysdig using the make file if the folder you're compiling from has spaces.
you can reproduce it by compiling from a folder you named with a space.
for example - "folder name"
you can do it with the command `mkdir "folder name"` and then run the `make`.
