### ISSUE TITLE
docker for mac - The paths /boot and /lib/modules are not shared from OS X and do not belong to the system.

### ISSUE THREAD

**Issue by krasi-georgiev** [draios/sysdig#637]
Is this the correct command when running in docker for mac ?

docker run -i -t --name sysdig --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro sysdig/sysdig

I get the error in the title

**Comment by nmcalabroso** [comment]
+1 to this

**Comment by aleks-f** [comment]
@krasimir-georgiev, see [How to Install Sysdig for Windows and OSX](https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-for-Windows-and-OSX)

**Comment by krasimir-georgiev** [comment]
so no need to run it inside a container ?

**Comment by luca3m** [comment]
You can run sysdig on mac but without capture support, you can only read file captured on linux hosts.

Otherwise to run sysdig on embedded linux machine inside docker4mac, you can try this repo: https://github.com/fdebonneval/mobydig. This is not official supported right now

**Comment by saada** [comment]
What do we need to do to have official support for Docker4Mac?

**Comment by etown** [comment]
A while ago, when docker for Mac came out, I was able to build the kernel probe for alpine and install it without a problem. 

To add support you would only need to:
1. Add the build to the kernel crawler
2. In the sysdig container image check if it's moby, and if it is download the precompiled probe and install it

**Comment by etown** [comment]
See this:
https://github.com/etown/install-sysdig-module/blob/master/Dockerfile

**Comment by krasi-georgiev** [comment]
the problem is not the kernel but the fact that docker for mac doesn't allow mounting folder from the moby vm

https://github.com/etown/install-sysdig-module/issues/4

**Comment by krasi-georgiev** [comment]
I will comment in the other ossue so closing this one.

**Comment by saada** [comment]
@krasi-georgiev the other issue was closed. Has this issue been resolved then?
