### ISSUE TITLE
csysdig F1-F5 not working in Ubuntu 16.04.1 tty

### ISSUE THREAD

**Issue by shemgp** [draios/sysdig#639]
The function keys F1-F5 are not working in Ubuntu 16.04.1 when running csysdig in the console.  Take note, it does work in gnome-terminal but not in the tty consoles.  Using 0.11.0.

**Comment by jrmain** [comment]
Confirmed. Running Ubuntu 16.04.1 and sysdig/csysdig 0.8.0. In my case, the function keys from F1 to F5 don't work, but the arrow keys also don't work. And the screen formatting is messed up. I don't see any of these problems on Ubuntu 12.04, and I don't see these problems with HTOP on Ubuntu 16.04.1.

**Comment by mstemm** [comment]
Did some more diagnosis with jrmain via public slack. Same problem appears in csysdig 0.12.0. Switching to a different ssh client like putty worked, if you additionally change function key handling to vt100+ (see attached screenshot).
<img width="455" alt="screen shot 2016-11-14 at 1 54 32 pm" src="https://cloud.githubusercontent.com/assets/13422831/20285469/efcf6b08-aa76-11e6-8aeb-ad836b700aea.png">

**Comment by hatifnatt** [comment]
Same problem with minor difference, F1-F4 doesn't work, other F-keys work fine.
Ubuntu 16.04.2 LTS
sysdig 0.8.0-1
Switching Putty to VT100+ helps with F1-F4 but breaks other F-keys.

**Comment by gildean** [comment]
The correct option is not VT100+ but Xterm R6. [See related bug](https://bugs.launchpad.net/ubuntu/+source/screen-profiles/+bug/317550)
