### ISSUE TITLE
installation fails on grsec kernel

### ISSUE THREAD

**Issue by deathtrip** [draios/sysdig#644]
when trying to install sysdig on Arch Linux i get this during a kernel upgrade:

==> dkms install -m sysdig -v 0.11.0 -k 4.6.5.201607312210-1-grsec
Error! Bad return status for module build on kernel: 4.6.5.201607312210-1-grsec (x86_64)
Consult /var/lib/dkms/sysdig/0.11.0/build/make.log for more information.

The make.log file reports this:

make: Entering directory '/usr/lib/modules/4.6.5.201607312210-1-grsec/build'
  LD      /var/lib/dkms/sysdig/0.11.0/build/built-in.o
make[1]: **\* No rule to make target '/var/lib/dkms/sysdig/0.11.0/build/main.o', needed by '/var/lib/dkms/sysdig/0.11.0/build/sysdig-probe.o'.  Stop.
make: **\* [Makefile:1437: _module_/var/lib/dkms/sysdig/0.11.0/build] Error 2
make: Leaving directory '/usr/lib/modules/4.6.5.201607312210-1-grsec/build'

**Comment by gianlucaborello** [comment]
How did you install sysdig on arch? Seems more of a packaging issue. Are you able to try and clone the repository and build the driver following these steps? https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code

You can also just limit the steps of the document to `make driver` once you correctly call cmake.

**Comment by deathtrip** [comment]
I'll try installing from source once i get back home.
I installed it from the official arch repositories.
Would the eventual packaging issue be with sysdig, dkms or linux-grsec-headers package?

**Comment by Daiquiry** [comment]
I had this problem also, grsec has a incompatible option with sysdig, check if you have activated with make menuconfig
 -> Security options               
   -> Grsecurity                   
     -> Grsecurity (GRKERNSEC [=y])
       -> Customize Configuration  
         -> Memory Protections     
Deny reading/writing to /dev/kmem, /dev/mem, and /dev/port

if so, desactivate it and re-enable tracers at kernel hacking, which won't appear until the memory protection from grsec it's desactivated.
now you should have on .config this options activated

CONFIG_TRACEPOINTS
CONFIG_HAVE_SYSCALL_TRACEPOINTS

which are a requirement for sysdig to work.

**Comment by deathtrip** [comment]
Now that grsec has gone private a long time ago, i'll go ahead and close this one. As not many people will encounter this problem, even if it's still there.
