### ISSUE TITLE
data is missing in some listen events

### ISSUE THREAD

**Issue by urihershgc** [draios/sysdig#645]
some data is missing in "listen" events, depending on the used filters.
I'm running a listening process with the command `nc -l -p 12345`

when I run sysdig with filtering only "listen" events `sysdig --json  "evt.type in ('listen')"` I get:
```
{"evt.cpu":0,"evt.dir":">","evt.info":"fd=3(<4>) backlog=1 ","evt.num":1379,"evt.outputtime":1470733556584455839,"evt.type":"listen","proc.name":"nc","thread.tid":27990},
{"evt.cpu":0,"evt.dir":"<","evt.info":"res=0 ","evt.num":1380,"evt.outputtime":1470733556584485824,"evt.type":"listen","proc.name":"nc","thread.tid":27990}
```

when I run sysdig with filtering both "listen" and "bind" events `sysdig --json  "evt.type in ('listen', 'bind')"` I get:
```
{"evt.cpu":0,"evt.dir":">","evt.info":"fd=3(<4>) ","evt.num":1266,"evt.outputtime":1470733568423507661,"evt.type":"bind","proc.name":"nc","thread.tid":27992},
{"evt.cpu":0,"evt.dir":"<","evt.info":"res=0 addr=0.0.0.0:12345 ","evt.num":1267,"evt.outputtime":1470733568423511852,"evt.type":"bind","proc.name":"nc","thread.tid":27992},
{"evt.cpu":0,"evt.dir":">","evt.info":"fd=3(<2>0.0.0.0:12345) backlog=1 ","evt.num":1268,"evt.outputtime":1470733568423515036,"evt.type":"listen","proc.name":"nc","thread.tid":27992},
{"evt.cpu":0,"evt.dir":"<","evt.info":"res=0 ","evt.num":1269,"evt.outputtime":1470733568423523007,"evt.type":"listen","proc.name":"nc","thread.tid":27992}
```

one could see that in the second run I get the right connection tuple (fd.name) in the listen event, which is 

> 0.0.0.0:12345

this data is missing in the first run.

**Comment by gianlucaborello** [comment]
I believe this is expected because you're not using data filters. Essentially, you want the `bind` event to still be processed by the sysdig engine, in order to update the state machine with the proper FD name (in this case the port comes from the `bind` event). Thus, you should use the `-d` flag as shown here:

```
gianluca@sid:~$ sudo sysdig -d evt.type=listen
4601 16:11:04.329034938 1 nc (37174) > listen fd=3(<2>0.0.0.0:12345) backlog=1
4602 16:11:04.329037043 1 nc (37174) < listen res=0
```

Compare with the original:

```
gianluca@sid:~$ sudo sysdig evt.type=listen
2202 16:11:14.105036334 1 nc (37180) > listen fd=3(<4>) backlog=1
2203 16:11:14.105038786 1 nc (37180) < listen res=0
```
