### ISSUE TITLE
Installation script tries to install unsupported EPEL release

### ISSUE THREAD

**Issue by itamartal** [draios/sysdig#650]
When trying to install sysdig using the command:
curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash

the script tries to download the EPEL release RPM package from the path:
http://mirrors.kernel.org/fedora-epel/7/x86_64/e/epel-release-7-5.noarch.rpm
which isn't supported anymore. Need to change it into:
http://mirrors.kernel.org/fedora-epel/7/x86_64/e/epel-release-7-8.noarch.rpm
or use "latest".

**Comment by gianlucaborello** [comment]
Fixed, should go live in the next release.
