### ISSUE TITLE
csysdig filter update weird behaviour

### ISSUE THREAD

**Issue by alexgallotta** [draios/sysdig#651]
When updating the csysdig filter, the `evt.type!=switch` is always repeated and if no filter is specified the curses UI crashes

https://files.slack.com/files-pri/T03A6N692-F25UKAX6E/download/wrong_filter_concatenation.mp4

**Comment by ldegio** [comment]
commit 793c394abe290d3cfbcfd981b2077adebb3f64d4 should fix this issue.
