### ISSUE TITLE
Segmentation fault when filtering by HTTP

### ISSUE THREAD

**Issue by alexgallotta** [draios/sysdig#652]
When using sysdig with the following commandline
```
sysdig fd.proto=HTTP
```
a segmentation fault is generated. It was reproduced on a linux machine with
```
Linux demo-virtual-machine 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
https://files.slack.com/files-pri/T03A6N692-F26S7MTHC/download/seg-fault.mp4

**Comment by ldegio** [comment]
194813bfddb67b75701588437cec111619dc0b55 should fix this.

BTW, you should use 'http' (lower case)
