### ISSUE TITLE
Segmentation Fault when looking at networking

### ISSUE THREAD

**Issue by cookandy** [draios/sysdig#654]
Hello,

I'm running sysdig `0.11.0` on Ubuntu 16 and am having trouble drilling down into the networking section of my container:

1. `csysdig -r log.scap`
2. Views -> Containers
3. Select nginx
4. Views -> Connections
5. Select any connection

csysdig will quit with a `segmentation fault (core dumped)` error.

I have attached a sample trace file below:

[log.scap.zip](https://github.com/draios/sysdig/files/458075/log.scap.zip)

Any ideas?

**Comment by luca3m** [comment]
It looks is failing [here](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/viewinfo.cpp#L291). For all the views that don't have an `is_key` column and a drilldown target, for example also *Files Open List*.

**Comment by ldegio** [comment]
commit ee01b9b025bcbe4aee5b024a3fc9f84ee2c3c707 should solve this issue. I'm essentially preventing drill down from list views, since they don't have a key column and therefore drill down from them is ambiguous and not supported.
