### ISSUE TITLE
Csysdig crash when inspecting new connection from trace file

### ISSUE THREAD

**Issue by mstemm** [draios/sysdig#668]
Found during ccwfs:

From the ccwfs zip file at http://go.sysdig.com/ccwfs-captures, open trace01.scap in csysdig. open "new connections" view, filter connections containing `sshd`, dig into first item.

csysdig reliably crashes.

Thanks for finding this nate rook!

**Comment by n-rook** [comment]
No problem, thanks for being so responsive!

**Comment by mstemm** [comment]
It looks like this was fixed in sysdig 0.12.0, which we released last week. I believe this commit https://github.com/draios/sysdig/commit/ee01b9b025bcbe4aee5b024a3fc9f84ee2c3c707 has the fix.

Could you try again with 0.12.0 and make sure the crash is gone for you as well?

**Comment by n-rook** [comment]
Yep, looks like it's fixed!
