### ISSUE TITLE
Executables in 0.12.0 are missing link dependency when linking against external OpenSSL

### ISSUE THREAD

**Issue by hhoffstaette** [draios/sysdig#669]
> $cmake -DUSE_BUNDLED_DEPS=OFF .. && make -j8
> ..
> [ 89%] Linking CXX executable csysdig
> /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../libsinsp/libsinsp.a(k8s_handler.cpp.o): undefined reference to symbol 'SSL_CTX_use_PrivateKey_file'
> /usr/lib64/libssl.so.1.0.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

The same for sysdig (csysdig is just the first failure).
Sure enough (temporarily) adding `-lssl -lcrypto` to the generated `<build>/userspace/sysdig/CMakeFiles/[c]sysdig.dir/link.txt` makes the link succeed. This indicates that OpenSSL should be a proper link dependency for the executables in `/userspace/sysdig/CMakeLists.txt`.

Curiously enough this didn't seem to be the case in 0.11 either, but worked anyway; apparently the openssl references in the new k8s modules in 0.12's libsinsp.a seem to go unsatisfied for some reason.

**Comment by ronin13** [comment]
@hhoffstaette  This is fixed with my pull request which was merged yesterday. https://github.com/draios/sysdig/pull/672

**Comment by hhoffstaette** [comment]
@ronin13 Indeed! Added the patch to my local Gentoo package and everything builds & works out of the box with completely unbundled dependencies. Thanks! :+1:

**Comment by hhoffstaette** [comment]
Closing since it's fixed with commit 8763adc.
