### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by djc2k** [draios/sysdig#677]
While porting sysdig to s390x, I got an error from "Building LuaJIT 2.0.3":
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"

Since LuaJIT does not support s390x yet, are there any workarounds for this problem?
Is there a way to build sysdig with Lua?

**Comment by luca3m** [comment]
You can try with Lua or by disabling chisels and curses interface. There are defines to do it.

**Comment by djc2k** [comment]
Where are the defines for disabling chisels and curses interfaces?

**Comment by luca3m** [comment]
`CSYSDIG` and `HAS_CHISELS`. You can disable them [here](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/settings.h)

**Comment by djc2k** [comment]
I undef these 2 but make still tried to download and build LuaJIT - see attached.
[makeoutput.zip](https://github.com/draios/sysdig/files/568029/makeoutput.zip)

**Comment by djc2k** [comment]
Hi any updates?  
Also I have ported Lua on s390x.  Can someone show me how to build with Lua instead of LuaJIT?

**Comment by luca3m** [comment]
I think you should hack our [CMakefile](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/CMakeLists.txt) of sinsp to do it. If it succeedes, just make it optional so we can use lua on non x86 platform instead of luajit

**Comment by vielmetti** [comment]
@djc2k  any success with the CMakefile changes? Running into a similar issue for aarch64.

**Comment by ketank-new** [comment]
@djc2k : Are you looking to build sysdig with luajit that has  s390x support on s390x platform?
Do let me know i can share inputs as i have tried this out

**Comment by djc2k** [comment]
@ketank-new : yes, were you able to build LuaJIT on s390x?

**Comment by ketank-new** [comment]
@djc2k : yes you can refer the below recipe
https://github.com/linux-on-ibm-z/docs/wiki/Building-LuaJIT

**Comment by djc2k** [comment]
@ketank-new : Thanks, I was able to build LuaJIT; but got other errors when building sysdig.  I changed 
the USE_BUNDLED_LUAJIT option to OFF in CMakeLists.txt.  Now I got the following errors from make:

[ 43%] Linking C static library libscap.a
[ 43%] Built target scap
Scanning dependencies of target sinsp
[ 43%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/chisel.cpp.o
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:125:1: error: elements of array ‘const luaL_reg ll_sysdig []’ have incomplete type
 };
 ^
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:125:1: error: storage size of ‘ll_sysdig’ isn’t known
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:136:1: error: elements of array ‘const luaL_reg ll_chisel []’ have incomplete type
 };
 ^
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:136:1: error: storage size of ‘ll_chisel’ isn’t known
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:146:1: error: elements of array ‘const luaL_reg ll_evt []’ have incomplete type
 };
 ^
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:146:1: error: storage size of ‘ll_evt’ isn’t known
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp: In static member function ‘static bool sinsp_chisel::init_lua_chisel(chisel_desc&, const string&)’:
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:949:27: error: ‘lua_open’ was not declared in this scope
  lua_State* ls = lua_open();
                           ^
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:960:41: error: ‘luaL_openlib’ was not declared in this scope
  luaL_openlib(ls, "sysdig", ll_sysdig, 0);
                                         ^
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp: In member function ‘void sinsp_chisel::load(std::__cxx11::string)’:
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:1190:18: error: ‘lua_open’ was not declared in this scope
  m_ls = lua_open();
                  ^
/home/firstuser/sysdig/userspace/libsinsp/chisel.cpp:1197:43: error: ‘luaL_openlib’ was not declared in this scope
  luaL_openlib(m_ls, "sysdig", ll_sysdig, 0);
                                           ^
userspace/libsinsp/CMakeFiles/sinsp.dir/build.make:62: recipe for target 'userspace/libsinsp/CMakeFiles/sinsp.dir/chisel.cpp.o' failed
make[2]: *** [userspace/libsinsp/CMakeFiles/sinsp.dir/chisel.cpp.o] Error 1
CMakeFiles/Makefile2:741: recipe for target 'userspace/libsinsp/CMakeFiles/sinsp.dir/all' failed
make[1]: *** [userspace/libsinsp/CMakeFiles/sinsp.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ketank-new** [comment]
@djc2k : i am pasting link to sysdig recipe , this provides you build steps for s390x across some distributions mentioned in receipe, please follow this and let me know if the build still breaks for you
https://github.com/linux-on-ibm-z/docs/wiki/Building-sysdig?cm_mc_uid=64949984861314847441935&cm_mc_sid_50200000=1489589980

Note: Since you are trying to build sysdig with LuaJIT, in step no 3 in recipe use 
- cmake ..  instead of cmake cmake -DUSE_BUNDLED_LUAJIT=OFF ..

**Comment by djc2k** [comment]
@ketank-new : I'm still getting these errors:

[ 43%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/chisel.cpp.o
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:125:1: error: elements of array ‘const luaL_reg ll_sysdig []’ have incomplete type
 };
 ^
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:125:1: error: storage size of ‘ll_sysdig’ isn’t known
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:136:1: error: elements of array ‘const luaL_reg ll_chisel []’ have incomplete type
 };
 ^
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:136:1: error: storage size of ‘ll_chisel’ isn’t known
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:146:1: error: elements of array ‘const luaL_reg ll_evt []’ have incomplete type
 };
 ^
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:146:1: error: storage size of ‘ll_evt’ isn’t known
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp: In static member function ‘static bool sinsp_chisel::init_lua_chisel(chisel_desc&, const string&)’:
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:949:27: error: ‘lua_open’ was not declared in this scope
  lua_State* ls = lua_open();
                           ^
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:960:41: error: ‘luaL_openlib’ was not declared in this scope
  luaL_openlib(ls, "sysdig", ll_sysdig, 0);
                                         ^
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp: In member function ‘void sinsp_chisel::load(std::__cxx11::string)’:
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:1190:18: error: ‘lua_open’ was not declared in this scope
  m_ls = lua_open();
                  ^
/home/firstuser/sysdig-0.15.1/userspace/libsinsp/chisel.cpp:1197:43: error: ‘luaL_openlib’ was not declared in this scope
  luaL_openlib(m_ls, "sysdig", ll_sysdig, 0);
                                           ^
userspace/libsinsp/CMakeFiles/sinsp.dir/build.make:62: recipe for target 'userspace/libsinsp/CMakeFiles/sinsp.dir/chisel.cpp.o' failed
make[2]: *** [userspace/libsinsp/CMakeFiles/sinsp.dir/chisel.cpp.o] Error 1
CMakeFiles/Makefile2:741: recipe for target 'userspace/libsinsp/CMakeFiles/sinsp.dir/all' failed
make[1]: *** [userspace/libsinsp/CMakeFiles/sinsp.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by djc2k** [comment]
The last build was on an Ubuntu 16.04 system.  I just tried the build on an SLES 12 system and got the same errors.

**Comment by ketank-new** [comment]
i could build sysdig v 0.15 .1 on ub 16.04 successfully , using the above recipes of luajit and sysdig.
I would suggest you to overwrite the luajit 2.0 folder within sysdig source with luajit v 2.1 


lujait 2.0 does s390x support

you can send me the steps which u performed to re create the above error logs.

**Comment by djc2k** [comment]
I followed the steps in https://github.com/linux-on-ibm-z/docs/wiki/Building-sysdig?cm_mc_uid=64949984861314847441935&cm_mc_sid_50200000=1489589980

The only thing I changed was in step 4, where I changed Makefile.dkms per instruction:
KERNELDIR               ?= /lib/modules/**4.4.0-77-generic**/build

Note: "4.4.0-77-generic" is the result of "uname -r"

BTW, where's the luajit 2.0 folder in sysdig-0.15.1/ ?

**Comment by ketank-new** [comment]
you will find the luajit 2.0 get downloaded during the "make' step
it gets created with "build" folder

If you would want to luajit 2.1 to get downloaded you will have to make changes to Makefile post "cmake " step.

If you do not want to make changes to make file and just want the driver file created then run the build once( Build will fail saying arch not supported) at this stage you will find luajit 2.0 related folder created within build folder....... replace them with equivalent luajit 2.1 and re run the "make"

**Comment by djc2k** [comment]
Thanks.  The first method didn't work for me but the the 2nd method did.   When will s390x be supported in the basic sysdig install ("one step" install)?

**Comment by ketank-new** [comment]
s390x support is now already present in sysdig
the recipe helps you to install sysdig on s390x platform
 https://github.com/linux-on-ibm-z/docs/wiki/Building-sysdig?cm_mc_uid=64949984861314847441935&cm_mc_sid_50200000=1489589980

**Comment by djc2k** [comment]
I understand; even though I had to use the workaround to make it work... I was referring to the install from: http://www.sysdig.org/install/

**Comment by djc2k** [comment]
I found a new issue while building it on an RHEL 7.2 system, at the very last step with the insmod:

[root@rhel-7 driver]# insmod sysdig-probe.ko
insmod: ERROR: could not insert module sysdig-probe.ko: Unknown symbol in module

**Comment by ketank-new** [comment]
This must be Happening because you may have built driver module with kernel version which is higher than the running kernel version on the host, on which you are trying to insmod <driver.ko>

Make sure Host has a running kernel higher than the kernel used while building driver module
