### ISSUE TITLE
Build failed on SLES 12 SP1: make[4]: *** /lib/modules/3.12.49-1-default/build: No such file or directory.  Stop.

### ISSUE THREAD

**Issue by djc2k** [draios/sysdig#680]
Got an error from make on an SLES 12 SP1 running on AWS.  Attached is the make output.
[makeout.zip](https://github.com/draios/sysdig/files/577220/makeout.zip)

Environment - output from uname -a:
Linux ip-172-31-12-131.us-west-2.compute.internal 3.12.49-1-default #1 SMP Fri Dec 11 11:36:56 UTC 2015 (6571a4b) x86_64 x86_64 x86_64 GNU/Linux

Errors from make:

[ 40%] Built target zlib
Scanning dependencies of target configure_driver
[ 40%] Built target configure_driver
Scanning dependencies of target driver
make[4]: *** /lib/modules/3.12.49-1-default/build: No such file or directory.  Stop.
Makefile:9: recipe for target 'all' failed
make[3]: *** [all] Error 2
driver/CMakeFiles/driver.dir/build.make:52: recipe for target 'driver/CMakeFiles/driver' failed
make[2]: *** [driver/CMakeFiles/driver] Error 2
CMakeFiles/Makefile2:361: recipe for target 'driver/CMakeFiles/driver.dir/all' failed
make[1]: *** [driver/CMakeFiles/driver.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sbahling** [comment]
You need to install the kernel-default-devel package to build kernel modules.

**Comment by ketank-new** [comment]
After installing  kernel-default-devel packages you might also have to create a soflink by name 'build' in /lib/modules/<kernel version>/build.
