### ISSUE TITLE
S3 access denied for kernel module

### ISSUE THREAD

**Issue by Fusion** [draios/sysdig#704]
Is that normal? Unable to install sysdig or run the docker container, which seems to make sense when I try this:

    sudo /usr/bin/sysdig-probe-loader

> ...
> Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community

And indeed this is what happens when I try to curl the link:

    curl  https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.13.0-x86_64-4.4.24-rancher-31f99e811d71fcddfcff69bdeb52f64e.ko

> <?xml version="1.0" encoding="UTF-8"?>
> <Error>< Code >AccessDenied< /Code ><Message>Access Denied</Message><RequestId>3EACC47AD15B964B</RequestId><HostId>Szd4d7iXoBp/uy4Y1nO/oxLpsMXmSeBQozOyecEj8OroViKIXV7Sf4LHsHkXf9KzFJEZxbX5qP0=</HostId></Error>

**Comment by luca3m** [comment]
It looks kernel headers are not installed in your system. Please install them and try again. The download fails because we don't precompile binaries for RancherOS.
