### ISSUE TITLE
TLSv1_2_client_method(void) deprecated in OpenSSL 1.1

### ISSUE THREAD

**Issue by hlieberman** [draios/sysdig#707]
FYI, when building sysdig against OpenSSL >= 1.1, we're now seeing build warnings that TLSv1_2_client_method() is deprecated.  According to the docs, all of the version specific methods were deprecated as of 1.1.  I don't know whether they're planning on removing them (will check with one of my co-workers who is an OpenSSL core dev when I get back from vacation), but it's something that will probably need fixing /eventually/.

**Comment by aleks-f** [comment]
fix is on the way, currently under review and test ...

**Comment by aleks-f** [comment]
Fix for this particular issue is in dev branch now. However, libcurl < 7.48 also fails to build with OpenSSL 1.1, so the compete fix will be in once #709 is merged.
