### ISSUE TITLE
csysdig doesn't show nicely in tmux

### ISSUE THREAD

**Issue by gianlucaborello** [draios/sysdig#716]
In tmux:

<img width="1643" alt="screen shot 2017-01-11 at 7 20 58 pm" src="https://cloud.githubusercontent.com/assets/4187028/21875772/3a0c72da-d833-11e6-9c3b-bad0c14ae70d.png">

Outside tmux:

<img width="1636" alt="screen shot 2017-01-11 at 7 21 18 pm" src="https://cloud.githubusercontent.com/assets/4187028/21875774/3ed8f680-d833-11e6-9d00-57e83ec4b019.png">

Also, the mouse doesn't work in tmux, but it works fine with other programs (e.g. htop) ran in tmux.

**Comment by faxm0dem** [comment]
Off the top of my head this is related to BCE, which tmux doesn't support

**Comment by faxm0dem** [comment]
[✅] I'm not a robot
