### ISSUE TITLE
proc.name/proc.pname don't handle arguments with spaces in them

### ISSUE THREAD

**Issue by mstemm** [draios/sysdig#718]
@gianlucaborello noticed some problems with falco handling of tmux and shell spawning. While diagnosing, I found problems with handling of process names with spaces. tmux presumably changes its exe to include its role after startup from "tmux" to either "tmux: client" or "tmux: server".

1. you can't specify a process name/parent process name in a filtering expression with a space:

```
$ sysdig -r trace.scap proc.pname=tmux: client
syntax error in filter at position 17
$ sysdig -r trace.scap proc.name=tmux: client
syntax error in filter at position 16
$ sysdig -r trace.scap "proc.pname in (tmux: client, tmux)"
expected either ')' or ',' after a value inside the 'in/pmatch' clause
```

2. When creating parent process information for a process spawned by "tmux: xxx", the parent process information is truncated:

```
$ sysdig -r trace.scap evt.type=execve -p "*%evt.num %evt.outputtime %evt.cpu %proc.name parent=%proc.pname %evt.dir %evt.type"
470 12:15:34.628604411 0 tmux: server parent=tmux: > execve
503 12:15:34.630097658 1 sh parent=tmux: < execve
```

Note how the shell execve()d by "tmux: server" thinks its parent is "tmux:"

Trace file attached.
[trace.scap.zip](https://github.com/draios/sysdig/files/702978/trace.scap.zip)

**Comment by karastojko** [comment]
Will check the second part and how it can be fixed.

**Comment by mstemm** [comment]
For #1, the command line works if you're careful about escaped/nested quotes, so once the process information is no longer truncated the rest should work.

**Comment by karastojko** [comment]
Confirmed that 2) works fine with the fix https://github.com/draios/sysdig/pull/827.
