### ISSUE TITLE
Sinsp crashes when compiling without -DHAS_CAPTURE flag. 

### ISSUE THREAD

**Issue by arossert** [draios/sysdig#724]
When linking and using sinsp class under linux on my program, i compiled the sysdig without -DHAS_CAPTURE and the program crash when deleting the sinsp object.

sample program:

```
#include <sinsp.h>

int main() {
    sinsp *inspector = new sinsp();
    delete inspector; <-- crashed in this line
}
```

After adding -DHAS_CAPTURE to the compilation the program did not crash.

**Comment by ldegio** [comment]
what version of sysdig are you using?

The most recent dev branch was not compiling with HAS_CAPTURE undefined. https://github.com/draios/sysdig/commit/314b63a04f6b817a447b07130d310f07b46b434d fixes that, but at that point I can't replicate your bug: the code you posted doesn't crash. 

I'm closing it for the moment. If you replicated on dev could you reopen with more details?
