### ISSUE TITLE
Sinsp crashes when compiling without -DHAS_CAPTURE flag (#724)

### ISSUE THREAD

**Issue by arossert** [draios/sysdig#728]
In continue to issue #724, this happens in the DEV branch as well.
Im trying to create shared library of the sysdig (libsysdig.so) and linking to this library.

I'm using this cmake file to create the libsysdig.so
[CMakeLists.txt](https://github.com/draios/sysdig/files/716412/CMakeLists.txt)

After linking to this library the following program crash:
```
#include <sinsp.h>

int main() {
    sinsp *inspector = new sinsp();
    delete inspector; <-- crashed in this line
}
```

This is the error output:
**double free or corruption (out): 0x00000000009671b0**

After debugging the crash happens in ```sinsp_evt::~sinsp_evt()``` when destructing ```std::vector<char>```

**Comment by ldegio** [comment]
Running as shared library is not something sinsp is been developed and tested for. What's the problem with linking it statically like sysdig does? Other than a small increase in the binary size it should be the same and you would avoid these kinds of problems.

**Comment by arossert** [comment]
Static linking has solved this issue.
