### ISSUE TITLE
Program returns random data in a function 

### ISSUE THREAD

**Issue by plusky** [draios/sysdig#734]
While building packages for openSUSE, I have noticed build failure due to possibly random return value:
`no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/sysdig-0.14.0/userspace/libscap/scap_savefile.c:45` 

It seems to be solvable via i.e [following patch](https://build.opensuse.org/package/view_file/devel:tools/sysdig/sysdig-no_return_random.patch?expand=1):

```
Index: userspace/libscap/scap_savefile.c
===================================================================
--- userspace/libscap/scap_savefile.c.orig
+++ userspace/libscap/scap_savefile.c
@@ -42,6 +42,10 @@ int scap_dump_write(scap_dumper_t *d, vo
 	{
 		return gzwrite(d->m_f, buf, len);
 	}
+  else
+  {
+    return -1;
+  }
 }
 
 #ifndef _WIN32
```

**Comment by luca3m** [comment]
Thanks for reporting, we'll solve it on next release
