### ISSUE TITLE
sysdig-probe-loader - Failed

### ISSUE THREAD

**Issue by Asshad** [draios/sysdig#738]
Hi,

Good day to everyone. I have an inquiry regarding on one my Amazon Linux Instances.
I managed to install sysdig by running this command 

#sudo curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
* Detecting operating system
* Installing sysdig public key
* Installing sysdig repository
* Installing kernel headers
Error: Nothing to do
Unable to find kernel development files for the current kernel version 4.4.10-22.54.amzn1.x86_64
This usually means that your system is not up-to-date or you installed a custom kernel version.
The installation will continue but you'll need to install these yourself in order to use sysdig.
Please write to the mailing list at https://groups.google.com/forum/#!forum/sysdig
if you need further assistance.
* Installing sysdig
Package sysdig-0.14.0-1.x86_64 already installed and latest version

Then I'd like to probe, it gave me errors:

#sysdig-probe-loader
* Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms autoinstall
grep: /usr/src/kernels/4.4.10-22.54.amzn1.x86_64/include/generated/compile.h: No such file or directory
CC: /usr/bin/gcc
Error! echo
Your kernel headers for kernel 4.4.10-22.54.amzn1.x86_64 cannot be found at
/lib/modules/4.4.10-22.54.amzn1.x86_64/build or /lib/modules/4.4.10-22.54.amzn1.x86_64/source.
* Trying to load a system sysdig-probe, if present
* Trying to load a dkms sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 4.4.10-22.54.amzn1.x86_64
Found kernel config at /boot/config-4.4.10-22.54.amzn1.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.14.0-x86_64-4.4.10-22.54.amzn1.x86_64-b0shejb61308b11222ffbeshshshsh8b3.ko
Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community

Do you have any suggestions what should I do?

**Comment by luca3m** [comment]
Can you check if you have latest kernel version and headers?

**Comment by Asshad** [comment]
@luca3m Hi Luca, thanks for your prompt reply.

Please refer to the kernel list. Whenever I tried to install the kernel-devel and headers it gave me this error.
No package kernel-devel-4.4.10-22.54.amzn1.x86_64 available

The latest kernel is there, 4.4.41-x-x but I may need to check any particular reasons why it's using the old kernel.

rpm -qa |grep kernel
kernel-4.4.41-35.53.amzn1.x86_64
kernel-tools-4.4.41-36.55.amzn1.x86_64
**kernel-4.4.10-22.54.amzn1.x86_64**
kernel-4.4.41-36.55.amzn1.x86_64

**Comment by Asshad** [comment]
@luca3m Hi Luca, I'll close this case. Thanks for the heads up! 
Cheers!

**Comment by bertocci** [comment]
Amazon is a special case. See https://support.sysdigcloud.com/hc/en-us/articles/204187225-Why-does-the-agent-install-fail-with-Unable-to-find-kernel-development-files- for how to either upgrade or find the old kernel headers.

**Comment by Asshad** [comment]
@bertocci Thanks man.
