### ISSUE TITLE
sysdig crashes when using `evtin` filter

### ISSUE THREAD

**Issue by luca3m** [draios/sysdig#740]
```
2612 12:48:05.037111720 1 python2.7 (26002) > setns fd=13(<f>mnt:[4026531840]) nstype=0
2613 12:48:05.037113186 1 python2.7 (26002) < setns res=0
2614 12:48:05.037114194 1 python2.7 (26002) > setns fd=16(<f>uts:[4026531838]) nstype=0
2615 12:48:05.037114869 1 python2.7 (26002) < setns res=0
2617 12:48:05.037235996 1 python2.7 (26002) < tracer id=26002 tags=checks.redis args=metrics:31,exception:no
[1]    28941 segmentation fault (core dumped)  sysdig -r trace.scap evtin.span.p.arg.pid = 26621
 ~ >
```

To replicate it run:

```
sysdig -r trace.scap evtin.span.p.arg.pid = 26621
```

With this [capture](https://www.dropbox.com/s/76o9o1o0gtiyun6/trace.scap?dl=0)

**Comment by thom-sd** [comment]
This crash occurred in 

#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x0000000000755c0b in sinsp_filter_check_evtin::extract_tracer (
    this=0xf7ade0, evt=0xf43620, pae=0xf47690, len=0x7fffffffd93c)
    at /draios/sysdig/userspace/libsinsp/filterchecks.cpp:5126

where strlen(val) was called when val was NULL.
It was added as part of pull request #737.
Will have a fix shortly.
