### ISSUE TITLE
proc.name not recorded in capture file

### ISSUE THREAD

**Issue by mfischer-zd** [draios/sysdig#745]
It looks like the `proc.name` field is missing from sysdig capture files.  

For example, if I run `sysdig --json fd.port=53`, I get the following (as expected).  Note the `proc.name` field is `ping`.

```
{"evt.cpu":0,"evt.dir":"<","evt.info":"res=0 tuple=10.0.2.15:57854->10.0.2.3:domain ","evt.num":2253,"evt.outputtime":1486051398854929464,"evt.type":"connect","proc.name":"ping","thread.tid":20380}
{"evt.cpu":0,"evt.dir":">","evt.info":"fd=4(<4u>10.0.2.15:57854->10.0.2.3:domain) size=25 tuple=NULL ","evt.num":2256,"evt.outputtime":1486051398854937001,"evt.type":"sendto","proc.name":"ping","thread.tid":20380}
```

Now, if I record that to a capture via `sysdig -w sysdig.cap fd.port=53`, then play it back via `sysdig -r sysdig.cap --json`, the `proc.name` field is `<NA>`:

```
{"evt.cpu":0,"evt.dir":"<","evt.info":"res=0 tuple=10.0.2.15:48856->10.0.2.3:domain ","evt.num":109,"evt.outputtime":1486051330102373709,"evt.type":"connect","proc.name":"<NA>","thread.tid":20375}
{"evt.cpu":0,"evt.dir":">","evt.info":"fd=4 size=25 tuple=NULL ","evt.num":110,"evt.outputtime":1486051330102382695,"evt.type":"sendto","proc.name":"<NA>","thread.tid":20375}
{"evt.cpu":0,"evt.dir":"<","evt.info":"res=25 data=.............mit.edu..... ","evt.num":111,"evt.outputtime":1486051330102476447,"evt.type":"sendto","proc.name":"<NA>","thread.tid":20375}
{"evt.cpu":0,"evt.dir":">","evt.info":"fd=4 request=541B argument=7FFDA0328830 ","evt.num":112,"evt.outputtime":1486051330141017874,"evt.type":"ioctl","proc.name":"<NA>","thread.tid":20375}
```

**Comment by ret2libc** [comment]
Hi! Try to use `-F`/`--fatfile` flag when recording to file. It should fix your problem.
```
 -F, --fatfile      Enable fatfile mode
                    when writing in fatfile mode, the output file will contain
                    events that will be invisible when reading the file, but
                    that are necessary to fully reconstruct the state.
                    Fatfile mode is useful when saving events to disk with an
                    aggressive filter. The filter could drop events that would
                    the state to be updated (e.g. clone() or open()). With
                    fatfile mode, those events are still saved to file, but
                    'hidden' so that they won't appear when reading the file.
                    Be aware that using this flag might generate substantially
                    bigger traces files.
```

**Comment by mfischer-zd** [comment]
Why isn't this the default?  The current behavior violates the Principle of Least Surprise.

**Comment by ret2libc** [comment]
You may not be interested in keeping track of everything, but just of the events you are filtering and, as written in the help, `fatfile` can generate very big capture files. Moreover, it could be surprising also to see the sysdig collecting events that you did not require.

**Comment by mfischer-zd** [comment]
There are two dimensions involved here: the events, which can optionally be filtered (as I am doing in this example), and the fields in the events.

I expect my captures to have all the fields, regardless of the filter.  I understand that if I express a filter that not all events will be logged, but I still expect the fields to be there.  Does that make sense?

**Comment by mfischer-zd** [comment]
@ldegio Can I get a second opinion here, please?

**Comment by ldegio** [comment]
yeah, this is not ideal, but at the same time the fatfile approach has limitations too (For example, it makes it harder to iteratively filter out stuff from captures), so we decided to make it optional.

Another (still not ideal) solution to your problem would be relaxing the filter with something like this

`./sysdig -w lo.scap fd.port=80 or evt.type=execve`
