### ISSUE TITLE
Get actual path of file descriptor

### ISSUE THREAD

**Issue by vrastogi** [draios/sysdig#749]
System calls such as `open` result in file descriptors. Sysdig computes the file path of the file descriptor simply by concatenating the current working directory with the file path specified in the syscall arguments. However, this may include symlinks.

Since symlinks may change over time, a canonical path with all symlinks resolved is better for analyzing logs later on. It may in some situations be possible to carefully track the state of the file system to map symlinked paths to actual paths but this is likely to be error-prone. Can we have this actual, canonical path retrieved directly from the kernel at the time the file descriptor is created?

**Comment by therealbobo** [comment]
Hi @vrastogi! As far as I know this feature has been requested for a long time and there is something moving... (https://github.com/falcosecurity/falco/issues/2203#issuecomment-1559632952). When this feature will make its way in libs, you'll find it in sysdig 😄
