### ISSUE TITLE
Parent thread state results in a loop

### ISSUE THREAD

**Issue by mstemm** [draios/sysdig#752]
https://github.com/draios/falco/issues/208 revealed a problem with our thread state management where a set of processes had a loop in their parent information. This issue tracks fixing whatever is causing the thread state to be corrupted.

The (simpler) task of detecting a loop and breaking rather than getting stuck is handled in https://github.com/draios/sysdig/pull/753.

**Comment by aleks-f** [comment]
@mstemm not sure if this can contribute and whether it makes sense to be done in this pull, but there is another [traversal](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/container.cpp#L173) of the process tree that can be significantly optimized - it is only needed when agent is running on mesos cluster (both slave or master) and can probably additionally be curtailed down to 10 steps max

**Comment by mstemm** [comment]
Sure I will add it to https://github.com/draios/sysdig/pull/753.
