### ISSUE TITLE
Unable to load the driver

### ISSUE THREAD

**Issue by dogeow** [draios/sysdig#763]
> root@sam:~# sysdig
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.

on Ubuntu 16.04

**Comment by ret2libc** [comment]
Could you provide more info? Like how you installed sysdig, what dmesg says, etc.

**Comment by sardpost** [comment]
I experienced the same problem of likunyan on Fedora 25 but now everything works fine. I installed sysdig with these commands:
``
sudo rpm --import https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
sudo curl -s -o /etc/yum.repos.d/draios.repo http://download.draios.com/stable/rpm/draios.repo 
sudo dnf install sysdig

``
After the installation I launched sysdig as root and I got the same error as likunyan. I solved the issue launching **sysdig-probe-loader** from the command line as root and after that everything worked fine.

**Comment by likunyan** [comment]
@ret2libc Thank you.
`curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash`
But something is wrong

> W: The repository 'http://download.draios.com/stable/deb stable-amd64/ Release' does not have a Release file.
E: Failed to fetch http://download.draios.com/stable/deb/stable-amd64/Packages  403  Forbidden [IP: 115.28.122.210 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

So, i use
```
curl -s https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public | apt-key add -
curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/stable/deb/draios.list
apt-get update
apt install sysdig
```

On Ubuntu 16.04.2 LTS, `uname -r` is "kernel 16.044.9.8-040908-lowlatency", I think it should be the release and kernel versions is advanced version.

**Comment by likunyan** [comment]
@sardpost how to launch `sysdig-probe-loader`,

> sysdig-probe-loader: command not found

**Comment by sardpost** [comment]
@likunyan  On my system, Fedora 25, sysdig-probe-loader has been installed along with the sysdig rpm package with sysdig.

**Comment by ketank-new** [comment]
@likunyan : I have faced similar issues while using it on Ubuntu. Problem basically occurs if you have build the sysdig source using certain kernel version , and if you try to load the driver module on to host which has different kernel version , having same kernel version in build and also on the host should solve your problem

**Comment by axiaoxin** [comment]
On my CentOS 7, the problem is simular

```$ sysdig
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

``` $ /usr/lib/dkms/dkms_autoinstaller
Usage: /usr/lib/dkms/dkms_autoinstaller {start}
[root@Tencent-SNG /data/home/ashinchen]# sysdig-probe-loader
* Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms install for sysdig
Error! echo
Your kernel headers for kernel 3.10.107-1-tlinux2-0046 cannot be found at
/lib/modules/3.10.107-1-tlinux2-0046/build or /lib/modules/3.10.107-1-tlinux2-0046/source.
* Trying to load a system sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 3.10.107-1-tlinux2-0046
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.20.0-x86_64-3.10.107-1-tlinux2-0046-3dd0470f9f52a2738df992393a18794f.ko
Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community
```

``` sysdig-probe-loader
* Unloading sysdig-probe, if present
rmmod: ERROR: Module sysdig_probe is not currently loaded
* Running dkms install for sysdig
Error! echo
Your kernel headers for kernel 3.10.107-1-tlinux2-0046 cannot be found at
/lib/modules/3.10.107-1-tlinux2-0046/build or /lib/modules/3.10.107-1-tlinux2-0046/source.
* Trying to load a system sysdig-probe, if present
* Trying to find precompiled sysdig-probe for 3.10.107-1-tlinux2-0046
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/sysdig-probe-0.20.0-x86_64-3.10.107-1-tlinux2-0046-3dd0470f9f52a2738df992393a18794f.ko
Download failed, consider compiling your own sysdig-probe and loading it or getting in touch with the sysdig community
```

```$  rpm -qa |grep kernel
kernel-tlinux2-modules-nat-3.10.107-1.0046.tl2.x86_64
kernel-tools-libs-3.10.0-327.10.1.el7.x86_64
kernel-headers-3.10.0-327.10.1.el7.x86_64
kernel-tlinux2-3.10.107-1.0046.tl2.x86_64
kernel-tlinux2-debuginfo-3.10.107-1.0046.tl2.x86_64
kernel-tools-3.10.0-327.10.1.el7.x86_64
kernel-devel-3.10.0-693.17.1.el7.x86_64
mlnx-ofa_kernel-2.3-OFED.2.3.2.0.5.1.gc2c6d89.rhel7u0.x86_64
```

```$ uname -r
3.10.107-1-tlinux2-0046
```

**Comment by likunyan** [comment]
@axiaoxin use `sudo sysdig -c topprocs_net`. it's ok! so, you must add `sudo`.

**Comment by axiaoxin** [comment]
@likunyan I logged in as root. It's not working. I think the reason is sysdig can't distinguish the name of `tlinux2`?

```
curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash
* Detecting operating system
Unsupported operating system. Please consider writing to the mailing list at
https://groups.google.com/forum/#!forum/sysdig or trying the manual installation.
```

**Comment by likunyan** [comment]
@axiaoxin 天呐，不懂啊。换 Ubuntu 不，我和 wiki 一样换 Ubuntu 了。

**Comment by likunyan** [comment]
@ketank-new 

Sorry, I forgot to reply. What you say is difficult for me. Fortunately, it is normal on Ubuntu 16.04 LTS.Thank you.

**Comment by likunyan** [comment]
@axiaoxin 
`$ whereis sysdig-probe-loader
sysdig-probe-loader: /usr/bin/sysdig-probe-loader
$ /usr/bin/sysdig-probe-loader`
