### ISSUE TITLE
netstat chisel ignores ports presumably binded to ipv6

### ISSUE THREAD

**Issue by ceizner** [draios/sysdig#778]
Let say we are looking for a port 1337 in one of the containers

```
root@ubuntu:~# sudo sysdig -c netstat "'(container.id=dc291357b717 and fd.type=ipv6)'"
Proto Server Address           Client Address           State          TID/PID/Program Name
root@ubuntu:~#
```
So one might think there is nothing listening in port 1337 inside container with id dc291357b717
However let us double-check with more traditional tools:

```
root@ubuntu:~# docker exec -it dc291357b717 bash
root@sysdigcloud-api-2507006246-nvxlk:/# netstat -pant| grep 1337
tcp6       0      0 :::1337                 :::*                    LISTEN      86/node
```

**Comment by mstemm** [comment]
I helped debug this with ceizner and I think the fact that the node process was listening on ipv6 was important. The netstat chisel has a default filter of  `(fd.type=ipv4)`. Obviously changing the filter didn't help, though.
