### ISSUE TITLE
Reading with a custom format %proc.ppid bug

### ISSUE THREAD

**Issue by JohannesTK** [draios/sysdig#788]
Reading a .scap file with a custom format: 

`sysdig -r foo.scap -p"*%evt.datetime %proc.pid %proc.ppid" evt.type=execve`

Gives this output: 

`
2017-03-16 09:22:06.034463980 9393 -1
2017-03-16 09:22:06.040573163 9394 9393  
2017-03-16 09:22:06.040747878 9394 9393  
`

Note the **-1** on the first line. Looks like the %proc.ppid has a bug with reading the parent PID for the first process. 

Reading the foo.scap normally the first process parent PID is displayed correctly: 

`sysdig -r foo.scap evt.type=execve`

`187 09:22:06.034463980 0 blah.sh (9393) < execve res=0 exe=/bin/bash args=./blah.sh. tid=9393(blah.sh) pid=9393(blah.sh) ptid=9391 cwd= fdlimit=1024 pgft_maj=0 pgft_min=14 vm_size=1356 vm_rss=4 vm_swap=0 comm=blah.sh cgroups=cpuset=/.cpu=/user.slice.cpuacct=/user.slice.io=/user.slice.memory=/user.slic... env=LC_PAPER=et_EE.UTF-8.LC_ADDRESS=et_EE.UTF-8.LC_MONETARY=et_EE.UTF-8.TERM=xter... 
896 09:22:06.040573163 1 blah.sh (9394) > execve 
899 09:22:06.040747878 0 ls (9394) < execve res=0 exe=ls args= tid=9394(ls) pid=9394(ls) ptid=9393(blah.sh) cwd= fdlimit=1024 pgft_maj=0 pgft_min=36 vm_size=448 vm_rss=4 vm_swap=0 comm=ls cgroups=cpuset=/.cpu=/user.slice.cpuacct=/user.slice.io=/user.slice.memory=/user.slic... env=LC_PAPER=et_EE.UTF-8.LC_ADDRESS=et_EE.UTF-8.LC_MONETARY=et_EE.UTF-8.SHELL=/bi... 
`

**Comment by karastojko** [comment]
I understand that the following scenario is performed:
- `blah.sh` is created with a single command `ls` executing inside
- `sysdig -w foo.scap` started
- `blah.sh` started

In my case, the same steps give me the correct result. `sysdig -r foo.scap evt.type=execve` prints 
```1407 05:45:58.561802087 0 bash (6334) > execve
1408 05:45:58.561944799 0 blah.sh (6334) < execve res=0 exe=/bin/sh args=./blah.sh. tid=6334(blah.sh) pid=6334(blah.sh) ptid=5825(bash) cwd= fdlimit=1024 pgft_maj=0 pgft_min=63 vm_size=1232 vm_rss=4 vm_swap=0 comm=blah.sh cgroups=cpuset=/.cpu_cgroup=/.cpuacct=/.mem_cgroup=/.devices=/user.slice.freezer=/.ne... env=XDG_SESSION_ID=24.HOSTNAME=localhost.localdomain.TERM=xterm.SHELL=/bin/bash.H... tty=34817
1708 05:45:58.563084850 0 blah.sh (6335) > execve
1709 05:45:58.563159618 0 ls (6335) < execve res=0 exe=ls args= tid=6335(ls) pid=6335(ls) ptid=6334(blah.sh) cwd= fdlimit=1024 pgft_maj=0 pgft_min=62 vm_size=400 vm_rss=4 vm_swap=0 comm=ls cgroups=cpuset=/.cpu_cgroup=/.cpuacct=/.mem_cgroup=/.devices=/user.slice.freezer=/.ne... env=XDG_SESSION_ID=24.HOSTNAME=localhost.localdomain.SHELL=/bin/bash.TERM=xterm.H... tty=34817```
and `sysdig -r foo.scap -p"*%evt.datetime %proc.pid %proc.ppid" evt.type=execve` prints
```2017-05-04 05:45:58.561802087 6334 5825
2017-05-04 05:45:58.561944799 6334 5825
2017-05-04 05:45:58.563084850 6335 6334
2017-05-04 05:45:58.563159618 6335 6334```
The results seem fine to me, can you please elaborate if the reproducing steps are correct? Sysdig version, platform and other environment details might be helpful.

**Comment by JohannesTK** [comment]
@karastojko 

Thank you for collaborating. 

I can not seem to reproduce it again as well. 

Sysdig version: 0.16.0
Ubuntu 16.04.02 LTS x64, kernel 4.4.0-66. 

Looks like it can be closed.

**Comment by karastojko** [comment]
Cannot be reproduced.
