### ISSUE TITLE
Feature Request: Naively Alert against Custom Events / Send Notification from Custom Event

### ISSUE THREAD

**Issue by darrenway** [draios/sysdig#795]
We have set up alerting against our application and send these to a slack channel,

I am interested to know if we can set up an Alert for if custom event from kube/docker/falco occurs, or send a notification to a slack channel if a given custom even occurs,

Essentially, I want an alert to fire, if we receive a 'Container Killed' custom event from docker, but as this is not a metric known to sysdig, we cannot alert against this. We are unable to involve sysdigbot in our instance

This seems like a Feature Request to me, if it's already possible i'm more than happy to be proved wrong!

**Comment by payalc5** [comment]
Hi Darren,  I work in the product team at Sysdig and currently in the process of implementing this feature for Sysdig Cloud. Would you be interested in getting a preview and providing us your early feedback on this ? If yes, let me know a few time slots that work for you and I can set it up

**Comment by darrenway** [comment]
Hi Payal thanks for getting back to me,

Great news that this is already in the process of being implemented! 
I'd be very interested with getting a preview and proving feedback on this.  I would be unable to do so today or tomorrow (29th) but can make some time on 30th or 31st March? I am flexible with time slots on these days - whatever works for you!

**Comment by luca3m** [comment]
I'm closing this since it's not a request for Sysdig opensource
