### ISSUE TITLE
sysdig/driver/ppm.h does not have an ARM64 syscall table entry defined for SYSCALL_TABLE_ID0

### ISSUE THREAD

**Issue by ColinIanKing** [draios/sysdig#802]
The CONFIG_ARM64 case for arm64 is missing in driver/ppm.h causing build failures for this architecture.  Can this be fixed?

**Comment by luca3m** [comment]
Yes, feel free to open a pull request with any changes to make the driver compile on arm64

**Comment by ketank-new** [comment]
@ColinIanKing : I have done it similarly for s390x arch , you can refer in driver/ppm.h , i will be happy to help you if you have any questions

**Comment by bsphere** [comment]
Did you solve it?

**Comment by ColinIanKing** [comment]
Not yet, it fall off my radar.
