### ISSUE TITLE
unlink should have flags

### ISSUE THREAD

**Issue by JohannesTK** [draios/sysdig#803]
At the moment there is no way to differentiate if the unlink is deleting a file or a directory: 

![image](https://cloud.githubusercontent.com/assets/3767980/24792481/d8028cc2-1b86-11e7-9ad9-a725b83ba60a.png)

Strace output: unlinkat(AT_FDCWD, "testfolder", AT_REMOVEDIR) = 0

So we have **AT_REMOVEDIR** that shows that we are deleting a directory

**Comment by luca3m** [comment]
Yes we don't decode flags, it can be added in [ppm_fillers.c](https://github.com/draios/sysdig/blob/dev/driver/ppm_fillers.c)

**Comment by JohannesTK** [comment]
Thank you for the reply!

Is it planned to support it in the future?

**Comment by luca3m** [comment]
yes we can, but no ETA yet. If you would like to contribute we are open to review and merge pull requests!

**Comment by mattpag** [comment]
Resolved with https://github.com/draios/sysdig/pull/1076
