### ISSUE TITLE
Open syscall file permissions support

### ISSUE THREAD

**Issue by JohannesTK** [draios/sysdig#804]
Strace open syscall output: `open("testfile", O_WRONLY|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = 3`

Sysdig open syscall output: `1133 08:42:22.561772773 0 touch (14066) < open fd=3(<f>/home/ubuntu/testfile) name=testfile(/home/ubuntu/testfile) flags=70(O_NONBLOCK|O_CREAT|O_WRONLY) mode=0 
`

Why is the **mode=0** always for sysdig?

File permissions are obtained with **mode_t mode**: http://man7.org/linux/man-pages/man2/open.2.html

**Comment by luca3m** [comment]
Yes right now sysdig reports 0, it can be easily changed [here](https://github.com/draios/sysdig/blob/0d55bcc4154b827254ee5b85ab20bff2c6602613/driver/ppm_fillers.c#L557)

**Comment by JohannesTK** [comment]
Thank you for the reply!

Is it planned to support it in the future?

**Comment by luca3m** [comment]
yes we can, but no ETA yet. If you would like to contribute we are open to review and merge pull requests!
