### ISSUE TITLE
Comparison operator on event.time.

### ISSUE THREAD

**Issue by Waseem-farooqui** [draios/sysdig#825]
I want to apply a filter on the `event.time` that it should be greater then specific time.
This is the practical usecase when storing the log in the file and using them after specific interval of time.

     sysdig -r logfile.scap evt.time < 08:32:28.247315654
     filter error: unrecognized comparison operator after evt.time

How can apply such type of filter ?
Another thing is there any flag that I can use to write the logs to the file in background, there will be something but I have't searched a lot.

**Comment by rajeeshckr** [comment]
FYI, this works. Shows first 2 seconds of events with this example

`sysdig -r sysdig.scap "evt.reltime.s < 2"`
