### ISSUE TITLE
Anyway to just write container specific logs to the file.

### ISSUE THREAD

**Issue by Waseem-farooqui** [draios/sysdig#826]
I am only interested in viewing the container specific logs so I just want to write all the logs that are specific to container is there any way to do that ?

**Comment by luca3m** [comment]
Hi @Waseem-farooqui , yes you can, just filter stderr of your containers:

```
sysdig -c echo_fds fd.num = 1 and container.id = <containerid>
```

or you can also use `spy_logs` chisel

**Comment by Waseem-farooqui** [comment]
I want to write these container specific logs in the file.
You mean like this
`sysdig -s 4096 -z -w /location/file.scap.gz -c echo_fds fd.num = 1 and container.id = <containerid> &`
Is this possible ?

**Comment by luca3m** [comment]
sysdig `-w` captures on a file all the systemcalls, to capture just the log content to a file you can write your own chisel using echo_fds as inspiration

**Comment by Waseem-farooqui** [comment]
Please share a link from where O can find an example of writing chisel.

**Comment by luca3m** [comment]
You can start from here: https://github.com/draios/sysdig/wiki/Sysdig-Chisel-API-Reference-Manual
