### ISSUE TITLE
How I could understand the event arguments ?

### ISSUE THREAD

**Issue by Waseem-farooqui** [draios/sysdig#831]
Sysdig mostly normalize the logs in it basic format 
`*%evt.num %evt.time %evt.cpu %proc.name (%thread.tid) %evt.dir %evt.type %evt.args` 
but most of the important stuff regarding the system lies in `evt.args` which contains lot of stuff as per system call. This data is also normalize and separated by the *=* and *space*. 
I want to understand these argument, is there any documentation. These are different for different  `evt.type` how could I assume that if the `evt.type=clone` then this this will be the arguments.
Is there any mapping available in sysdig that I could look to co-relate the events.
I tried to understand the arguments from the kernal level system call function but these functions have different parameter then I have in my logs data.

**Comment by luca3m** [comment]
Each event argument maps the arguments of the system calls almost always, so you can just refer to respective man pages. `man 2 open` for example or `man clone`

**Comment by Waseem-farooqui** [comment]
`4791816 07:48:32.411186905 0 bash (4743) < clone res=0 exe=bash args= tid=4743(bash) pid=4743(bash) ptid=4652(bash) cwd= fdlimit=524288 pgft_maj=0 pgft_min=1 vm_size=18244 vm_rss=480 vm_swap=0 comm=bash cgroups=
cpuset=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dcpu=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dcpuacct=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dio=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dmemory=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23ddevices=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dfreezer=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dnet_cls=/perf_event=/docker/2aa71f14ea88e535cfb7aa3be467f55ab51ba3eb88b91f490452ca9e296ef23dnet_prio=/hugetlb=/pids=/ flags=0 uid=0 gid=0 vtid=42 vpid=42`

This is the sysdig event for the clone
And this is man of the clone https://linux.die.net/man/2/clone
I was not able to find the any of its function that has these much arguments. 

`res, exe, args,args, pid,ptid,cwd,fdlimit,pgft_maj,pgft_min,vm_size,vm_rss,vm_swap,comm,cgroups,cpuset,cpu,cpuacct,dio,memory,memory,freezer,net_cls,perf_event,net_prio,hugetlb,pids,flags, uid,gid, vtid,vpid`

Tell me how I can understand this if its in man.
Thanks.

**Comment by luca3m** [comment]
clone event is a bit special because we use it to grab all the info of a process:

```
res, exe, args,args, pid,ptid,cwd,fdlimit,pgft_maj,pgft_min,vm_size,vm_rss,vm_swap,comm
```
exe, arguments, pid, tid, current directory, page faults, used memory, process name (called comm by the kernel)
and so forth

these here:

```
cpuset,cpu,cpuacct,dio,memory,memory,freezer,net_cls,perf_event,net_prio
```

are not arguments of the systemcalls, they are cgroup names, cgroups are a map of key -> value and these are the keys. You can get more info from `man cgroups`

**Comment by Waseem-farooqui** [comment]
Is here any other special event other then `clone`.

This looks like a big world :( There is too much to digest.

So I have to see the man for each and everything.

Where is the reference of the things you are telling me because I can't found them in clone's man.

**Comment by luca3m** [comment]
I suggest you to start focus on events more simple like `open`, `close`, `read`, `write`, `connect` and so forth.

**Comment by Waseem-farooqui** [comment]
I was reading man of `read` system call its function is 
`read(int fd, void *buf, size_t count);`
But when looked in my logs I got this 

     4902456 07:48:46.351817915 0 sshd (4745) > read fd=3(<f>/etc/ssh/ssh_host_dsa_key.pub) size=4096 
     4902457 07:48:46.351821781 0 sshd (4745) < read res=601 data= ssh-dss AAAAB3NzaC1kc3MAAACBAKKuhqmj8pFk3+cSycnJtF3GjyMEmi5AFMQGJh1LciUmEOZlUDO1

I can't see the `*buf` where is this in the logs ? I am also confused on **>** and **<**, One shows the input and others shows the return ?
According to man 

> On success, the number of bytes read is returned (zero indicates end of file), and the file position is advanced by this number.
   
Where is the return in these logs ?

**Comment by luca3m** [comment]
> I can't see the *buf where is this in the logs ? I am also confused on > and <, One shows the input and others shows the return ?

buf is `data`, count is `size`. `>` and `<` work as you described.

> Where is the return in these logs ?

return is `res`

**Comment by Waseem-farooqui** [comment]
If **>** is an input then according to the function `read(int fd, void *buf, size_t count);` the logs should be like this. 

    4902456 07:48:46.351817915 0 sshd (4745) > read fd=3(<f>/etc/ssh/ssh_host_dsa_key.pub)  data= ssh-dss AAAAB3NzaC1kc3MAAACBAKKuhqmj8pFk3+cSycnJtF3GjyMEmi5AFMQGJh1LciUmEOZlUDO1 size=4096

**Comment by luca3m** [comment]
for user buffers (any parameter that is a pointer) we parse them on exit events because otherwise the parsing may fail.

**Comment by Waseem-farooqui** [comment]
I have another confusion regarding send with its other function sendto and sendmsg.
If I see the functions its like this.

    ssize_t send(int sockfd, const void *buf, size_t len, int flags);
    ssize_t sendto(int sockfd, const void *buf, size_t len, int flags,const struct sockaddr *dest_addr, socklen_t addrlen);
    ssize_t sendmsg(int sockfd, const struct msghdr *msg, int flags);
But when I tried to co-relate them its like this.

    50575438 12:08:54.468238042 0 sshd (5495) > sendto fd=4(<o>) size=136 tuple=NULL 
    50575439 12:08:54.468245272 0 sshd (5495) < sendto res=136 data= Qop=PAM:session_open acct="ubuntu" exe="/usr/sbin/sshd" hostname=

    50575995 12:08:54.586330451 0 sshd (5495) > sendmsg fd=5(<u>) size=1 tuple=NULL 
    50575996 12:08:54.586345846 0 sshd (5495) < sendmsg res=1 data=

I am again at the same place where is buffer if its data then what are other things in that data in some logs there is **VTY, ~_Y** and some times nothing in the data.

where are the other arguments of of the send to function.

Kindly explain each part of data in detail I would be very great-full.

1 more thing, there are fds `<f>,<4>,<6>,<s>,<e>,<i>,<t>` which are specified by sysdig but what is `<o>` which is in sendto.
