### ISSUE TITLE
Unable to get the complete syscall list of container

### ISSUE THREAD

**Issue by ihac** [draios/sysdig#840]
Hi, I was using Sysdig for tracing syscalls by container, and then limiting the container by [Seccomp](https://docs.docker.com/engine/security/seccomp/).
More specifically, I developed a tool to generate Seccomp sandbox automatically for any container. It uses Sysdig to capture syscalls of an container, and then limits container by allowing these syscalls and disallowing all other syscalls.
However, it seems that Sysdig does not produce a complete syscall list of container. There are some syscalls which are used by a container but not captured by Sysdig.
For example. I tested [nginx](https://hub.docker.com/_/nginx/) and [httpd](https://hub.docker.com/_/httpd/) container, and here are the missing syscall lists:
``` bash
# for nginx
capget
capset
chdir
clock_gettime
dup2
eventfd2
execve
exit_group
fchown
getdents64
getgid
getppid
gettid
getuid
kill
lstat
openat
rt_sigreturn
select
```
``` bash
# for httpd
capget
capset
chdir
clock_gettime
dup3
fchown
getdents64
getgid
getuid
lstat
openat
prctl
rt_sigreturn
```
BTW, even though Sysdig does capture `write()`, its argument value seems to be wrong(?). 
``` bash
# here are what Sysdig captured
      fd=7(<f>/usr/local/apache2/logs/httpd.pid) size=2
      fd=6(<f>/proc/self/fd/1) size=68
      fd=2(<p>) size=170
      fd=2(<f>/proc/self/fd/2) size=170
      fd=2(<f>/proc/self/fd/2) size=152
      fd=2(<f>/proc/self/fd/2) size=121
```
I tried to allow syscall `write` only if its first argument(`fd`) is less than or equal to `8`(seems work) by Seccomp, but it failed that some `write` is not allowed, in other word, there must be some `write` has `fd > 8`.

I'm pretty curious about these puzzles. I conjectured that there might be some important procedures(probably the initialization) of a container, while ignored by Sysdig?

Looking forward to your reply.

**Comment by ihac** [comment]
Sysdig: `version 0.16.0`
System: `Ubuntu 16.04.2 LTS`
Docker: `version 17.04.0-ce, build 4845c56`

**Comment by gianlucaborello** [comment]
Those system calls seem way too popular, so the majority should indeed be there. A couple suggestions:

1) Did you drop events during the tracing of your containers? You can check that by loading the module with `modprobe sysdig-probe verbose=1` and check if `dr_buf` or `dr_pf` in your `dmesg` are high: ideally they should be 0.

2) Make sure you check also the exit events and not only the enter events. We detect a new container when we see the return of a `clone()` or `execve()` with a proper cgroup set. For example, here I have a startup of a random nginx container, and you can see how the `execve` transitioned from being outside the container to inside the container, and this is an artifact due to our effective cgroups polling just at execve time:

```
gianluca@sid:~$ sysdig -pc -r trace.scap thread.tid=11423 and evt.type=execve
65523 23:54:49.960760742 0 host (host) runc:[1:CHILD] (11423:1) > execve
65652 23:54:49.962372906 3 vigorous_shaw (8b36ba22cc6f) nginx (11423:1) < execve res=0 exe=nginx args=-g.daemon off;. tid=11423(nginx) pid=11423(nginx) ptid=11406(docker-containe) cwd= fdlimit=1048576 pgft_maj=2 pgft_min=586 vm_size=1644 vm_rss=4 vm_swap=0 comm=nginx cgroups=cpuset=/docker/8b36ba22cc6ff8124524844d50415e2c35b73533cd0464414f981a08e10a1e... env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin.HOSTNAME=8b... tty=34828
```

**Comment by ihac** [comment]
@gianlucaborello Thanks for your reply. I tried `modprobe sysdig-probe verbose=1`, but I didn't saw any `dr_buf` or `dr_pf`. Here is the output of `dmesg`:
```
[61193.456318] sysdig_probe: module verification failed: signature and/or required key missing - tainting kernel
[61193.457340] sysdig_probe: driver loading, sysdig-probe 0.16.0
```

I also checked the exit events, and I did found the return of `execve` in `Nginx`'s trace records. Do you mean that all the missing events might occurred before `execve` returns a cgroup set?
If yes, then, is there any chance that some event(before `execve (xxx) <`) belongs to the container, not the host?  since the missing syscalls are still detected by Docker when running the container.

Thanks

**Comment by kadamvandita** [comment]
Check if this command gives you the desired output: sudo csysdig -vcontainers

**Comment by ketank-new** [comment]
@ihac : Is your issue resolved?
