### ISSUE TITLE
Access execve arguments in exit events

### ISSUE THREAD

**Issue by arossert** [draios/sysdig#842]
In continuing to my previous issue #832, I'm trying to get syscall arguments in `f_proc_startupdate` function to get the execve first filename argument ([execve](http://man7.org/linux/man-pages/man2/execve.2.html)) in the exit event.

When I use the fallowing code:
```
syscall_get_arguments(current, args->regs, 0, 1, &val);
	    	res = val_to_ring(args, val, 0, true, 0);
		if (unlikely(res != PPM_SUCCESS))
			return res;
```
`val` is always 0.

When doing this in the execve enter event I can access the arguments.
Is it possible to access the syscall arguments in the exit events? If so, what am I doing wrong here?

**Comment by gianlucaborello** [comment]
I think if you tried both and it doesn't work for the exit event is sort of normal: execve replaces the address space of the calling process, so I can see how dereferencing the `filename` pointer after the address space is gone would not work (again, haven't checked it myself, but your tests seem reasonable). So, can't you just add `filename` to the enter event and keep it there? sinsp and the rest of the userspace will be able to parse it.

**Comment by arossert** [comment]
This sounds very reasonable.
My goal is to use this (with the CWD field) to get the real exepath #717.

I'm using sysdig and only examine the execve exit events, is it possible to add this value in the exit events?

**Comment by gianlucaborello** [comment]
From your other PR I seem to understand you went with the option of storing it in the enter event, which is what I was gonna recommend anyway since it's the easiest. Will take a look asap.

**Comment by arossert** [comment]
Yes, this was the easiest solution.
The only problem that I have is with the ASSERT (as I mentioned in the PR)

**Comment by luca3m** [comment]
I guess we can close this
