### ISSUE TITLE
Retrieve `auid` for user operations

### ISSUE THREAD

**Issue by jayaddison** [draios/sysdig#865]
I'm chiseling some system events using `sysdig` and was wondering about the feasibility of including the Audit user ID (`auid`) along with the existing `uid` and `gid` fields?

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sec-Understanding_Audit_Log_Files.html

I also saw https://github.com/draios/sysdig/pull/792 which does provide some of the same value I'm looking for in terms of process interactivity, but retrieving the audit system's user identity for operations would be brilliant if possible.

**Comment by blindphaze** [comment]
This would be extremely helpful to have so that we can easily see the user instead of "root".

**Comment by arossert** [comment]
@jayaddison I have submitted a PR to add this value to sysdig, can you test it and let me know if this is what you are looking for?

**Comment by jayaddison** [comment]
@arossert absolutely, I should be able to give this a try soon.  I'll let you know how it goes!

**Comment by jayaddison** [comment]
@arossert I built this from scratch on a host running fedora-26 with kernel `uname -r` of `4.14.4-200.fc26.x86_64` - unfortunately I seem to get some kind of buffer garbage when tracing the new field:

```
# sysdig -p"%user.loginuid" | head -n 2
?
????
```

I noticed there are some `exepath` related-changes in the diff here - any chance those could be accidental/unrelated changes pulled in?

Glad to co-ordinate further off-PR in terms of debugging if that'll help.

**Comment by arossert** [comment]
@jayaddison the `exepath` changes are just indentation fixes that I inserted by mistake to this PR, this should not be related to what you see.
Can you run sysdig as:
```
sysdig evt.type=execve
```
To see what is the value you have in the syscall?

**Comment by arossert** [comment]
@jayaddison do you still have this issue?
If so, can you share the output of:
```
sysdig evt.type=execve
```

**Comment by SteveHallNNT** [comment]
Hi Amir
Do you know if this "loginuid" is or will be available for all events?  i.e the fchmod / fchown you added recently and existing syscalls?
Thanks - this could be a life-saver for me if it is!
Steve

**Comment by arossert** [comment]
@SteveHallNNT the `loginuid` will be added to the thread state on `execve` syscall and should be available on all syscalls.

**Comment by SteveHallNNT** [comment]
Thanks Amir, is there a PR I can test this with or would it have been included in the one you did for chown / chmod a few weeks ago?
Steve

**Comment by arossert** [comment]
@SteveHallNNT there is no PR that contains both of this feature.
There are some changes lately (code revert) that will probably cause conflicts with this 2 branches and the DEV branch.
Let me work on a branch that will combine both and I will share it with you (I will not submit a PR for that so we will have to wait for both of them to be merge by the sysdig team).

**Comment by SteveHallNNT** [comment]
Thanks Amir, that sounds good - I'm happy to test both aspects together and let you know how I get on.

Steve

**Comment by arossert** [comment]
Hi Steve, I have created a branch that combines the `loginuid` and `chmod\chown` features on my sysdig fork here:
https://github.com/arossert/sysdig/tree/lodinuid_chmod

As working on this I have noticed a bug that @jayaddison has reported and fixed it on this branch (will add this later to the PR as well).

I have one dilemma, from what I know when the `auid` is not set its value is `-1`, currently I have defined this field as `uint32_t` so instead of `-1` the value is `4294967295` (in the kernel this field is defined as `unsigned int`).
Should I change the field type to `int` (so it will be listed as `-1`)?

**Comment by SteveHallNNT** [comment]
Thanks Amir.  That's a tricky one re: the auid.  I suspect int would be OK as the upper limit for the int is unlikely to be any kind of user id value and the benefit if being able to check for -1 as opposed to the unsigned value is probably worth it.

**Comment by arossert** [comment]
Steve, I have changed the `loginuid` type to `int`.
Please notice that this is not been tested so **use it at your own risk**.

**Comment by SteveHallNNT** [comment]
Hi Amir.  This is looking good.  Using your "lodinuid_chmod" branch I get :

```
# ./userspace/sysdig/sysdig "evt.type in (chmod,fchmod,fchmodat)" -p "%evt.args %user.loginuid %user.uid %user.name"
dirfd=-100(ENETDOWN) mode=0777 flags=0  1000 0 root
res=0 pathname=test.txt(/home/steve/sysdig/amir/sysdig/build/test.txt)  1000 0 root
```

So the original UID (1000) is successfully being retrieved - thanks!  Sessions without a loginuid display -1 as discussed :

```
fd=27(<f>/run/systemd/sessions/.#176iOCyB8) mode=0644  -1 0 root
```

My only question is would it be possible to get "loginname" as well as "loginuid" (as per user.uid and user.name in the current model)?

Not essential though but may be worth adding if it's not too hard?

Thanks for the good work - this is potentially a huge boon for us in the way we use sysdig.

Steve

**Comment by arossert** [comment]
Hi Steve, thanks for checking this out, glad to see that it is useful.
I will see if I can add the `loginname` as requested and if so will put it in `lodinuid_chmod`, if it will work as expected I will push it to the original branch.

**Comment by arossert** [comment]
Hi Steve, I have added the ability to filter/format using `user.loginname`.
You can try it on the same branch.
Let me know if you have any issues.

**Comment by SteveHallNNT** [comment]
Looks good :  

```
# ./userspace/sysdig/sysdig "evt.type in (chmod,fchmod,fchmodat)" -p "%evt.args %user.loginuid %user.loginname %user.uid %user.name %proc.name %evt.dir"
dirfd=-100(ENETDOWN) mode=0666 flags=0  1000 steve 0 root chmod >
res=0 pathname=test.txt(/usr/src/sysdig/amir/sysdig/build/test.txt)  1000 steve 0 root chmod <

```

Great work - thanks for this Amir, it's much appreciated here.

Steve

**Comment by arossert** [comment]
Thanks for testing this out, I will add the recent changes to the PR and we will wait for the sysdig team to review and merge.

**Comment by jayaddison** [comment]
@arossert I'm going to take another look at testing the PR now, thanks again for this!

**Comment by jayaddison** [comment]
@arossert this is brilliant stuff - everything compiled and loaded correctly, and I was able to test this  out using the filter below to trace actions by a dummy user following privilege escalation:

```
# sysdig "evt.type=execve and evt.dir=< and user.loginuid=1000" -p"%evt.type: %user.loginname (uiuid=%user.loginuid) : roc.name %proc.args"
execve: fedora (uiuid=1000) : sudo -i
< shell init events redacted >
execve: fedora (uiuid=1000) : dmesg
```

**Comment by arossert** [comment]
@jayaddison thanks for testing this. 
This was now tested by 2 different users (thanks @SteveHallNNT) so I believe that this is a needed feature. 

Hope that it will be merged soon by sysdig team. 
(If there are any changes needed I’m willing to take the time and fix them)

**Comment by SteveHallNNT** [comment]
I second that @arossert - this is a great feature and am greatly looking forward to it being part of sysdig.  Thanks again for your work on this.

**Comment by SteveHallNNT** [comment]
Hi,
Is there any update on this (excellent) enhancement being included in sysdig yet?  
Thanks
Steve H

**Comment by arossert** [comment]
@SteveHallNNT I will fix the conflicts on #1008 so it will be ready for merge.

**Comment by SteveHallNNT** [comment]
Thanks @arossert

**Comment by jayaddison** [comment]
Looking forward to this too, thanks again @arossert

**Comment by SteveHallNNT** [comment]
Hi @arossert - it looks like the checks have passed so thanks for sorting out the conflicts.  Do you know what happens next?  i.e when it will get merged?
Thanks
Steve

**Comment by arossert** [comment]
Hi Steve, this is now in the hands of the Sysdig team members, they need to review this (and probably test) and merge.
Regarding when will it be I cannot tell you that but I can tell you that they are very responsive to the community so if this a highly requested feature they will work fast to merge it.
(You can try to ask for this on the Sysdig open source Slack channel).

**Comment by SteveHallNNT** [comment]
Hi @arossert - the PR is listed as "This branch has conflicts that must be resolved" - is this something that needs some attention?  https://github.com/draios/sysdig/pull/1008  Sorry to hassle you (I'm being hassled myself!).  Thanks, Steve

**Comment by arossert** [comment]
No worries, I will look into it today.

**Comment by arossert** [comment]
@SteveHallNNT, I have fixed the conflicts and the PR is ready to be merged again.

**Comment by SteveHallNNT** [comment]
Thanks so much @arossert

**Comment by SteveHallNNT** [comment]
Hi @arossert - sorry too bother you, but do you know what we need to do to get this merged?  All looks good on the PR but I can't see that it's been merged yet?
Thanks
Steve H

**Comment by arossert** [comment]
I believe that this can be closed now.

**Comment by jayaddison** [comment]
Thanks @arossert !
