### ISSUE TITLE
Block errors while processing scap file

### ISSUE THREAD

**Issue by mcstafford-git** [draios/sysdig#867]
[scap+lsmod.zip](https://github.com/draios/sysdig/files/1081544/scap.lsmod.zip)
Ubuntu yakkety/16.10 4.8.0-54-generic

sysdig version 0.16.0

$ steam & sudo sysdig -qw sysdig-${!}.scap

_steam fails_
_press ctrl+c_

$ sysdig -r sysdig-27755.scap proc.name=steam and evt.type=open 
> res = 1
> event block length 65948 greater than read buffer size 65536

$ csysdig -r sysdig-27755.scap
> invalid block type

**Comment by adrianlzt** [comment]
Same error capturing with kubectl-capture

**Comment by aishvaryaps** [comment]
when I run following command:
 sysdig -r capture-reviews.scap

I get following error:

res = 1
event block length 17835928 greater than read buffer size 65536

capture file generated by kubectl-capture. kubectl version "v1.12.0"
other capture files generated by sysdig SaaS version runs fine on sysdig and sysdig inspect

**Comment by byrdog55** [comment]
I am also having this problem with kubectl version "v1.12.8-gke.10" . Does anyone have a work around?
