### ISSUE TITLE
Segmentation fault with bad chisel (missing opening bracket in condition) on CentOs7

### ISSUE THREAD

**Issue by HristoMohamed** [draios/sysdig#890]
Hi,
Kernel: 4.11.0-1.el7.elrepo.x86_64
The following typo in a chisel made sysdig segfault:
    chisel.set_filter(
     "(evt.type=unlinkat and evt.arg.name=" .. path .. ") or \
     (evt.type=unlink and evt.arg.path=" .. path .. ") or \
     **evt.type=umount)** or \
     (evt.type=remove and evt.arg.path=" .. path .. ")")

The bolded part is missing the opening bracket.

Not an important bug but thought I should report it :)

**Comment by kadamvandita** [comment]
Hi,

Can you follow the steps from the recipe mentioned in the link for rhel7.
(https://github.com/linux-on-ibm-z/docs/wiki/Building-sysdig)

Check if the issue can be resolved using the steps mentioned.

**Comment by kadamvandita** [comment]
Hi,

Could you please give some information on when this error occurs?
