### ISSUE TITLE
Compilation error with recent curl

### ISSUE THREAD

**Issue by mtorromeo** [draios/sysdig#895]
Since curl 7.55.0 the header `curl/curlbuild.h` has been removed [1][2] and `curl/system.h` should be used instead.

The compilation currently fails with the following error:

```
[ 63%] Building CXX object userspace/libsinsp/CMakeFiles/sinsp.dir/marathon_http.cpp.o
/build/sysdig/src/sysdig-0.17.0/userspace/libsinsp/marathon_http.cpp:10:10: fatal error: curl/curlbuild.h: No such file or directory
 #include "curl/curlbuild.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I am able to workaround the issue with the following substitution but a proper solution that checks for the curl version should used instead:
```
  sed 's|curl/curlbuild\.h|curl/system.h|' -i \
      userspace/libsinsp/marathon_http.cpp \
      userspace/libsinsp/mesos_http.cpp
```

[1] https://github.com/curl/curl/blob/a548183546cd6d9983cb46a4e2e17ea3116432d4/RELEASE-NOTES#L21
[2] https://daniel.haxx.se/blog/2017/06/15/target-independent-libcurl-headers/

**Comment by hhoffstaette** [comment]
Please *do not* start checking for versions or make things more fragile in other ways; all sysdig needs to do is stick with public API. The important part here is that including `curl/system.h` is not even necessary; it will build just fine when all references to `curl/curlbuild.h` are simply removed. I am currently using the [following patch](https://github.com/hhoffstaette/portage/blob/master/dev-util/sysdig/files/sysdig-0.17.0-curl-7.55.patch) without issue; feel free to apply it. I verified that his works for both curl-7.54 (which still has the old header) and 7.55.
