### ISSUE TITLE
APT error

### ISSUE THREAD

**Issue by rlex** [draios/sysdig#896]
Hello, started today (it seems) on debian9:
Err:9 http://download.draios.com/stable/deb stable-amd64/ InRelease
  The following signatures were invalid: D27A72F32D867DF9300A241574490FD6EC51E8C4
Reading package lists... Done
W: GPG error: http://download.draios.com/stable/deb stable-amd64/ InRelease: The following signatures were invalid: D27A72F32D867DF9300A241574490FD6EC51E8C4
E: The repository 'http://download.draios.com/stable/deb stable-amd64/ InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Additionally, ubuntu 16.04 reports:
W: http://download.draios.com/stable/deb/stable-amd64/InRelease: Signature by key D27A72F32D867DF9300A241574490FD6EC51E8C4 uses weak digest algorithm (SHA1)

**Comment by luca3m** [comment]
It should be fixed by latest release
