### ISSUE TITLE
Docker http://containers/json endpoint depreciation notification

### ISSUE THREAD

**Issue by mrbobbytables** [draios/sysdig#900]
This is more of a general informative post following up a conversation in #falco with @mstemm.

Docker has depreciated the `http://containers/json` endpoint and all future API calls should be prepend the API version. e.g. `http://v1.25/containers/json`. 

It is targeted for removal in the v17.12 release.
For further information, please see the below links:
* https://docs.docker.com/engine/deprecated/#api-calls-without-a-version
* https://github.com/moby/moby/pull/28208

**Comment by gnosek** [comment]
As far as I could find, the docker client always uses an explicit version number ("v1.18" and "v1.24"). Going back through the code, it seems like it has always been the case.
