### ISSUE TITLE
build failure on musl libc due to usage of getaddrinfo_a

### ISSUE THREAD

**Issue by rofl0r** [draios/sysdig#903]
```
/src/build/sysdig/sysdig-0.16.0/userspace/libsinsp/socket_handler.h: In member function 'bool socket_data_handler<T>::try_resolve()':
/src/build/sysdig/sysdig-0.16.0/userspace/libsinsp/socket_handler.h:1279:66: error: invalid application of 'sizeof' to incomplete type 'gaicb'
      m_dns_reqs[0] = (struct gaicb*)calloc(1, sizeof(struct gaicb));
                                                                  ^
```
getaddrinfo_a()/struct gaicb is gnu only (i.e. not portable).
since alpine linux is docker's pick, i would have expected that this compiles on it...

**Comment by luca3m** [comment]
Why do you need to compile on Alpine? Can't you just use our docker container?

**Comment by rofl0r** [comment]
what kind of question is that ? source is there to compile it.

anyway, i actually try to add it as a package to my distro sabotage linux which is based on musl just like the popular alpine linux.

and no, i don't typically use a docker container to get an app running, since it's a huge waste of memory and harddisk space instead of just, you know, compiling and running the app i'm interested in.

**Comment by luca3m** [comment]
Makes sense, you are welcome to patch it and send a PR.

**Comment by kippandrew** [comment]
I've run into the same issuing trying to build the falco driver for linuxkit (which uses Alpine). LinuxKit is used by Docker for Mac.

**Comment by jjqq2013** [comment]
same issue when I am trying to build it to linuxkit (the Docker VM, or should be called Docker Desktop for Windows or Mac), which use alpine.

This really make sense, I have waited for long time for using sysdig in Docker Desktop, is there anyone working on this?

To quickly start working on this, you can run following command to do investigation ( as I am doing now), 

First, run following command once to get a docker image as builder environment, named mybuilder.
```
docker build -t mybuilder - < EOFEOF
ARG KERNEL_VERSION=4.19.76

FROM linuxkit/kernel:${KERNEL_VERSION} as ksrc

FROM alpine:3.10 AS build
RUN apk update && apk upgrade -a && \
  apk add --no-cache \
  argp-standalone \
  autoconf \
  automake \
  bison \
  build-base \
  clang \
  clang-dev \
  clang-static \
  cmake \
  curl \
  flex-dev \
  fts-dev \
  gettext-dev \
  git \
  iperf3 \
  libedit-dev \
  libtool \
  llvm \
  llvm-dev \
  llvm-static \
  luajit-dev \
  m4 \
  python \
  zlib-dev \
  && true

RUN ln -s /usr/lib/cmake/llvm5/ /usr/lib/cmake/llvm && \
    ln -s /usr/include/llvm5/llvm-c/ /usr/include/llvm-c && \
    ln -s /usr/include/llvm5/llvm/ /usr/include/llvm

COPY --from=ksrc /kernel-headers.tar /
COPY --from=ksrc /kernel-dev.tar /
COPY --from=ksrc /kernel.tar /
RUN set -x && \
    echo $PWD && \
    tar xf /kernel-headers.tar && \
    tar xf /kernel-dev.tar && \
    tar xf /kernel.tar

#RUN set -x && \
#  export KERNEL_VERSION=`uname -r  | cut -d '-' -f 1`  && \
#  export KERNEL_DIR=/usr/src/linux-headers-${KERNEL_VERSION}-linuxkit/ && \
#  cd $KERNEL_DIR && \
#  zcat /proc/1/root/proc/config.gz > .config && \
#  make olddefconfig

RUN set -x && \
  git clone https://github.com/draios/sysdig && \
  cd sysdig && \
  git checkout 0.26.6 && \
  mkdir build && \
  cd build && \
  cmake ..

RUN set -x && \
  apk add elfutils-dev

EOFEOF
```

Then enter the mybuilder
```
docker run -it mybuilder bash -l
```

then 
```
cd /sysdig/build
make
```

you will see exactly same error.


The problematic `struct gaicb` is a part of function [`getaddrinfo_a`](https://libusual.github.io/netdb_8h.html), 
but I found that nowhere is using `getaddrinfo_a`, 
if I am lucky, I may get rid of this error by manually add the struc to netdb.h.

**Comment by jjqq2013** [comment]
no luck, I am wrong, there are code using `getaddrinfo_a`, so I have to make glibc works, maybe better statically linked, so can work with alpine's musl libc.

there were already discussion about this: https://dev.alpinelinux.org/irclogs/%23alpine-devel-2017-01.log

**Comment by jjqq2013** [comment]
finally, I come up with a thought, just build the kernel driver with apline (Successfully done), others all built with glibc, this should works.

**Comment by Vaelatern** [comment]
Any luck on making this build on muslc?
