### ISSUE TITLE
Duplicate `clone` events on kernel 2.6.18

### ISSUE THREAD

**Issue by arossert** [draios/sysdig#908]
I have noticed that on kernel 2.6.18 that sysdig reports on duplicate clone events:
Example:

`sysdig evt.type=clone`
```
14337 18:11:26.261318000 0 bash (17021) > clone 
14339 18:11:26.261446000 0 bash (3640) < clone res=0 exe=bash args= tid=3640(bash) pid=3640(bash) ptid=17021(bash) cwd= fdlimit=0 pgft_maj=0 pgft_min=1 vm_size=66216 vm_rss=480 vm_swap=0 comm=bash cgroups= flags=0 uid=500 gid=500 vtid=0 vpid=0 
14340 18:11:26.261448000 0 bash (3640) < clone res=0 exe=bash args= tid=3640(bash) pid=3640(bash) ptid=17021(bash) cwd= fdlimit=0 pgft_maj=0 pgft_min=1 vm_size=66216 vm_rss=480 vm_swap=0 comm=bash cgroups= flags=0 uid=500 gid=500 vtid=0 vpid=0 
14364 18:11:26.261530000 0 bash (17021) < clone res=3640(bash) exe=bash args= tid=17021(bash) pid=17021(bash) ptid=5704(gnome-terminal) cwd= fdlimit=0 pgft_maj=0 pgft_min=4039 vm_size=66216 vm_rss=1696 vm_swap=0 comm=bash cgroups= flags=0 uid=500 gid=500 vtid=0 vpid=0 
```

In the output the are 2 clone exit event from the child, `14339` & `14340` (it should be one for the parent and one for the child).
I have tested the same on ubuntu 14.04 and the output is correct (no duplications).

Sysdig: 0.17.0
OS: RHEL 5.11
Kernel: 2.6.18-419.el5

**Comment by ketank-new** [comment]
will steps using sysdig on ub 16.04 help you?, if yes than let me know i can share with you

**Comment by arossert** [comment]
I haven't tested this scenario on ubuntu 16

**Comment by ketank-new** [comment]
@arossert : would you like to give it a try then you can use the below recipe for the same.
https://github.com/linux-on-ibm-z/docs/wiki/Building-sysdig

The recipe is for s390x arch , but the same steps also work for a intel architecture

Let me know if it helps you or if you come across any issues while trying to build it

**Comment by arossert** [comment]
I will try it on ubuntu 16 but I assume that the output will be correct (as on ubuntu 14). 
I'm trying to understand why on RHEL5 there is duplicate clone events (on every clone)

**Comment by ketank-new** [comment]
@arossert : could you elaborate more on the issue faced by you
can you mention on which steps do you face duplication of cloning

**Comment by arossert** [comment]
I have set up a RHEL5 machine and compile the sysdig source code (tested on 0.16.0 & 0.17.0).
after that just use this command

`sysdig evt.type=clone`
this is the output:
```
8502 15:33:06.520518000 2 bash (31025) > clone 
8515 15:33:06.520606000 2 bash (31054) < clone res=0 exe=bash args= tid=31054(bash) pid=31054(bash) ptid=31025(bash) cwd= fdlimit=0 pgft_maj=0 pgft_min=1 vm_size=66228 vm_rss=452 vm_swap=0 comm=bash cgroups= flags=0 uid=500 gid=500 vtid=0 vpid=0 
8516 15:33:06.520609000 2 bash (31054) < clone res=0 exe=bash args= tid=31054(bash) pid=31054(bash) ptid=31025(bash) cwd= fdlimit=0 pgft_maj=0 pgft_min=1 vm_size=66228 vm_rss=452 vm_swap=0 comm=bash cgroups= flags=0 uid=500 gid=500 vtid=0 vpid=0 
8546 15:33:06.520672000 2 bash (31025) < clone res=31054(bash) exe=bash args= tid=31025(bash) pid=31025(bash) ptid=5765(gnome-terminal) cwd= fdlimit=0 pgft_maj=0 pgft_min=1039 vm_size=66228 vm_rss=1652 vm_swap=0 comm=bash cgroups= flags=0 uid=500 gid=500 vtid=0 vpid=0 
```
As you can see, there are 4 clone events for each process, 1 enter and 3 exits.
In the exits events, there are 2 events with `res=0` (return in the child process), these events look identical (with the same parameters).

As far as I know, the `clone` syscall should enter once and exit twice, one in the parent and one in the child.

**Comment by arossert** [comment]
I have tested it on Ubuntu 16.04.3 with the expected results (with sysdig 0.17.0)
```
882 06:05:00.499020113 0 bash (46952) > clone
883 06:05:00.499151188 0 bash (46952) < clone res=46966(bash) exe=-bash args= tid=46952(bash) pid=46952(bash) ptid=46951(sshd) cwd= fdlimit=1024 pgft_maj=1 pgft_min=1249 vm_size=22468 vm_rss=4896 vm_swap=0 comm=bash cgroups=cpuset=/.cpu=/.cpuacct=/.io=/.memory=/.devices=/user.slice.freezer=/.net_cls=... flags=0 uid=1000 gid=1000 vtid=46952(bash) vpid=46952(bash)
908 06:05:00.499258992 0 bash (46966) < clone res=0 exe=-bash args= tid=46966(bash) pid=46966(bash) ptid=46952(bash) cwd= fdlimit=1024 pgft_maj=0 pgft_min=1 vm_size=22468 vm_rss=1768 vm_swap=0 comm=bash cgroups=cpuset=/.cpu=/.cpuacct=/.io=/.memory=/.devices=/user.slice.freezer=/.net_cls=... flags=0 uid=1000 gid=1000 vtid=46966(bash) vpid=46966(bash)
```
Returns only once in the child process

**Comment by ketank-new** [comment]
RHEL5 is a old distro, may be sysdig should be used with the lastest distros that shoudl help.
@arossert : so was the  recipe helpful for you going ahead?

**Comment by arossert** [comment]
We currently have some RHEL5 machine that can't be updated.
I have downloaded the source code and built it
```
mkdir build && cd build
cmake ..
make
```
Then loaded the module with `insmod`.
Everything is working but I can`t figure out why the `clone` events are duplicated.
Maybe you can point me out where to look in the code and I will try to patch this and submit a PR.

**Comment by ketank-new** [comment]
@luca3m : any suggestions for @arossert query?

**Comment by luca3m** [comment]
I'd start by putting some debug prints [here](https://github.com/draios/sysdig/blob/dev/driver/main.c#L1776) to track why these duplicates events happen

**Comment by arossert** [comment]
@luca3m, @ketank-new thanks for trying to help with this.

@luca3m I have put some debug prints in that function like you suggested and all that I can come up with is that the `syscall_exit_probe` is called 3 times on new process creation for `clone` events.
This is what I have added:
```
if (type == PPME_SYSCALL_CLONE_20_X) {
	pr_info("type: %d, comm: %s\n", type, current->comm);
}
```
And I can see 3 prints when a new process is created.
Do you have any other idea how I can debug this?

**Comment by arossert** [comment]
@luca3m I have tried to debug this but without any success, do you have any idea where else can I look?
It looks like the `TRACEPOINT_PROBE(syscall_exit_probe, struct pt_regs *regs, long ret)` invokes 3 times on each `clone` operation (1 for the parent and 2 for the child)
