### ISSUE TITLE
Automatic openssl download - please consider adding a cmake-switch for this behaviour

### ISSUE THREAD

**Issue by shevegen** [draios/sysdig#944]
Hello.

Sysdig currently seems to download openssl if it can not find a recent version or something.

    [ 1%] Creating directories for 'openssl' 
    [ 1%] Performing download step (download, verify and extract) for 'openssl' 
    -- Downloading... 
       dst='/Depot/Temp/sysdig-0.18.0/BUILD/openssl-prefix/src/openssl-1.0.2j.tar.gz' 
       timeout='none' 
    -- Using src='http://download.draios.com/dependencies/openssl-1.0.2j.tar.gz' 
    -- [download 0% complete] 
    -- [download 1% complete] 
    -- [download 2% complete] 
    -- [download 3% complete] 

I do not think that this is a good behaviour by default. I am sure other people may
like it, so this is perhaps not easy to resolve. I manage all dependencies on my
linux system on my own, via ruby scripts. I can install openssl just fine (usually
I follow the linux from scratch instructions) - I would in this example appreciate
an error instead and sysdig telling me that openssl should be updated or something
like that.

Perhaps there could be a CMAKE option added that could toggle the wanted
behaviour? By default to not auto-build without asking the user, but to enable
a cmake option such as via -D switch, to allow people to assume that openssl
should be downloaded. Perhaps a switch such as -DDOWNLOAD_MISSING_OPENSSL
or something like that. The alternative can also be a possible such as a switch
to NOT automatically download, e. g. -DDO_NOT_DOWNLOAD_MISSING_OPENSSL.

The names are just examples, perhaps there are better ways. If such a switch
would exist, I could store this switch in the config file that I use for sysdig. I
only recently found sysdig as recommendation by the void linux guys, that
is why I found them - hopefully the above issue request appears acceptable,
it's my first issue request here. Feel free to close this issue request at any
moment in time and thanks for reading!

**Comment by luca3m** [comment]
Yes there is: https://github.com/draios/sysdig/blob/dev/CMakeLists.txt#L98
Just use: `cmake -DUSE_BUNDLED_DEPS=OFF`
