### ISSUE TITLE
openat event sometimes is dropped

### ISSUE THREAD

**Issue by luca3m** [draios/sysdig#979]
openat() currently has parsing of `name` field on the enter side, since copying user memory in an atomic context can't be always guaranteed to work it leads to dropped events.

I found it casually while I was playing with `docker service scale`, scaling up and down a service (so creating/destroying containers).

debug prints:
```
Nov  8 19:00:59 art kernel: [13556.558790] sysdigcloud_probe: Invalid read from user for event 102 cbres=-2
Nov  8 19:00:59 art kernel: [13556.569465] sysdig Failed to copy openat name
```

solution:

we should move `name` parameter from enter to exit events as we did other times, then also update any relevant code/tests

**Comment by abucodonosor** [comment]
sometimes ?:)

```
$ dmesg | grep 'Invalid read from user for event 102' | wc -l
1197
```

**Comment by teresaejunior** [comment]
I was going to report this here on Sysdig, but I'm not sure this is a duplicate: https://github.com/draios/falco/issues/377
