### ISSUE TITLE
chmod / chown tracing

### ISSUE THREAD

**Issue by SteveHallNNT** [draios/sysdig#986]
Hi all,

I’m trying to track when someone changes the file mode or owner of a file on Linux.   As a simple test I have tried : 

`# sysdig "evt.type in (fchmodat,fchownat)" `

But when I use chown / chmod on a file all I get from sysdig is :

```
413521 11:55:35.104206570 1 chown (21109) > fchownat 
413682 11:55:35.111606556 1 chown (21109) < fchownat 
1382463 11:56:25.208109993 0 chmod (21130) > fchmodat 
1382464 11:56:25.208138185 0 chmod (21130) < fchmodat 
```

With no information on the file being changed or the user making the change.  Trying %evt.args or %evt.info yields nothing either.

Is there any way I can do this?  I’m using sysdig 0.19.1 :

```
# sysdig --version
sysdig version 0.19.1
```

Many thanks

Steve H

**Comment by luca3m** [comment]
sysdig currently does not support it. You can add them using this commit as an example: https://github.com/draios/sysdig/commit/a353da7dfac9a2862b52008ef7b0f2a23bae339b

more info: https://github.com/draios/sysdig/wiki/Adding-an-event-to-sysdig

**Comment by SteveHallNNT** [comment]
Thanks Luca.  I'll take a look at these links.  Much appreciated.

**Comment by arossert** [comment]
I wanted to do this before but didn't have the time.
I can take a look to see if I can submit a PR for that.

**Comment by SteveHallNNT** [comment]
I've managed to get this working on my setup here for chmod but need to extend it to support chmod as well.  I've never done a git "merge" before so may need a hand with that.  Or if there's another way to get support for chown / chmod I'm all ears!

**Comment by arossert** [comment]
@SteveHallNNT You need to create a branch with your changes and submit a pull request for the maintainers to do a review and merge.
Just remember to follow the ["Rules"](https://github.com/draios/sysdig#what-do-i-need-to-do-in-order-to-contribute-code).

If you willing to wait I can do this and submit a pull request for this changes.
By looking at the man pages ([chown](http://man7.org/linux/man-pages/man2/chown.2.html)/[chmod](http://man7.org/linux/man-pages/man2/chmod.2.html)) there are multiple versions for each call (chown, lchown, fchown...) and we probably want to support them all, so it might take me a couple of days.

**Comment by SteveHallNNT** [comment]
Hi Amir,
Thanks so much - if you're happy to do the work then that would be great.  Let me know if you change you mind or won't have the time, I'm sure I can get there in the end but it sounds faster if you're OK doing it.  Let me know if you have anything you'd like me to test?
Thanks again
Steve H

**Comment by arossert** [comment]
Sure, I will work on it and submit the PR for that.

@luca3m can we keep it simple and put all the arguments/return value in the exit events?

**Comment by arossert** [comment]
@SteveHallNNT I have created PR #1003 to support all variations of `chmod`/`chown` syscalls.
You can take this and do some tests, let me know if fixes are needed.

**Comment by SteveHallNNT** [comment]
Thanks Amir, that's great work.  I've tested it on RHEL 7.2 and Ubuntu 14 and it looks good :

```
# insmod driver/sysdig-probe.ko 
# ./userspace/sysdig/sysdig "evt.type in (fchmod,chmod,fchmodat,chown,fchown,fchownat)"
30874 12:14:18.655373653 1 chmod (13332) > fchmodat 
30875 12:14:18.655389951 1 chmod (13332) < fchmodat res=0 dirfd=-100(ENETDOWN) pathname=test.txt(/home/steve/sysdig/git/arossert/sysdig/build/test.txt) mode=0666 flags=0 
51993 12:14:20.543732506 1 chown (13342) > fchownat 
51994 12:14:20.543745366 1 chown (13342) < fchownat res=0 dirfd=-100(ENETDOWN) pathname=test.txt(/home/steve/sysdig/git/arossert/sysdig/build/test.txt) owner=1000(steve) group=1000(steve) flags=0 
```

Thanks again!
Steve H

**Comment by SteveHallNNT** [comment]
Hi Amir
I'm trying to setup a chisel to use these new events and am having some trouble working with the FD used by these sys calls.  Is it because they're only being captured on the function exit?  I'm trying to get the fd.type and fd.name and they're always returning nil.
Thanks
Steve

**Comment by arossert** [comment]
@SteveHallNNT currently this only parse and show the arguments of the syscalls and you might do simple filtering on the arguments.
What kind of filter are you trying to do?
I will take a look to see if I can add the fd information on the syscalls (probably will have to capture the arguments in the enter event)

**Comment by SteveHallNNT** [comment]
Thanks.  Just running sysdig as above is working fine.  When I use in a chisel though I'm struggling to get the fd.type and fd.name.  My code looks a little like this :

```
function on_init()
  f_fd_type = chisel.request_field("fd.type")
  f_fd_name = chisel.request_field("fd.name")
  chisel.set_filter("evt.type in (chmod,fchmod,fchmodat,chown,fchown,fchownat)")
  return true
end

function on_event()
  print(evt.field(f_fd_type))
  print(evt.field(f_fd_name))
end
```

Always shows nil / nil?  I can provide a more concrete example if you'd like it.
Thanks
Steve

**Comment by arossert** [comment]
I have moved the parameters to the enter event and tested this with sysdig like this:
```
sysdig -p "%evt.type %fd.type(%fd.name)" evt.type contains chown
```
And then run a c program that calls all the different variations (`chown`, `lchown`, `fchown`, `fchownat`) and this is the output:
```
sysdig -p "%evt.type %evt.dir %fd.type(%fd.name)" evt.type contains chown
fchown > file(/tmp/amir)
fchown < file(/tmp/amir)
fchownat > file(/tmp/amir)
fchownat < file(/tmp/amir)
```
So only the `fchown` & `fchownat` working with fd and have this information, the others are working with file names.

Do you want me to push this changes so you can test it?

**Comment by SteveHallNNT** [comment]
That would be great, thanks.

**Comment by arossert** [comment]
@SteveHallNNT done, let me know if this is working for you

**Comment by SteveHallNNT** [comment]
Looks good @arossert, thanks

**Comment by arossert** [comment]
Great, no we just need to wait for a merge.

**Comment by therealbobo** [comment]
Hi @SteveHallNNT! Thank you for bringing up this! I double checked and now the [libs](https://github.com/falcosecurity/libs) (the building block underlying `sysdig`) support che chmod/chown syscalls! 😄
